# Generated by Django 3.2.19 on 2023-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0004_auto_20230704_1116"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tbtendisdtsjob",
            constraint=models.UniqueConstraint(
                fields=("bill_id", "src_cluster", "dst_cluster"), name="unique_dts_job_key"
            ),
        ),
    ]
