# Generated by Django 3.2.19 on 2023-07-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0002_auto_20230621_1500"),
        ("redis_dts", "0006_tbtendisdtstask_dts_task_unique_key"),
    ]

    operations = []
