# Generated by Django 3.2.19 on 2023-07-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0008_auto_20230718_2249"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="dst_cluster_id",
            field=models.BigIntegerField(default=0, verbose_name="目的集群id"),
        ),
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="src_cluster_id",
            field=models.BigIntegerField(default=0, verbose_name="源集群id"),
        ),
    ]
