# Generated by Django 3.2.19 on 2023-08-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0009_auto_20230720_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="dts_copy_type",
            field=models.CharField(
                choices=[
                    ("one_app_diff_cluster", "业务内"),
                    ("diff_app_diff_cluster", "跨业务"),
                    ("copy_from_rollback_temp", "从回滚临时环境复制数据"),
                    ("copy_to_other_system", "业务内至第三方"),
                    ("user_built_to_dbm", "自建集群至业务内"),
                    ("copy_from_rollback_instance", "构造实例至业务内"),
                ],
                default="",
                max_length=64,
                verbose_name="DTS数据复制类型",
            ),
        ),
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="key_black_regex",
            field=models.TextField(default="", verbose_name="key正则(排除key)"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="key_white_regex",
            field=models.TextField(default="", verbose_name="key正则(包含key)"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="reason",
            field=models.TextField(default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="src_rollback_instances",
            field=models.TextField(default="", verbose_name="回滚临时环境实例"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtstask",
            name="key_black_regex",
            field=models.TextField(default="", verbose_name="排除key(正则)"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtstask",
            name="key_white_regex",
            field=models.TextField(default="", verbose_name="包含key(正则)"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtstask",
            name="message",
            field=models.TextField(default="", verbose_name="信息"),
        ),
    ]
