# Generated by Django 3.2.19 on 2023-08-18 02:08

from django.db import migrations, models

import backend.db_services.redis.redis_dts.enums.type_enums


class Migration(migrations.Migration):

    replaces = [
        ("redis_dts", "0011_tbtendisdtsjob_online_switch_flow_id"),
        ("redis_dts", "0012_tbtendisdtsjob_dst_cluster_shutdown_flow_id"),
        ("redis_dts", "0013_alter_tbtendisdtsjob_online_switch_type"),
        ("redis_dts", "0014_tbtendisdtsjob_dst_cluster_close_flow_id"),
        ("redis_dts", "0015_auto_20230817_1059"),
    ]

    dependencies = [
        ("redis_dts", "0010_auto_20230801_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="online_switch_flow_id",
            field=models.CharField(default="", max_length=64, verbose_name="在线切换 flow id"),
        ),
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="dst_cluster_shutdown_flow_id",
            field=models.CharField(default="", max_length=64, verbose_name="目的集群下架 flow id"),
        ),
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="online_switch_type",
            field=models.CharField(
                choices=[("no_confirm", "自动切换"), ("user_confirm", "用户确认切换")],
                default=backend.db_services.redis.redis_dts.enums.type_enums.DtsOnlineSwitchType["USER_CONFIRM"],
                max_length=64,
                verbose_name="在线切换类型",
            ),
        ),
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="dst_cluster_close_flow_id",
            field=models.CharField(default="", max_length=64, verbose_name="目的集群禁用 flow id"),
        ),
        migrations.RemoveConstraint(
            model_name="tbtendisdtstask",
            name="dts_task_unique_key",
        ),
        migrations.AddConstraint(
            model_name="tbtendisdtstask",
            constraint=models.UniqueConstraint(
                fields=("bill_id", "src_cluster", "dst_cluster", "src_ip", "src_port", "src_kvstore_id"),
                name="dts_task_unique_key",
            ),
        ),
    ]
