# Generated by Django 3.2.19 on 2023-08-31 01:36

from django.db import migrations, models

from backend.db_services.redis.redis_dts.enums import DtsBillType, DtsCopyType


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0011_tbtendisdtsjob_online_switch_flow_id_squashed_0015_auto_20230817_1059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="dts_bill_type",
            field=models.CharField(
                choices=DtsBillType.get_choices(),
                default="",
                max_length=64,
                verbose_name="DTS单据类型",
            ),
        ),
        migrations.AlterField(
            model_name="tbtendisdtsjob",
            name="dts_copy_type",
            field=models.CharField(
                choices=DtsCopyType.get_choices(),
                default="",
                max_length=64,
                verbose_name="DTS数据复制类型",
            ),
        ),
    ]
