# Generated by Django 3.2.19 on 2023-09-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0012_auto_20230831_0936"),
        ("redis_dts", "0012_auto_20230921_0952"),
    ]

    operations = []
