# Generated by Django 3.2.19 on 2023-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0013_merge_0012_auto_20230831_0936_0012_auto_20230921_0952"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tbtendisdtstask",
            index=models.Index(
                fields=["bk_cloud_id", "dts_server", "task_type", "src_dbtype", "status", "create_time"],
                name="tb_tendis_d_bk_clou_49fdd5_idx",
            ),
        ),
    ]
