# Generated by Django 3.2.19 on 2024-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0014_tbtendisdtstask_tb_tendis_d_bk_clou_49fdd5_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TbTendisDtsSwitchBackup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bill_id", models.BigIntegerField(db_index=True, default=0, verbose_name="单据号")),
                ("src_cluster", models.CharField(default="", max_length=128, verbose_name="源集群")),
                ("dst_cluster", models.CharField(default="", max_length=128, verbose_name="目的集群")),
                ("data_type", models.CharField(default="", max_length=128, verbose_name="数据类型")),
                ("data", models.TextField(default="", verbose_name="数据")),
            ],
            options={
                "verbose_name": "Tendis Dts online switch backup",
                "verbose_name_plural": "Tendis Dts online switch backup",
                "db_table": "tb_tendis_dts_switch_backup",
            },
        ),
        migrations.AddConstraint(
            model_name="tbtendisdtsswitchbackup",
            constraint=models.UniqueConstraint(
                fields=("bill_id", "src_cluster", "dst_cluster"), name="unique_switch_job_key"
            ),
        ),
    ]
