# Generated by Django 3.2.19 on 2024-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0015_auto_20240306_1044"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tbtendisdtsswitchbackup",
            name="unique_switch_job_key",
        ),
        migrations.AddConstraint(
            model_name="tbtendisdtsswitchbackup",
            constraint=models.UniqueConstraint(
                fields=("bill_id", "src_cluster", "dst_cluster", "data_type"), name="unique_switch_job_key"
            ),
        ),
    ]
