# Generated by Django 3.2.25 on 2024-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("redis_dts", "0017_auto_20240908_1038"), ("redis_dts", "0018_auto_20240914_1754")]

    dependencies = [
        ("redis_dts", "0016_auto_20240307_0946"),
    ]

    operations = [
        migrations.CreateModel(
            name="TendisplusTunnelerJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("ticket_id", models.BigIntegerField(verbose_name="单据ID")),
                ("user", models.CharField(default="", max_length=64, verbose_name="申请人")),
                ("bk_biz_id", models.CharField(default="", max_length=64, verbose_name="业务bk_biz_d")),
                ("bk_cloud_id", models.BigIntegerField(verbose_name="云区域ID")),
                ("dst_cluster", models.CharField(max_length=128, verbose_name="目标集群")),
                ("dst_cluster_id", models.BigIntegerField(verbose_name="目标集群ID")),
                ("cluster_nodes", models.TextField(verbose_name="集群节点")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "Tendisplus Tunneler Job",
                "verbose_name_plural": "Tendisplus Tunneler Job",
                "db_table": "tb_tendisplus_tunneler_job",
            },
        ),
        migrations.CreateModel(
            name="TendisplusTunnelerTask",
            fields=[
                ("task_id", models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="任务ID")),
                ("ticket_id", models.BigIntegerField(verbose_name="单据ID")),
                ("user", models.CharField(default="", max_length=64, verbose_name="申请人")),
                ("bk_biz_id", models.CharField(default="", max_length=64, verbose_name="业务bk_biz_d")),
                ("bk_cloud_id", models.BigIntegerField(verbose_name="云区域ID")),
                ("cos_key", models.CharField(max_length=128, verbose_name="cos文件key")),
                ("cos_file_size", models.BigIntegerField(verbose_name="cos文件大小")),
                ("dts_server", models.CharField(max_length=128, verbose_name="dts服务地址")),
                ("dst_cluster", models.CharField(max_length=128, verbose_name="目标集群")),
                ("dst_cluster_id", models.BigIntegerField(verbose_name="目标集群ID")),
                ("dst_cluster_priority", models.IntegerField(default=0, verbose_name="目标集群优先级,越大优先级越高")),
                ("status", models.IntegerField(default=0, verbose_name="任务状态")),
                ("message", models.TextField(verbose_name="任务消息")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Tendisplus Tunneler Task",
                "verbose_name_plural": "Tendisplus Tunneler Task",
                "db_table": "tb_tendisplus_tunneler_task",
            },
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelertask",
            index=models.Index(fields=["update_time"], name="tb_tendispl_update__425a81_idx"),
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelertask",
            index=models.Index(fields=["dst_cluster_id"], name="tb_tendispl_dst_clu_c3fb72_idx"),
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelertask",
            index=models.Index(fields=["user"], name="tb_tendispl_user_d85fd6_idx"),
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelertask",
            index=models.Index(fields=["ticket_id", "dst_cluster_id"], name="tb_tendispl_ticket__da0496_idx"),
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelerjob",
            index=models.Index(fields=["create_time"], name="tb_tendispl_create__b2f3e3_idx"),
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelerjob",
            index=models.Index(fields=["dst_cluster_id"], name="tb_tendispl_dst_clu_c52482_idx"),
        ),
        migrations.AddIndex(
            model_name="tendisplustunnelerjob",
            index=models.Index(fields=["user"], name="tb_tendispl_user_65d13e_idx"),
        ),
        migrations.AddConstraint(
            model_name="tendisplustunnelerjob",
            constraint=models.UniqueConstraint(fields=("ticket_id", "dst_cluster"), name="uniq_ticket_cluster"),
        ),
        migrations.CreateModel(
            name="TendisplusLightningTask",
            fields=[
                ("task_id", models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="任务ID")),
                ("ticket_id", models.BigIntegerField(verbose_name="单据ID")),
                ("user", models.CharField(default="", max_length=64, verbose_name="申请人")),
                ("bk_biz_id", models.CharField(default="", max_length=64, verbose_name="业务bk_biz_d")),
                ("bk_cloud_id", models.BigIntegerField(verbose_name="云区域ID")),
                ("cos_key", models.CharField(max_length=128, verbose_name="cos文件key")),
                ("cos_file_size", models.BigIntegerField(verbose_name="cos文件大小")),
                ("dts_server", models.CharField(max_length=128, verbose_name="dts服务地址")),
                ("dst_cluster", models.CharField(max_length=128, verbose_name="目标集群")),
                ("dst_cluster_id", models.BigIntegerField(verbose_name="目标集群ID")),
                ("dst_cluster_priority", models.IntegerField(default=0, verbose_name="目标集群优先级,越大优先级越高")),
                ("dst_zonename", models.CharField(max_length=128, verbose_name="目标集群城市")),
                ("task_type", models.CharField(max_length=128, verbose_name="任务类型")),
                ("operate_type", models.CharField(max_length=128, verbose_name="操作类型")),
                ("status", models.IntegerField(default=0, verbose_name="任务状态")),
                ("message", models.TextField(verbose_name="任务消息")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Tendisplus Lightning Task",
                "verbose_name_plural": "Tendisplus Lightning Task",
                "db_table": "tb_tendisplus_lightning_task",
            },
        ),
        migrations.RenameModel(
            old_name="TendisplusTunnelerJob",
            new_name="TendisplusLightningJob",
        ),
        migrations.DeleteModel(
            name="TendisplusTunnelerTask",
        ),
        migrations.AlterModelOptions(
            name="tendispluslightningjob",
            options={"verbose_name": "Tendisplus Lightning Job", "verbose_name_plural": "Tendisplus Lightning Job"},
        ),
        migrations.RemoveIndex(
            model_name="tendispluslightningjob",
            name="tb_tendispl_create__b2f3e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="tendispluslightningjob",
            name="tb_tendispl_dst_clu_c52482_idx",
        ),
        migrations.RemoveIndex(
            model_name="tendispluslightningjob",
            name="tb_tendispl_user_65d13e_idx",
        ),
        migrations.AddIndex(
            model_name="tendispluslightningjob",
            index=models.Index(fields=["create_time"], name="tb_tendispl_create__2a0918_idx"),
        ),
        migrations.AddIndex(
            model_name="tendispluslightningjob",
            index=models.Index(fields=["dst_cluster_id"], name="tb_tendispl_dst_clu_f167e8_idx"),
        ),
        migrations.AddIndex(
            model_name="tendispluslightningjob",
            index=models.Index(fields=["user"], name="tb_tendispl_user_3b18a1_idx"),
        ),
        migrations.AlterModelTable(
            name="tendispluslightningjob",
            table="tb_tendisplus_lightning_job",
        ),
        migrations.AddIndex(
            model_name="tendispluslightningtask",
            index=models.Index(fields=["update_time"], name="tb_tendispl_update__4c107b_idx"),
        ),
        migrations.AddIndex(
            model_name="tendispluslightningtask",
            index=models.Index(fields=["dst_cluster_id"], name="tb_tendispl_dst_clu_0013b5_idx"),
        ),
        migrations.AddIndex(
            model_name="tendispluslightningtask",
            index=models.Index(fields=["user"], name="tb_tendispl_user_c6340e_idx"),
        ),
        migrations.AddIndex(
            model_name="tendispluslightningtask",
            index=models.Index(fields=["ticket_id", "dst_cluster_id"], name="tb_tendispl_ticket__942488_idx"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningjob",
            name="bk_cloud_id",
            field=models.BigIntegerField(default=0, verbose_name="云区域ID"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningjob",
            name="cluster_nodes",
            field=models.TextField(default="", verbose_name="集群节点"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningjob",
            name="dst_cluster",
            field=models.CharField(default="", max_length=128, verbose_name="目标集群"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningjob",
            name="dst_cluster_id",
            field=models.BigIntegerField(default=0, verbose_name="目标集群ID"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningjob",
            name="ticket_id",
            field=models.BigIntegerField(default=0, verbose_name="单据ID"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="bk_cloud_id",
            field=models.BigIntegerField(default=0, verbose_name="云区域ID"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="cos_file_size",
            field=models.BigIntegerField(default=0, verbose_name="cos文件大小"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="cos_key",
            field=models.CharField(default="", max_length=128, verbose_name="cos文件key"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="dst_cluster",
            field=models.CharField(default="", max_length=128, verbose_name="目标集群"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="dst_cluster_id",
            field=models.BigIntegerField(default=0, verbose_name="目标集群ID"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="dst_zonename",
            field=models.CharField(default="", max_length=128, verbose_name="目标集群城市"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="dts_server",
            field=models.CharField(default="", max_length=128, verbose_name="dts服务地址"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="message",
            field=models.TextField(default="", verbose_name="任务消息"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="operate_type",
            field=models.CharField(default="", max_length=128, verbose_name="操作类型"),
        ),
        migrations.AlterField(
            model_name="tendispluslightningtask",
            name="task_type",
            field=models.CharField(default="", max_length=128, verbose_name="任务类型"),
        ),
    ]
