# Generated by Django 3.2.19 on 2023-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TbTendisRollbackTasks",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("related_rollback_bill_id", models.BigIntegerField(verbose_name=("单据号，关联单据",))),
                ("bk_biz_id", models.BigIntegerField(verbose_name=("业务id",))),
                ("app", models.CharField(default="", max_length=64, verbose_name=("业务名",))),
                ("bk_cloud_id", models.BigIntegerField(default=0, verbose_name=("云区域id",))),
                ("prod_cluster_type", models.CharField(default="", max_length=64, verbose_name=("构造源集群类型",))),
                ("prod_cluster", models.CharField(default="", max_length=128, verbose_name=("构造的源集群，线上环境cluster",))),
                ("prod_instance_range", models.TextField(max_length=10000, verbose_name=("源构造的实例范围",))),
                ("temp_cluster_type", models.CharField(default="", max_length=64, verbose_name=("临时集群类型",))),
                ("temp_password", models.CharField(default="", max_length=128, verbose_name=("临时集群proxy密码base64值",))),
                ("temp_instance_range", models.TextField(max_length=10000, verbose_name=("临时集群构造实例范围",))),
                ("temp_cluster_proxy", models.CharField(max_length=100, verbose_name=("构造产物访问入口ip:port",))),
                (
                    "prod_temp_instance_pairs",
                    models.TextField(default="", max_length=20000, verbose_name=("构造源实例和临时实例一一对应关系",)),
                ),
                ("status", models.IntegerField(default=0, verbose_name=("任务状态",))),
                ("is_destroyed", models.IntegerField(default=0, verbose_name=("是否已销毁",))),
                ("specification", models.CharField(max_length=100, verbose_name=("规格需求",))),
                ("host_count", models.IntegerField(verbose_name=("构造的主机数量",))),
                ("recovery_time_point", models.DateTimeField(verbose_name=("构造到指定时间",))),
            ],
            options={
                "verbose_name": "Tendis data construction task",
                "db_table": "tb_tendis_rollback_tasks",
            },
        ),
        migrations.AddIndex(
            model_name="tbtendisrollbacktasks",
            index=models.Index(fields=["update_at"], name="idx_update_at"),
        ),
        migrations.AddIndex(
            model_name="tbtendisrollbacktasks",
            index=models.Index(fields=["prod_cluster"], name="idx_prod_cluster"),
        ),
    ]
