# Generated by Django 3.2.19 on 2023-07-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0003_auto_20230721_1011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="prod_instance_range",
            field=models.JSONField(default=dict, verbose_name="源构造的实例范围"),
        ),
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="prod_temp_instance_pairs",
            field=models.JSONField(default=dict, verbose_name="构造源实例和临时实例一一对应关系"),
        ),
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="temp_instance_range",
            field=models.JSONField(default=dict, verbose_name="临时集群构造实例范围"),
        ),
    ]
