# Generated by Django 3.2.19 on 2023-07-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0004_auto_20230725_1744"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tbtendisrollbacktasks",
            name="is_destroyed",
        ),
        migrations.AddField(
            model_name="tbtendisrollbacktasks",
            name="destroyed_status",
            field=models.IntegerField(default=0, verbose_name="销毁状态"),
        ),
    ]
