# Generated by Django 3.2.19 on 2023-08-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0008_auto_20230821_1028"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbtendisrollbacktasks",
            old_name="temp_password",
            new_name="temp_proxy_password",
        ),
    ]
