# Generated by Django 3.2.19 on 2023-09-12 08:23

from django.db import migrations, models

import backend.db_meta.enums.destroyed_status


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0009_rename_temp_password_tbtendisrollbacktasks_temp_proxy_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="destroyed_status",
            field=models.IntegerField(
                choices=[(0, "Not destroyed"), (1, "Destroying"), (2, "Destroyed")],
                default=backend.db_meta.enums.destroyed_status.DestroyedStatus["NOT_DESTROYED"],
                verbose_name="销毁状态",
            ),
        ),
    ]
