# Generated by Django 3.2.19 on 2023-10-08 11:38

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0010_alter_tbtendisrollbacktasks_destroyed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="prod_cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="构造源集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="temp_cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="临时集群类型",
            ),
        ),
    ]
