# Generated by Django 3.2.19 on 2023-11-20 11:55

from django.db import migrations, models

import backend.db_meta.enums.destroyed_status


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0011_auto_20231008_1938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisrollbacktasks",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Not started"), (1, "Executing"), (2, "Completed"), (-1, "Error occurred")],
                default=backend.db_meta.enums.destroyed_status.DataStructureStatus["NOT_STARTED"],
                verbose_name="状态",
            ),
        ),
    ]
