# Generated by Django 3.2.25 on 2026-09-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0012_alter_tbtendisrollbacktasks_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbtendisrollbacktasks",
            name="backup_identify",
            field=models.CharField(default="", max_length=255, verbose_name="备份批次标识"),
        ),
        migrations.AddField(
            model_name="tbtendisrollbacktasks",
            name="rollback_detail",
            field=models.JSONField(default=dict, verbose_name="回档明细"),
        ),
        migrations.AddField(
            model_name="tbtendisrollbacktasks",
            name="rollback_mode",
            field=models.CharField(default="", max_length=32, verbose_name="选备模式"),
        ),
        migrations.AddField(
            model_name="tbtendisrollbacktasks",
            name="rollback_version",
            field=models.CharField(default="datastructure", max_length=16, verbose_name="回档实现版本"),
        ),
    ]
