# Generated by Django 3.2.25 on 2026-09-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollback", "0013_tbtendisrollbacktasks_rollback_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TbTendisRollbackPlan",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务id")),
                ("cluster_id", models.BigIntegerField(db_index=True, verbose_name="集群id")),
                ("ticket_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="单据id")),
                ("plan", models.JSONField(default=dict, verbose_name="回档计划")),
            ],
            options={
                "verbose_name": "Tendis rollback plan",
                "db_table": "tb_tendis_rollback_plan",
            },
        ),
    ]
