# Generated by Django 3.2.19 on 2023-10-08 11:38

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metacheckreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
            ),
        ),
    ]
