# Generated by Django 3.2.19 on 2023-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0002_alter_metacheckreport_cluster_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisBackupCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "tendbsingle"),
                            ("tendbha", "tendbha"),
                            ("tendbcluster", "tendbcluster"),
                            ("redis", "Redis集群"),
                            ("PredixyRedisCluster", "Tendisplus集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群 GetTendisType 获取redis类型值"),
                            ("RedisInstance", "TendisCache集群 GetTendisType 获取redis类型值"),
                            ("TendisSSDInstance", "TendisSSD集群 GetTendisType 获取redis类型值"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance", models.CharField(max_length=100, verbose_name="实例节点 ip:port")),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("full_backup", "集群可用全备"),
                            ("binlog_slave", "从库binlog备份"),
                            ("binlog_seq", "binlog连续性检查"),
                        ],
                        default="",
                        help_text="备份检查子项",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="checksumcheckreport",
            name="cluster",
            field=models.CharField(default="", max_length=255, verbose_name="集群名称"),
        ),
        migrations.AlterField(
            model_name="checksumcheckreport",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("tendbsingle", "tendbsingle"),
                    ("tendbha", "tendbha"),
                    ("tendbcluster", "tendbcluster"),
                    ("redis", "Redis集群"),
                    ("PredixyRedisCluster", "Tendisplus集群"),
                    ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                    ("TwemproxyRedisInstance", "TendisCache集群"),
                    ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                    ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                    ("RedisInstance", "RedisCache主从版"),
                    ("TendisSSDInstance", "TendisSSD主从版"),
                    ("TendisplusInstance", "Tendisplus主从版"),
                    ("RedisCluster", "RedisCluster集群"),
                    ("TendisplusCluster", "TendisplusCluster集群"),
                    ("TendisplusInstance", "Tendisplus存储版集群 GetTendisType 获取redis类型值"),
                    ("RedisInstance", "TendisCache集群 GetTendisType 获取redis类型值"),
                    ("TendisSSDInstance", "TendisSSD集群 GetTendisType 获取redis类型值"),
                    ("es", "ES集群"),
                    ("kafka", "Kafka集群"),
                    ("hdfs", "Hdfs集群"),
                    ("influxdb", "Influxdb实例"),
                    ("pulsar", "Pulsar集群"),
                    ("MongoReplicaSet", "Mongo副本集"),
                    ("MongoShardedCluster", "Mongo分片集群"),
                    ("riak", "Riak集群"),
                ],
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="checksumcheckreport",
            name="fail_slaves",
            field=models.IntegerField(default=0, verbose_name="失败的slave实例数量"),
        ),
    ]
