# Generated by Django 3.2.19 on 2023-10-23 06:45

from django.db import migrations, models

from backend.db_meta.enums import ClusterType
from backend.db_report.enums import RedisBackupCheckSubType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0002_alter_metacheckreport_cluster_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisBackupCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance", models.CharField(max_length=100, verbose_name="实例节点 ip:port")),
                (
                    "subtype",
                    models.CharField(
                        choices=RedisBackupCheckSubType.get_choices(),
                        default="",
                        help_text="备份检查子项",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="checksumcheckreport",
            name="cluster",
            field=models.CharField(default="", max_length=255, verbose_name="集群名称"),
        ),
        migrations.AlterField(
            model_name="checksumcheckreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="checksumcheckreport",
            name="fail_slaves",
            field=models.IntegerField(default=0, verbose_name="失败的slave实例数量"),
        ),
    ]
