# Generated by Django 3.2.19 on 2023-10-28 08:40

from django.db import migrations, models

from backend.db_meta.enums import ClusterType
from backend.db_report.enums import MysqlBackupCheckSubType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0003_auto_20231023_1445"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlBackupCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255)),
                ("cluster_type", models.CharField(choices=ClusterType.get_choices(), default="", max_length=64)),
                (
                    "subtype",
                    models.CharField(
                        choices=MysqlBackupCheckSubType.get_choices(), default="", help_text="备份检查子项", max_length=64
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="redisbackupcheckreport",
            name="subtype",
            field=models.CharField(
                choices=[("full_backup", "集群全备"), ("binlog_slave", "从库binlog备份")],
                default="",
                help_text="备份检查子项",
                max_length=64,
            ),
        ),
    ]
