# Generated by Django 3.2.19 on 2023-11-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0004_auto_20231028_1640"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbmonHeartbeatReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("twemproxy", "TWEMPROXY"),
                            ("predixy", "PREDIXY"),
                            ("redis_ssd", "REDIS_SSD"),
                            ("redis_cache", "REDIS_CACHE"),
                            ("tendisplus", "TENDISPLUS"),
                        ],
                        help_text="实例类型子项",
                        max_length=64,
                    ),
                ),
                ("instance", models.CharField(max_length=100, verbose_name="实例节点 ip:port")),
                ("app", models.CharField(max_length=100, verbose_name="业务名")),
                ("dba", models.JSONField(max_length=100, verbose_name="业务所属dba")),
                ("time", models.DateTimeField(verbose_name="心跳超时时间")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
