# Generated by Django 3.2.19 on 2023-11-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0005_dbmonheartbeatreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbmonheartbeatreport",
            name="time",
        ),
        migrations.AlterField(
            model_name="dbmonheartbeatreport",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("TWEMPROXY", "TWEMPROXY"),
                    ("PREDIXY", "PREDIXY"),
                    ("REDIS_SSD", "REDIS_SSD"),
                    ("REDIS_CACHE", "REDIS_CACHE"),
                    ("TENDISPLUS", "TENDISPLUS"),
                ],
                help_text="实例类型子项",
                max_length=64,
            ),
        ),
    ]
