# Generated by Django 3.2.25 on 2024-11-25 07:00

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0006_auto_20231121_1621"),
    ]

    operations = [
        migrations.CreateModel(
            name="SqlserverCheckAppSettingReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance_host", models.CharField(default="", max_length=255, verbose_name="实例IP")),
                ("instance_port", models.IntegerField(default=48322, verbose_name="实例端口")),
                ("is_inconsistent", models.IntegerField(default=0, verbose_name="元信息是否不一致")),
                ("is_fix", models.IntegerField(default=0, verbose_name="元数据是否自动修复成功")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SqlserverCheckJobSyncReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance_host", models.CharField(default="", max_length=255, verbose_name="实例IP")),
                ("instance_port", models.IntegerField(default=48322, verbose_name="实例端口")),
                ("is_job_inconsistent", models.IntegerField(default=2, verbose_name="业务Job数量是否不一致")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SqlserverCheckLinkServerReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance_host", models.CharField(default="", max_length=255, verbose_name="实例IP")),
                ("instance_port", models.IntegerField(default=48322, verbose_name="实例端口")),
                ("is_link_server_inconsistent", models.IntegerField(default=2, verbose_name="业务LinkServer数量是否不一致")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SqlserverCheckSysJobStatuReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance_host", models.CharField(default="", max_length=255, verbose_name="实例IP")),
                ("instance_port", models.IntegerField(default=48322, verbose_name="实例端口")),
                ("is_job_disable", models.IntegerField(default=0, verbose_name="是否存在disable状态的系统job")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SqlserverCheckUserSyncReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("instance_host", models.CharField(default="", max_length=255, verbose_name="实例IP")),
                ("instance_port", models.IntegerField(default=48322, verbose_name="实例端口")),
                ("is_user_inconsistent", models.IntegerField(default=0, verbose_name="业务账号是否不一致")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
