# Generated by Django 3.2.25 on 2024-11-29 09:54

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        (
            "db_report",
            "0007_sqlservercheckappsettingreport_sqlservercheckjobsyncreport_sqlserverchecklinkserverreport_sqlserverc",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlservercheckappsettingreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlservercheckappsettingreport",
            name="is_fix",
            field=models.BooleanField(default=False, verbose_name="元数据是否自动修复成功"),
        ),
        migrations.AlterField(
            model_name="sqlservercheckappsettingreport",
            name="is_inconsistent",
            field=models.BooleanField(default=False, verbose_name="元信息是否不一致"),
        ),
        migrations.AlterField(
            model_name="sqlservercheckjobsyncreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlservercheckjobsyncreport",
            name="is_job_inconsistent",
            field=models.BooleanField(default=False, verbose_name="业务Job数量是否不一致"),
        ),
        migrations.AlterField(
            model_name="sqlserverchecklinkserverreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlserverchecklinkserverreport",
            name="is_link_server_inconsistent",
            field=models.BooleanField(default=False, verbose_name="业务LinkServer数量是否不一致"),
        ),
        migrations.AlterField(
            model_name="sqlserverchecksysjobstatureport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlserverchecksysjobstatureport",
            name="is_job_disable",
            field=models.BooleanField(default=False, verbose_name="是否存在disable状态的系统job"),
        ),
        migrations.AlterField(
            model_name="sqlservercheckusersyncreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlservercheckusersyncreport",
            name="is_user_inconsistent",
            field=models.BooleanField(default=False, verbose_name="业务账号是否不一致"),
        ),
    ]
