# Generated by Django 3.2.25 on 2025-01-02 08:38

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0008_auto_20241129_1754"),
    ]

    operations = [
        migrations.CreateModel(
            name="SqlserverFullBackupInfoReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                        verbose_name="集群类型",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SqlserverLogBackupInfoReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255, verbose_name="集群名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                        verbose_name="集群类型",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
