# Generated by Django 3.2.25 on 2025-02-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0009_sqlserverfullbackupinforeport_sqlserverlogbackupinforeport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metacheckreport",
            name="ip",
            field=models.GenericIPAddressField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="metacheckreport",
            name="port",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
