# Generated by Django 3.2.25 on 2025-05-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0010_auto_20250218_1047"),
    ]

    operations = [
        migrations.CreateModel(
            name="MongodbBackupCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "MySQL单节点集群"),
                            ("tendbha", "MySQL高可用集群"),
                            ("tendbcluster", "TendbCluster集群"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("redis", "Redis"),
                            ("PredixyRedisCluster", "RedisCluster集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群"),
                            ("RedisInstance", "TendisCache集群"),
                            ("TendisSSDInstance", "TendisSSD集群"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("doris", "Doris集群"),
                            ("vm", "vm集群"),
                            ("dbmon", "redis监控"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                            ("sqlserver_single", "sqlserver单节点版"),
                            ("sqlserver_ha", "sqlserver主从版"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("shard", models.CharField(max_length=100, verbose_name="shard or set_name")),
                ("instance", models.CharField(max_length=100, verbose_name="实例节点 ip:port")),
                ("subtype", models.CharField(max_length=100, verbose_name="检查子项")),
            ],
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(fields=["bk_biz_id", "create_at"], name="db_report_m_bk_biz__ad7376_idx"),
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(fields=["status", "create_at"], name="db_report_m_status_4b8bc7_idx"),
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(fields=["creator", "create_at"], name="db_report_m_creator_efc547_idx"),
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(fields=["cluster", "create_at"], name="db_report_m_cluster_aa985f_idx"),
        ),
    ]
