# Generated by Django 3.2.25 on 2025-07-15 01:27

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0011_auto_20250507_1315"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailoverDrillReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("main_task_id", models.CharField(default="", help_text="主任务ID", max_length=64, unique=True)),
                ("cluster_domain", models.CharField(default="", help_text="集群域名", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        max_length=64,
                    ),
                ),
                ("city", models.CharField(default="", help_text="城市", max_length=128)),
                ("drill_ip", models.GenericIPAddressField(default="", help_text="演练实例IP")),
                ("drill_role_type", models.CharField(default="", help_text="演练实例角色", max_length=64)),
                ("drill_start_time", models.DateTimeField(auto_now_add=True, help_text="演练开始时间")),
                ("drill_end_time", models.DateTimeField(auto_now=True, help_text="演练结束始时间")),
                ("task_info", models.TextField(default="", help_text="演练任务执行信息")),
                (
                    "dhha_status",
                    models.CharField(
                        choices=[("info", "切换中？"), ("failed", "切换失败"), ("success", "切换成功")],
                        default="",
                        help_text="dbha切换状态",
                        max_length=255,
                    ),
                ),
                ("dbha_info", models.TextField(default="", help_text="dbha切换信息")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
