# Generated by Django 3.2.25 on 2025-07-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0012_failoverdrillreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failoverdrillreport",
            name="drill_ip",
        ),
        migrations.RemoveField(
            model_name="failoverdrillreport",
            name="drill_role_type",
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="drill_info",
            field=models.TextField(default="", help_text="演练执行信息"),
        ),
    ]
