# Generated by Django 3.2.25 on 2025-07-22 04:24

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0013_auto_20250716_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failoverdrillreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                max_length=64,
            ),
        ),
    ]
