# Generated by Django 3.2.25 on 2025-09-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0014_alter_failoverdrillreport_cluster_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlBackupResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("event_create_timestamp", models.BigIntegerField(blank=True, null=True)),
                ("event_report_timestamp", models.BigIntegerField(blank=True, null=True)),
                ("event_receive_timestamp", models.BigIntegerField(blank=True, null=True)),
                ("event_source_ip", models.CharField(blank=True, max_length=30, null=True)),
                ("event_bk_cloud_id", models.BigIntegerField(blank=True, null=True)),
                ("event_bk_biz_id", models.BigIntegerField(blank=True, null=True)),
                ("backup_id", models.CharField(max_length=60)),
                ("backup_type", models.CharField(max_length=32)),
                ("cluster_id", models.BigIntegerField()),
                ("cluster_address", models.CharField(max_length=255)),
                ("backup_host", models.CharField(max_length=32)),
                ("backup_port", models.BigIntegerField()),
                ("mysql_role", models.CharField(max_length=32)),
                ("shard_value", models.BigIntegerField()),
                ("bill_id", models.CharField(max_length=32)),
                ("bk_biz_id", models.BigIntegerField()),
                ("mysql_version", models.CharField(max_length=120)),
                ("data_schema_grant", models.CharField(max_length=32)),
                ("is_full_backup", models.IntegerField()),
                ("file_retention_tag", models.CharField(max_length=32)),
                ("total_filesize", models.BigIntegerField()),
                ("backup_consistent_time", models.DateTimeField(blank=True, null=True)),
                ("backup_begin_time", models.DateTimeField()),
                ("backup_end_time", models.DateTimeField()),
                ("binlog_info", models.TextField()),
                ("file_list", models.TextField()),
                ("extra_fields", models.TextField()),
                ("backup_status", models.CharField(max_length=32)),
                ("backup_method", models.CharField(blank=True, max_length=32, null=True)),
                ("is_standby", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "tb_mysql_backup_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MysqlBinlogResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("event_create_timestamp", models.BigIntegerField(blank=True, null=True)),
                ("event_report_timestamp", models.BigIntegerField(blank=True, null=True)),
                ("event_receive_timestamp", models.BigIntegerField(blank=True, null=True)),
                ("event_source_ip", models.CharField(blank=True, max_length=30, null=True)),
                ("event_bk_cloud_id", models.BigIntegerField(blank=True, null=True)),
                ("event_bk_biz_id", models.BigIntegerField(blank=True, null=True)),
                ("bk_biz_id", models.BigIntegerField()),
                ("cluster_id", models.BigIntegerField()),
                ("cluster_domain", models.CharField(max_length=255)),
                ("db_role", models.CharField(max_length=32)),
                ("host", models.CharField(max_length=32)),
                ("port", models.BigIntegerField()),
                ("filename", models.CharField(max_length=32)),
                ("filesize", models.BigIntegerField()),
                ("file_mtime", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                ("backup_enable", models.IntegerField()),
                ("backup_status", models.IntegerField()),
                ("backup_status_info", models.CharField(max_length=255)),
                ("task_id", models.CharField(max_length=60)),
                ("file_retention_tag", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "tb_mysql_binlog_result",
                "managed": False,
            },
        ),
    ]
