# Generated by Django 3.2.25 on 2025-09-16 06:19

from django.db import migrations, models

from backend.db_meta.enums.cluster_type import ClusterType


class Migration(migrations.Migration):

    replaces = [
        ("db_report", "0016_auto_20250913_1416"),
        ("db_report", "0017_alter_failoverdrillreport_main_task_id"),
        ("db_report", "0018_auto_20250913_1519"),
    ]

    dependencies = [
        ("db_report", "0015_auto_20250905_1929"),
    ]

    operations = [
        migrations.RenameField(
            model_name="failoverdrillreport",
            old_name="dhha_status",
            new_name="dbha_status",
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="instance_role",
            field=models.CharField(default="", help_text="实例类型", max_length=64),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="switch_finished_time",
            field=models.DateTimeField(help_text="结束切换时间", null=True),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="switch_start_time",
            field=models.DateTimeField(help_text="开始切换时间", null=True),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="task_status",
            field=models.CharField(default="", help_text="容灾任务执行状态", max_length=255),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="trigger_dbha_time",
            field=models.DateTimeField(help_text="开始触发dbha时间", null=True),
        ),
        migrations.AlterField(
            model_name="failoverdrillreport",
            name="cluster_type",
            field=models.CharField(choices=ClusterType.get_choices(), help_text="集群类型", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="failoverdrillreport",
            constraint=models.UniqueConstraint(fields=("main_task_id", "instance_role"), name="unique_main_role"),
        ),
        migrations.AlterField(
            model_name="failoverdrillreport",
            name="main_task_id",
            field=models.CharField(default="", help_text="主任务ID", max_length=64),
        ),
        migrations.RemoveConstraint(
            model_name="failoverdrillreport",
            name="unique_main_role",
        ),
        migrations.RenameField(
            model_name="failoverdrillreport",
            old_name="instance_role",
            new_name="instance_type",
        ),
        migrations.AddConstraint(
            model_name="failoverdrillreport",
            constraint=models.UniqueConstraint(fields=("main_task_id", "instance_type"), name="unique_main_type"),
        ),
    ]
