# Generated by Django 3.2.25 on 2025-09-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0015_auto_20250905_1929"),
        ("db_report", "0015_mysqlbackupresult_mysqlbinlogresult"),
    ]

    operations = []
