# Generated by Django 3.2.25 on 2025-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0016_auto_20250913_1416_squashed_0018_auto_20250913_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="checksumcheckreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="checksumcheckreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="dbmonheartbeatreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="dbmonheartbeatreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="metacheckreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="metacheckreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="mongodbbackupcheckreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="mongodbbackupcheckreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="mysqlbackupcheckreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="redisbackupcheckreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="redisbackupcheckreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlservercheckappsettingreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlservercheckappsettingreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlservercheckjobsyncreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlservercheckjobsyncreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlserverchecklinkserverreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlserverchecklinkserverreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlserverchecksysjobstatureport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlserverchecksysjobstatureport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlservercheckusersyncreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlservercheckusersyncreport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlserverfullbackupinforeport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlserverfullbackupinforeport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
        migrations.AddField(
            model_name="sqlserverlogbackupinforeport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="sqlserverlogbackupinforeport",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
    ]
