# Generated by Django 3.2.25 on 2025-09-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0017_auto_20250917_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="mongodbbackupcheckreport",
            name="cluster_id",
            field=models.IntegerField(default=0, verbose_name="集群 id"),
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(fields=["cluster_id", "create_at"], name="db_report_m_cluster_3a7a95_idx"),
        ),
    ]
