# Generated by Django 3.2.25 on 2025-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0018_auto_20250924_1652"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mongodbbackupcheckreport",
            name="db_report_m_cluster_3a7a95_idx",
        ),
        migrations.AddField(
            model_name="mongodbbackupcheckreport",
            name="report_day",
            field=models.IntegerField(default=0, verbose_name="报告日期"),
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(fields=["subtype", "report_day", "cluster_id"], name="db_report_m_subtype_b9e0c8_idx"),
        ),
        migrations.AddIndex(
            model_name="mongodbbackupcheckreport",
            index=models.Index(
                fields=["subtype", "bk_biz_id", "state", "create_at"], name="db_report_m_subtype_296f78_idx"
            ),
        ),
    ]
