# Generated by Django 3.2.25 on 2025-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0019_auto_20250925_1446"),
    ]

    operations = [
        migrations.AddField(
            model_name="checksumcheckreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="dbmonheartbeatreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="failoverdrillreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="metacheckreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="mongodbbackupcheckreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="mysqlbackupcheckreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="redisbackupcheckreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlservercheckappsettingreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlservercheckjobsyncreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlserverchecklinkserverreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlserverchecksysjobstatureport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlservercheckusersyncreport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlserverfullbackupinforeport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
        migrations.AddField(
            model_name="sqlserverlogbackupinforeport",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
    ]
