# Generated by Django 3.2.25 on 2025-10-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0016_merge_20250912_0910"),
        ("db_report", "0019_auto_20250925_1446"),
    ]

    operations = []
