# Generated by Django 3.2.25 on 2025-10-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0020_merge_20251009_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqlbackupcheckreport",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddIndex(
            model_name="metacheckreport",
            index=models.Index(
                fields=["cluster", "ip", "port", "subtype", "create_at"], name="db_report_m_cluster_7ebc48_idx"
            ),
        ),
    ]
