# Generated by Django 4.2.23 on 2025-11-06 03:43

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0021_auto_20251021_1559"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffinityCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster_id", models.IntegerField(default=0, help_text="集群ID")),
                ("cluster", models.CharField(default="", help_text="集群域名", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        help_text="集群类型",
                        max_length=64,
                    ),
                ),
                ("region", models.CharField(default="", help_text="地域", max_length=255)),
                ("affinity_type", models.CharField(default="", help_text="亲和性类型", max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cluster_id", "affinity_type", "create_at"], name="db_report_a_cluster_be9a1a_idx"
                    ),
                    models.Index(fields=["cluster_id"], name="db_report_a_cluster_d3fe33_idx"),
                ],
            },
        ),
    ]
