# Generated by Django 4.2.23 on 2025-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0022_affinitycheckreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlInspectIgnore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(help_text="业务的id")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "MySQL单节点集群"),
                            ("tendbha", "MySQL高可用集群"),
                            ("tendbcluster", "TendbCluster集群"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("redis", "Redis"),
                            ("PredixyRedisCluster", "RedisCluster集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群"),
                            ("RedisInstance", "TendisCache集群"),
                            ("TendisSSDInstance", "TendisSSD集群"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("doris", "Doris集群"),
                            ("vm", "vm集群"),
                            ("dbmon", "redis监控"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                            ("sqlserver_single", "sqlserver单节点版"),
                            ("sqlserver_ha", "sqlserver主从版"),
                            ("oracle_primary_standby", "oracle主从版"),
                            ("oracle_single_none", "oracle单节点版"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("cluster", models.CharField(help_text="集群域名", max_length=255)),
                ("subtype", models.CharField(help_text="忽略的巡检类型", max_length=64)),
                ("reason", models.TextField(default="", help_text="忽略原因")),
                ("is_enabled", models.BooleanField(default=True, help_text="是否启用")),
            ],
            options={
                "verbose_name": "巡检忽略配置",
                "verbose_name_plural": "巡检忽略配置",
                "db_table": "tb_mysql_inspect_ignore",
                "managed": True,
                "unique_together": {("cluster", "bk_biz_id", "subtype")},
                "index_together": {("subtype", "cluster_type")},
            },
        ),
    ]
