# Generated by Django 4.2.23 on 2025-11-18 07:19

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0022_affinitycheckreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlInspectIgnore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(help_text="业务的id")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("cluster", models.CharField(help_text="集群域名", max_length=255)),
                ("subtype", models.CharField(help_text="忽略的巡检类型", max_length=64)),
                ("reason", models.TextField(default="", help_text="忽略原因")),
                ("is_enabled", models.BooleanField(default=True, help_text="是否启用")),
            ],
            options={
                "verbose_name": "巡检忽略配置",
                "verbose_name_plural": "巡检忽略配置",
                "db_table": "tb_mysql_inspect_ignore",
                "managed": True,
                "unique_together": {("cluster", "bk_biz_id", "subtype")},
                "index_together": {("subtype", "cluster_type")},
            },
        ),
        migrations.CreateModel(
            name="MysqlExporterCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("mysqld_exporter_up", "mysqld_exporter上报检查"),
                            ("mysqlproxy_exporter_up", "mysqlproxy_exporter上报检查"),
                        ],
                        default="",
                        help_text="exporter检查子项",
                        max_length=64,
                    ),
                ),
                ("instance", models.CharField(default="", help_text="实例地址", max_length=255)),
            ],
            options={
                "managed": True,
                "index_together": {("cluster", "subtype"), ("cluster", "instance")},
            },
        ),
    ]
