# Generated by Django 4.2.23 on 2025-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0023_mysqlinspectignore"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="metacheckreport",
            index=models.Index(fields=["subtype", "failed_days", "create_at"], name="db_report_m_subtype_2272a8_idx"),
        ),
    ]
