# Generated by Django 4.2.23 on 2025-12-11 06:25

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0025_esaccountreport_esdatanodereport_esdomainreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisCheckReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="集群 id")),
                ("cluster", models.CharField(default="", max_length=255)),
                ("cluster_type", models.CharField(default="", max_length=128, verbose_name="集群类型")),
                ("shard", models.CharField(default="", max_length=100, verbose_name="shard or set_name")),
                ("instance", models.CharField(max_length=100, verbose_name="实例节点 ip:port")),
                ("subtype", models.CharField(max_length=100, verbose_name="检查子项")),
                ("report_day", models.IntegerField(default=0, verbose_name="报告日期")),
            ],
        ),
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(fields=["bk_biz_id", "create_at"], name="db_report_r_bk_biz__989b55_idx"),
        ),
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(fields=["status", "create_at"], name="db_report_r_status_724975_idx"),
        ),
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(fields=["creator", "create_at"], name="db_report_r_creator_757c53_idx"),
        ),
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(fields=["cluster", "create_at"], name="db_report_r_cluster_280497_idx"),
        ),
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(fields=["subtype", "report_day", "cluster_id"], name="db_report_r_subtype_88dbcd_idx"),
        ),
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(
                fields=["subtype", "bk_biz_id", "state", "create_at"], name="db_report_r_subtype_eeff67_idx"
            ),
        ),
        migrations.AlterField(
            model_name="esaccountreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="esdatanodereport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="esdomainreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="esmasterreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="esstatusreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="esversionreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
    ]
