# Generated by Django 4.2.23 on 2025-12-10 02:52

import django.utils.timezone
from django.db import migrations, models

import backend.db_report.enums.redis_rollback_exercise_task_stage


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0025_esaccountreport_esdatanodereport_esdomainreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisRollbackExerciseReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("status", models.BooleanField(default=True, help_text="巡检结果状态, 默认正常")),
                ("state", models.CharField(default="", help_text="巡检结果状态", max_length=64)),
                ("failed_days", models.IntegerField(default=0, help_text="失败持续天数")),
                ("msg", models.TextField(default="", help_text="备注信息")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="源集群ID")),
                ("cluster_domain", models.CharField(default="", max_length=255, verbose_name="源集群域名")),
                ("cluster_type", models.CharField(default="", max_length=64, verbose_name="源集群类型")),
                ("instance_ip", models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="IP")),
                ("instance_port", models.IntegerField(blank=True, default=0, null=True, verbose_name="Port")),
                ("redis_version", models.CharField(default="", max_length=64, verbose_name="实例版本")),
                ("backup_info", models.TextField(default="", verbose_name="备份信息")),
                ("task_start_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="任务开始时间")),
                ("recover_start_time", models.DateTimeField(blank=True, null=True, verbose_name="回档开始时间")),
                ("recover_end_time", models.DateTimeField(blank=True, null=True, verbose_name="回档结束时间")),
                ("task_end_time", models.DateTimeField(blank=True, null=True, verbose_name="任务结束时间")),
                ("ticket_id", models.IntegerField(default=0, null=True, verbose_name="关联单据ID")),
                (
                    "rollback_flow_obj_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="构造流程ID"),
                ),
                ("delete_flow_obj_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="销毁流程ID")),
                (
                    "task_stage",
                    models.CharField(
                        choices=[
                            ("task_generated", "任务已生成"),
                            ("skipped", "已跳过"),
                            ("ticket_gen_failed", "单据生成失败"),
                            ("ticket_generated", "单据已生成"),
                            ("resource_appli_failed", "资源申请失败"),
                            ("resource_appli_succeeded", "资源申请成功"),
                            ("rollback_flow_gen_failed", "回档流程生成失败"),
                            ("rollback_flow_generated", "回档流程已生成"),
                            ("rollback_failed", "回档失败"),
                            ("rollback_succeeded", "回档成功"),
                            ("delete_flow_gen_failed", "删除流程生成失败"),
                            ("delete_flow_generated", "删除流程已生成"),
                            ("delete_failed", "删除失败"),
                            ("delete_succeeded", "删除成功"),
                            ("done", "已完成"),
                        ],
                        default=backend.db_report.enums.redis_rollback_exercise_task_stage.RedisRollbackExerciseTaskStage[
                            "TASK_GENERATED"
                        ],
                        help_text="当前任务执行阶段",
                        max_length=32,
                        verbose_name="任务阶段",
                    ),
                ),
                ("task_message", models.TextField(default="", verbose_name="任务日志")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "-update_at"], name="db_report_r_state_15594e_idx"),
                    models.Index(fields=["task_stage", "-update_at"], name="db_report_r_task_st_1ac65a_idx"),
                    models.Index(fields=["cluster_id", "-update_at"], name="db_report_r_cluster_0fb2ec_idx"),
                ],
            },
        ),
    ]
