# Generated by Django 4.2.23 on 2025-12-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0026_redischeckreport_alter_esaccountreport_cluster_type_and_more"),
        ("db_report", "0026_redisrollbackexercisereport"),
    ]

    operations = []
