# Generated by Django 4.2.23 on 2025-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0028_kafkabrokeraffinityreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRecord",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="主键")),
                ("db_type", models.CharField(default="", max_length=128, verbose_name="数据库类型")),
                ("task_name", models.CharField(default="", max_length=255, verbose_name="任务名称")),
                ("task_type", models.CharField(default="", max_length=128, verbose_name="任务类型")),
                ("task_status", models.CharField(default="", max_length=128, verbose_name="任务状态")),
                ("task_result", models.TextField(default="", verbose_name="任务结果")),
                ("start_time", models.DateTimeField(auto_now=True, verbose_name="任务开始时间")),
                ("end_time", models.DateTimeField(default=None, verbose_name="任务结束时间")),
                ("task_duration", models.IntegerField(default=0, verbose_name="任务时长")),
                ("cluster_num", models.IntegerField(default=0, verbose_name="集群数量")),
                ("cluster_success_num", models.IntegerField(default=0, verbose_name="集群成功数量")),
                ("cluster_skip_num", models.IntegerField(default=0, verbose_name="集群跳过数量")),
                ("cluster_warning_num", models.IntegerField(default=0, verbose_name="集群警告数量")),
                ("cluster_failed_num", models.IntegerField(default=0, verbose_name="集群失败数量")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["db_type", "task_name", "create_at"], name="db_report_t_db_type_2997e8_idx")
                ],
            },
        ),
    ]
