# Generated by Django 4.2.23 on 2025-12-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0028_kafkabrokeraffinityreport_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="redisrollbackexercisereport",
            name="db_report_r_state_15594e_idx",
        ),
        migrations.AddIndex(
            model_name="redisrollbackexercisereport",
            index=models.Index(fields=["state", "-create_at"], name="db_report_r_state_82ce4a_idx"),
        ),
    ]
