# Generated by Django 4.2.23 on 2025-12-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0029_remove_redisrollbackexercisereport_db_report_r_state_15594e_idx_and_more"),
        ("db_report", "0029_taskrecord"),
    ]

    operations = []
