# Generated by Django 4.2.23 on 2026-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0030_merge_20251224_0955"),
    ]

    operations = [
        migrations.CreateModel(
            name="TdbctlUpgradeRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域ID")),
                ("cluster_id", models.IntegerField(default=0, help_text="集群ID")),
                ("cluster_domain", models.CharField(default="", help_text="集群域名", max_length=255)),
                ("ip", models.GenericIPAddressField(help_text="tdbctl实例IP")),
                ("port", models.IntegerField(help_text="tdbctl实例端口")),
                ("spider_port", models.IntegerField(default=0, help_text="对应的spider端口")),
                (
                    "instance_role",
                    models.CharField(
                        choices=[("primary", "主节点"), ("secondary", "从节点")],
                        default="secondary",
                        help_text="实例角色:primary/secondary",
                        max_length=32,
                    ),
                ),
                ("current_version", models.CharField(default="", help_text="升级前版本", max_length=128)),
                ("target_version", models.CharField(default="", help_text="目标版本", max_length=128)),
                ("upgraded_version", models.CharField(default="", help_text="实际升级后版本", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待升级"),
                            ("running", "升级中"),
                            ("success", "升级成功"),
                            ("failed", "升级失败"),
                            ("skipped", "已跳过-版本已是最新"),
                        ],
                        default="pending",
                        help_text="升级状态",
                        max_length=32,
                    ),
                ),
                ("task_id", models.CharField(default="", help_text="关联的flow任务ID", max_length=128)),
                ("pkg_id", models.IntegerField(default=0, help_text="升级包ID")),
                ("error_msg", models.TextField(default="", help_text="错误信息")),
                ("batch_id", models.CharField(default="", help_text="批次ID", max_length=128)),
                ("upgrade_history", models.JSONField(default=list, help_text="升级历史记录")),
                ("upgrade_count", models.IntegerField(default=0, help_text="累计升级次数")),
            ],
            options={
                "verbose_name": "tdbctl升级记录",
                "verbose_name_plural": "tdbctl升级记录",
                "indexes": [
                    models.Index(fields=["cluster_id", "status"], name="db_report_t_cluster_02eba4_idx"),
                    models.Index(fields=["bk_biz_id", "status"], name="db_report_t_bk_biz__37613a_idx"),
                    models.Index(fields=["status", "target_version"], name="db_report_t_status_449a67_idx"),
                ],
                "unique_together": {("ip", "port")},
            },
        ),
    ]
