# Generated by Django 4.2.27 on 2026-03-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0031_tdbctlupgraderecord"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="redischeckreport",
            index=models.Index(fields=["subtype", "create_at", "cluster_id"], name="db_report_r_subtype_26d26e_idx"),
        ),
    ]
