# Generated by Django 4.2.27 on 2026-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0031_tdbctlupgraderecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="SQLServerBinlogResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("bk_biz_id", models.IntegerField()),
                ("bk_cloud_id", models.IntegerField(default=0)),
                ("cluster_id", models.IntegerField()),
                ("cluster_domain", models.CharField(max_length=255)),
                ("db_role", models.CharField(max_length=32)),
                ("host", models.CharField(max_length=32)),
                ("port", models.IntegerField()),
                ("backup_id", models.CharField(max_length=64)),
                ("dbname", models.CharField(max_length=128)),
                ("file_name", models.CharField(max_length=256)),
                ("file_cnt", models.IntegerField(default=1)),
                ("first_lsn", models.CharField(default="", max_length=30)),
                ("last_lsn", models.CharField(default="", max_length=30)),
                ("checkpoint_lsn", models.CharField(default="", max_length=30)),
                ("database_backup_lsn", models.CharField(default="", max_length=30)),
                ("backup_task_start_time", models.DateTimeField(blank=True, null=True)),
                ("backup_task_end_time", models.DateTimeField(blank=True, null=True)),
                ("backup_begin_time", models.DateTimeField(blank=True, null=True)),
                ("backup_end_time", models.DateTimeField(blank=True, null=True)),
                ("backup_status", models.SmallIntegerField()),
                ("backup_status_info", models.CharField(max_length=255)),
                ("task_id", models.CharField(max_length=60)),
                ("local_path", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "tb_sqlserver_binlog_result",
                "indexes": [
                    models.Index(
                        fields=["cluster_id", "cluster_domain", "dbname", "backup_end_time"],
                        name="idx_cluster_dbname_time",
                    )
                ],
                "unique_together": {("cluster_id", "cluster_domain", "host", "port", "backup_id", "dbname")},
            },
        ),
        migrations.CreateModel(
            name="SQLServerBackupResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("backup_id", models.CharField(max_length=60)),
                ("backup_type", models.CharField(max_length=32)),
                ("cluster_id", models.IntegerField()),
                ("cluster_domain", models.CharField(max_length=255)),
                ("backup_host", models.CharField(max_length=32)),
                ("backup_port", models.IntegerField()),
                ("master_ip", models.CharField(default="", max_length=32)),
                ("master_port", models.IntegerField(default=0)),
                ("role", models.CharField(default="", max_length=32)),
                ("bill_id", models.CharField(default="", max_length=32)),
                ("bk_biz_id", models.IntegerField()),
                ("bk_cloud_id", models.IntegerField(default=0)),
                ("charset", models.CharField(default="", max_length=64)),
                ("time_zone", models.CharField(default="+08:00", max_length=16)),
                ("version", models.CharField(default="", max_length=64)),
                ("data_schema_grant", models.CharField(default="", max_length=32)),
                ("is_full_backup", models.BooleanField()),
                ("first_lsn", models.CharField(default="", max_length=30)),
                ("last_lsn", models.CharField(default="", max_length=30)),
                ("checkpoint_lsn", models.CharField(default="", max_length=30)),
                ("database_backup_lsn", models.CharField(default="", max_length=30)),
                ("backup_task_start_time", models.DateTimeField(blank=True, null=True)),
                ("backup_task_end_time", models.DateTimeField(blank=True, null=True)),
                ("backup_begin_time", models.DateTimeField(blank=True, null=True)),
                ("backup_end_time", models.DateTimeField(blank=True, null=True)),
                ("db_list", models.TextField()),
                ("dbname", models.CharField(default="", max_length=128)),
                ("file_cnt", models.IntegerField(default=0)),
                ("task_id", models.CharField(default="", max_length=64)),
                ("file_name", models.CharField(default="", max_length=255)),
                ("file_size_kb", models.BigIntegerField(default=0)),
                ("db_size_kb", models.BigIntegerField(default=0)),
                ("compatibility_level", models.IntegerField(default=0)),
                ("local_path", models.CharField(default="", max_length=255)),
            ],
            options={
                "db_table": "tb_sqlserver_dbbackup_result",
                "indexes": [
                    models.Index(fields=["cluster_id", "cluster_domain", "backup_end_time"], name="idx_cluster_time")
                ],
                "unique_together": {
                    ("cluster_id", "cluster_domain", "backup_host", "backup_port", "backup_id", "dbname")
                },
            },
        ),
    ]
