# Generated by Django 4.2.27 on 2026-03-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0032_redischeckreport_db_report_r_subtype_26d26e_idx"),
        ("db_report", "0032_sqlserverbinlogresult_sqlserverbackupresult"),
    ]

    operations = []
