# Generated by Django 4.2.27 on 2026-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0034_alter_redisrollbackexercisereport_task_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlinspectignore",
            name="policy",
            field=models.CharField(
                default="exclude",
                help_text="exclude or include. default empty means exclude",
                max_length=64,
            ),
        ),
    ]
