# Generated by Django 4.2.27 on 2026-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0035_mysqlinspectignore_policy"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="redisbackupcheckreport",
            index=models.Index(
                fields=["subtype", "bk_biz_id", "state", "create_at"], name="db_report_r_subtype_c21f11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redisbackupcheckreport",
            index=models.Index(fields=["subtype", "create_at", "cluster"], name="db_report_r_subtype_22ec30_idx"),
        ),
    ]
