# Generated by Django 4.2.27 on 2026-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0035_mysqlinspectignore_policy"),
        ("db_report", "0035_sqlserverfullbackupcheckreport_and_more"),
    ]

    operations = []
