# Generated by Django 4.2.27 on 2026-04-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0036_merge_20260413_1812"),
        ("db_report", "0036_redisbackupcheckreport_db_report_r_subtype_c21f11_idx_and_more"),
    ]

    operations = []
