# Generated by Django 4.2.27 on 2026-04-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0039_alter_redisrollbackexercisereport_task_stage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mysqlinspectignore",
            unique_together={("cluster", "bk_biz_id", "subtype", "cluster_type")},
        ),
    ]
