# Generated by Django 4.2.27 on 2026-04-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0040_alter_mysqlinspectignore_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlSlowlogAiAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(help_text="业务的id")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "MySQL单节点集群"),
                            ("tendbha", "MySQL高可用集群"),
                            ("tendbcluster", "TendbCluster集群"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("redis", "Redis"),
                            ("PredixyRedisCluster", "RedisCluster集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群"),
                            ("RedisInstance", "TendisCache集群"),
                            ("TendisSSDInstance", "TendisSSD集群"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("doris", "Doris集群"),
                            ("vm", "vm集群"),
                            ("dbmon", "redis监控"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                            ("sqlserver_single", "sqlserver单节点版"),
                            ("sqlserver_ha", "sqlserver主从版"),
                            ("oracle_primary_standby", "oracle主从版"),
                            ("oracle_single_none", "oracle单节点版"),
                            ("k8s_surrealdb", "k8s SurrealDB集群"),
                            ("k8s_victoriametrics", "k8s VictoriaMetrics集群"),
                            ("k8s_risingwave", "k8s Risingwave集群"),
                            ("k8s_milvus", "k8s Milvus集群"),
                            ("k8s_qdrant", "k8s Qdrant集群"),
                            ("k8s_greptimedb", "k8s GreptimeDB集群"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("cluster_domain", models.CharField(help_text="集群域名", max_length=255)),
                ("instance_role", models.CharField(help_text="实例角色", max_length=64)),
                ("time_window_start", models.DateTimeField(help_text="时间窗口开始时间")),
                ("time_window_end", models.DateTimeField(help_text="时间窗口结束时间")),
                ("instance", models.CharField(help_text="实例，为空表示按集群维度分析的", max_length=255)),
                ("analyze_time", models.DateTimeField(help_text="分析时间")),
                ("analyze_result", models.TextField(help_text="分析结果")),
            ],
            options={
                "verbose_name": "MySQL慢日志AI分析结果",
                "verbose_name_plural": "MySQL慢日志AI分析结果",
                "db_table": "tb_mysql_slowlog_ai_analysis",
                "managed": True,
                "index_together": {("cluster_domain", "analyze_time")},
            },
        ),
    ]
