# Generated by Django 4.2.27 on 2026-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0040_alter_mysqlinspectignore_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlserverbackupresult",
            name="backup_file_tag",
            field=models.CharField(default="", max_length=255, verbose_name="备份系统文件过期标签"),
        ),
        migrations.AddField(
            model_name="sqlserverbinlogresult",
            name="backup_file_tag",
            field=models.CharField(default="", max_length=255, verbose_name="备份系统文件过期标签"),
        ),
        migrations.AddField(
            model_name="sqlserverbinlogresult",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
