# Generated by Django 4.2.27 on 2026-05-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0041_sqlserverbackupresult_backup_file_tag_and_more"),
        ("db_report", "0042_alter_kafkabrokeraffinityreport_cluster_type_and_more"),
    ]

    operations = []
