# Generated by Django 4.2.27 on 2026-06-08 07:33

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0044_mysqlpartitionresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlConfigCheckResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(help_text="业务的id")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        help_text="集群类型",
                        max_length=64,
                    ),
                ),
                ("cluster_id", models.IntegerField(default=0, help_text="集群ID")),
                ("cluster_domain", models.CharField(help_text="集群域名", max_length=255)),
                ("cluster_snapshot", models.JSONField(default=dict, help_text="集群基础信息快照")),
                ("analyze_result", models.JSONField(default=dict, help_text="分析结果")),
                ("analyze_time", models.DateTimeField(help_text="分析时间")),
            ],
            options={
                "verbose_name": "集群配置巡检结果",
                "verbose_name_plural": "集群配置巡检结果",
                "db_table": "tb_tendb_config_check_result",
                "managed": True,
                "indexes": [
                    models.Index(fields=["cluster_id", "analyze_time"], name="tb_tendb_co_cluster_26453c_idx"),
                    models.Index(fields=["cluster_domain", "analyze_time"], name="tb_tendb_co_cluster_712176_idx"),
                ],
            },
        ),
    ]
