# Generated by Django 4.2.27 on 2026-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0045_mysqlconfigcheckresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlSqlExecDuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_id", models.PositiveIntegerField(blank=True, db_index=True, help_text="集群ID", null=True)),
                (
                    "cluster_domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="集群主域名（冗余字段，从 db_meta.Cluster.immute_domain 取）",
                        max_length=255,
                    ),
                ),
                ("ticket_id", models.PositiveIntegerField(blank=True, db_index=True, help_text="单据ID", null=True)),
                ("root_id", models.CharField(db_index=True, help_text="流程任务ID", max_length=33)),
                ("job_instance_id", models.BigIntegerField(db_index=True, help_text="蓝鲸作业实例ID")),
                ("step_instance_id", models.BigIntegerField(blank=True, help_text="蓝鲸步骤实例ID", null=True)),
                ("ip", models.CharField(db_index=True, help_text="执行IP", max_length=64)),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域ID")),
                (
                    "db_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="数据库名（来自 USE 语句或 dbactuator marker）",
                        max_length=128,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(blank=True, default="", help_text="表名（暂留空，待 SQL 解析 API 回填）", max_length=255),
                ),
                ("sql_text", models.TextField(help_text="SQL 完整内容")),
                (
                    "sql_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SQL 语句类型（如 SELECT/INSERT/...，暂留空，待 SQL 解析 API 回填）",
                        max_length=32,
                    ),
                ),
                (
                    "sql_checksum",
                    models.CharField(db_index=True, help_text="md5(sql_text) 的 32 位十六进制，用作去重唯一键的一部分", max_length=32),
                ),
                (
                    "table_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="表大小，单位字节。当前阶段以该 SQL 涉及的 db 总大小（SUM(table_size) by db_name）作为占位值；待 SQL 解析 API 给出 table_name 后由 enrich 路径覆盖为精确单表大小",
                        null=True,
                    ),
                ),
                ("duration_sec", models.FloatField(db_index=True, help_text="单条 SQL 执行耗时（秒）")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
            ],
            options={
                "verbose_name": "MySQL SQL 执行耗时",
                "verbose_name_plural": "MySQL SQL 执行耗时",
                "db_table": "tb_mysql_sql_exec_duration",
                "indexes": [
                    models.Index(fields=["cluster_id", "created_at"], name="tb_mysql_sq_cluster_da7046_idx"),
                    models.Index(fields=["ticket_id", "root_id"], name="tb_mysql_sq_ticket__6eb90f_idx"),
                ],
                "unique_together": {("root_id", "job_instance_id", "ip", "sql_checksum")},
            },
        ),
    ]
