# Generated by Django 4.2.30 on 2026-06-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0046_mysqlsqlexecduration"),
        ("db_report", "0046_sqlserver_backup_result_is_repaired"),
    ]

    operations = []
