# Generated by Django 4.2.30 on 2026-07-06 08:06

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0047_merge_20260615_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kafkabrokeraffinityreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="kafkazookeeperaffinityreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="mysqlslowlogaianalysis",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="sqlserverbackupresult",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlserverbackupresult",
            name="is_repaired",
            field=models.BooleanField(default=False, null=True, verbose_name="是否为巡检自动补录"),
        ),
        migrations.AlterField(
            model_name="sqlserverbinlogresult",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlserverfullbackupcheckreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="sqlserverlogbackupcheckreport",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
    ]
