# Generated by Django 4.2.30 on 2026-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0047_alter_kafkabrokeraffinityreport_cluster_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowNodeNameAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("ticket_type", models.CharField(max_length=64, verbose_name="单据类型")),
                ("component_code", models.CharField(max_length=128, verbose_name="组件代码")),
                (
                    "cleaned_name",
                    models.CharField(
                        help_text="原始 name 经 NameCleaner 正则清洗后的字符串（IP/端口/hex 已参数化）",
                        max_length=255,
                        verbose_name="清洗后节点名",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        help_text="最终归入的语义类别代表名；等于自身表示自成一类",
                        max_length=255,
                        verbose_name="归一化节点名",
                    ),
                ),
                (
                    "match_source",
                    models.CharField(
                        choices=[
                            ("first_seen", "首次出现"),
                            ("llm_matched", "LLM 匹配已有类别"),
                            ("llm_new_cluster", "LLM 创建新类别"),
                            ("llm_fallback", "LLM 失败降级"),
                            ("manual", "人工设定"),
                        ],
                        default="first_seen",
                        help_text="记录此条映射如何生成，供审阅与效果评估",
                        max_length=32,
                        verbose_name="归一化来源",
                    ),
                ),
                (
                    "llm_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="LLM 输出的 confidence 字段，取值 0~1；非 LLM 决策为 NULL",
                        null=True,
                        verbose_name="LLM 置信度",
                    ),
                ),
                (
                    "llm_reasoning",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="LLM 输出的 reasoning 文本，供人工审阅；非 LLM 决策为空串",
                        verbose_name="LLM 判定理由",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="LLM 降级或低置信度时置 True，DBA 审阅确认后可置 False",
                        verbose_name="需要人工审阅",
                    ),
                ),
                (
                    "manual_locked",
                    models.BooleanField(
                        default=False, help_text="True 时任何自动流程不得覆盖 normalized_name", verbose_name="人工锁定"
                    ),
                ),
                (
                    "hit_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="此映射被查询命中的累计次数，用于热点观测；不参与业务判定",
                        verbose_name="命中次数",
                    ),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="最近一次被查询命中的时间；用于识别陈旧映射",
                        null=True,
                        verbose_name="最近命中时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程节点名称归一化映射",
                "verbose_name_plural": "流程节点名称归一化映射",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["ticket_type", "component_code", "normalized_name"],
                        name="db_report_f_ticket__901394_idx",
                    ),
                    models.Index(fields=["needs_review", "manual_locked"], name="db_report_f_needs_r_78e1d9_idx"),
                ],
                "unique_together": {("ticket_type", "component_code", "cleaned_name")},
            },
        ),
        migrations.CreateModel(
            name="FlowNodeDurationBaseline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "ticket_type",
                    models.CharField(help_text="如 MYSQL_PARTITION_V2", max_length=64, verbose_name="单据类型"),
                ),
                (
                    "bk_biz_id",
                    models.IntegerField(default=0, help_text="CMDB 业务ID；0 表示跨业务全局基线", verbose_name="业务ID"),
                ),
                (
                    "component_code",
                    models.CharField(
                        help_text="flow tree activity component.code，如 mysql_db_actuator_execute",
                        max_length=128,
                        verbose_name="组件代码",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        help_text="经 NameCleaner + LLM 归一化后的节点名，作为四维 key 之一",
                        max_length=255,
                        verbose_name="归一化节点名",
                    ),
                ),
                (
                    "sample_count",
                    models.BigIntegerField(default=0, help_text="累计有效样本数，用于可靠性判定", verbose_name="样本数量"),
                ),
                (
                    "mean_seconds",
                    models.FloatField(default=0.0, help_text="Welford 算法维护的耗时均值", verbose_name="均值(秒)"),
                ),
                (
                    "stddev_seconds",
                    models.FloatField(default=0.0, help_text="Welford 算法维护的耗时标准差", verbose_name="标准差(秒)"),
                ),
                (
                    "m2_accumulator",
                    models.FloatField(
                        default=0.0,
                        help_text="Welford 中间量 sum((x-mean)^2)，用于增量合并；不供上层直接使用",
                        verbose_name="Welford M2 累计量",
                    ),
                ),
                ("p50_seconds", models.FloatField(default=0.0, verbose_name="P50(秒)")),
                ("p90_seconds", models.FloatField(default=0.0, verbose_name="P90(秒)")),
                ("p95_seconds", models.FloatField(default=0.0, verbose_name="P95(秒)")),
                ("p99_seconds", models.FloatField(default=0.0, verbose_name="P99(秒)")),
                ("min_seconds", models.FloatField(default=0.0, verbose_name="最小值(秒)")),
                ("max_seconds", models.FloatField(default=0.0, verbose_name="最大值(秒)")),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("narrow_unimodal", "窄单峰分布"),
                            ("wide_unimodal", "宽单峰分布"),
                            ("heavy_tailed", "重尾分布"),
                            ("unreliable", "样本不足"),
                        ],
                        default="unreliable",
                        help_text="依据 stddev/mean 与 sample_count 判定；上层应据此决定信任 mean 还是分位数",
                        max_length=32,
                        verbose_name="分布形态",
                    ),
                ),
                (
                    "is_reliable",
                    models.BooleanField(
                        default=False,
                        help_text="sample_count >= 可靠阈值 且 分布形态非 UNRELIABLE 时为 True",
                        verbose_name="是否可靠",
                    ),
                ),
                (
                    "last_sample_finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="已纳入基线的最新一条 flow_node.updated_at；用于诊断增量水位",
                        null=True,
                        verbose_name="最新样本完成时间",
                    ),
                ),
                (
                    "baseline_version",
                    models.PositiveIntegerField(default=1, help_text="每次 rebuild 递增；增量任务不改此值", verbose_name="基线版本号"),
                ),
            ],
            options={
                "verbose_name": "流程节点耗时基线",
                "verbose_name_plural": "流程节点耗时基线",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["bk_biz_id", "ticket_type"], name="db_report_f_bk_biz__39bfe4_idx"),
                    models.Index(
                        fields=["ticket_type", "component_code", "normalized_name"],
                        name="db_report_f_ticket__6e3e7d_idx",
                    ),
                    models.Index(fields=["is_reliable", "distribution_type"], name="db_report_f_is_reli_a68ed4_idx"),
                ],
                "unique_together": {("ticket_type", "bk_biz_id", "component_code", "normalized_name")},
            },
        ),
        migrations.CreateModel(
            name="FlowNodeBaselineWatermark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("ticket_type", models.CharField(max_length=64, verbose_name="单据类型")),
                (
                    "bk_biz_id",
                    models.IntegerField(default=0, help_text="CMDB 业务ID；0 表示全局基线维度", verbose_name="业务ID"),
                ),
                (
                    "last_processed_finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="已纳入基线的最新一条 flow_node.updated_at；下次增量的 since 起点",
                        null=True,
                        verbose_name="已处理最新样本时间",
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="最近一次增量任务执行完成的时间；用于诊断任务是否卡住",
                        null=True,
                        verbose_name="最近一次运行时间",
                    ),
                ),
                (
                    "last_run_sample_count",
                    models.IntegerField(
                        default=0,
                        help_text="最近一次增量任务处理的样本数量；用于识别异常波动",
                        verbose_name="最近一次运行处理样本数",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程节点基线增量水位",
                "verbose_name_plural": "流程节点基线增量水位",
                "abstract": False,
                "unique_together": {("ticket_type", "bk_biz_id")},
            },
        ),
    ]
