# Generated by Django 4.2.30 on 2026-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0048_flownodenamealias_flownodedurationbaseline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowNodeSampleReject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "root_id",
                    models.CharField(
                        help_text="对应 FlowTree.root_id，可用于反查原始流程",
                        max_length=64,
                        verbose_name="流程 root_id",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="对应 FlowNode.node_id，可用于反查原始节点",
                        max_length=64,
                        verbose_name="节点 node_id",
                    ),
                ),
                (
                    "bk_biz_id",
                    models.IntegerField(default=0, help_text="CMDB 业务ID；0 表示未知/跨业务", verbose_name="业务ID"),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        default="",
                        help_text="如 MYSQL_PARTITION_V2；空表示 flow_tree 未取到",
                        max_length=64,
                        verbose_name="单据类型",
                    ),
                ),
                (
                    "component_code",
                    models.CharField(
                        default="",
                        help_text="flow tree activity component.code；空表示 tree 缺失该字段",
                        max_length=128,
                        verbose_name="组件代码",
                    ),
                ),
                (
                    "raw_name",
                    models.CharField(
                        default="",
                        help_text="flow tree activity.name 原文，未清洗；仅用于人工识别",
                        max_length=255,
                        verbose_name="原始节点名",
                    ),
                ),
                (
                    "duration_seconds",
                    models.BigIntegerField(
                        default=0,
                        help_text="(node.updated_at - node.started_at) 秒数；照实存储不截断",
                        verbose_name="原始耗时(秒)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="对应 FlowNode.started_at；用于时序核对",
                        null=True,
                        verbose_name="节点开始时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="对应 FlowNode.updated_at（最后一次进入 FINISHED）；用于时序核对",
                        null=True,
                        verbose_name="节点结束时间",
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(
                        choices=[("too_short", "耗时过短(疑似时钟回拨)"), ("too_long", "耗时过长(疑似节点悬挂)")],
                        help_text="仅两种：too_short(时钟回拨) / too_long(节点悬挂)",
                        max_length=32,
                        verbose_name="拒绝原因",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程节点样本拒绝档案",
                "verbose_name_plural": "流程节点样本拒绝档案",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["reject_reason", "duration_seconds"], name="db_report_f_reject__e707a5_idx"),
                    models.Index(fields=["bk_biz_id", "ticket_type"], name="db_report_f_bk_biz__236c36_idx"),
                    models.Index(fields=["component_code"], name="db_report_f_compone_57cb6e_idx"),
                ],
                "unique_together": {("root_id", "node_id")},
            },
        ),
    ]
