# Generated by Django 4.2.30 on 2026-07-10 04:45

from django.db import migrations, models

from backend.configuration.constants import DBType


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0049_mysqlclusterskewreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortraitDimensionSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(help_text="CMDB 业务 ID", verbose_name="业务ID")),
                (
                    "cluster_domain",
                    models.CharField(help_text="集群不可变主域名，作为画像检索维度", max_length=255, verbose_name="集群域名"),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        help_text="集群所属 DB 类型，与 tb_portrait_dimension_registry.db_type 对齐",
                        max_length=32,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="维度稳定标识，与 tb_portrait_dimension_registry.code 对齐",
                        max_length=64,
                        verbose_name="维度编码",
                    ),
                ),
                (
                    "report_time",
                    models.DateTimeField(help_text="本次巡检产出的业务时间，精确到秒；Agent 按 time_range 过滤", verbose_name="巡检时间"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="单次巡检的摘要文本；示例：'近 24h 慢日志同比上涨 32%，top1 SQL 未走索引'",
                        verbose_name="巡检摘要",
                    ),
                ),
                (
                    "detail_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="本次巡检产出的详情页完整链接，前端画像报告在该维度卡片提供跳转",
                        max_length=1024,
                        verbose_name="详情页URL",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "集群画像-维度巡检摘要",
                "verbose_name_plural": "集群画像-维度巡检摘要",
                "db_table": "tb_portrait_dimension_summary",
                "managed": True,
                "indexes": [
                    models.Index(fields=["cluster_domain", "code", "-report_time"], name="idx_pt_sum_cluster_code_t"),
                    models.Index(fields=["bk_biz_id", "db_type", "-report_time"], name="idx_pt_sum_biz_dbtype_t"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PortraitDimensionRegistry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        help_text="巡检维度所属的数据库类型，如 mysql/redis/sqlserver 等",
                        max_length=32,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="维度稳定标识，同一 db_type 下唯一，示例：slow_query / config_check / cluster_skew",
                        max_length=64,
                        verbose_name="维度编码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="维度中文名，用于前端展示和 LLM Prompt 中的自然语言引用",
                        max_length=128,
                        verbose_name="维度名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="用于 LLM 理解本维度语义的说明，建议 100~300 字，描述检查内容与产出的 summary 语义",
                        verbose_name="维度描述",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="False 表示该维度暂不参与集群画像分析", verbose_name="是否启用"),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "集群画像-维度注册表",
                "verbose_name_plural": "集群画像-维度注册表",
                "db_table": "tb_portrait_dimension_registry",
                "managed": True,
                "indexes": [models.Index(fields=["db_type", "enabled"], name="idx_portrait_dim_dbtype_enable")],
            },
        ),
        migrations.AddConstraint(
            model_name="portraitdimensionregistry",
            constraint=models.UniqueConstraint(fields=("db_type", "code"), name="uniq_portrait_dim_dbtype_code"),
        ),
    ]
