# Generated by Django 4.2.30 on 2026-07-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0048_alter_kafkabrokeraffinityreport_cluster_type_and_more"),
        ("db_report", "0049_flownodesamplereject"),
    ]

    operations = []
