# Generated by Django 4.2.30 on 2026-07-15 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0049_mysqlclusterskewreport"),
        ("db_report", "0049_portraitdimensionsummary_portraitdimensionregistry_and_more"),
    ]

    operations = []
