# Generated by Django 4.2.30 on 2026-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0049_portraitdimensionsummary_portraitdimensionregistry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlConfigAiInspect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("batch_id", models.CharField(default="", help_text="批次 ID", max_length=64)),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务 ID")),
                ("cluster_id", models.IntegerField(default=0, help_text="集群 ID")),
                ("cluster_domain", models.CharField(default="", help_text="集群域名", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "MySQL单节点集群"),
                            ("tendbha", "MySQL高可用集群"),
                            ("tendbcluster", "TendbCluster集群"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("mysqldts", "MySQLDTS"),
                            ("redis", "Redis"),
                            ("PredixyRedisCluster", "RedisCluster集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("PredixyTendisplusInstance", "TendisPlus 标准版"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群"),
                            ("RedisInstance", "TendisCache集群"),
                            ("TendisSSDInstance", "TendisSSD集群"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("doris", "Doris集群"),
                            ("vm", "vm集群"),
                            ("dbmon", "redis监控"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                            ("sqlserver_single", "sqlserver单节点版"),
                            ("sqlserver_ha", "sqlserver主从版"),
                            ("oracle_primary_standby", "oracle主从版"),
                            ("oracle_single_none", "oracle单节点版"),
                            ("k8s_surrealdb_ha", "k8s SurrealDB集群版"),
                            ("k8s_surrealdb_single", "k8s SurrealDB单机版"),
                            ("k8s_victoriametrics_ha", "k8s VictoriaMetrics集群版"),
                            ("k8s_risingwave_ha", "k8s Risingwave集群版"),
                            ("k8s_greptimedb_ha", "k8s GreptimeDB集群版"),
                            ("k8s_milvus_ha", "k8s Milvus集群版"),
                            ("k8s_qdrant_ha", "k8s Qdrant集群版"),
                        ],
                        default="",
                        help_text="集群类型",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        help_text="巡检状态",
                        max_length=32,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0, help_text="已尝试次数")),
                ("report_id", models.CharField(default="", help_text="报告 ID", max_length=64)),
                ("share_url", models.CharField(default="", help_text="报告分享完整链接", max_length=512)),
                ("summary", models.TextField(default="", help_text="巡检总结")),
                ("agent_cost_ms", models.IntegerField(default=0, help_text="Agent 耗时（毫秒）")),
                ("error_msg", models.TextField(default="", help_text="失败原因")),
            ],
            options={
                "verbose_name": "MySQL配置AI巡检",
                "verbose_name_plural": "MySQL配置AI巡检",
                "db_table": "tb_mysql_config_ai_inspect",
                "managed": True,
                "indexes": [
                    models.Index(fields=["batch_id", "status"], name="idx_cfg_ai_insp_batch_status"),
                    models.Index(fields=["cluster_domain", "create_at"], name="idx_cfg_ai_insp_domain_create"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mysqlconfigaiinspect",
            constraint=models.UniqueConstraint(
                fields=("batch_id", "cluster_id"), name="uniq_cfg_ai_insp_batch_cluster"
            ),
        ),
    ]
