# Generated by Django 4.2.30 on 2026-07-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0049_mysqlclusterskewreport"),
        ("db_report", "0050_merge_20260708_1739"),
    ]

    operations = []
