# Generated by Django 4.2.30 on 2026-08-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0050_mysql_config_ai_inspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqlclusterskewreport",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("tendbsingle", "MySQL单节点集群"),
                    ("tendbha", "MySQL高可用集群"),
                    ("tendbcluster", "TendbCluster集群"),
                    ("tbinlogdumper", "TBinlogDumper"),
                    ("mysqldts", "MySQLDTS"),
                    ("redis", "Redis"),
                    ("PredixyRedisCluster", "RedisCluster集群"),
                    ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                    ("PredixyTendisplusInstance", "TendisPlus 标准版"),
                    ("TwemproxyRedisInstance", "TendisCache集群"),
                    ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                    ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                    ("RedisInstance", "RedisCache主从版"),
                    ("TendisSSDInstance", "TendisSSD主从版"),
                    ("TendisplusInstance", "Tendisplus主从版"),
                    ("RedisCluster", "RedisCluster集群"),
                    ("TendisplusCluster", "TendisplusCluster集群"),
                    ("TendisplusInstance", "Tendisplus存储版集群"),
                    ("RedisInstance", "TendisCache集群"),
                    ("TendisSSDInstance", "TendisSSD集群"),
                    ("es", "ES集群"),
                    ("kafka", "Kafka集群"),
                    ("hdfs", "Hdfs集群"),
                    ("influxdb", "Influxdb实例"),
                    ("pulsar", "Pulsar集群"),
                    ("doris", "Doris集群"),
                    ("vm", "vm集群"),
                    ("dbmon", "redis监控"),
                    ("MongoReplicaSet", "Mongo副本集"),
                    ("MongoShardedCluster", "Mongo分片集群"),
                    ("riak", "Riak集群"),
                    ("sqlserver_single", "sqlserver单节点版"),
                    ("sqlserver_ha", "sqlserver主从版"),
                    ("oracle_primary_standby", "oracle主从版"),
                    ("oracle_single_none", "oracle单节点版"),
                    ("k8s_surrealdb_ha", "k8s SurrealDB集群版"),
                    ("k8s_surrealdb_single", "k8s SurrealDB单机版"),
                    ("k8s_victoriametrics_ha", "k8s VictoriaMetrics集群版"),
                    ("k8s_risingwave_ha", "k8s Risingwave集群版"),
                    ("k8s_greptimedb_ha", "k8s GreptimeDB集群版"),
                    ("k8s_milvus_ha", "k8s Milvus集群版"),
                    ("k8s_qdrant_ha", "k8s Qdrant集群版"),
                ],
                default="",
                help_text="集群类型",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="mysqlsqlexecduration",
            name="sql_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SQL 语句类型（来自解析 API 的 command，如 update/delete/alter_table/drop_db）",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="mysqlsqlexecduration",
            name="table_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="表名（来自 SQL 解析 API，多表逗号拼接；drop_db 等场景可为空）",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mysqlsqlexecduration",
            name="table_size",
            field=models.BigIntegerField(
                blank=True,
                help_text="大小，单位字节。表级 SQL 为涉及表 size 之和；drop_db 为逻辑库 database_size；call/过程函数等不查 size 时为 NULL",
                null=True,
            ),
        ),
    ]
