# Generated by Django 4.2.27 on 2026-07-16 00:00

from django.db import migrations, models

import backend.db_report.enums.redis_rollback_exercise_task_stage


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0050_mysql_config_ai_inspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redisrollbackexercisereport",
            name="task_stage",
            field=models.CharField(
                choices=[
                    ("task_generated", "任务已生成"),
                    ("skipped", "已跳过"),
                    ("backup_invalid", "备份不可用"),
                    ("ticket_gen_failed", "单据生成失败"),
                    ("ticket_generated", "单据已生成"),
                    ("resource_appli_failed", "资源申请失败"),
                    ("resource_appli_succeeded", "资源申请成功"),
                    ("rollback_started", "回档开始"),
                    ("rollback_failed", "回档失败"),
                    ("rollback_succeeded", "回档成功"),
                    ("cleanup_failed", "清理失败"),
                    ("scene_preserved", "现场保留待排查"),
                    ("done", "已完成"),
                ],
                default=backend.db_report.enums.redis_rollback_exercise_task_stage.RedisRollbackExerciseTaskStage[
                    "TASK_GENERATED"
                ],
                help_text="当前任务执行阶段",
                max_length=32,
                verbose_name="任务阶段",
            ),
        ),
    ]
