# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0051_alter_redisrollbackexercisereport_task_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlSqlFileExecDuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticket_id", models.PositiveIntegerField(db_index=True, verbose_name="单据ID")),
                ("cluster_id", models.PositiveIntegerField(db_index=True, verbose_name="集群ID")),
                (
                    "cluster_domain",
                    models.CharField(blank=True, db_index=True, default="", max_length=255, verbose_name="集群主域名"),
                ),
                ("db_name", models.CharField(db_index=True, max_length=128, verbose_name="数据库名")),
                ("sql_file", models.CharField(max_length=255, verbose_name="SQL文件名")),
                (
                    "sql_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="BKRepo 对象路径，如 mysql/sqlfile/{biz}/foo.sql，不含 project/bucket",
                        max_length=512,
                        verbose_name="SQL文件制品库路径",
                    ),
                ),
                ("duration_sec", models.IntegerField(verbose_name="执行耗时(秒)")),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "root_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=33, verbose_name="流程任务ID"),
                ),
                ("ip", models.CharField(blank=True, default="", max_length=64, verbose_name="执行IP")),
                ("port", models.IntegerField(blank=True, null=True, verbose_name="执行端口")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "MySQL SQL文件执行耗时",
                "verbose_name_plural": "MySQL SQL文件执行耗时",
                "db_table": "tb_mysql_sql_file_exec_duration",
                "unique_together": {("ticket_id", "cluster_id", "db_name", "sql_file")},
            },
        ),
    ]
