# Generated by Django 4.2.30 on 2026-08-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0051_alter_mysqlclusterskewreport_cluster_type_and_more"),
        ("db_report", "0051_alter_redisrollbackexercisereport_task_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterPortraitReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="CMDB 业务 ID", verbose_name="业务ID")),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("tendbcluster", "TenDBCluster"),
                            ("redis", "Redis"),
                            ("mongodb", "MongoDB"),
                            ("kafka", "Kafka"),
                            ("hdfs", "HDFS"),
                            ("es", "ElasticSearch"),
                            ("pulsar", "Pulsar"),
                            ("influxdb", "InfluxDB"),
                            ("riak", "Riak"),
                            ("sqlserver", "SQLServer"),
                            ("doris", "Doris"),
                            ("vm", "Vm"),
                            ("oracle", "Oracle"),
                            ("k8s_surrealdb", "K8s SurrealDB"),
                            ("k8s_victoriametrics", "K8s VictoriaMetrics"),
                            ("k8s_risingwave", "K8s Risingwave"),
                            ("k8s_milvus", "K8s Milvus"),
                            ("k8s_qdrant", "K8s Qdrant"),
                            ("k8s_greptimedb", "K8s GreptimeDB"),
                            ("cloud", "Cloud"),
                            ("tbinlogdumper", "TBinlogDumper"),
                        ],
                        default="",
                        help_text="集群所属 DB 类型，与 tb_portrait_dimension_registry.db_type 对齐",
                        max_length=32,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "cluster_domain",
                    models.CharField(
                        default="",
                        help_text="集群不可变主域名，作为画像报告的主检索键",
                        max_length=255,
                        verbose_name="集群域名",
                    ),
                ),
                (
                    "report_from_time",
                    models.DateTimeField(help_text="本次画像分析所覆盖的时间窗起点（业务时间）", verbose_name="报告时间段起始"),
                ),
                (
                    "report_to_time",
                    models.DateTimeField(help_text="本次画像分析所覆盖的时间窗终点（业务时间）", verbose_name="报告时间段结束"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="本次画像报告的整体摘要文本；空字符串代表无风险要点",
                        verbose_name="报告摘要",
                    ),
                ),
                (
                    "share_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="前端可访问的完整画像报告页面链接",
                        max_length=512,
                        verbose_name="报告分享链接",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=-1,
                        help_text="报告综合健康分；-1 表示未上报或分数系统未开启，正常范围 0~100",
                        verbose_name="报告健康分",
                    ),
                ),
            ],
            options={
                "verbose_name": "集群画像-报告基础信息",
                "verbose_name_plural": "集群画像-报告基础信息",
                "db_table": "tb_cluster_portrait_report",
                "indexes": [
                    models.Index(fields=["cluster_domain", "report_from_time"], name="idx_portrait_rep_domain_from"),
                    models.Index(
                        fields=["bk_biz_id", "db_type", "report_from_time"], name="idx_portrait_rep_biz_dbtype"
                    ),
                ],
            },
        ),
    ]
