# Generated by Django 4.2.30 on 2026-09-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_report", "0052_mysqlsqlfileexecduration"),
        ("db_report", "0053_portraitdimension_weight_strategy_score"),
    ]

    operations = []
