# Generated by Django 3.2.19 on 2024-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalUserMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_username", models.CharField(max_length=64, unique=True, verbose_name="外部用户名")),
                ("internal_username", models.CharField(max_length=64, verbose_name="内部用户名")),
            ],
        ),
    ]
