files: ^dbm-ui/backend/
fail_fast: true
repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--config=./dbm-ui/pyproject.toml]
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    args: [--config=./dbm-ui/backend/.flake8]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
