# use parent values

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}

livenessProbe: {}

readinessProbe: {}

initJob:
  resources: {}

saas:
  api:
    enabled: true
    resources: {}
    replicaCount: 1
    gunicornWorker: 8
  celeryBeat:
    enabled: true
    resources: {}
    replicaCount: 1
  celeryWorker:
    enabled: true
    resources: {}
    replicaCount: 1
  pipelineWorker:
    enabled: true
    resources: {}
    replicaCount: 1
