USE MASTER
SET QUOTED_IDENTIFIER ON
SET NOCOUNT ON
GO


EXEC SP_CONFIGURE 'SHOW ADVANCED OPTIONS',1
GO
RECONFIGURE;
GO

EXEC SP_CONFIGURE 'CROSS DB OWNERSHIP CHAINING',1
EXEC SP_CONFIGURE 'AGENT XPS',1
exec SP_CONFIGURE 'remote access',1
EXEC SP_CONFIGURE 'REMOTE ADMIN CONNECTIONS',0
EXEC SP_CONFIGURE 'XP_CMDSHELL',1
EXEC SP_CONFIGURE 'C2 AUDIT MODE',0
EXEC SP_CONFIGURE 'RECOVERY INTERVAL',0
EXEC SP_CONFIGURE 'FILL FACTOR (%)',80
EXEC SP_CONFIGURE 'ALLOW UPDATES',0
EXEC SP_CONFIGURE 'BACKUP COMPRESSION DEFAULT',1
EXEC SP_CONFIGURE 'AD HOC DISTRIBUTED QUERIES',1
EXEC SP_CONFIGURE 'SMO and DMO XPs',1

GO
RECONFIGURE
GO

EXEC SP_CONFIGURE 'SHOW ADVANCED OPTIONS',0
GO
RECONFIGURE;
GO