USE MASTER
SET QUOTED_IDENTIFIER ON
SET NOCOUNT ON
GO

DECLARE @SQL VARCHAR(8000)
SELECT @SQL = ISNULL(@SQL+'
','')+'EXEC SP_TRACE_SETSTATUS '+LTRIM(ID)+',0;EXEC SP_TRACE_SETSTATUS '+LTRIM(ID)+',2;'
FROM SYS.TRACES A
-- WHERE A.IS_DEFAULT = 0
select @SQL
--EXEC(@SQL)
--GO
