# Generated by Django 3.2.19 on 2023-07-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirtyMachine",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID")),
                (
                    "bk_host_id",
                    models.PositiveBigIntegerField(default=0, help_text="主机ID", primary_key=True, serialize=False),
                ),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="主机云区域")),
                ("ip", models.CharField(help_text="主机IP", max_length=128)),
                (
                    "flow",
                    models.ForeignKey(help_text="关联任务", on_delete=django.db.models.deletion.CASCADE, to="ticket.flow"),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="关联单据", on_delete=django.db.models.deletion.CASCADE, to="ticket.ticket"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
