# Generated by Django 3.2.25 on 2024-06-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_dirty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dirtymachine",
            options={"verbose_name": "污点池机器(DirtyMachine)", "verbose_name_plural": "污点池机器(DirtyMachine)"},
        ),
    ]
