# Generated by Django 3.2.25 on 2024-11-15 07:21

from django.db import migrations, models

from backend.db_dirty.constants import PoolType


class Migration(migrations.Migration):

    dependencies = [
        ("db_dirty", "0003_auto_20240925_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dirtymachine",
            name="device_class",
            field=models.CharField(blank=True, default="", help_text="机型", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machineevent",
            name="to",
            field=models.CharField(
                blank=True, choices=PoolType.get_choices(), help_text="资源流向", max_length=128, null=True
            ),
        ),
    ]
