# Generated by Django 3.2.25 on 2025-03-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_dirty", "0004_auto_20241115_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineevent",
            name="remark",
            field=models.CharField(default="", help_text="备注", max_length=255),
        ),
    ]
