# Generated by Django 3.2.25 on 2025-03-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_dirty", "0005_machineevent_remark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dirtymachine",
            name="bk_biz_id",
        ),
    ]
