{{- if .Values.global.enableMultiTenantMode -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-router.fullname" . }}
  labels:
    {{- include "tenant-router.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tenant-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # 配置变更自动滚动（依赖 stakater reloader）
        reloader.stakater.com/auto: "true"
      labels:
        {{- include "tenant-router.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.imageRegistry | default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: bk-dbm-tenant-router-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
