{{- if .Values.global.enableMultiTenantMode -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-router.fullname" . }}
  labels:
    {{- include "tenant-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tenant-router.selectorLabels" . | nindent 4 }}
{{- end }}
