apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dbs
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-dbs
  template:
    metadata:
      labels:
        app: k8s-dbs
    spec:
      containers:
        - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          name: dbs
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          command: ["/app/server"]
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
          env:
          - name: LOG_LEVEL
            value: "{{ .Values.server.log.log_level }}"
          - name: LOG_MAX_SIZE_MB
            value: "{{ .Values.server.log.max_size_mb }}"
          - name: LOG_MAX_BACKUPS
            value: "{{ .Values.server.log.max_backups }}"
          - name: LOG_MAX_AGE
            value: "{{ .Values.server.log.max_age }}"
          - name: LOG_COMPRESS
            value: "{{ .Values.server.log.compress }}"
          - name: VM_METRIC_SERVER_HOST
            value: "{{ .Values.server.vmMetricServerHost }}"
          - name: VM_METRIC_SERVER_PORT
            value: "{{ .Values.server.vmMetricServerPort }}"
          - name: TZ
            value: {{ .Values.server.timezone }}
          - name: AUTH_MYSQL_HOST
            value: "{{ .Values.server.datasource.auth.host }}"
          - name: AUTH_MYSQL_PORT
            value: "{{ .Values.server.datasource.auth.port }}"
          - name: AUTH_MYSQL_USER
            value: "{{ .Values.server.datasource.auth.user }}"
          - name: AUTH_MYSQL_PASSWORD
            value: "{{ .Values.server.datasource.auth.password }}"
          - name: AUTH_MYSQL_DBNAME
            value: "{{ .Values.server.datasource.auth.dbname }}"
          - name: AUTH_MYSQL_TLSMODE
            value: "{{ .Values.server.datasource.auth.tlsmode }}"
          - name: AUTH_MYSQL_MAX_OPEN_CONN
            value: "{{ .Values.server.datasource.auth.maxOpenConns }}"
          - name: AUTH_MYSQL_MAX_IDLE_CONN
            value: "{{ .Values.server.datasource.auth.maxIdelConns }}"
          - name: AUTH_MYSQL_MAX_LIFETIME
            value: "{{ .Values.server.datasource.auth.maxLifeTime }}"
          - name: DBS_MYSQL_HOST
            value: "{{ .Values.server.datasource.dbs.host }}"
          - name: DBS_MYSQL_PORT
            value: "{{ .Values.server.datasource.dbs.port }}"
          - name: DBS_MYSQL_USER
            value: "{{ .Values.server.datasource.dbs.user }}"
          - name: DBS_MYSQL_PASSWORD
            value: "{{ .Values.server.datasource.dbs.password }}"
          - name: DBS_MYSQL_DBNAME
            value: "{{ .Values.server.datasource.dbs.dbname }}"
          - name: DBS_MYSQL_TLSMODE
            value: "{{ .Values.server.datasource.dbs.tlsmode }}"
          - name: DBS_MYSQL_MAX_OPEN_CONN
            value: "{{ .Values.server.datasource.dbs.maxOpenConns }}"
          - name: DBS_MYSQL_MAX_IDLE_CONN
            value: "{{ .Values.server.datasource.dbs.maxIdelConns }}"
          - name: DBS_MYSQL_MAX_LIFETIME
            value: "{{ .Values.server.datasource.dbs.maxLifeTime }}"
          # dbm api 配置
          - name: ASYNC_TO_DBM
            value: "{{ .Values.server.dbmConfig.asyncToDbm }}"
          - name: DBM_SYNCDATA_API_URL
            value: "{{ .Values.server.dbmConfig.syncDataApiUrl }}"
          - name: DBM_AUTH_API_URL
            value: "{{ .Values.server.dbmConfig.dbmAuthApiUrl }}"
          - name: K8S_DBS_IAM_EXEMPT_STORAGE_WHITELIST
            value: "{{ .Values.server.dbmConfig.iamExemptStorageWhitelist }}"
          - name: BKBASE_BIZ_API_URL
            value: "{{ .Values.server.dbmConfig.bkbaseBizApiUrl }}"
          - name: INNER_BK_APP_CODE
            value: "{{ .Values.server.dbmConfig.innerBkAppCode }}"
          - name: INNER_BK_APP_SECRET
            value: "{{ .Values.server.dbmConfig.innerBkAppSecret }}"
          - name: BKBASE_BK_BIZ_ID
            value: "{{ .Values.server.dbmConfig.bkbaseBkBizId }}"
          # clb api 配置
          - name: BKBASE_CLB_API_URL
            value: "{{ .Values.server.clbApiConfig.clbApiURL }}"
          - name: BKBASE_CLB_USERNAME
            value: "{{ .Values.server.clbApiConfig.username }}"
          - name: BKBASE_CLB_BACKUP_USERNAME
            value: "{{ .Values.server.clbApiConfig.backupUsername }}"
          - name: BKBASE_CLB_OPERATION_PRODUCT
            value: "{{ .Values.server.clbApiConfig.operationProduct }}"
          - name: BKBASE_CLB_FIRST_LEVEL_BIZ
            value: "{{ .Values.server.clbApiConfig.firstLevelBiz }}"
          - name: BKBASE_CLB_SECOND_LEVEL_BIZ
            value: "{{ .Values.server.clbApiConfig.secondLevelBiz }}"
