# Generated by Django 3.2.19 on 2023-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TendisDtsServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_cloud_id", models.BigIntegerField(default=0, verbose_name="云区域ID")),
                ("ip", models.CharField(default="", max_length=128, verbose_name="DTS_Server IP")),
                ("city_id", models.IntegerField(default=0, verbose_name="城市ID")),
                ("city_name", models.CharField(default="", max_length=128, verbose_name="城市名")),
                ("status", models.IntegerField(default=0, verbose_name="状态")),
                ("heartbeat_time", models.DateTimeField(default="1997-01-01 00:00:00", verbose_name="最近心跳时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "db_table": "tb_tendis_dts_server",
            },
        ),
        migrations.AddIndex(
            model_name="tendisdtsserver",
            index=models.Index(fields=["update_time"], name="index_update_time"),
        ),
        migrations.AddConstraint(
            model_name="tendisdtsserver",
            constraint=models.UniqueConstraint(fields=("bk_cloud_id", "ip"), name="unique_tendis_dts_server"),
        ),
    ]
