# Generated by Django 3.2.19 on 2023-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0002_auto_20230629_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="last_data_check_repair_bill_execute_time",
            field=models.DateTimeField(null=True, verbose_name="最近一次数据校验与修复 单据执行时间"),
        ),
        migrations.AddField(
            model_name="tbtendisdtstask",
            name="src_twemproxy_hash_tag_enabled",
            field=models.IntegerField(default=0, verbose_name="源twemproxy集群是否开启hash_tag"),
        ),
    ]
