# Generated by Django 3.2.19 on 2023-07-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_dts", "0003_auto_20230703_2114"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbtendisdtsjob",
            old_name="last_data_check_repair_bill_execute_time",
            new_name="last_data_check_repair_flow_execute_time",
        ),
        migrations.RenameField(
            model_name="tbtendisdtsjob",
            old_name="last_data_check_repair_bill_status",
            new_name="last_data_check_repair_flow_status",
        ),
        migrations.RemoveField(
            model_name="tbtendisdtsjob",
            name="last_data_check_repair_bill_id",
        ),
        migrations.AddField(
            model_name="tbtendisdtsjob",
            name="last_data_check_repair_flow_id",
            field=models.CharField(default="", max_length=64, verbose_name="最近一次数据校验与修复 flow id"),
        ),
    ]
