# Generated by Django 3.2.25 on 2025-10-15 04:38

import django.db.models.deletion
from django.db import migrations, models

from backend.configuration.constants import DBType
from backend.db_services.risk_memo.constants import RiskOpType, RiskPriority, Status


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskMemo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(default="", help_text="风险名称", max_length=64)),
                ("bk_biz_id", models.IntegerField(default=0)),
                (
                    "level",
                    models.CharField(
                        choices=RiskPriority.get_choices(), default="Middle", help_text="风险等级", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=Status.get_choices(), default="backlog", help_text="风险状态", max_length=32),
                ),
                (
                    "db_type",
                    models.CharField(choices=DBType.get_choices(), default="", help_text="影响DB", max_length=64),
                ),
                ("description", models.TextField(default="", help_text="风险描述")),
                ("biz_inpact", models.CharField(default="", help_text="业务影响", max_length=255)),
                ("inpact_cluster", models.CharField(default="", help_text="影响集群", max_length=255)),
                ("is_special", models.BooleanField(default=False, help_text="是否特殊")),
                ("duration_time", models.IntegerField(default=0)),
                ("finalist", models.CharField(default="", help_text="结项人", max_length=64)),
                ("final_time", models.DateTimeField(blank=True, help_text="结项时间", null=True)),
                ("final_content", models.TextField(blank=True, help_text="结项内容", null=True)),
            ],
            options={
                "verbose_name": "风险备忘录数据表",
                "verbose_name_plural": "风险备忘录数据表",
                "db_table": "tb_risk_memo",
            },
        ),
        migrations.CreateModel(
            name="RiskOperateRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("oper_type", models.CharField(choices=RiskOpType.get_choices(), default="", max_length=64)),
                (
                    "risk",
                    models.ForeignKey(
                        help_text="关联风险备忘录", on_delete=django.db.models.deletion.CASCADE, to="risk_memo.riskmemo"
                    ),
                ),
            ],
            options={
                "verbose_name": "风险操作记录表",
                "verbose_name_plural": "风险操作记录表",
                "db_table": "tb_risk_oper_record",
            },
        ),
        migrations.CreateModel(
            name="RiskMemoFollowUp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("content", models.TextField(blank=True, help_text="跟进内容", null=True)),
                (
                    "risk",
                    models.ForeignKey(
                        help_text="关联风险备忘录", on_delete=django.db.models.deletion.CASCADE, to="risk_memo.riskmemo"
                    ),
                ),
            ],
            options={
                "verbose_name": "风险备忘录跟进表",
                "verbose_name_plural": "风险备忘录跟进表",
                "db_table": "tb_risk_memo_follow_up",
            },
        ),
    ]
