# Generated by Django 3.2.25 on 2025-09-19 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskMemo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(default="", help_text="风险名称", max_length=64)),
                ("bk_biz_id", models.IntegerField(default=0)),
                (
                    "level",
                    models.CharField(
                        choices=[("Low", "低"), ("Middle", "中"), ("High", "高")],
                        default="Low",
                        help_text="风险等级",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("backlog", "进行中"), ("done", "结项")],
                        default="backlog",
                        help_text="风险状态",
                        max_length=32,
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("tendbcluster", "TenDBCluster"),
                            ("redis", "Redis"),
                            ("mongodb", "MongoDB"),
                            ("kafka", "Kafka"),
                            ("hdfs", "HDFS"),
                            ("es", "ElasticSearch"),
                            ("pulsar", "Pulsar"),
                            ("influxdb", "InfluxDB"),
                            ("riak", "Riak"),
                            ("sqlserver", "SQLServer"),
                            ("doris", "Doris"),
                            ("vm", "Vm"),
                            ("oracle", "Oracle"),
                            ("cloud", "Cloud"),
                            ("tbinlogdumper", "TBinlogDumper"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(default="", help_text="风险描述")),
                (
                    "biz_inpact",
                    models.CharField(choices=[("online", "在线"), ("login", "登录")], default="", max_length=64),
                ),
                ("inpact_cluster", models.TextField()),
                ("is_special", models.BooleanField(default=False, help_text="是否特殊")),
                ("duration_time", models.IntegerField(default=0)),
                ("finalist", models.CharField(default="", help_text="结项人", max_length=64)),
                ("final_time", models.CharField(blank=True, help_text="结项时间", max_length=32, null=True)),
                ("final_content", models.TextField(blank=True, help_text="结项内容", null=True)),
            ],
            options={
                "verbose_name": "风险备忘录数据表",
                "verbose_name_plural": "风险备忘录数据表",
                "db_table": "tb_risk_memo",
            },
        ),
        migrations.CreateModel(
            name="RiskOperateRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "oper_type",
                    models.CharField(
                        choices=[
                            ("create_risk", "创建风险"),
                            ("create_require", "创建要求"),
                            ("create_follow_up", "添加跟进"),
                            ("update_risk", "修改风险"),
                            ("update_require", "修改要求"),
                            ("update_follow_up", "修改跟进内容"),
                            ("delete_risk", "删除风险"),
                            ("delete_follow_up", "删除跟进"),
                            ("restart_risk", "重启风险"),
                            ("restart_require", "重启要求"),
                            ("final", "结项"),
                            ("final_require", "标记为失效"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        help_text="关联风险备忘录", on_delete=django.db.models.deletion.CASCADE, to="risk_memo.riskmemo"
                    ),
                ),
            ],
            options={
                "verbose_name": "风险操作记录表",
                "verbose_name_plural": "风险操作记录表",
                "db_table": "tb_risk_oper_record",
            },
        ),
        migrations.CreateModel(
            name="RiskMemoFollowUp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("content", models.TextField(blank=True, help_text="跟进内容", null=True)),
                (
                    "risk",
                    models.ForeignKey(
                        help_text="关联风险备忘录", on_delete=django.db.models.deletion.CASCADE, to="risk_memo.riskmemo"
                    ),
                ),
            ],
            options={
                "verbose_name": "风险备忘录跟进表",
                "verbose_name_plural": "风险备忘录跟进表",
                "db_table": "tb_risk_memo_follow_up",
            },
        ),
    ]
