# Generated by Django 3.2.25 on 2025-09-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_memo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskmemo",
            name="biz_inpact",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="riskmemo",
            name="inpact_cluster",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="riskmemo",
            name="level",
            field=models.CharField(
                choices=[("Low", "低"), ("Middle", "中"), ("High", "高")],
                default="Middle",
                help_text="风险等级",
                max_length=64,
            ),
        ),
    ]
