# Generated by Django 4.2.27 on 2026-01-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_memo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskmemo",
            name="inpact_cluster",
            field=models.TextField(default="", help_text="影响集群"),
        ),
    ]
