# Generated by Django 3.2.25 on 2025-10-10 02:59

from datetime import datetime, timezone

from django.db import migrations, models


def convert_string_to_datetime(apps, schema_editor):
    Model = apps.get_model("risk_memo", "riskmemo")
    for obj in Model.objects.all():
        old_value = obj.final_time  # 获取旧的字符串字段值

        if old_value is None:
            continue
        try:
            # 将字符串转换为日期时间对象
            new_value = datetime.strptime(old_value, "%Y-%m-%d %H:%M:%S%z")
            new_value = new_value.astimezone(timezone.utc).replace(tzinfo=None, microsecond=0)
            obj.final_time = new_value.strftime("%Y-%m-%d %H:%M:%S.%f%z")  # 存入新字段
            obj.save()
        except ValueError:
            # 处理无法解析的字符串（例如：放入NULL或默认值）
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("risk_memo", "0002_auto_20250925_1516"),
    ]

    operations = [
        migrations.RunPython(convert_string_to_datetime),
        migrations.AlterField(
            model_name="riskmemo",
            name="final_time",
            field=models.DateTimeField(blank=True, help_text="结项时间", null=True),
        ),
    ]
