# Generated by Django 3.2.25 on 2025-10-10 02:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_memo", "0002_auto_20250925_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskmemo",
            name="final_time",
            field=models.DateTimeField(blank=True, help_text="结项时间", null=True),
        ),
    ]
