# Generated by Django 3.2.25 on 2025-09-09 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapacityEvaluateHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="Business ID")),
                ("bk_biz_name", models.CharField(default="", max_length=64, verbose_name="Business Name")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="Cluster ID")),
                ("cluster_domain", models.CharField(default="", max_length=64, verbose_name="Cluster Domain")),
                ("cluster_type", models.CharField(default="", max_length=256, verbose_name="Cluster Type")),
                ("free_size_mb", models.IntegerField(default=0, verbose_name="Free Size MB")),
                ("total_size_mb", models.IntegerField(default=0, verbose_name="Total Size MB")),
                ("proxy_count", models.IntegerField(default=0, verbose_name="Proxy Count")),
                ("proxy_qps_k", models.IntegerField(default=0, verbose_name="Proxy QPS K")),
                (
                    "evaluate_method",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Evaluate Method"),
                ),
                (
                    "evaluate_time",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Evaluate Time"),
                ),
                ("time_elapsed_ms", models.IntegerField(default=0, verbose_name="Evaluate cost time ms")),
                ("action_id", models.CharField(default="", max_length=128, verbose_name="Action ID")),
                ("action_name", models.CharField(default="", max_length=128, verbose_name="Action Name")),
                ("action_type", models.CharField(default="", max_length=64, verbose_name="Action Type")),
                ("req_qps_k", models.IntegerField(default=0, verbose_name="Req QPS K")),
                ("req_capacity_m", models.IntegerField(default=0, verbose_name="Req Capacity M")),
                ("req_flags_json", models.CharField(default="", max_length=1024, verbose_name="Req Flags JSON")),
                ("req_qps_k_total", models.IntegerField(default=0, verbose_name="Req QPS K Total")),
                ("req_capacity_m_total", models.IntegerField(default=0, verbose_name="Req Capacity M Total")),
                (
                    "not_finished_records_json",
                    models.CharField(default="", max_length=4096, verbose_name="Not Finished Records JSON"),
                ),
                ("is_force", models.IntegerField(default=0, null=True, verbose_name="Is Force")),
                (
                    "action_user",
                    models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="Action User"),
                ),
                (
                    "approved_user",
                    models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="Approved User"),
                ),
                ("approved_status", models.CharField(default="", max_length=64, verbose_name="Approved Status")),
                (
                    "approved_time",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True, verbose_name="Approved Time"
                    ),
                ),
                (
                    "approved_comment",
                    models.CharField(blank=True, default="", max_length=2048, verbose_name="Approved Comment"),
                ),
            ],
            options={
                "verbose_name": "Capacity Evaluate History",
                "verbose_name_plural": "Capacity Evaluate Histories",
                "db_table": "tb_capacity_evaluate_history",
                "ordering": ["-evaluate_time"],
            },
        ),
        migrations.CreateModel(
            name="CapacityEvaluateRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_id", models.CharField(default="", max_length=128, verbose_name="Action ID")),
                ("action_name", models.CharField(default="", max_length=128, verbose_name="Action Name")),
                ("action_type", models.CharField(default="", max_length=64, verbose_name="Action Type")),
                (
                    "action_user",
                    models.CharField(blank=True, default="", max_length=64, null=True, verbose_name="Action User"),
                ),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="Business ID")),
                ("bk_biz_name", models.CharField(default="", max_length=64, verbose_name="Business Name")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="Cluster ID")),
                ("cluster_domain", models.CharField(default="", max_length=64, verbose_name="Cluster Domain")),
                ("cluster_type", models.CharField(default="", max_length=256, verbose_name="Cluster Type")),
                (
                    "evaluate_method",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Evaluate Method"),
                ),
                (
                    "evaluate_time",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Evaluate Time"),
                ),
                ("start_time", models.DateTimeField(default=None, verbose_name="Start Time")),
                ("end_time", models.DateTimeField(default=None, verbose_name="End Time")),
                ("req_qps_k", models.IntegerField(default=0, verbose_name="Req QPS K")),
                ("req_capacity_m", models.IntegerField(default=0, verbose_name="Req Capacity M")),
                ("key_pattern", models.CharField(default="", max_length=2048, verbose_name="Key Pattern")),
                (
                    "req_flag_no_big_key_with_a_lot_of_member",
                    models.BooleanField(default=False, verbose_name="Req Flag No Big Key With A Lot Of Member"),
                ),
                ("req_flag_no_big_result", models.BooleanField(default=False, verbose_name="Req Flag No Big Result")),
                ("req_flag_no_big_value", models.BooleanField(default=False, verbose_name="Req Flag No Big Value")),
                ("req_flag_no_hot_key", models.BooleanField(default=False, verbose_name="Req Flag No Hot Key")),
                ("req_flag_no_use_dns", models.IntegerField(default=0, verbose_name="Req Flag No Use DNS")),
                ("is_force", models.IntegerField(default=0, null=True, verbose_name="Is Force")),
                ("last_approved_user", models.CharField(default="", max_length=64, verbose_name="Last Approved User")),
                ("last_approved_status", models.IntegerField(default=0, verbose_name="Last Approved Status")),
                (
                    "last_approved_time",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Last Approved Time"),
                ),
            ],
            options={
                "verbose_name": "Capacity Evaluate Record",
                "verbose_name_plural": "Capacity Evaluate Records",
                "db_table": "tb_capacity_evaluate_request",
                "ordering": ["-start_time"],
                "unique_together": {("cluster_id", "action_id")},
            },
        ),
        migrations.AddIndex(
            model_name="capacityevaluatehistory",
            index=models.Index(fields=["cluster_id", "evaluate_time"], name="tb_capacity_cluster_a57d3a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="capacityevaluatehistory",
            unique_together={("cluster_id", "evaluate_time")},
        ),
    ]
