# Default values for qdrant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

fullnameOverride: ""

## @param application images
##
image:
  registry: docker.io
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: "v1.16.3"
  tools:
    repository: apecloud/curl-jq
    tag: 0.1.0

## @param data volume mount path
dataMountPath: /qdrant/storage
