{{- $dbCeleryServiceDB := fromYaml (include "bk-dbm.database" (list . "dbCeleryService")) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-celery-service-configmap
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
data:
  config.yaml: |-
    gormlog: true

    db:
      name:  "{{ $dbCeleryServiceDB.name }}"
      addr:  "{{ $dbCeleryServiceDB.host }}:{{ $dbCeleryServiceDB.port }}"
      username:  "{{ $dbCeleryServiceDB.user }}"
      password:  "{{ $dbCeleryServiceDB.password }}"

  CS_DB_NAME: "{{ $dbCeleryServiceDB.name }}"
  CS_DB_USER: "{{ $dbCeleryServiceDB.user }}"
  CS_DB_PASSWORD: "{{ $dbCeleryServiceDB.password }}"
  CS_DB_ADDRESS: "{{ $dbCeleryServiceDB.host }}:{{ $dbCeleryServiceDB.port }}"
