{{- $dbmDB := fromYaml (include "bk-dbm.database" (list . "dbm")) -}}
{{- $dbmReportDB := fromYaml (include "bk-dbm.database" (list . "dbmReport")) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-dbm-db-env
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
data:
  DB_NAME: "{{ $dbmDB.name }}"
  DB_HOST: "{{ $dbmDB.host }}"
  DB_PORT: "{{ $dbmDB.port }}"
  DB_USER: "{{ $dbmDB.user }}"
  DB_PASSWORD: "{{ $dbmDB.password }}"
  REPORT_DB_NAME: "{{ $dbmReportDB.name }}"
  REPORT_DB_HOST: "{{ $dbmReportDB.host }}"
  REPORT_DB_PORT: "{{ $dbmReportDB.port }}"
  REPORT_DB_USER: "{{ $dbmReportDB.user }}"
  REPORT_DB_PASSWORD: "{{ $dbmReportDB.password }}"
  DJANGO_SETTINGS_MODULE: "{{ .Values.dbm.envs.djangoSettingsModule }}"
  RUN_VER: "{{ .Values.dbm.envs.runVer }}"
  SERVICE_ONLY: "True"
  BK_APP_CODE: "{{ .Values.dbm.envs.bkAppCode }}"
  APP_ID: "{{ .Values.dbm.envs.bkAppCode }}"
  APP_TOKEN: "{{ .Values.dbm.envs.bkAppToken }}"
  BK_DOMAIN: "{{ .Values.global.bkDomain }}"
  BK_SAAS_HOST: "{{ .Values.dbm.envs.bkSaasUrl }}"
  BROKER_URL: "{{ .Values.dbm.envs.brokerUrl }}"
  DBA_APP_BK_BIZ_ID: "{{ .Values.dbm.envs.dbaAppBkBizId }}"
  CORS_ALLOWED_ORIGINS: "{{ .Values.dbm.envs.corsAllowedOrigins | default (list) }}"
  # REDIS
  REDIS_HOST: "{{ .Values.externalRedis.host }}"
  REDIS_PORT: "{{ .Values.externalRedis.port }}"
  REDIS_PASSWORD: "{{ .Values.externalRedis.password }}"
  # 蓝鲸PaaS平台
  BK_PAAS_URL: "{{ .Values.bk.bkPaasUrl }}"
  BK_PAAS_HOST: "{{ .Values.bk.bkPaasUrl }}"
  BK_COMPONENT_API_URL: "{{ .Values.bk.bkComponentApiUrl }}"
  BKPAAS_LOGIN_URL: "{{ .Values.bk.bkLoginUrl }}"
  LOGIN_URL: "{{ .Values.bk.bkLoginUrl }}"
  # 蓝鲸配置平台
  BK_CMDB_URL: "{{ .Values.bk.bkCmdbUrl }}"
  # 蓝鲸作业平台
  BK_JOB_URL: "{{ .Values.bk.bkJobUrl }}"
  JOB_BLUEKING_BIZ_ID: "{{ .Values.bk.bluekingBizId }}"
  # 蓝鲸节点管理
  BK_NODEMAN_URL: "{{ .Values.bk.bkNodemanUrl}}"
  # gcs/scr平台
  BK_SCR_URL: "{{ .Values.bk.bkScrUrl}}"
  SCR_APIGW_DOMAIN: "{{ .Values.bk.bkScrApigwDomain }}"
  GCS_APIGW_DOMAIN: "{{  .Values.bk.bkGcsApigwDomain }}"
  # 蓝鲸制品库
  BKREPO_PROJECT: "{{ .Values.bk.bkRepoProject }}"
  BKREPO_PASSWORD: "{{ .Values.bk.bkRepoPassword }}"
  BKREPO_USERNAME: "{{ .Values.bk.bkRepoUsername }}"
  BKREPO_PUBLIC_BUCKET: "{{ .Values.bk.bkRepoPublicBucket }}"
  BKREPO_ENDPOINT_URL: "{{ .Values.bk.bkRepoUrl }}"
  # 蓝鲸权限中心
  BK_IAM_SKIP: "{{ .Values.bk.bkIamSkipMigrate }}"
  IAM_APP_URL: "{{ .Values.bk.bkIamUrl }}"
  BK_IAM_APIGATEWAY: "{{ .Values.bk.bkIamApiUrl }}"
  BK_IAM_RESOURCE_API_HOST: "{{ .Values.bk.bkIamResourceApiHost }}"
  # 蓝鲸监控平台
  GRAFANA_URL: "{{ .Values.bk.grafanaUrl }}"
  BKMONITOR_URL: "{{ .Values.bk.bkMonitorUrl }}"
  BKM_DBM_TOKEN: "{{ .Values.bk.bkmDbmToken }}"
  MYSQL_CROND_BEAT_PATH: "{{ .Values.bk.mysqlCrondBeatPath }}"
  MYSQL_CROND_AGENT_ADDRESS: "{{ .Values.bk.mysqlCrondAgentAddress }}"
  MYSQL_CROND_METRICS_DATA_TOKEN: "{{ .Values.bk.mysqlCrondMetricsDataToken }}"
  MYSQL_CROND_METRICS_DATA_ID: "{{ .Values.bk.mysqlCrondMetricsDataId }}"
  # 蓝鲸数据库管理平台
  MYSQL_PRIV_MANAGER_APIGW_DOMAIN: "{{ .Values.dbm.envs.mysqlPrivManagerApigwDomain }}"
  PARTITION_APIGW_DOMAIN: "{{ .Values.dbm.envs.partitionApigwDomain }}"
  DBCONFIG_APIGW_DOMAIN: "{{ .Values.dbm.envs.dbconfigApigwDomain }}"
  MYSQL_SIMULATION_DOMAIN: "{{ .Values.dbm.envs.mySqlSimulationDomain }}"
  DNS_APIGW_DOMAIN: "{{ .Values.dbm.envs.dnsApigwDomain }}"
  HADB_APIGW_DOMAIN: "{{ .Values.dbm.envs.hadbApigwDomain }}"
  DBRESOURCE_APIGW_DOMAIN: "{{ .Values.dbm.envs.dbResourceApigwDomain }}"
  DRS_APIGW_DOMAIN: "{{ .Values.dbm.envs.dbRemoteServiceApigwDomain }}"
  SLOW_QUERY_PARSER_DOMAIN: "{{ .Values.dbm.envs.slowQueryParseApigwDomain | default (printf "http://bk-dbm-slow-query-parser-service.%s.svc.cluster.local" .Values.bk.bkBcsNamespace) }}"
  BK_APIGW_STATIC_VERSION: "{{ .Values.bk.bkApigwStaticVersion }}"
  BK_APIGW_MANAGER_MAINTAINERS: "{{ .Values.bk.bkApigwManagerMaintainers }}"
  BK_APIGW_STAGE_NAME: "{{ .Values.bk.bkApigwStageName }}"
  BK_APIGW_GRANT_APPS: "{{ .Values.bk.bkApigwGrantApps}}"
  BK_APIGW_RESOURCE_DOCS_ARCHIVE_FILE: "{{ .Values.bk.bkApigwResourceDocsArchiveFile }}"
  BK_APIGATEWAY_DOMAIN : "{{ .Values.bk.bkApigatewayDomain | default .Values.bk.bkComponentApiUrl }}"
