{{- if .Values.grafana.enabled }}
{{- $grafanaDb := fromYaml (include "bk-dbm.database" (list . "dbGrafana")) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-dbm-grafana-ini
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
data:
  grafana.ini: |-
    [plugins]
    allow_loading_unsigned_plugins = bkmonitor-timeseries-datasource,bkmonitor-event-datasource,bk_log_datasource
    [live]
    max_connections = 0
    [auth]
    # disable login
    disable_login_form = true
    # disable logout
    disable_signout_menu = true
    [auth.proxy]
    # use auth proxy
    enabled = true
    auto_sign_up = false
    [users]
    # disable use sign up
    allow_sign_up = false
    # disable user create org
    allow_org_create = false
    # new user auto assign to org
    auto_assign_org = false
    # theme
    default_theme = "light"
    editors_can_admin = true
    [security]
    # set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
    allow_embedding = true
    admin_user = admin
    admin_password = admin
    [server]
    http_port = 3000
    root_url = /grafana/
    serve_from_sub_path = true
    [alerting]
    enabled = false
    [unified_alerting]
    enabled = false
    [explore]
    # Enable the Explore section
    enabled = false
    [database]
    type = mysql
    host = {{ $grafanaDb.host }}:{{ $grafanaDb.port }}
    name = {{ $grafanaDb.name }}
    user = {{ $grafanaDb.user }}
    # """ tree double quote to escape special char in password
    password = """{{ $grafanaDb.password }}"""
    [snapshots]
    external_enabled = false
{{- end }}
