apiVersion: v1
kind: ConfigMap
metadata:
  name: db-nginx-configmap
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
data:
  DB_CLOUD_TOKEN: "{{ .Values.dbm.envs.bkAppCode }}:{{ .Values.dbm.envs.bkAppToken }}"
  BK_DBM_URL: "{{ .Values.dbm.envs.dbmApigwDomain }}"
  DBM_NGINX_DOMAIN: "{{ index .Values "db-nginx" "ingress" "hosts" 0 "host" }}"
