# Generated by Django 3.2.4 on 2023-04-18 11:32

from django.db import migrations, models

from backend.configuration.constants import DBType
from backend.db_meta.enums import InstanceStatus
from backend.db_proxy.constants import ExtensionType


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DBCloudProxy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(db_index=True, verbose_name="云区域 ID")),
                ("internal_address", models.CharField(max_length=255, verbose_name="代理内部地址")),
                ("external_address", models.CharField(max_length=255, verbose_name="代理外部地址")),
            ],
            options={
                "verbose_name": "云区域代理",
            },
        ),
        migrations.CreateModel(
            name="DBExtension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(db_index=True, verbose_name="云区域 ID")),
                (
                    "extension",
                    models.CharField(
                        choices=ExtensionType.get_choices(),
                        max_length=64,
                        verbose_name="扩展类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=InstanceStatus.get_choices(),
                        max_length=64,
                        verbose_name="服务状态",
                    ),
                ),
                ("details", models.JSONField(verbose_name="详情")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClusterExtension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("ip", models.CharField(max_length=64, verbose_name="部署机器ip")),
                ("port", models.CharField(max_length=64, verbose_name="部署机器port")),
                ("service_type", models.CharField(max_length=64, verbose_name="服务类型")),
                ("cluster_name", models.CharField(max_length=255, verbose_name="集群名")),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        max_length=32,
                        verbose_name="集群类型",
                    ),
                ),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("is_flush", models.BooleanField(default=False, verbose_name="是否刷新(该条记录是否执行)")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("access_url", models.TextField(default="", verbose_name="服务访问地址")),
            ],
            options={
                "unique_together": {("bk_biz_id", "db_type", "cluster_name", "service_type")},
            },
        ),
    ]
