# Generated by Django 3.2.19 on 2023-07-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_proxy", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clusterextension",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="clusterextension",
            index_together={("bk_biz_id", "db_type", "cluster_name", "service_type")},
        ),
    ]
