# Generated by Django 3.2.25 on 2024-06-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_proxy", "0002_auto_20230711_1147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clusterextension",
            options={"verbose_name": "集群扩展服务（ClusterExtension）", "verbose_name_plural": "集群扩展服务（ClusterExtension）"},
        ),
        migrations.AlterModelOptions(
            name="dbcloudproxy",
            options={"verbose_name": "云区域代理（DBCloudProxy）", "verbose_name_plural": "云区域代理（DBCloudProxy）"},
        ),
        migrations.AlterModelOptions(
            name="dbextension",
            options={"verbose_name": "云区域组件扩展（DBExtension）", "verbose_name_plural": "云区域组件扩展（DBExtension）"},
        ),
    ]
