# Generated by Django 3.2.19 on 2023-09-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_proxy', '0002_auto_20230711_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterextension',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dbcloudproxy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dbextension',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
