# Generated by Django 3.2.19 on 2023-07-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_proxy", "0002_auto_20230711_1147"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsManage",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("bk_host_id", models.PositiveBigIntegerField(help_text="主机ID", primary_key=True, serialize=False)),
                ("ip", models.CharField(help_text="主机IP", max_length=128)),
                (
                    "dns",
                    models.ForeignKey(
                        help_text="关联DNS", on_delete=django.db.models.deletion.CASCADE, to="db_proxy.dbextension"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
