# Generated by Django 3.2.19 on 2024-04-04 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_proxy", "0003_dnsmanage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBCloudKit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID")),
                ("bk_cloud_id", models.IntegerField(help_text="云区域 ID")),
                ("name", models.CharField(help_text="套件ID名称", max_length=64)),
                ("alias", models.CharField(default="", help_text="套件别名", max_length=64)),
            ],
        ),
        migrations.AddIndex(
            model_name="dbcloudkit",
            index=models.Index(fields=["bk_biz_id"], name="db_proxy_db_bk_biz__f9e891_idx"),
        ),
        migrations.AddIndex(
            model_name="dbcloudkit",
            index=models.Index(fields=["bk_cloud_id"], name="db_proxy_db_bk_clou_342cc7_idx"),
        ),
        migrations.AddField(
            model_name="dbextension",
            name="cloud_kit",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db_proxy.dbcloudkit",
                verbose_name="所属DB套件",
            ),
        ),
    ]
