/**
 * 业务设置列表key
 */
export enum BizSettingKeys {
  BIZ_ASSISTANCE_SWITCH = 'BIZ_ASSISTANCE_SWITCH',
  BIZ_ASSISTANCE_VARS = 'BIZ_ASSISTANCE_VARS',
  DATABASE_MANAGE_MENU = 'DATABASE_MANAGE_MENU',
  NOTIFY_CONFIG = 'NOTIFY_CONFIG',
  OPEN_AREA_VARS = 'OPEN_AREA_VARS',
}
