/**
 * 用户个人设置 keys
 */
// mysql
export enum UserPersonalSettings {
  MYSQL_TOOLBOX_FAVOR = 'MYSQL_TOOLBOX_FAVOR_1',
  MYSQL_TOOLBOX_MENUS = 'MYSQL_TOOLBOX_MENUS_1',
  MYSQL_TOOLBOX_USED = 'MYSQL_TOOLBOX_USED_1',
  TENDBHA_INSTANCE_SETTINGS = 'TENDBHA_INSTANCE_SETTINGS',
  TENDBHA_TABLE_SETTINGS = 'TENDBHA_TABLE_SETTINGS_v1',
  TENDBSINGLE_TABLE_SETTINGS = 'TENDBSINGLE_TABLE_SETTINGS',
}
// spider(tendbcluster)
export enum UserPersonalSettings {
  TENDBCLUSTER_INSTANCE_TABLE = 'TENDBCLUSTER_INSTANCE_TABLE',
  TENDBCLUSTER_TABLE_SETTINGS = 'TENDBCLUSTER_TABLE_SETTINGS',
  TENDBCLUSTER_TOOLBOX_FAVOR = 'TENDBCLUSTER_TOOLBOX_FAVOR_1',
  TENDBCLUSTER_TOOLBOX_MENUS = 'TENDBCLUSTER_TOOLBOX_MENUS_1',
  TENDBCLUSTER_TOOLBOX_USED = 'TENDBCLUSTER_TOOLBOX_USED_1',
}
// redis
export enum UserPersonalSettings {
  REDIS_HA_INSTANCE_SETTINGS = 'REDIS_HA_INSTANCE_SETTINGS',
  REDIS_HA_TABLE_SETTINGS = 'REDIS_HA_TABLE_SETTINGS',
  REDIS_INSTANCE_SETTINGS = 'REDIS_INSTANCE_SETTINGS',
  REDIS_TABLE_SETTINGS = 'REDIS_TABLE_SETTINGS',
  REDIS_TOOLBOX_FAVOR = 'REDIS_TOOLBOX_FAVOR_1',
  REDIS_TOOLBOX_MENUS = 'REDIS_TOOLBOX_MENUS_1',
  REDIS_TOOLBOX_USED = 'REDIS_TOOLBOX_USED_1',
}
// bigdata
export enum UserPersonalSettings {
  DORIS_TABLE_SETTINGS = 'DORIS_TABLE_SETTINGS',
  ES_TABLE_SETTINGS = 'ES_TABLE_SETTINGS',
  HDFS_TABLE_SETTINGS = 'HDFS_TABLE_SETTINGS',
  INFLUXDB_TABLE_SETTINGS = 'INFLUXDB_TABLE_SETTINGS',
  KAFKA_TABLE_SETTINGS = 'KAFKA_TABLE_SETTINGS',
  PULSAR_TABLE_SETTINGS = 'PULSAR_TABLE_SETTINGS',
}
// mongo
export enum UserPersonalSettings {
  MONGO_TOOLBOX_FAVOR = 'MONGO_TOOLBOX_FAVOR_1',
  MONGO_TOOLBOX_MENUS = 'MONGO_TOOLBOX_MENUS_1',
  MONGO_TOOLBOX_USED = 'MONGO_TOOLBOX_USED_1',
  MONGODB_REPLICA_SET_INSTANCE = 'MONGODB_REPLICA_SET_INSTANCE',
  MONGODB_REPLICA_SET_SETTINGS = 'MONGODB_REPLICA_SET_SETTINGS',
  MONGODB_SHARED_CLUSTER_INSTANCE = 'MONGODB_SHARED_CLUSTER_INSTANCE',
  MONGODB_SHARED_CLUSTER_SETTINGS = 'MONGODB_SHARED_CLUSTER_SETTINGS',
}
// sqlserver
export enum UserPersonalSettings {
  SQLSERVER_HA_INSTANCE_SETTINGS = 'SQLSERVER_HA_INSTANCE_SETTINGS',
  SQLSERVER_HA_TABLE_SETTINGS = 'SQLSERVER_HA_TABLE_SETTINGS',
  SQLSERVER_SINGLE_TABLE_SETTINGS = 'SQLSERVER_SINGLE_TABLE_SETTINGS',
  SQLSERVER_TOOLBOX_FAVOR = 'SQLSERVER_TOOLBOX_FAVOR',
  SQLSERVER_TOOLBOX_MENUS = 'SQLSERVER_TOOLBOX_MENUS',
  SQLSERVER_TOOLBOX_USED = 'SQLSERVER_TOOLBOX_USE',
}

// ORACLE
export enum UserPersonalSettings {
  ORACLE_HA_CLUSTER_SETTINGS = 'ORACLE_HA_CLUSTER_SETTINGS',
  ORACLE_HA_INSTANCE_SETTINGS = ' ORACLE_HA_INSTANCE_SETTINGS',
  ORACLE_SINGLE_CLUSTER_SETTINGS = 'ORACLE_SINGLE_CLUSTER_SETTINGS',
  ORACLE_TOOLBOX_FAVOR = 'SORACLE_TOOLBOX_FAVOR',
  ORACLE_TOOLBOX_MENUS = 'ORACLE_TOOLBOX_MENUS',
  ORACLE_TOOLBOX_USED = 'ORACLE_TOOLBOX_USED',
}
// riak
export enum UserPersonalSettings {
  RIAK_TABLE_SETTINGS = 'RIAK_TABLE_SETTINGS',
}
// k8s surrealdb
export enum UserPersonalSettings {
  SURREALDB_HA_INSTANCE_SETTINGS = 'SURREALDB_HA_INSTANCE_SETTINGS',
  SURREALDB_HA_TABLE_SETTINGS = 'SURREALDB_HA_TABLE_SETTINGS',
  SURREALDB_SINGLE_TABLE_SETTINGS = 'SURREALDB_SINGLE_TABLE_SETTINGS',
}
// k8s Qdrant
export enum UserPersonalSettings {
  QDRANT_HA_TABLE_SETTINGS = 'QDRANT_HA_TABLE_SETTINGS',
}
// quicksearch
export enum UserPersonalSettings {
  QUICK_SEARCH_CLUSTER_DOMAIN = 'QUICK_SEARCH_CLUSTER_DOMAIN',
  QUICK_SEARCH_CLUSTER_NAME = 'QUICK_SEARCH_CLUSTER_NAME',
  QUICK_SEARCH_INSTANCE = 'QUICK_SEARCH_INSTANCE',
  QUICK_SEARCH_RESOURCE_POOL = 'QUICK_SEARCH_RESOURCE_POOL',
  QUICK_SEARCH_TASK = 'QUICK_SEARCH_TASK',
}
export enum UserPersonalSettings {
  ACTIVATED_APP = 'ACTIVATED_APP',
  APP_FAVOR = 'APP_FAVOR',
  DBHA_SWITCH_EVENTS = 'DBHA_SWITCH_EVENTS',
  MONITOR_STRATEGY_BIZ_SETTINGS = 'MONITOR_STRATEGY_BIZ_SETTINGS',
  MONITOR_STRATEGY_GLOBAL_SETTINGS = 'MONITOR_STRATEGY_GLOBAL_SETTINGS',
  PARTITION_TABLE_SETTINGS = 'PARTITION_TABLE_SETTINGS',
  RESOURCE_POOL_HOST_LIST_SETTINGS = 'RESOURCE_POOL_HOST_LIST_SETTINGS',
  RESOURCE_POOL_SELECTOR_SETTINGS = 'RESOURCE_POOL_SELECTOR_SETTINGS',
  SERVICE_APPLY_FAVOR = 'SERVICE_APPLY_FAVOR',
  SPECIFICATION_TABLE_SETTINGS = 'SPECIFICATION_TABLE_SETTINGS',
  TOP_DB_TYPES = 'TOP_DB_TYPES',
}
