apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: {{ include "risingwave-cdName" . }}
spec:
  topologies:
    - components:
        - compDef: {{ include "risingwave-compactor.cmpdRegexpPattern" . }}
          name: compactor
        - compDef: {{ include "risingwave-compute.cmpdRegexpPattern" . }}
          name: compute
        - compDef: {{ include "risingwave-frontend.cmpdRegexpPattern" . }}
          name: frontend
        - compDef: {{ include "risingwave-meta.cmpdRegexpPattern" . }}
          name: meta
      default: true
      name: risingwave