apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: {{ include "risingwave-meta.cmpvName" . }}
spec:
  compatibilityRules:
    - releases:
        - meta-2.2.1-2.0.0
        - meta-2.3.0-2.0.0
        - meta-2.4.1-2.0.0
      compDefs:
        - risingwave-meta-2.0.0
  releases:
    - name: meta-2.2.1-2.0.0
      serviceVersion: 2.2.1-2.0.0
      images:
        meta: docker.risingwave.com/risingwavelabs/risingwave:v2.2.1
    - name: meta-2.3.0-2.0.0
      serviceVersion: 2.3.0-2.0.0
      images:
        meta: docker.risingwave.com/risingwavelabs/risingwave:v2.3.0
    - name: meta-2.4.1-2.0.0
      serviceVersion: 2.4.1-2.0.0
      images:
        meta: docker.risingwave.com/risingwavelabs/risingwave:v2.4.1