apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: {{ include "risingwave-compactor.cmpvName" . }}
spec:
  compatibilityRules:
    - releases:
        - compactor-2.2.1-2.0.0
        - compactor-2.3.0-2.0.0
        - compactor-2.4.1-2.0.0
      compDefs:
        - risingwave-compactor-2.0.0
  releases:
    - name: compactor-2.2.1-2.0.0
      serviceVersion: 2.2.1-2.0.0
      images:
        compactor: docker.risingwave.com/risingwavelabs/risingwave:v2.2.1
    - name: compactor-2.3.0-2.0.0
      serviceVersion: 2.3.0-2.0.0
      images:
        compactor: docker.risingwave.com/risingwavelabs/risingwave:v2.3.0
    - name: compactor-2.4.1-2.0.0
      serviceVersion: 2.4.1-2.0.0
      images:
        compactor: docker.risingwave.com/risingwavelabs/risingwave:v2.4.1