{{- if .Values.saas.pipelineWorker.autoscaling.enabled }}
apiVersion: {{ include "dbm.capabilities.hpa.apiVersion" (dict "context" .) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dbm.pipeline-worker.fullname" . }}
  labels:
    {{- include "bk-dbm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dbm.pipeline-worker.fullname" . }}
  minReplicas: {{ .Values.saas.pipelineWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.saas.pipelineWorker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.saas.pipelineWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" .Capabilities.KubeVersion.GitVersion }}
        targetAverageUtilization: {{ .Values.saas.pipelineWorker.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.saas.pipelineWorker.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if .Values.saas.pipelineWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" .Capabilities.KubeVersion.GitVersion }}
        targetAverageUtilization: {{ .Values.saas.pipelineWorker.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.saas.pipelineWorker.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
{{- end }}
