# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-DB管理系统(BlueKing-BK-DBM) available.
Copyright (C) 2017-2023 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.6 on 2021-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BKJobFileSource",
            fields=[
                (
                    "credential_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name="凭证ID"),
                ),
                ("file_source_id", models.IntegerField(db_index=True, verbose_name="文件源ID")),
                ("code", models.CharField(max_length=128, verbose_name="文件源标识")),
                ("alias", models.CharField(max_length=128, verbose_name="文件源别名")),
                ("access_params", models.JSONField(default=dict, verbose_name="文件源接入参数")),
                ("file_prefix", models.CharField(default="", max_length=128, verbose_name="文件源标识")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="更新时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "作业平台文件源",
                "verbose_name_plural": "作业平台文件源",
            },
        ),
        migrations.CreateModel(
            name="BKJobFileCredential",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务ID")),
                ("storage_type", models.CharField(db_index=True, max_length=128, verbose_name="文件源存储类型")),
                ("name", models.CharField(max_length=128, verbose_name="凭证名称")),
                ("type", models.CharField(max_length=64, verbose_name="凭证类型")),
                ("description", models.TextField(default="", verbose_name="凭证描述")),
                ("credential_id", models.CharField(max_length=128, verbose_name="凭证ID")),
                ("update_time", models.DateTimeField(auto_now=True, db_index=True, verbose_name="更新时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "作业平台文件凭证",
                "verbose_name_plural": "作业平台文件凭证",
                "unique_together": {("bk_biz_id", "storage_type")},
            },
        ),
    ]
