# Generated by Django 3.2.19 on 2023-09-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_alter_bkjobfilecredential_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkjobfilecredential',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
