# Generated by Django 3.2.19 on 2023-11-08 03:31

from django.db import migrations, models

from backend.db_meta.enums import MigrateStatus


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TbTendisSlotsMigrateRecord",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("related_slots_migrate_bill_id", models.BigIntegerField(verbose_name="单据号，关联单据")),
                ("bk_biz_id", models.BigIntegerField(verbose_name="业务id")),
                ("app", models.CharField(default="", max_length=64, verbose_name="业务名")),
                ("bk_cloud_id", models.BigIntegerField(default=0, verbose_name="云区域id")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "tendbsingle"),
                            ("tendbha", "tendbha"),
                            ("tendbcluster", "tendbcluster"),
                            ("redis", "Redis集群"),
                            ("PredixyRedisCluster", "Tendisplus集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群 GetTendisType 获取redis类型值"),
                            ("RedisInstance", "TendisCache集群 GetTendisType 获取redis类型值"),
                            ("TendisSSDInstance", "TendisSSD集群 GetTendisType 获取redis类型值"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="集群类型",
                    ),
                ),
                ("cluster_id", models.BigIntegerField(verbose_name="集群id，cluster.id")),
                ("cluster_name", models.CharField(default="", max_length=128, verbose_name="集群名")),
                ("old_instance_pair", models.JSONField(default=dict, verbose_name="扩缩容前实例主从对")),
                ("new_instance_pair", models.JSONField(default=dict, verbose_name="扩缩容后实例主从对")),
                ("add_new_master_slave_pair", models.JSONField(default=dict, verbose_name="扩容新增实例主从对")),
                ("shutdown_master_slave_pair", models.JSONField(default=dict, verbose_name="缩容下架实例主从对")),
                ("current_group_num", models.IntegerField(verbose_name="扩缩容前的主机数量")),
                ("target_group_num", models.IntegerField(verbose_name="扩缩容后的主机数量")),
                ("new_ip_group", models.JSONField(default=dict, verbose_name="扩容时新增的主从主机")),
                ("migrate_specified_slot", models.JSONField(default=dict, verbose_name="特定slots迁移信息")),
                (
                    "status",
                    models.IntegerField(
                        choices=MigrateStatus.get_choices(),
                        default=MigrateStatus.NOT_STARTED.value,
                        verbose_name="任务状态",
                    ),
                ),
                ("specification", models.JSONField(default=dict, verbose_name="规格需求")),
            ],
            options={
                "verbose_name": "Tendisplus slots migrate  record",
                "db_table": "tb_tendis_slots_migrate_record",
            },
        ),
        migrations.AddIndex(
            model_name="tbtendisslotsmigraterecord",
            index=models.Index(fields=["update_at"], name="idx_update_at_slots"),
        ),
        migrations.AddIndex(
            model_name="tbtendisslotsmigraterecord",
            index=models.Index(fields=["cluster_name"], name="idx_cluster_name_slots"),
        ),
    ]
