# Generated by Django 3.2.19 on 2023-11-20 11:55

from django.db import migrations, models

from backend.db_meta.enums import ClusterType
from backend.db_meta.enums.destroyed_status import MigrateStatus


class Migration(migrations.Migration):
    dependencies = [
        ("slots_migrate", "0004_alter_tbtendisslotsmigraterecord_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbtendisslotsmigraterecord",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="tbtendisslotsmigraterecord",
            name="status",
            field=models.IntegerField(
                choices=MigrateStatus.get_choices(),
                default=MigrateStatus["NOT_STARTED"],
                verbose_name="状态",
            ),
        ),
    ]
