# Generated by Django 3.2.4 on 2023-04-18 11:45

import django.db.models.deletion
from django.db import migrations, models

from backend.db_services.mysql.permission.constants import CloneType


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLPermissionCloneRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clone_type",
                    models.CharField(choices=CloneType.get_choices(), max_length=32, verbose_name="权限克隆类型"),
                ),
                ("source", models.CharField(max_length=64, verbose_name="旧实例/旧客户端IP")),
                ("target", models.TextField(verbose_name="新实例/新客户端IP列表")),
                ("status", models.BooleanField(default=True, verbose_name="是否克隆成功")),
                ("error", models.TextField(default="", verbose_name="错误信息")),
                ("record_time", models.DateTimeField(auto_now=True, verbose_name="记录时间")),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="关联工单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clone_records",
                        to="ticket.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限克隆记录",
                "verbose_name_plural": "权限克隆记录",
                "ordering": ["-record_time"],
            },
        ),
    ]
