# Generated by Django 3.2.4 on 2023-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlpermissionclonerecord",
            name="bk_cloud_id",
            field=models.IntegerField(default=0, verbose_name="云区域ID"),
            preserve_default=False,
        ),
    ]
