# Generated by Django 3.2.25

from django.db import migrations, models

from backend.db_meta.enums import ClusterType
from backend.db_services.mongodb.autofix.enums import MongoAutofixStatus


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MongoAutofixCtl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(db_index=True, verbose_name="云区域 ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("ctl_name", models.CharField(max_length=64, verbose_name="控制项")),
                ("ctl_value", models.CharField(max_length=10000, verbose_name="取值")),
            ],
            options={
                "db_table": "tb_mongodb_autofix_ctl",
            },
        ),
        migrations.CreateModel(
            name="MongoIgnoreAutofix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("cluster_id", models.IntegerField(verbose_name="集群ID")),
                (
                    "cluster_type",
                    models.CharField(choices=ClusterType.get_choices(), max_length=64, verbose_name="集群类型"),
                ),
                ("immute_domain", models.CharField(max_length=255, verbose_name="集群域名")),
                ("bk_host_id", models.IntegerField(verbose_name="机器ID")),
                ("ip", models.GenericIPAddressField(verbose_name="机器IP")),
                ("ignore_msg", models.CharField(max_length=64, verbose_name="忽略原因")),
                ("extra", models.JSONField(default=dict, verbose_name="扩展信息")),
            ],
            options={
                "db_table": "tb_mongodb_autofix_ignore",
                "index_together": {("bk_biz_id", "ip")},
            },
        ),
        migrations.CreateModel(
            name="MongoAutofixCore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("cluster_id", models.IntegerField(db_index=True, verbose_name="集群ID")),
                (
                    "cluster_type",
                    models.CharField(choices=ClusterType.get_choices(), max_length=64, verbose_name="集群类型"),
                ),
                ("immute_domain", models.CharField(max_length=255, verbose_name="集群主域名")),
                ("fault_machines", models.JSONField(max_length=10000, verbose_name="故障机器")),
                ("ip", models.GenericIPAddressField(db_index=True, verbose_name="故障IP")),
                ("bk_host_id", models.IntegerField(default=0, verbose_name="机器ID")),
                ("cluster_ids", models.JSONField(default=list, verbose_name="关联集群ID列表")),
                ("ports", models.JSONField(default=list, verbose_name="端口列表")),
                ("roles", models.JSONField(default=list, verbose_name="角色列表")),
                ("bk_city", models.CharField(blank=True, default="", max_length=64, verbose_name="城市")),
                ("bk_sub_zone_id", models.IntegerField(default=0, verbose_name="园区ID")),
                ("pre_ticket_id", models.BigIntegerField(default=-1, verbose_name="PRE单据ID")),
                ("ticket_id", models.BigIntegerField(default=-1, verbose_name="修复/替换单据ID")),
                ("confirm_result", models.CharField(blank=True, default="", max_length=64, verbose_name="确认结果")),
                (
                    "deal_status",
                    models.CharField(
                        choices=MongoAutofixStatus.get_choices(),
                        db_index=True,
                        max_length=64,
                        verbose_name="自愈状态",
                    ),
                ),
                ("status_version", models.CharField(max_length=64, verbose_name="状态版本")),
                (
                    "disk_rw_ok",
                    models.IntegerField(blank=True, default=-1, null=True, verbose_name="磁盘读写是否正常"),
                ),
                ("detected_at", models.DateTimeField(blank=True, null=True, verbose_name="发现时间")),
            ],
            options={
                "db_table": "tb_mongodb_autofix_core",
            },
        ),
    ]
