# Generated by Django 4.2.30 on 2026-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mongodb_autofix", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mongoautofixcore",
            options={
                "verbose_name": "MongoDB自愈待办 (tb_mongodb_autofix_core)",
                "verbose_name_plural": "MongoDB自愈待办 (tb_mongodb_autofix_core)",
            },
        ),
        migrations.AlterModelOptions(
            name="mongoautofixctl",
            options={"verbose_name": "MongoDB自愈控制项", "verbose_name_plural": "MongoDB自愈控制项"},
        ),
        migrations.AlterModelOptions(
            name="mongoignoreautofix",
            options={"verbose_name": "MongoDB自愈忽略记录", "verbose_name_plural": "MongoDB自愈忽略记录"},
        ),
        migrations.CreateModel(
            name="MongoAutofixLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("core_id", models.BigIntegerField(db_index=True, default=0, verbose_name="Core ID")),
                ("bk_cloud_id", models.IntegerField(default=0, verbose_name="云区域ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, default=0, verbose_name="业务ID")),
                ("cluster_id", models.IntegerField(db_index=True, default=0, verbose_name="集群ID")),
                ("immute_domain", models.CharField(blank=True, default="", max_length=255, verbose_name="集群域名")),
                ("ip", models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name="故障IP")),
                ("bk_host_id", models.IntegerField(default=0, verbose_name="机器ID")),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("detected", "发现故障"),
                            ("pre_ticket", "创建PRE单据"),
                            ("triage", "PRE确认分叉"),
                            ("followup_ticket", "创建修复/替换单据"),
                            ("status", "状态变更"),
                            ("ignore", "忽略"),
                            ("error", "异常"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="事件",
                    ),
                ),
                ("deal_status", models.CharField(blank=True, default="", max_length=64, verbose_name="当时自愈状态")),
                ("confirm_result", models.CharField(blank=True, default="", max_length=64, verbose_name="确认结果")),
                ("pre_ticket_id", models.BigIntegerField(default=-1, verbose_name="PRE单据ID")),
                ("ticket_id", models.BigIntegerField(default=-1, verbose_name="修复/替换单据ID")),
                ("message", models.CharField(blank=True, default="", max_length=10000, verbose_name="日志内容")),
                ("context", models.JSONField(default=dict, verbose_name="扩展上下文")),
            ],
            options={
                "verbose_name": "MongoDB自愈日志 (tb_mongodb_autofix_log)",
                "verbose_name_plural": "MongoDB自愈日志 (tb_mongodb_autofix_log)",
                "db_table": "tb_mongodb_autofix_log",
                "ordering": ("-id",),
                "index_together": {("bk_biz_id", "ip"), ("core_id", "event")},
            },
        ),
    ]
