SET NAMES utf8;
CREATE TABLE IF NOT EXISTS `mysql_partition_config_v2` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `bk_biz_id` int(11) NOT NULL,
  `db_app_abbr` varchar(128) NOT NULL COMMENT '业务名称缩写',
  `bk_biz_name` varchar(128) NOT NULL COMMENT '业务名称',
  `immute_domain` varchar(200) NOT NULL,
  `port` int(11) NOT NULL,
  `bk_cloud_id` int(11) NOT NULL,
  `cluster_id` int(11) NOT NULL,
  `dblike` varchar(100) NOT NULL,
  `tblike` varchar(100) NOT NULL,
  `partition_column` varchar(100) DEFAULT NULL,
  `partition_column_type` varchar(100) DEFAULT NULL,
  `reserved_partition` int(11) NOT NULL,
  `extra_partition` int(11) NOT NULL,
  `partition_time_interval` int(11) NOT NULL,
  `partition_type` int(11) NOT NULL,
  `expire_time` int(11) NOT NULL,
  `time_zone` varchar(16) NOT NULL COMMENT '集群所在的时区',
  `creator` varchar(100) DEFAULT NULL,
  `updator` varchar(100) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
  `phase` varchar(100) NOT NULL COMMENT 'online--在用;offline--停用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq` (`bk_biz_id`,`immute_domain`,`cluster_id`,`dblike`,`tblike`),
  KEY `idx_time_zone_phase` (`cluster_id`,`time_zone`,`phase`),
  KEY `idx_db_app_abbr_bk_biz_id` (`db_app_abbr`,`bk_biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `spider_partition_config_v2` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `bk_biz_id` int(11) NOT NULL,
  `db_app_abbr` varchar(128) NOT NULL COMMENT '业务名称缩写',
  `bk_biz_name` varchar(128) NOT NULL COMMENT '业务名称写',
  `immute_domain` varchar(200) NOT NULL,
  `port` int(11) NOT NULL,
  `bk_cloud_id` int(11) NOT NULL,
  `cluster_id` int(11) NOT NULL,
  `dblike` varchar(100) NOT NULL,
  `tblike` varchar(100) NOT NULL,
  `partition_column` varchar(100) DEFAULT NULL,
  `partition_column_type` varchar(100) DEFAULT NULL,
  `reserved_partition` int(11) NOT NULL,
  `extra_partition` int(11) NOT NULL,
  `partition_time_interval` int(11) NOT NULL,
  `partition_type` int(11) NOT NULL,
  `expire_time` int(11) NOT NULL,
  `time_zone` varchar(16) NOT NULL COMMENT '集群所在的时区',
  `creator` varchar(100) DEFAULT NULL,
  `updator` varchar(100) DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00',
  `phase` varchar(100) NOT NULL COMMENT 'online--在用;offline--停用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq` (`bk_biz_id`,`immute_domain`,`cluster_id`,`dblike`,`tblike`),
  KEY `idx_time_zone_phase` (`cluster_id`,`time_zone`,`phase`),
  KEY `idx_db_app_abbr_bk_biz_id` (`db_app_abbr`,`bk_biz_id`),
  KEY `idx1` (`bk_biz_id`,`dblike`,`tblike`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

