apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: {{ include "milvus.datanode.cmpvName" . }}
spec:
  compatibilityRules:
    - releases:
        - datanode-v2.6.0
      compDefs:
        - datanode-2.0.0
  releases:
    - name: datanode-v2.6.0
      serviceVersion: 2.6.0
      images:
        datanode: milvusdb/milvus:v2.6.0