# Generated by Django 4.2.23 on 2025-10-31 03:03


from django.db import migrations, models
import backend.flow.consts
from backend.db_meta.enums import ClusterType
from backend.flow.consts import StateType

import backend.flow.consts


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportRecord",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("record_id", models.AutoField(help_text="主键id", primary_key=True, serialize=False)),
                ("ticket_id", models.PositiveIntegerField(default=0, help_text="关联的单据id")),
                ("root_id", models.CharField(default="", help_text="关联root_id", max_length=64)),
                ("bk_biz_id", models.IntegerField(default=0, help_text="关联的业务id")),
                ("cluster_id", models.IntegerField(default=0, help_text="集群ID")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=[
                            ("tendbsingle", "MySQL单节点集群"),
                            ("tendbha", "MySQL高可用集群"),
                            ("tendbcluster", "TendbCluster集群"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("redis", "Redis"),
                            ("PredixyRedisCluster", "RedisCluster集群"),
                            ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                            ("TwemproxyRedisInstance", "TendisCache集群"),
                            ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                            ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                            ("RedisInstance", "RedisCache主从版"),
                            ("TendisSSDInstance", "TendisSSD主从版"),
                            ("TendisplusInstance", "Tendisplus主从版"),
                            ("RedisCluster", "RedisCluster集群"),
                            ("TendisplusCluster", "TendisplusCluster集群"),
                            ("TendisplusInstance", "Tendisplus存储版集群"),
                            ("RedisInstance", "TendisCache集群"),
                            ("TendisSSDInstance", "TendisSSD集群"),
                            ("es", "ES集群"),
                            ("kafka", "Kafka集群"),
                            ("hdfs", "Hdfs集群"),
                            ("influxdb", "Influxdb实例"),
                            ("pulsar", "Pulsar集群"),
                            ("doris", "Doris集群"),
                            ("vm", "vm集群"),
                            ("dbmon", "redis监控"),
                            ("MongoReplicaSet", "Mongo副本集"),
                            ("MongoShardedCluster", "Mongo分片集群"),
                            ("riak", "Riak集群"),
                            ("sqlserver_single", "sqlserver单节点版"),
                            ("sqlserver_ha", "sqlserver主从版"),
                            ("oracle_primary_standby", "oracle主从版"),
                            ("oracle_single_none", "oracle单节点版"),
                            ("k8s_surreal", "k8s surrealdb集群"),
                            ("k8s_vm", "k8s Victoria metrics集群"),
                            ("k8s_rw", "k8s Risingwave集群"),
                            ("k8s_mv", "k8s Milvus集群"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("immute_domain", models.CharField(default="", max_length=255)),
                ("cluster_shard_num", models.IntegerField(default=0, help_text="集群分片数")),
                ("analyzed_shard_num", models.IntegerField(default=0, help_text="参与分析的分片数")),
                ("analysis_time", models.IntegerField(default=0, help_text="分析时长")),
                ("redis_version", models.CharField(default="", help_text="redis版本", max_length=255)),
                ("source_type", models.CharField(default="", help_text="数据来源类型", max_length=255)),
                ("source_role", models.CharField(default="", help_text="rdb来源", max_length=255)),
                ("source_addr_list", models.JSONField(blank=True, default=list, help_text="rdb来源地址列表", null=True)),
                ("atime_available", models.BooleanField(default=False, help_text="atime可用性")),
                ("sampling_ratio", models.FloatField(default=0.1, help_text="采样比例, 0.1表示10%")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "创建态"),
                            ("READY", "准备态"),
                            ("RUNNING", "运行态"),
                            ("SUSPENDED", "暂停态"),
                            ("BLOCKED", "闭塞态"),
                            ("FINISHED", "完成态"),
                            ("FAILED", "失败态"),
                            ("REVOKED", "取消态"),
                            ("EXPIRED", "已过期"),
                        ],
                        default=backend.flow.consts.StateType["CREATED"],
                        help_text="报告状态",
                        max_length=64,
                    ),
                ),
                ("current_progress", models.CharField(default="", help_text="当前进度, 0-100", max_length=255)),
                ("exec_ip", models.CharField(default="", help_text="执行ip", max_length=255)),
                ("keystat_report_rows_num", models.IntegerField(default=0, help_text="内存分析统计报告行数据")),
                ("keystat_rank_rows_num", models.IntegerField(default=0, help_text="内存分析统计排行行数据")),
            ],
            options={
                "verbose_name": "内存分析统计记录表",
                "verbose_name_plural": "内存分析统计记录表",
                "indexes": [models.Index(fields=["bk_biz_id", "create_at"], name="redis_keyst_bk_biz__c53645_idx")],
            },
        ),
        migrations.CreateModel(
            name="ReportProgress",
            fields=[
                ("id", models.AutoField(help_text="主键id", primary_key=True, serialize=False)),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("record_id", models.BigIntegerField(default=0, help_text="关联的记录id")),
                ("progress", models.CharField(default="", help_text="进度, 0-100", max_length=255)),
                ("detail", models.JSONField(blank=True, default=dict, help_text="进度详情", null=True)),
            ],
            options={
                "verbose_name": "内存分析统计进度记录表",
                "verbose_name_plural": "内存分析统计进度记录表",
                "indexes": [models.Index(fields=["record_id"], name="redis_keyst_record__3cac24_idx")],
            },
        ),
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                ("id", models.AutoField(help_text="主键id", primary_key=True, serialize=False)),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("record_id", models.BigIntegerField(default=0, help_text="关联的记录id")),
                ("key_name", models.CharField(default="", help_text="key名称", max_length=255)),
                ("key_type", models.CharField(default="", help_text="key类型", max_length=255)),
                ("key_class", models.CharField(default="", help_text="key分类", max_length=255)),
                ("count", models.IntegerField(default=0, help_text="数量")),
                ("count_with_ttl", models.IntegerField(default=0, help_text="带TTL的数量")),
                ("member_max_count", models.IntegerField(default=0, help_text="成员最大数量")),
                ("avg_key_length", models.IntegerField(default=0, help_text="平均成员数量")),
                ("avg_ttl", models.IntegerField(default=0, help_text="平均TTL")),
                ("avg_ttl_human", models.CharField(default="", help_text="平均TTL人类化描述", max_length=255)),
                ("min_idletime_human", models.CharField(default="", help_text="最小空闲时间人类化描述", max_length=255)),
                ("so_min_idletime_human", models.CharField(default="", help_text="最小空闲时间人类化描述ForSo", max_length=255)),
                ("min_idletime", models.IntegerField(default=0, help_text="最小空闲时间")),
                ("avg_key_used_bytes", models.IntegerField(default=0, help_text="单key平均占用内存")),
                ("mem_used_bytes", models.IntegerField(default=0, help_text="内存使用量字节数")),
                ("mem_used_pct", models.FloatField(default=0, help_text="内存使用量字节数占比", max_length=255)),
            ],
            options={
                "verbose_name": "内存分析统计记录详情表",
                "verbose_name_plural": "内存分析统计记录详情表",
                "indexes": [models.Index(fields=["record_id"], name="redis_keyst_record__6e262f_idx")],
            },
        ),
        migrations.CreateModel(
            name="RankItem",
            fields=[
                ("id", models.AutoField(help_text="主键id", primary_key=True, serialize=False)),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("record_id", models.BigIntegerField(default=0, help_text="关联的记录id")),
                ("key_name", models.CharField(default="", help_text="key名称", max_length=255)),
                ("key_type", models.CharField(default="", help_text="key类型", max_length=255)),
                ("rank_value", models.IntegerField(default=0, help_text="排行值")),
                ("ttl", models.IntegerField(default=0, help_text="TTL")),
                ("atime", models.IntegerField(default=0, help_text="最后访问时间")),
                ("member", models.IntegerField(default=0, help_text="成员的数量")),
                ("member_len", models.IntegerField(default=0, help_text="成员的平均长度")),
                ("key_length", models.IntegerField(default=0, help_text="key的长度")),
                ("value_size", models.IntegerField(default=0, help_text="value的长度或者成员value的长度")),
                ("db", models.IntegerField(default=0, help_text="db")),
                ("memory_size", models.IntegerField(default=0, help_text="基础内存占用, 复合类型中是采样计算结果")),
            ],
            options={
                "verbose_name": "内存分析统计排行详情表",
                "verbose_name_plural": "内存分析统计排行详情表",
                "indexes": [models.Index(fields=["record_id"], name="redis_keyst_record__43f67f_idx")],
            },
        ),
    ]
