# Generated by Django 4.2.23 on 2025-11-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankitem",
            name="memory_size",
            field=models.BigIntegerField(default=0, help_text="基础内存占用, 复合类型中是采样计算结果"),
        ),
        migrations.AlterField(
            model_name="rankitem",
            name="value_size",
            field=models.BigIntegerField(default=0, help_text="value的长度或者成员value的长度"),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="mem_used_bytes",
            field=models.BigIntegerField(default=0, help_text="内存使用量字节数"),
        ),
    ]
