# Generated by Django 4.2.23 on 2025-12-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0002_alter_rankitem_memory_size_alter_rankitem_value_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankitem",
            name="atime",
            field=models.BigIntegerField(default=0, help_text="最后访问时间"),
        ),
        migrations.AlterField(
            model_name="rankitem",
            name="rank_value",
            field=models.BigIntegerField(default=0, help_text="排行值"),
        ),
        migrations.AlterField(
            model_name="rankitem",
            name="ttl",
            field=models.BigIntegerField(default=0, help_text="TTL"),
        ),
    ]
