# Generated by Django 4.2.23 on 2025-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankitem",
            name="ttl_human",
            field=models.CharField(default="", help_text="过期时间（带单位）", max_length=255),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="min_idletime_show",
            field=models.CharField(default="", help_text="最近访问时间（带单位）", max_length=255),
        ),
    ]
