# Generated by Django 4.2.23 on 2026-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0003_alter_rankitem_atime_alter_rankitem_rank_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankitem",
            name="member",
            field=models.BigIntegerField(default=0, help_text="成员的数量"),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="avg_key_used_bytes",
            field=models.BigIntegerField(default=0, help_text="单key平均占用内存"),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="avg_ttl",
            field=models.BigIntegerField(default=0, help_text="平均TTL"),
        ),
        migrations.AlterField(
            model_name="reportitem",
            name="min_idletime",
            field=models.BigIntegerField(default=0, help_text="最小空闲时间"),
        ),
    ]
