# Generated by Django 4.2.27 on 2026-04-24 07:41

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0004_alter_rankitem_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportrecord",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
            ),
        ),
    ]
