# Generated by Django 4.2.27 on 2026-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0004_alter_rankitem_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportrecord",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("tendbsingle", "MySQL单节点集群"),
                    ("tendbha", "MySQL高可用集群"),
                    ("tendbcluster", "TendbCluster集群"),
                    ("tbinlogdumper", "TBinlogDumper"),
                    ("redis", "Redis"),
                    ("PredixyRedisCluster", "RedisCluster集群"),
                    ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                    ("TwemproxyRedisInstance", "TendisCache集群"),
                    ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                    ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                    ("RedisInstance", "RedisCache主从版"),
                    ("TendisSSDInstance", "TendisSSD主从版"),
                    ("TendisplusInstance", "Tendisplus主从版"),
                    ("RedisCluster", "RedisCluster集群"),
                    ("TendisplusCluster", "TendisplusCluster集群"),
                    ("TendisplusInstance", "Tendisplus存储版集群"),
                    ("RedisInstance", "TendisCache集群"),
                    ("TendisSSDInstance", "TendisSSD集群"),
                    ("es", "ES集群"),
                    ("kafka", "Kafka集群"),
                    ("hdfs", "Hdfs集群"),
                    ("influxdb", "Influxdb实例"),
                    ("pulsar", "Pulsar集群"),
                    ("doris", "Doris集群"),
                    ("vm", "vm集群"),
                    ("dbmon", "redis监控"),
                    ("MongoReplicaSet", "Mongo副本集"),
                    ("MongoShardedCluster", "Mongo分片集群"),
                    ("riak", "Riak集群"),
                    ("sqlserver_single", "sqlserver单节点版"),
                    ("sqlserver_ha", "sqlserver主从版"),
                    ("oracle_primary_standby", "oracle主从版"),
                    ("oracle_single_none", "oracle单节点版"),
                    ("k8s_surrealdb", "k8s SurrealDB集群"),
                    ("k8s_victoriametrics", "k8s VictoriaMetrics集群"),
                    ("k8s_risingwave", "k8s Risingwave集群"),
                    ("k8s_milvus", "k8s Milvus集群"),
                    ("k8s_qdrant", "k8s Qdrant集群"),
                    ("k8s_greptimedb", "k8s GreptimeDB集群"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
