# Generated by Django 4.2.27 on 2026-05-06 06:28

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("redis_keystat_report", "0005_alter_reportrecord_cluster_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportrecord",
            name="cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                max_length=64,
            ),
        ),
    ]
