CREATE TABLE `tb_mysql_backup_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `backup_id` varchar(64) NOT NULL,
  `mysql_role` varchar(30) NOT NULL DEFAULT '',
  `shard_value` int(11) NOT NULL DEFAULT '0',
  `backup_type` varchar(30) NOT NULL,
  `cluster_id` int(11) NOT NULL,
  `cluster_address` varchar(255) DEFAULT NULL,
  `backup_host` varchar(30) NOT NULL,
  `backup_port` int(11) NOT NULL,
  `server_id` varchar(10) DEFAULT NULL,
  `bill_id` varchar(30) DEFAULT NULL,
  `bk_biz_id` int(11) DEFAULT NULL,
  `mysql_version` varchar(60) DEFAULT NULL,
  `data_schema_grant` varchar(30) DEFAULT NULL,
  `is_full_backup` tinyint(4) DEFAULT NULL,
  `file_retention_tag` varchar(60) DEFAULT NULL,
  `total_filesize` bigint(20) NOT NULL DEFAULT '0',
  `backup_begin_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `backup_end_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `backup_consistent_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `backup_status` varchar(60) DEFAULT NULL,
  `binlog_info` text,
  `file_list` text,
  `extra_fields` text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_1` (`backup_host`,`backup_port`,`mysql_role`,`backup_consistent_time`),
  UNIQUE KEY `uniq_2` (`cluster_address`,`shard_value`,`mysql_role`,`backup_id`),
  KEY `idx_1` (`backup_consistent_time`),
  KEY `idx_2`(`backup_id`)
) ENGINE=InnoDB AUTO_INCREMENT=81177 DEFAULT CHARSET=utf8;