CREATE TABLE `mysql_db_table_size` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `cluster_domain` varchar(200) NOT NULL,
    `dteventtimehour` datetime NOT NULL COMMENT 'datetime precision to hour, used as where,group-by,expire',
    `report_time` varchar(32) NULL,
    `thedate` int NOT NULL,
    `dteventtimestamp` bigint NOT NULL,
    `instance_host` varchar(60) NULL,
    `instance_port` int NULL,
    `shard_value` int NULL,
    `database_name` varchar(100) NULL,
    `table_name` varchar(100) NULL,
    `table_size` bigint NULL,
    `original_database_name` varchar(100) NULL,
    `database_size` bigint NULL,
    `machine_type` varchar(60) NULL,
    `instance_role` varchar(60) NULL,
    `bk_biz_id` int NULL,
    `bk_cloud_id` int NULL,
    PRIMARY KEY (`cluster_domain`,`dteventtimehour`,`id`),
    KEY idx_0(id),
    KEY idx_1(cluster_domain,database_name,original_database_name,table_name,dteventtimehour),
    KEY idx_2(cluster_domain,dteventtimehour),
    KEY idx_3(dteventtimehour,cluster_domain,database_name),
    KEY idx_4(dteventtimehour),
    KEY idx_5(instance_host,instance_port)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;