CREATE TABLE tb_mysql_binlog_result (
    id bigint not null auto_increment,
    bk_biz_id int not null,
    cluster_id int not null,
    cluster_domain varchar(120) default '',
    db_role varchar(20) not null default '',
    host varchar(64) not null,
    port int default 0,
    filename varchar(64) not null,
    filesize bigint not null,
    file_mtime varchar(32) not null,
    start_time varchar(32) default '',
    stop_time varchar(32) default '',
    backup_status int default -2,
    backup_status_info varchar(120) not null default '',
    task_id varchar(64) default '',
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    backup_enable tinyint(4) default -1,
    PRIMARY KEY(`id`),
    UNIQUE KEY uniq_1(cluster_domain,host,port,filename),
    KEY idx1_(bk_biz_id,file_mtime),
    KEY idx_2(file_mtime),
    KEY idx_3(host),
    KEY idx_4(backup_status),
    KEY idx_5(cluster_id),
    KEY idx_6(task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;