# Generated by Django 3.2.4 on 2023-04-18 11:32

from django.db import migrations, models

import backend.db_monitor.constants
from backend.configuration.constants import DBType
from backend.db_meta.enums import ClusterType
from backend.db_monitor.constants import GroupType


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID, 0代表全业务")),
                ("template_id", models.IntegerField(default=0, help_text="监控模板ID")),
                ("monitor_strategy_id", models.IntegerField(default=0, help_text="监控策略ID")),
                ("name", models.CharField(default="", max_length=128, verbose_name="策略名称")),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        default="mysql",
                        max_length=64,
                        verbose_name="DB类型",
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="实例详情")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "告警策略实例",
            },
        ),
        migrations.CreateModel(
            name="CollectInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID, 0代表全业务")),
                ("plugin_id", models.CharField(max_length=128, unique=True, verbose_name="插件ID")),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        default="mysql",
                        max_length=64,
                        verbose_name="DB类型",
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="详情")),
                ("template_id", models.IntegerField(default=0, help_text="监控插件模板ID")),
                ("collect_id", models.IntegerField(help_text="监控采集策略ID")),
            ],
            options={
                "verbose_name": "采集策略实例",
            },
        ),
        migrations.CreateModel(
            name="CollectTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID, 0代表全业务")),
                ("plugin_id", models.CharField(max_length=128, unique=True, verbose_name="插件ID")),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        default="mysql",
                        max_length=64,
                        verbose_name="DB类型",
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="详情")),
            ],
            options={
                "verbose_name": "采集策略模板",
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(default="", max_length=128, verbose_name="名称")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="详情")),
                ("variables", models.JSONField(default=dict, verbose_name="变量")),
                ("org_id", models.BigIntegerField(verbose_name="grafana-org_id")),
                ("org_name", models.CharField(max_length=64, verbose_name="grafana-org_name")),
                ("uid", models.CharField(max_length=64, verbose_name="grafana-uid")),
                ("url", models.CharField(max_length=255, verbose_name="grafana-url")),
            ],
            options={
                "verbose_name": "仪表盘",
            },
        ),
        migrations.CreateModel(
            name="NoticeGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID, 0代表全业务")),
                ("monitor_group_id", models.BigIntegerField(default=0, help_text="监控通知组ID")),
                (
                    "group_type",
                    models.CharField(
                        choices=GroupType.get_choices(),
                        default=backend.db_monitor.constants.GroupType["PLATFORM"],
                        max_length=64,
                        verbose_name="告警通知组类别",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        max_length=32,
                        verbose_name="数据库类型",
                    ),
                ),
                ("users", models.JSONField(verbose_name="人员列表")),
                ("dba_sync", models.BooleanField(default=True, help_text="自动同步DBA人员配置")),
            ],
            options={
                "verbose_name": "告警通知组",
            },
        ),
        migrations.CreateModel(
            name="RuleTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务ID, 0代表全业务")),
                ("monitor_strategy_id", models.IntegerField(default=0, help_text="监控策略ID")),
                ("name", models.CharField(default="", max_length=128, verbose_name="策略名称")),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        default="mysql",
                        max_length=64,
                        verbose_name="DB类型",
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="模板详情")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "告警策略模板",
            },
        ),
    ]
