# Generated by Django 3.2.19 on 2023-08-21 02:28

from django.db import migrations, models

from backend.configuration.constants import DBType


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0002_alter_noticegroup_db_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticegroup",
            name="db_type",
            field=models.CharField(
                choices=DBType.get_choices(),
                max_length=32,
                verbose_name="数据库类型",
            ),
        ),
    ]
