# Generated by Django 3.2.19 on 2023-08-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0002_alter_noticegroup_db_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticegroup",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("mysql", "MySQL"),
                    ("tendbcluster", "TendbCluster"),
                    ("redis", "Redis"),
                    ("mongodb", "MongoDB"),
                    ("kafka", "Kafka"),
                    ("hdfs", "HDFS"),
                    ("es", "ElasticSearch"),
                    ("pulsar", "Pulsar"),
                    ("influxdb", "InfluxDB"),
                    ("riak", "Riak"),
                    ("cloud", "Cloud"),
                ],
                max_length=32,
                verbose_name="数据库类型",
            ),
        ),
    ]
