# Generated by Django 3.2.19 on 2023-09-05 02:23

from django.db import migrations, models

from backend.db_monitor.constants import TargetLevel


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0004_auto_20230829_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="parent_details",
            field=models.JSONField(default=dict, verbose_name="父级策略模板详情，可用于还原"),
        ),
        migrations.AlterField(
            model_name="monitorpolicy",
            name="details",
            field=models.JSONField(default=dict, verbose_name="当前策略详情，可用于patch"),
        ),
        migrations.AlterField(
            model_name="monitorpolicy",
            name="target_level",
            field=models.CharField(
                choices=TargetLevel.get_choices(), default="app_id", max_length=64, verbose_name="监控目标级别，跟随targets调整"
            ),
        ),
    ]
