# Generated by Django 3.2.19 on 2023-09-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0005_auto_20230905_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="target_keyword",
            field=models.TextField(default="", verbose_name="监控目标检索冗余字段"),
        ),
    ]
