# Generated by Django 3.2.19 on 2023-09-12 03:28

from django.db import migrations, models

from backend.configuration.constants import DBType


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0006_monitorpolicy_target_keyword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticegroup",
            name="group_type",
        ),
        migrations.AddField(
            model_name="noticegroup",
            name="is_built_in",
            field=models.BooleanField(default=False, verbose_name="是否内置"),
        ),
        migrations.AddField(
            model_name="noticegroup",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="告警通知组名称"),
        ),
        migrations.AlterField(
            model_name="noticegroup",
            name="db_type",
            field=models.CharField(choices=DBType.get_choices(), default="", max_length=32, verbose_name="数据库类型"),
        ),
    ]
