# Generated by Django 3.2.19 on 2023-09-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0007_auto_20230912_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="expected_notify_groups",
            field=models.JSONField(default=dict, verbose_name="期望的通知组"),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="monitor_indicator",
            field=models.CharField(default="", max_length=128, verbose_name="监控指标名"),
        ),
    ]
