# Generated by Django 3.2.19 on 2023-09-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0008_auto_20230914_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorpolicy",
            name="expected_notify_groups",
        ),
    ]
