# Generated by Django 3.2.19 on 2023-10-07 07:25

from django.db import migrations, models

import backend.db_monitor.constants


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0010_auto_20230921_2148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatchgroup",
            name="is_synced",
        ),
        migrations.RemoveField(
            model_name="dispatchgroup",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dispatchgroup",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="monitorpolicy",
            name="dispatch_group_id",
        ),
        migrations.RemoveField(
            model_name="monitorpolicy",
            name="is_synced",
        ),
        migrations.RemoveField(
            model_name="noticegroup",
            name="is_synced",
        ),
        migrations.AddField(
            model_name="collectinstance",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="策略名称，全局唯一"),
        ),
        migrations.AddField(
            model_name="collectinstance",
            name="short_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="collectinstance",
            name="sync_at",
            field=models.DateTimeField(null=True, verbose_name="最近一次的同步时间"),
        ),
        migrations.AddField(
            model_name="collectinstance",
            name="version",
            field=models.IntegerField(default=0, verbose_name="版本"),
        ),
        migrations.AddField(
            model_name="collecttemplate",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="策略名称，全局唯一"),
        ),
        migrations.AddField(
            model_name="collecttemplate",
            name="short_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="collecttemplate",
            name="version",
            field=models.IntegerField(default=0, verbose_name="版本"),
        ),
        migrations.AddField(
            model_name="dispatchgroup",
            name="bk_biz_id",
            field=models.IntegerField(default=0, unique=True, verbose_name="业务ID, 0代表全业务"),
        ),
        migrations.AddField(
            model_name="dispatchgroup",
            name="rules",
            field=models.JSONField(default=list, verbose_name="规则列表"),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="alert_source",
            field=models.CharField(
                choices=[("time_series", "时序数据"), ("event", "事件数据"), ("log", "日志关键字")],
                default=backend.db_monitor.constants.AlertSourceEnum["TIME_SERIES"],
                max_length=32,
                verbose_name="告警数据来源",
            ),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="version",
            field=models.IntegerField(default=0, verbose_name="版本"),
        ),
        migrations.AlterField(
            model_name="collectinstance",
            name="plugin_id",
            field=models.CharField(max_length=128, verbose_name="插件ID"),
        ),
        migrations.AlterField(
            model_name="collecttemplate",
            name="plugin_id",
            field=models.CharField(max_length=128, verbose_name="插件ID"),
        ),
        migrations.AlterField(
            model_name="dispatchgroup",
            name="details",
            field=models.JSONField(default=dict, verbose_name="策略模板详情"),
        ),
        migrations.AlterField(
            model_name="monitorpolicy",
            name="notify_groups",
            field=models.JSONField(default=list, verbose_name="通知组"),
        ),
        migrations.AlterField(
            model_name="monitorpolicy",
            name="notify_rules",
            field=models.JSONField(default=list, verbose_name="通知规则"),
        ),
        migrations.AlterField(
            model_name="monitorpolicy",
            name="targets",
            field=models.JSONField(default=list, verbose_name="监控目标"),
        ),
        migrations.AlterField(
            model_name="monitorpolicy",
            name="test_rules",
            field=models.JSONField(default=list, verbose_name="检测规则"),
        ),
    ]
