# Generated by Django 3.2.19 on 2023-10-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0011_auto_20231007_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyrule",
            name="monitor_duty_rule_id",
            field=models.IntegerField(default=0, verbose_name="监控轮值规则 ID"),
        ),
        migrations.AddField(
            model_name="noticegroup",
            name="monitor_duty_rule_id",
            field=models.IntegerField(default=0, verbose_name="监控轮值规则 ID"),
        ),
    ]
