# Generated by Django 3.2.19 on 2023-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0012_auto_20231009_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitorpolicy",
            name="target_level",
            field=models.CharField(
                choices=[
                    ("platform", "platform"),
                    ("appid", "app id"),
                    ("db_module", "db module"),
                    ("cluster_domain", "cluster domain"),
                    ("custom", "custom"),
                ],
                default="appid",
                max_length=64,
                verbose_name="监控目标级别，跟随targets调整",
            ),
        ),
    ]
