# Generated by Django 3.2.19 on 2023-10-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0013_alter_monitorpolicy_target_level"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="noticegroup",
            unique_together={("bk_biz_id", "name")},
        ),
    ]
