# Generated by Django 3.2.19 on 2023-10-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0014_alter_noticegroup_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectinstance",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="collecttemplate",
            name="short_name",
        ),
        migrations.AddField(
            model_name="collectinstance",
            name="machine_types",
            field=models.JSONField(default=list, verbose_name="绑定machine"),
        ),
        migrations.AddField(
            model_name="collecttemplate",
            name="machine_types",
            field=models.JSONField(default=list, verbose_name="绑定machine"),
        ),
    ]
