# Generated by Django 3.2.19 on 2023-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0015_auto_20231031_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="custom_conditions",
            field=models.JSONField(default=list, verbose_name="自定义过滤列表"),
        ),
    ]
