# Generated by Django 3.2.19 on 2023-11-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0016_monitorpolicy_custom_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyrule",
            name="name",
            field=models.CharField(max_length=128, verbose_name="轮值规则名称"),
        ),
        migrations.AlterField(
            model_name="noticegroup",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="告警通知组名称"),
        ),
    ]
