# Generated by Django 3.2.25 on 2024-06-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0019_alter_dashboard_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dutyrule",
            options={"verbose_name": "轮值规则(DutyRule)", "verbose_name_plural": "轮值规则(DutyRule)"},
        ),
        migrations.AlterModelOptions(
            name="monitorpolicy",
            options={"verbose_name": "告警策略(MonitorPolicy)"},
        ),
        migrations.AlterModelOptions(
            name="noticegroup",
            options={"verbose_name": "告警通知组(NoticeGroup)", "verbose_name_plural": "告警通知组(NoticeGroup)"},
        ),
    ]
