# Generated by Django 3.2.25 on 2024-09-19 02:19

from django.db import migrations, models

from backend.db_meta.enums import ClusterType, InstanceRole, MachineType
from backend.db_monitor.models import MySQLAutofixTicketStatus


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0020_auto_20240621_1216"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLAutofixTodo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(default=0)),
                ("bk_biz_id", models.IntegerField(default=0)),
                ("cluster_id", models.IntegerField(default=0)),
                ("immute_domain", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=MachineType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "instance_role",
                    models.CharField(
                        choices=InstanceRole.get_choices(),
                        default="",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("ip", models.GenericIPAddressField(default="")),
                ("port", models.IntegerField(default=0)),
                ("event_create_time", models.DateTimeField()),
                ("dbha_gm_ip", models.GenericIPAddressField(default="")),
                ("context_master_host", models.GenericIPAddressField(default="", null=True)),
                ("context_master_port", models.IntegerField(default=0, null=True)),
                ("context_master_log_file", models.CharField(default="", max_length=255, null=True)),
                ("context_master_log_pos", models.IntegerField(default=0, null=True)),
                ("inplace_ticket_id", models.BigIntegerField(default=0)),
                (
                    "inplace_ticket_status",
                    models.CharField(
                        choices=MySQLAutofixTicketStatus.get_choices(),
                        default="UNSUBMITTED",
                        max_length=64,
                    ),
                ),
                ("replace_ticket_id", models.BigIntegerField(default=0)),
                (
                    "replace_ticket_status",
                    models.CharField(
                        choices=MySQLAutofixTicketStatus.get_choices(),
                        default="UNSUBMITTED",
                        max_length=64,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[("IN_PLACE_AUTOFIX", "原地自愈"), ("REPLACE_NEW", "新机替换")],
                        default="IN_PLACE_AUTOFIX",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(
                fields=["inplace_ticket_status", "current_step", "inplace_ticket_id"],
                name="db_monitor__inplace_45d255_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(
                fields=["replace_ticket_status", "current_step", "replace_ticket_id"],
                name="db_monitor__replace_188286_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(fields=["inplace_ticket_id"], name="db_monitor__inplace_a1b225_idx"),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(fields=["replace_ticket_id"], name="db_monitor__replace_191a06_idx"),
        ),
    ]
