# Generated by Django 3.2.25 on 2025-01-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0020_auto_20240621_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyrule",
            name="biz_config",
            field=models.JSONField(default=dict, verbose_name="业务设置(包含业务include/排除业务exclude)"),
        ),
    ]
