# Generated by Django 3.2.25 on 2024-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0021_auto_20240919_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlautofixtodo",
            name="check_id",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="mysqlautofixtodo",
            unique_together={("check_id", "ip", "port")},
        ),
    ]
