# Generated by Django 3.2.25 on 2025-03-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0021_dutyrule_biz_config"),
        ("db_monitor", "0022_auto_20240924_0953"),
    ]

    operations = []
