# Generated by Django 3.2.25 on 2025-04-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0023_merge_20250312_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqlautofixtodo",
            name="inplace_ticket_status",
            field=models.CharField(
                choices=[
                    ("UNSUBMITTED", "未提交"),
                    ("SKIPPED", "跳过"),
                    ("PENDING", "等待中"),
                    ("RUNNING", "执行中"),
                    ("SUCCEEDED", "成功"),
                    ("FAILED", "失败"),
                    ("REVOKED", "撤销"),
                    ("TERMINATED", "终止"),
                    ("TIMEOUT", "等待超时"),
                ],
                default="UNSUBMITTED",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="mysqlautofixtodo",
            name="replace_ticket_status",
            field=models.CharField(
                choices=[
                    ("UNSUBMITTED", "未提交"),
                    ("SKIPPED", "跳过"),
                    ("PENDING", "等待中"),
                    ("RUNNING", "执行中"),
                    ("SUCCEEDED", "成功"),
                    ("FAILED", "失败"),
                    ("REVOKED", "撤销"),
                    ("TERMINATED", "终止"),
                    ("TIMEOUT", "等待超时"),
                ],
                default="UNSUBMITTED",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(
                fields=["current_step", "replace_ticket_id", "check_id", "ip"], name="db_monitor__current_ee3478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(
                fields=["current_step", "inplace_ticket_id", "check_id", "ip"], name="db_monitor__current_9b0a65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(
                fields=["inplace_ticket_status", "current_step", "check_id"], name="db_monitor__inplace_5698f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mysqlautofixtodo",
            index=models.Index(
                fields=["replace_ticket_status", "current_step", "check_id"], name="db_monitor__replace_1c2737_idx"
            ),
        ),
    ]
