# Generated by Django 3.2.25 on 2025-06-10 09:45

from django.db import migrations, models

from backend.configuration.constants import DBType
from backend.db_monitor.constants import DashboardType


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0024_auto_20250407_0846"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="db_type",
            field=models.CharField(choices=DBType.get_choices(), default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="type",
            field=models.CharField(
                choices=DashboardType.get_choices(), default="cluster", help_text="仪表盘类型", max_length=64
            ),
            preserve_default=False,
        ),
    ]
