# Generated by Django 3.2.25 on 2025-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0025_auto_20250610_1745"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__inplace_45d255_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__replace_188286_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__inplace_a1b225_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__replace_191a06_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__current_ee3478_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__current_9b0a65_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__inplace_5698f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="mysqlautofixtodo",
            name="db_monitor__replace_1c2737_idx",
        ),
        migrations.RenameField(
            model_name="mysqlautofixtodo",
            old_name="inplace_ticket_status",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="context_master_host",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="context_master_log_file",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="context_master_log_pos",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="context_master_port",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="current_step",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="dbha_gm_ip",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="inplace_ticket_id",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="instance_role",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="replace_ticket_id",
        ),
        migrations.RemoveField(
            model_name="mysqlautofixtodo",
            name="replace_ticket_status",
        ),
        migrations.AddField(
            model_name="mysqlautofixtodo",
            name="ticket_id",
            field=models.BigIntegerField(default=0, help_text="自愈单据"),
        ),
        migrations.AlterField(
            model_name="mysqlautofixtodo",
            name="cluster_id",
            field=models.BigIntegerField(default=0),
        ),
    ]
