# Generated by Django 3.2.25 on 2025-07-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0026_auto_20250703_1309"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MySQLAutofixTodo",
            new_name="MySQLDBHAAutofixTodo",
        ),
    ]
