# Generated by Django 3.2.25 on 2025-07-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0027_rename_mysqlautofixtodo_mysqldbhaautofixtodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqldbhaautofixtodo",
            name="instance_role",
            field=models.CharField(
                choices=[
                    ("orphan", "orphan"),
                    ("backend_master", "Master"),
                    ("backend_repeater", "Repeater"),
                    ("backend_slave", "Slave"),
                    ("remote_master", "Remote Master"),
                    ("remote_repeater", "Remote Repeater"),
                    ("remote_slave", "Remote Slave"),
                    ("proxy", "Proxy"),
                    ("redis_master", "Master"),
                    ("redis_slave", "Slave"),
                    ("es_datanode_hot", "热节点"),
                    ("es_datanode_cold", "冷节点"),
                    ("es_master", "Master 节点"),
                    ("es_client", "Client 节点"),
                    ("broker", "Broker"),
                    ("zookeeper", "Zookeeper"),
                    ("hdfs_namenode", "NameNode"),
                    ("hdfs_zookeeper", "Zookeeper"),
                    ("hdfs_journalnode", "Journalnode"),
                    ("hdfs_datanode", "DataNode"),
                    ("influxdb", "influxdb"),
                    ("pulsar_bookkeeper", "Bookkeeper"),
                    ("pulsar_zookeeper", "Zookeeper"),
                    ("pulsar_broker", "Broker"),
                    ("doris_backend_hot", "热节点"),
                    ("doris_backend_warm", "温节点"),
                    ("doris_backend_cold", "冷节点"),
                    ("doris_follower", "Follower"),
                    ("doris_observer", "Observer"),
                    ("m1", "m1"),
                    ("m2", "m2"),
                    ("m3", "m3"),
                    ("m4", "m4"),
                    ("m5", "m5"),
                    ("m6", "m6"),
                    ("m7", "m7"),
                    ("m8", "m8"),
                    ("m9", "m9"),
                    ("m10", "m10"),
                    ("backup", "backup"),
                    ("riak_node", "Riak"),
                    ("vmstorage", "vmstorage"),
                    ("vminsert", "vminsert"),
                    ("vmselect", "vmselect"),
                    ("vmauth", "vmauth"),
                    ("primary", "primary"),
                    ("standby", "standby"),
                ],
                default="",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mysqldbhaautofixtodo",
            name="new_master_host",
            field=models.GenericIPAddressField(default="", null=True),
        ),
        migrations.AddField(
            model_name="mysqldbhaautofixtodo",
            name="new_master_log_file",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mysqldbhaautofixtodo",
            name="new_master_log_pos",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="mysqldbhaautofixtodo",
            name="new_master_port",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
