# Generated by Django 3.2.25 on 2025-10-09 03:48

from django.db import migrations, models

import backend.db_monitor.models.mysql_dbha_autofix_event
from backend.db_meta.enums import ClusterType, InstanceRole, MachineType


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0028_auto_20250725_1433"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLDBHAAutofixTicketStageQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("ticket_id", models.BigIntegerField(default=0, help_text="单据 id")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("RUNNING", "执行中"),
                            ("SUCCEEDED", "成功"),
                            ("TERMINATED", "终止"),
                            ("FAILED", "失败"),
                            ("REVOKED", "撤销"),
                            ("SKIPPED", "跳过"),
                        ],
                        default="UNCOMMIT",
                        max_length=128,
                    ),
                ),
                ("check_id", models.IntegerField(help_text="关联check_id")),
                ("cluster_id", models.IntegerField(help_text="关联集群id")),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("spider", "spider"),
                            ("remote", "remote"),
                            ("proxy", "proxy"),
                            ("backend", "backend"),
                            ("single", "single"),
                            ("predixy", "predixy"),
                            ("twemproxy", "twemproxy"),
                            ("redis", "redis"),
                            ("tendiscache", "tendiscache"),
                            ("tendisssd", "tendisssd"),
                            ("tendisplus", "tendisplus"),
                            ("es_datanode", "es_datanode"),
                            ("es_master", "es_master"),
                            ("es_client", "es_client"),
                            ("broker", "broker"),
                            ("zookeeper", "zookeeper"),
                            ("hdfs_master", "hdfs_master"),
                            ("hdfs_datanode", "hdfs_datanode"),
                            ("mongos", "mongos"),
                            ("mongodb", "mongodb"),
                            ("mongo_config", "mongo_config"),
                            ("influxdb", "influxdb"),
                            ("pulsar_zookeeper", "pulsar_zookeeper"),
                            ("pulsar_bookkeeper", "pulsar_bookkeeper"),
                            ("pulsar_broker", "pulsar_broker"),
                            ("riak", "riak"),
                            ("doris_backend", "doris_backend"),
                            ("doris_follower", "doris_follower"),
                            ("doris_observer", "doris_observer"),
                            ("sqlserver_single", "sqlserver_single"),
                            ("sqlserver_ha", "sqlserver_ha"),
                            ("vmstorage", "vmstorage"),
                            ("vminsert", "vminsert"),
                            ("vmselect", "vmselect"),
                            ("vmauth", "vmauth"),
                            ("tbinlogdumper", "TBinlogDumper"),
                            ("oracle", "oracle"),
                        ],
                        help_text="机器类型",
                        max_length=64,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "优先级一"), (2, "优先级二")],
                        default=backend.db_monitor.models.mysql_dbha_autofix_event.MySQLDBHAAutofixTicketPriority[
                            "P1"
                        ],
                        help_text="单据优先级",
                    ),
                ),
                ("ticket_param", models.JSONField(default=dict, help_text="单据参数")),
                ("af_uuid", models.CharField(help_text="关联自愈调度uuid", max_length=256)),
                ("queue_uuid", models.CharField(help_text="单据队列uuid", max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="MySQLDBHAEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(default=0)),
                ("bk_biz_id", models.IntegerField(default=0)),
                ("check_id", models.BigIntegerField(default=0)),
                ("cluster_id", models.BigIntegerField(default=0)),
                ("immute_domain", models.CharField(default="", max_length=255)),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=MachineType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "instance_role",
                    models.CharField(
                        choices=InstanceRole.get_choices(),
                        default="",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("ip", models.GenericIPAddressField(default="")),
                ("port", models.IntegerField(default=0)),
                ("new_master_host", models.GenericIPAddressField(default="", null=True)),
                ("new_master_port", models.IntegerField(default=0, null=True)),
                ("new_master_log_file", models.CharField(default="", max_length=255, null=True)),
                ("new_master_log_pos", models.IntegerField(default=0, null=True)),
                ("event_create_time", models.DateTimeField()),
                ("validated", models.BooleanField(blank=True, default=True, help_text="校验状态", null=True)),
                ("validate_memo", models.TextField(help_text="校验失败的说明")),
                ("af_uuid", models.CharField(default="", help_text="自愈task的唯一id", max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name="MySQLDBHAAutofixTodo",
        ),
        migrations.AddIndex(
            model_name="mysqldbhaevent",
            index=models.Index(fields=["af_uuid", "event_create_time"], name="db_monitor__af_uuid_484f3d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mysqldbhaevent",
            unique_together={("check_id", "ip", "port")},
        ),
        migrations.AddIndex(
            model_name="mysqldbhaautofixticketstagequeue",
            index=models.Index(fields=["status", "cluster_id"], name="db_monitor__status_87c47d_idx"),
        ),
    ]
