# Generated by Django 3.2.25 on 2025-10-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0029_auto_20251009_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="priority_group_key",
            field=models.CharField(default="", max_length=128, verbose_name="策略分组ID"),
        ),
    ]
