# Generated by Django 4.2.23 on 2025-11-06 01:15

from django.db import migrations, models

import backend.db_monitor.models.mysql_dbha_autofix_event


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0030_monitorpolicy_priority_group_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqldbhaautofixticketstagequeue",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "优先级一"), (2, "优先级二"), (3, "优先级三")],
                default=backend.db_monitor.models.mysql_dbha_autofix_event.MySQLDBHAAutofixTicketPriority["P1"],
                help_text="单据优先级",
            ),
        ),
        migrations.AlterField(
            model_name="mysqldbhaautofixticketstagequeue",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "等待中"),
                    ("APPROVE", "待审批"),
                    ("RESOURCE_REPLENISH", "待补货"),
                    ("TODO", "待执行"),
                    ("TIMER", "定时中"),
                    ("RUNNING", "执行中"),
                    ("SUCCEEDED", "已完成"),
                    ("FAILED", "已失败"),
                    ("REVOKED", "已撤销"),
                    ("TERMINATED", "已终止"),
                    ("INNER_TODO", "待继续"),
                ],
                default="UNCOMMIT",
                max_length=128,
            ),
        ),
    ]
