# Generated by Django 4.2.23 on 2025-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0031_alter_mysqldbhaautofixticketstagequeue_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqldbhaevent",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("tendbsingle", "MySQL单节点集群"),
                    ("tendbha", "MySQL高可用集群"),
                    ("tendbcluster", "TendbCluster集群"),
                    ("tbinlogdumper", "TBinlogDumper"),
                    ("redis", "Redis"),
                    ("PredixyRedisCluster", "RedisCluster集群"),
                    ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                    ("TwemproxyRedisInstance", "TendisCache集群"),
                    ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                    ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                    ("RedisInstance", "RedisCache主从版"),
                    ("TendisSSDInstance", "TendisSSD主从版"),
                    ("TendisplusInstance", "Tendisplus主从版"),
                    ("RedisCluster", "RedisCluster集群"),
                    ("TendisplusCluster", "TendisplusCluster集群"),
                    ("TendisplusInstance", "Tendisplus存储版集群"),
                    ("RedisInstance", "TendisCache集群"),
                    ("TendisSSDInstance", "TendisSSD集群"),
                    ("es", "ES集群"),
                    ("kafka", "Kafka集群"),
                    ("hdfs", "Hdfs集群"),
                    ("influxdb", "Influxdb实例"),
                    ("pulsar", "Pulsar集群"),
                    ("doris", "Doris集群"),
                    ("vm", "vm集群"),
                    ("dbmon", "redis监控"),
                    ("MongoReplicaSet", "Mongo副本集"),
                    ("MongoShardedCluster", "Mongo分片集群"),
                    ("riak", "Riak集群"),
                    ("sqlserver_single", "sqlserver单节点版"),
                    ("sqlserver_ha", "sqlserver主从版"),
                    ("oracle_primary_standby", "oracle主从版"),
                    ("oracle_single_none", "oracle单节点版"),
                    ("k8s_surreal", "k8s surrealdb集群"),
                    ("k8s_vm", "k8s Victoria metrics集群"),
                    ("k8s_rw", "k8s Risingwave集群"),
                    ("k8s_mv", "k8s Milvus集群"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
