# Generated by Django 4.2.27 on 2026-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0032_monitorpolicy_detects_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="agg_info",
            field=models.JSONField(default=list, verbose_name="汇聚方式和周期配置"),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="expression",
            field=models.CharField(default="", max_length=128, verbose_name="多指标表达式"),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="notify_config",
            field=models.JSONField(default=dict, verbose_name="通知间隔"),
        ),
        migrations.AddField(
            model_name="monitorpolicy",
            name="policy_type",
            field=models.CharField(
                choices=[("single", "单指标"), ("multi", "多指标"), ("PromQL", "PromQL")],
                default="",
                max_length=64,
                verbose_name="策略类型",
            ),
        ),
    ]
