# Generated by Django 4.2.27 on 2026-03-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0033_monitorpolicy_agg_info_monitorpolicy_expression_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorpolicy",
            name="expression",
        ),
        migrations.RemoveField(
            model_name="monitorpolicy",
            name="policy_type",
        ),
    ]
