# Generated by Django 4.2.27 on 2026-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0034_remove_monitorpolicy_expression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="policy_tag",
            field=models.CharField(
                choices=[("inner", "内置"), ("custom", "自定义"), ("subord", "子策略")],
                default="",
                max_length=64,
                verbose_name="策略类型",
            ),
        ),
    ]
