# Generated by Django 4.2.27 on 2026-05-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0035_monitorpolicy_policy_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqldbhaautofixticketstagequeue",
            name="error_message",
            field=models.TextField(blank=True, default="", help_text="提单失败的错误信息"),
        ),
    ]
