# Generated by Django 4.2.27 on 2026-06-01 17:36

from django.db import migrations


def add_user_channel_to_notice_groups(apps, schema_editor):
    NoticeGroup = apps.get_model("db_monitor", "NoticeGroup")
    notice_group_list = []
    for notice in NoticeGroup.objects.all():
        try:
            old_details = notice.details
            old_details["channels"] = ["user"]
            notice.details = old_details
            notice_group_list.append(notice)
        except Exception:
            pass
    # 分批更新，设100一次
    NoticeGroup.objects.bulk_update(notice_group_list, fields=["details"], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("db_monitor", "0036_mysqldbhaautofixticketstagequeue_error_message"),
    ]

    operations = [
        migrations.RunPython(add_user_channel_to_notice_groups),
    ]
