# Generated by Django 4.2.30 on 2026-09-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0038_alter_mysqldbhaautofixticketstagequeue_check_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="policy_code",
            field=models.CharField(
                choices=[("actual_cpu_usage", "实际CPU使用率")], default="", max_length=128, verbose_name="策略代号"
            ),
        ),
        migrations.AlterField(
            model_name="mysqldbhaautofixticketstagequeue",
            name="machine_type",
            field=models.CharField(
                choices=[
                    ("spider", "spider"),
                    ("remote", "remote"),
                    ("proxy", "proxy"),
                    ("backend", "backend"),
                    ("single", "single"),
                    ("mysql_dts_master", "mysql_dts_master"),
                    ("mysql_dts_worker", "mysql_dts_worker"),
                    ("mysql_dts_colocated", "mysql_dts_colocated"),
                    ("predixy", "predixy"),
                    ("twemproxy", "twemproxy"),
                    ("redis", "redis"),
                    ("tendiscache", "tendiscache"),
                    ("tendisssd", "tendisssd"),
                    ("tendisplus", "tendisplus"),
                    ("es_datanode", "es_datanode"),
                    ("es_master", "es_master"),
                    ("es_client", "es_client"),
                    ("broker", "broker"),
                    ("zookeeper", "zookeeper"),
                    ("hdfs_master", "hdfs_master"),
                    ("hdfs_datanode", "hdfs_datanode"),
                    ("mongos", "mongos"),
                    ("mongodb", "mongodb"),
                    ("mongo_config", "mongo_config"),
                    ("influxdb", "influxdb"),
                    ("pulsar_zookeeper", "pulsar_zookeeper"),
                    ("pulsar_bookkeeper", "pulsar_bookkeeper"),
                    ("pulsar_broker", "pulsar_broker"),
                    ("riak", "riak"),
                    ("doris_backend", "doris_backend"),
                    ("doris_follower", "doris_follower"),
                    ("doris_observer", "doris_observer"),
                    ("sqlserver_single", "sqlserver_single"),
                    ("sqlserver_ha", "sqlserver_ha"),
                    ("vmstorage", "vmstorage"),
                    ("vminsert", "vminsert"),
                    ("vmselect", "vmselect"),
                    ("vmauth", "vmauth"),
                    ("tbinlogdumper", "TBinlogDumper"),
                    ("oracle", "oracle"),
                ],
                help_text="机器类型",
                max_length=64,
            ),
        ),
    ]
