# Generated by Django 4.2.30 on 2026-09-04 08:36

from django.db import migrations, models

from backend.db_meta.enums import MachineType
from backend.db_monitor.constants import PolicyGlobalCode


class Migration(migrations.Migration):

    dependencies = [
        ("db_monitor", "0038_alter_mysqldbhaautofixticketstagequeue_check_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorpolicy",
            name="policy_code",
            field=models.CharField(
                choices=PolicyGlobalCode.get_choices(), default="", max_length=128, verbose_name="策略代号"
            ),
        ),
        migrations.AlterField(
            model_name="mysqldbhaautofixticketstagequeue",
            name="machine_type",
            field=models.CharField(
                choices=MachineType.get_choices(),
                help_text="机器类型",
                max_length=64,
            ),
        ),
    ]
