{{- if eq .Values.topoName "cluster" }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kb-{{ .Release.Name }}-opsrequest-creator
rules:
  - apiGroups: ["apps.kubeblocks.io"]
    resources: ["opsrequests"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kb-{{ .Release.Name }}-opsrequest-creator
subjects:
  - kind: ServiceAccount
    name: kb-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kb-{{ .Release.Name }}-opsrequest-creator
  apiGroup: rbac.authorization.k8s.io

{{- end }}