# Generated by Django 3.2.19 on 2023-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flow",
            index=models.Index(fields=["err_code"], name="ticket_flow_err_cod_219590_idx"),
        ),
    ]
