# Generated by Django 3.2.19 on 2023-12-01 12:32

from django.db import migrations, models

from backend.configuration.constants import DBType
from backend.ticket.constants import TicketType


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_flow_ticket_flow_err_cod_219590_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketFlowConfig",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "ticket_type",
                    models.CharField(
                        choices=TicketType.get_choices(),
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="单据类型",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=DBType.get_choices(),
                        max_length=64,
                        verbose_name="单据分组类型",
                    ),
                ),
                ("editable", models.BooleanField(verbose_name="是否支持用户配置")),
                (
                    "configs",
                    models.JSONField(
                        default=dict, verbose_name="单据配置 eg: {'need_itsm': false, 'need_manual_confirm': false}"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ticketflowconfig",
            index=models.Index(fields=["group"], name="ticket_tick_group_cdbc04_idx"),
        ),
    ]
