# Generated by Django 3.2.19 on 2024-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_auto_20231201_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instanceoperaterecord",
            name="instance_id",
            field=models.CharField(max_length=128, verbose_name="实例ID"),
        ),
    ]
