# Generated by Django 3.2.19 on 2024-05-14 13:28

from django.db import migrations, models

from backend.configuration.constants import DBType
from backend.ticket.constants import TicketType


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_ticket_send_msg_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketFlowsConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="业务ID")),
                (
                    "ticket_type",
                    models.CharField(
                        choices=TicketType.get_choices(),
                        max_length=128,
                        verbose_name="单据类型",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=DBType.get_choices(),
                        max_length=64,
                        verbose_name="单据分组类型",
                    ),
                ),
                ("editable", models.BooleanField(verbose_name="是否支持用户配置")),
                (
                    "configs",
                    models.JSONField(
                        default=dict, verbose_name="单据配置 eg: {'need_itsm': false, 'need_manual_confirm': false}"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TicketFlowConfig",
        ),
        migrations.AddIndex(
            model_name="ticketflowsconfig",
            index=models.Index(fields=["group"], name="ticket_tick_group_f763ef_idx"),
        ),
    ]
