# Generated by Django 3.2.19 on 2024-01-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_alter_instanceoperaterecord_instance_id"),
        ("ticket", "0004_ticket_send_msg_config"),
    ]

    operations = []
