# Generated by Django 3.2.19 on 2024-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_merge_20240126_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="flow_obj_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name="单据流程对象ID"),
        ),
    ]
