# Generated by Django 3.2.25 on 2024-05-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_auto_20240514_2128"),
        ("ticket", "0006_alter_flow_flow_obj_id"),
    ]

    operations = []
