# Generated by Django 3.2.25 on 2024-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0009_auto_20240621_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="context",
            field=models.JSONField(default=dict, verbose_name="流程上下文(用于扩展字段)"),
        ),
    ]
