# Generated by Django 3.2.25 on 2024-09-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0011_auto_20240821_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="remark",
            field=models.CharField(max_length=512, verbose_name="备注"),
        ),
    ]
