# Generated by Django 3.2.25 on 2025-03-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0013_todo_helpers"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteroperaterecord",
            name="is_pause",
            field=models.BooleanField(default=False, help_text="代表记录是否处于暂停待执行的节点中"),
        ),
        migrations.AddField(
            model_name="clusteroperaterecord",
            name="unlock_ticket_type_condition",
            field=models.JSONField(
                default=list, help_text="流程运行中解锁的单据类型，默认空list，运行中保持互斥条件，如果使用'*', 表示全解锁，每个元素应该是平台定义好的ticket_type"
            ),
        ),
    ]
