# Generated by Django 3.2.25 on 2025-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0014_auto_20250309_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="单据配置"),
        ),
    ]
