# Generated by Django 3.2.25 on 2025-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0015_ticket_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketflowsconfig",
            name="remark",
            field=models.CharField(default=None, max_length=512, null=True, verbose_name="备注"),
        ),
    ]
