# Generated by Django 3.2.25 on 2025-07-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0016_ticketflowsconfig_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.JSONField(blank=True, default=list, null=True, verbose_name="流程摘要")),
                ("flow", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="ticket.flow")),
            ],
        ),
    ]
