# Generated by Django 3.2.25 on 2025-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0017_flowsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketflowsconfig",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
    ]
