# Generated by Django 3.2.25 on 2026-01-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0017_flowsummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="flow",
            field=models.ForeignKey(
                help_text="关联流程任务",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_of_flow",
                to="ticket.flow",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="ticket",
            field=models.ForeignKey(
                help_text="关联工单",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_of_ticket",
                to="ticket.ticket",
            ),
        ),
    ]
