# Generated by Codex on 2026-07-13

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def forwards(apps, schema_editor):
    # 将存量 cluster_ids 从集群 ID 列表迁移为包含 immute_domain 的字典列表。
    try:
        TicketFlowsConfig = apps.get_model("ticket", "TicketFlowsConfig")
        Cluster = apps.get_model("db_meta", "Cluster")

        configs = list(TicketFlowsConfig.objects.exclude(cluster_ids=[]).only("id", "cluster_ids"))
        cluster_id_set = set()
        for config in configs:
            for cluster in config.cluster_ids or []:
                if isinstance(cluster, dict):
                    cluster_id = cluster.get("id")
                else:
                    cluster_id = cluster
                if cluster_id is not None:
                    cluster_id_set.add(cluster_id)

        cluster_map = Cluster.objects.in_bulk(cluster_id_set)
        updated_configs = []
        for config in configs:
            new_cluster_ids = []
            changed = False

            for cluster in config.cluster_ids or []:
                if isinstance(cluster, dict):
                    cluster_id = cluster.get("id")
                    immute_domain = cluster.get("immute_domain")
                    if cluster_id is not None and immute_domain is not None:
                        new_cluster_ids.append({"id": cluster_id, "immute_domain": immute_domain})
                        continue
                    changed = True
                else:
                    cluster_id = cluster
                    changed = True

                cluster_obj = cluster_map.get(cluster_id)
                new_cluster_ids.append(
                    {
                        "id": cluster_id,
                        "immute_domain": cluster_obj.immute_domain if cluster_obj else "",
                    }
                )

            if changed:
                config.cluster_ids = new_cluster_ids
                updated_configs.append(config)

        if updated_configs:
            TicketFlowsConfig.objects.bulk_update(updated_configs, ["cluster_ids"])
    except Exception:
        logger.exception("Failed to migrate TicketFlowsConfig cluster_ids.")


def backwards(apps, schema_editor):
    # 回滚时将 cluster_ids 从字典列表还原为集群 ID 列表。
    try:
        TicketFlowsConfig = apps.get_model("ticket", "TicketFlowsConfig")

        configs = list(TicketFlowsConfig.objects.exclude(cluster_ids=[]).only("id", "cluster_ids"))
        updated_configs = []
        for config in configs:
            old_cluster_ids = []
            changed = False

            for cluster in config.cluster_ids or []:
                if isinstance(cluster, dict):
                    cluster_id = cluster.get("id") or cluster.get("cluster_id")
                    changed = True
                else:
                    cluster_id = cluster

                if cluster_id is not None:
                    old_cluster_ids.append(cluster_id)

            if changed:
                config.cluster_ids = old_cluster_ids
                updated_configs.append(config)

        if updated_configs:
            TicketFlowsConfig.objects.bulk_update(updated_configs, ["cluster_ids"])
    except Exception:
        logger.exception("Failed to rollback TicketFlowsConfig cluster_ids.")


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0065_appoperate_appcache_managed_time_appcache_status_and_more"),
        ("ticket", "0018_auto_20260104_1505"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketflowsconfig",
            name="cluster_tags",
            field=models.JSONField(default=list, verbose_name="集群标签列表"),
        ),
        migrations.RunPython(forwards, backwards),
    ]
