# Generated by Django 3.2.4 on 2023-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                ("version", models.CharField(max_length=64, verbose_name="版本号")),
                (
                    "pkg_type",
                    models.CharField(
                        choices=[
                            ("mysql", "mysql"),
                            ("mysql-proxy", "mysql-proxy"),
                            ("redis", "redis"),
                            ("tendisplus", "tendisplus"),
                            ("tendisssd", "tendisssd"),
                            ("dbbackup", "dbbackup"),
                            ("actuator", "actuator"),
                            ("latest", "最新版本"),
                            ("twemproxy", "twemproxy"),
                            ("predixy", "predixy"),
                            ("tools", "redis_tools"),
                            ("es", "es"),
                            ("kafka", "kafka"),
                            ("hdfs", "hdfs"),
                            ("pulsar", "pulsar"),
                            ("influxdb", "influxdb"),
                            ("dbmon", "dbmon"),
                            ("mysql-checksum", "mysql-checksum"),
                            ("rotate-binlog", "Binlog 滚动备份工具"),
                            ("dba-toolkit", "DBA 工具集"),
                            ("mysql-crond", "mysql-crond"),
                            ("mysql-monitor", "MySQL 监控"),
                            ("cloud-nginx", "nginx 服务"),
                            ("cloud-dns-bind", "dns-bind 服务"),
                            ("cloud-dns-pullcrond", "dns-pull-crond服务"),
                            ("cloud-dbha", "cloud-dbha服务"),
                            ("cloud-drs", "cloud-drs服务"),
                            ("cloud-drs-tmysqlparse", "cloud-drs-tmysqlparse服务"),
                            ("spider", "spider节点名称"),
                            ("tdbctl", "spider中控节点名称"),
                        ],
                        max_length=32,
                        verbose_name="安装包类型",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("redis", "Redis"),
                            ("kafka", "Kafka"),
                            ("hdfs", "HDFS"),
                            ("es", "ElasticSearch"),
                            ("pulsar", "Pulsar"),
                            ("influxdb", "InfluxDB"),
                            ("cloud", "Cloud"),
                        ],
                        default="mysql",
                        max_length=32,
                        verbose_name="存储类型",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="包路径")),
                ("size", models.IntegerField(verbose_name="包大小")),
                ("md5", models.CharField(max_length=32, verbose_name="md5值")),
                ("allow_biz_ids", models.JSONField(null=True, verbose_name="允许的业务列表")),
                (
                    "mode",
                    models.CharField(
                        choices=[("user", "用户定义"), ("system", "系统内置")],
                        default="system",
                        max_length=32,
                        verbose_name="安装包模式",
                    ),
                ),
            ],
            options={
                "verbose_name": "介质包（Package）",
                "ordering": ("-create_at",),
            },
        ),
    ]
