# Generated by Django 3.2.19 on 2023-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_package", "0002_auto_20231101_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="enable",
            field=models.BooleanField(default=True, help_text="是否启用"),
        ),
        migrations.AddField(
            model_name="package",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="文件优先级(目前只用作区分是否为默认版本)"),
        ),
    ]
