# Generated by Django 3.2.19 on 2024-01-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_package", "0003_auto_20231221_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="size",
            field=models.BigIntegerField(verbose_name="包大小"),
        ),
    ]
