# Generated by Django 3.2.25 on 2024-06-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_package", "0004_alter_package_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "ordering": ("-create_at",),
                "verbose_name": "介质包（Package）",
                "verbose_name_plural": "介质包（Package）",
            },
        ),
    ]
