# Generated by Django 3.2.25 on 2025-10-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0057_auto_20251021_1215"),
        ("db_package", "0005_alter_package_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="db_version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="db_meta.dbversion"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="permit_os",
            field=models.JSONField(blank=True, default=list, help_text="os 列表", null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="permit_os_type",
            field=models.CharField(blank=True, default="", help_text="os 类型", max_length=128, null=True),
        ),
    ]
