-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_file_def`
--
-- WHERE:  namespace='hdfs'

INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (78,'hdfs','core-site','2.6.0-cdh5.4.11-tendataV0.2','core-site配置','core-site.xml','plat,app,cluster','cluster',1,1,0,NULL,5,365,0,'core-site配置','2022-09-18 17:08:55','2023-06-30 17:26:25','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (101,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs集群配置','2.6.0-cdh5.4.11','plat,app,cluster','cluster',1,1,0,NULL,5,365,0,'hdfs集群配置','2022-10-18 16:00:03','2023-06-29 10:36:47','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (77,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site配置','hdfs-site.xml','plat,app,cluster','cluster',1,1,0,NULL,5,365,0,'hdfs-site配置','2022-09-18 17:08:55','2023-06-30 17:26:19','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (76,'hdfs','hdfsconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs配置','hdfs config','plat,app,cluster','cluster',1,1,0,NULL,5,365,0,'hdfs配置','2022-09-18 16:53:04','2023-06-30 17:26:37','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (83,'hdfs','install','2.6.0-cdh5.4.11-tendataV0.2','hdfs安装配置','2.6.0-cdh5.4.11','plat,app,cluster','cluster',1,1,0,NULL,5,365,0,'hdfs安装配置','2022-09-19 17:02:17','2023-06-29 10:37:49','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (79,'hdfs','zoo.cfg','2.6.0-cdh5.4.11-tendataV0.2','zk配置','zoo.cfg','plat,app,cluster','cluster',1,1,0,NULL,5,365,0,'zk配置','2022-09-18 17:08:55','2023-06-30 17:26:47','');
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_name_def`
--
-- WHERE:  namespace='hdfs' AND (flag_encrypt!=1 or value_default like '{{%')

INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8878,'hdfs','core-site','2.6.0-cdh5.4.11-tendataV0.2','fs.defaultFS','STRING','hdfs://{{cluster_name}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2023-04-17 17:11:39',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8877,'hdfs','core-site','2.6.0-cdh5.4.11-tendataV0.2','fs.trash.interval','STRING','1440','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8876,'hdfs','core-site','2.6.0-cdh5.4.11-tendataV0.2','io.file.buffer.size','STRING','131072','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8875,'hdfs','core-site','2.6.0-cdh5.4.11-tendataV0.2','net.topology.script.file.name','STRING','/data/hadoopenv/hadoop/etc/hadoop/rack-aware.sh','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12407,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','core-site.fs.defaultFS','STRING','hdfs://{{cluster_name}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2023-04-17 17:11:39',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12408,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','core-site.fs.trash.interval','INT','1440','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2022-11-18 11:23:15',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12409,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','core-site.io.file.buffer.size','INT','131072','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 00:04:42','2022-11-18 11:23:15',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12410,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','core-site.net.topology.script.file.name','STRING','/data/hadoopenv/hadoop/etc/hadoop/rack-aware.sh','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,'域名解析脚本','2022-09-19 00:04:42','2022-11-18 11:38:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12373,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.blockreport.intervalMsec','INT','43200000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,'块上报间隔时间毫秒','2022-09-21 14:33:49','2022-11-18 11:34:08',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12374,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.blocksize','INT','134217728','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,'块大小','2022-09-21 14:33:49','2022-11-18 11:34:08',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12375,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.client.failover.proxy.provider.{{cluster_name}}','STRING','org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12376,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.datanode.data.dir','STRING','file:///data/hadoopdata/data','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12377,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.datanode.fsdataset.volume.choosing.policy','STRING','org.apache.hadoop.hdfs.server.datanode.fsdataset.AvailableSpaceVolumeChoosingPolicy','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12378,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.datanode.hostname','STRING','{{dn_host}}',NULL,'',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-23 15:02:59','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12379,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.datanode.http.address','STRING','0.0.0.0:50075','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12380,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.ha.automatic-failover.enabled','STRING','true','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12381,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.ha.fencing.methods','STRING','shell(/bin/true)','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12382,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.ha.namenodes.{{cluster_name}}','STRING','nn1,nn2','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12383,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.hosts','STRING','/data/hadoopenv/hadoop/etc/hadoop/dfs.include','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12384,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.hosts.exclude','STRING','/data/hadoopenv/hadoop/etc/hadoop/dfs.exclude','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12385,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.journalnode.edits.dir','STRING','/data/hadoopdata/jn','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12386,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.checkpoint.period','INT','3600','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12387,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.checkpoint.txns','INT','2000000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12388,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.handler.count','INT','128','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12389,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.heartbeat.recheck-interval','INT','300000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12390,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.http-address.{{cluster_name}}.nn1','STRING','{{nn1_host}}:{{http_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12391,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.http-address.{{cluster_name}}.nn2','STRING','{{nn2_host}}:{{http_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12392,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.name.dir','STRING','file:///data/hadoopdata/name','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12393,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.replication.max-streams','INT','20','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12394,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.replication.max-streams-hard-limit','INT','40','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12395,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.replication.work.multiplier.per.iteration','INT','10','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12396,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.rpc-address.{{cluster_name}}.nn1','STRING','{{nn1_host}}:{{rpc_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12397,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.rpc-address.{{cluster_name}}.nn2','STRING','{{nn2_host}}:{{rpc_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12398,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.service.handler.count','INT','64','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12399,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.servicerpc-address.{{cluster_name}}.nn1','STRING','{{nn1_host}}:53310','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12400,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.servicerpc-address.{{cluster_name}}.nn2','STRING','{{nn2_host}}:53310','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12401,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.namenode.shared.edits.dir','STRING','qjournal://{{jn0_host}}:8485;{{jn1_host}}:8485;{{jn2_host}}:8485;/{{cluster_name}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:21:08','2023-04-17 17:11:39',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12402,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.nameservices','STRING','{{cluster_name}}',NULL,'',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-18 17:02:55','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12403,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.dfs.replication','INT','2','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:14',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12404,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.ha.failover-controller.cli-check.rpc-timeout.ms','INT','60000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-11-18 11:23:15',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12405,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.ha.zookeeper.quorum','STRING','{{zk0_ip}}:2181,{{zk1_ip}}:2181,{{zk2_ip}}:2181','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12406,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','hdfs-site.ha.zookeeper.session-timeout.ms','INT','5000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:21:08','2022-11-18 11:23:15',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12367,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','http_port','INT','50070',NULL,'',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,'NN WEB端口','2022-10-10 10:51:06','2022-11-18 11:32:57',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8918,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','install.haproxy_rpm','STRING','libslz-1.1.0-2.el7.x86_64.rpm,haproxy-1.8.12-1.el7.x86_64.rpm,libslz-1.1.0-2.el6.x86_64.rpm,haproxy-1.8.12-1.el6.x86_64.rpm',NULL,'',1,0,0,0,1,'NULL',NULL,NULL,-1,NULL,'安装HaProxy RPM配置','2022-09-23 15:12:46','2022-11-18 11:32:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12362,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','nn1_host','STRING','{{nn1_host}}','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,'NN1主机名','2022-10-08 12:53:23','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12365,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','nn1_ip','STRING','{{nn1_ip}}',NULL,'',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,'NN1 IP','2022-10-08 14:40:29','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12363,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','nn2_host','STRING','{{nn2_host}}','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,'NN2主机名','2022-10-08 12:56:52','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12364,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','nn2_ip','STRING','{{nn2_ip}}',NULL,'',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,'NN2 IP','2022-10-08 14:40:29','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12368,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','rpc_port','INT','9000',NULL,'',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,'NN RPC端口','2022-10-10 10:51:06','2022-11-18 11:32:57',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (13047,'hdfs','dbconf','2.6.0-cdh5.4.11-tendataV0.2','username','STRING','haproxy_user',NULL,'',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,'haproxy用户名','2022-12-01 18:56:55','2022-12-01 18:56:55',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8911,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.blockreport.intervalMsec','STRING','43200000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8901,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.blocksize','STRING','134217728','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8915,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.client.failover.proxy.provider.{{cluster_name}}','STRING','org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8910,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.datanode.data.dir','STRING','file:///data/hadoopdata/data','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8909,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.datanode.fsdataset.volume.choosing.policy','STRING','org.apache.hadoop.hdfs.server.datanode.fsdataset.AvailableSpaceVolumeChoosingPolicy','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8917,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.datanode.hostname','STRING','{{dn_host}}',NULL,'',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-23 15:02:59','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8908,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.datanode.http.address','STRING','0.0.0.0:50075','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8913,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.ha.automatic-failover.enabled','STRING','true','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8912,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.ha.fencing.methods','STRING','shell(/bin/true)','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8879,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.ha.namenodes.{{cluster_name}}','STRING','nn1,nn2','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8897,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.hosts','STRING','/data/hadoopenv/hadoop/etc/hadoop/dfs.include','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8898,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.hosts.exclude','STRING','/data/hadoopenv/hadoop/etc/hadoop/dfs.exclude','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8914,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.journalnode.edits.dir','STRING','/data/hadoopdata/jn','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8899,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.checkpoint.period','STRING','3600','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8900,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.checkpoint.txns','STRING','2000000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8907,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.handler.count','STRING','128','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8896,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.heartbeat.recheck-interval','STRING','300000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8882,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.http-address.{{cluster_name}}.nn1','STRING','{{nn1_host}}:{{http_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8883,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.http-address.{{cluster_name}}.nn2','STRING','{{nn2_host}}:{{http_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8905,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.name.dir','STRING','file:///data/hadoopdata/name','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8902,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.replication.max-streams','STRING','20','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8903,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.replication.max-streams-hard-limit','STRING','40','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8904,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.replication.work.multiplier.per.iteration','STRING','10','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8880,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.rpc-address.{{cluster_name}}.nn1','STRING','{{nn1_host}}:{{rpc_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8881,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.rpc-address.{{cluster_name}}.nn2','STRING','{{nn2_host}}:{{rpc_port}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8906,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.service.handler.count','STRING','64','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8884,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.servicerpc-address.{{cluster_name}}.nn1','STRING','{{nn1_host}}:53310','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8885,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.servicerpc-address.{{cluster_name}}.nn2','STRING','{{nn2_host}}:53310','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8893,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.namenode.shared.edits.dir','STRING','qjournal://{{jn0_host}}:8485;{{jn1_host}}:8485;{{jn2_host}}:8485;/{{cluster_name}}','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:21:08','2023-04-17 17:11:39',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8874,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.nameservices','STRING','{{cluster_name}}',NULL,'',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-18 17:02:55','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8895,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','dfs.replication','STRING','2','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8916,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','ha.failover-controller.cli-check.rpc-timeout.ms','STRING','60000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:33:49','2022-10-20 11:24:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8886,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','ha.zookeeper.quorum','STRING','{{zk0_ip}}:2181,{{zk1_ip}}:2181,{{zk2_ip}}:2181','NULL','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-19 01:26:50','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (8894,'hdfs','hdfs-site','2.6.0-cdh5.4.11-tendataV0.2','ha.zookeeper.session-timeout.ms','STRING','5000','NULL','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-21 14:21:08','2022-10-20 11:24:09',0);
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

