-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_file_def`
--
-- WHERE:  namespace='TwemproxyTendisplusInstance'

INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (87,'TwemproxyTendisplusInstance','config','backup','备份相关的配置','backup','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'备份相关的配置','2022-09-27 17:48:51','2023-06-30 17:27:33','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (88,'TwemproxyTendisplusInstance','config','monitor','监控相关的配置','monitor','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'监控相关的配置','2022-09-27 17:49:02','2023-06-30 17:27:28','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (85,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','redis配置','Tendisplus-2.5','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'Tendisplus-2.5的配置文件','2022-09-27 17:48:42','2023-06-29 10:33:39','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (86,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','redis配置','Twemproxy-latest','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'twemproxy配置文件','2022-09-27 17:48:46','2023-06-29 10:37:01','');
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_name_def`
--
-- WHERE:  namespace='TwemproxyTendisplusInstance' AND (flag_encrypt!=1 or value_default like '{{%')

INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12061,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','bind','STRING','{{address}}','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12082,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','binlog-using-defaultCF','STRING','off','on|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12098,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','binlogdelrange','INT','500000','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12072,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','cluster-enabled','STRING','{{cluster_enabled}}','no|yes','ENUM',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12086,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','cluster-migration-rate-limit','INT','200','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12069,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','databases','INT','2','[2,16]','',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-12-08 10:32:28',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12100,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','deletefilesinrange-for-binlog','INT','1','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12065,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','dir','STRING','{{redis_data_dir}}/data/db','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12093,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','domain-enabled','STRING','off','on|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12066,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','dumpdir','STRING','{{redis_data_dir}}/data/dump','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12074,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','executorThreadNum','INT','24','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12073,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','executorWorkPoolSize','INT','2','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12101,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','incrpushthreadnum','INT','10','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12078,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','kvstorecount','INT','10','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12064,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','logdir','STRING','{{redis_data_dir}}/data/log','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12063,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','loglevel','STRING','notice','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12071,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','masterauth','STRING','{{password}}','','',2,0,0,1,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12083,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','maxBinlogKeepNum','INT','1','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12099,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','migrate-gc-enabled','STRING','false','false | true','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:20:50',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12089,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','migrate-snapshot-key-num','INT','30000','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12087,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','migrateReceiveThreadnum','INT','4','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12088,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','migrateSenderThreadnum','INT','4','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12097,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','minbinlogkeepsec','INT','1800','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12084,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','netBatchSize','INT','1048576','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12085,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','netBatchTimeoutSec','INT','10','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12075,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','netIoThreadNum','INT','3','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12076,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','noexpire','STRING','no','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12094,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','pauseTimeIndexMgr','INT','1','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12067,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','pidfile','STRING','{{redis_data_dir}}data/tendisplus.pid','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12062,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','port','INT','{{port}}','[6379,55535]','RANGE',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12102,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','rename-command','STRING','config confxx \nrename-command flushdb cleandb \nrename-command flushall cleanall\nrename-command debug nobug\nrename-command keys mykeys','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12070,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','requirepass','STRING','{{password}}','','',2,0,0,1,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12077,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','rocks.blockcachemb','STRING','{{rocks_blockcachemb}}','','',2,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12091,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','rocks.cache_index_and_filter_blocks','INT','0','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12079,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','rocks.compress_type','STRING','lz4','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12080,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','rocks.max_background_compactions','INT','12','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12081,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','rocks.write_buffer_size','INT','{{rocks_write_buffer_size}}','','',2,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12095,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','scanCntIndexMgr','INT','10000','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12090,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','slave-migrate-enabled','STRING','on','\non|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12068,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','slowlog','STRING','{{redis_data_dir}}/data/slowlog','','',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12096,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','truncateBinlogIntervalMs','INT','100','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12092,'TwemproxyTendisplusInstance','dbconf','Tendisplus-2.5','truncateBinlogNum','INT','10000000','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12108,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','auto_eject_hosts','STRING','false','true|false','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12104,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','backlog','INT','512','nullNULL','nullNULL',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12106,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','distribution','STRING','modhash','modhash','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12107,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','hash','STRING','fnv1a_64','fnv1a_64','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12113,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','mbuf-size','INT','1024','[128,102400]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12116,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','password','STRING','{{password}}','','',2,0,0,1,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12115,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','port','INT','{{port}}','[50000,59999]','RANGE',2,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12109,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','preconnect','STRING','false','true|false','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12105,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','redis','STRING','true','true','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12114,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','redis_password','STRING','{{redis_password}}','','',2,0,0,1,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2023-04-17 17:10:41',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12111,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','server_connections','INT','1','[1,10]','RANGE',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12112,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','server_failure_limit','INT','3','[1,10]','RANGE',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12110,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','server_retry_timeout','INT','2000','[1000,10000]','RANGE',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12103,'TwemproxyTendisplusInstance','proxyconf','Twemproxy-latest','slowms','INT','1000000','[0,10000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2022-09-27 17:50:24','2022-09-27 17:50:24',0);
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

