-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_file_def`
--
-- WHERE:  namespace='PredixyTendisplusCluster'

INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (99,'PredixyTendisplusCluster','config','backup','备份相关的配置','backup','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'备份相关的配置','2022-09-28 12:08:17','2023-06-30 17:28:27','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (121,'PredixyTendisplusCluster','config','binlogbackup','binlog备份相关的配置','binlogbackup','pub,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'binlog备份相关的配置','2022-11-23 19:54:59','2023-06-30 17:29:56','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (120,'PredixyTendisplusCluster','config','fullbackup','全备相关的配置','fullbackup','pub,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'全备相关的配置','2022-11-23 19:54:59','2023-06-30 17:29:33','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (122,'PredixyTendisplusCluster','config','heartbeat','心跳相关的配置','heartbeat','pub,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'心跳相关的配置','2022-11-23 19:54:59','2023-06-30 17:29:29','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (100,'PredixyTendisplusCluster','config','monitor','监控相关的配置','monitor','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'监控相关的配置','2022-09-28 12:08:17','2023-06-30 17:28:33','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (97,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','redis配置','Tendisplus-2.5','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'Tendisplus-2.5的配置文件','2022-09-28 12:08:17','2023-06-29 10:33:33','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (202,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','redis配置','Tendisplus-2.6','pub,plat,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,NULL,'2023-03-30 19:17:40','2023-06-29 10:35:33','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (98,'PredixyTendisplusCluster','proxyconf','Predixy-latest','redis配置','Predixy-latest','plat,app,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'predixy配置文件','2022-09-28 12:08:17','2023-06-29 10:36:57','');
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_name_def`
--
-- WHERE:  namespace='PredixyTendisplusCluster' AND (flag_encrypt!=1 or value_default like '{{%')

INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12966,'PredixyTendisplusCluster','config','binlogbackup','cron','STRING','@every 10m','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:52','2022-11-23 19:57:52',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12965,'PredixyTendisplusCluster','config','binlogbackup','old_file_left_day','INT','2','[0,365]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:52','2022-11-23 19:57:52',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12964,'PredixyTendisplusCluster','config','binlogbackup','to_backup_system','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:52','2022-11-23 19:57:52',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12961,'PredixyTendisplusCluster','config','fullbackup','cron','STRING','0 5,13,21 * * *','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:42','2022-11-23 19:57:42',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12960,'PredixyTendisplusCluster','config','fullbackup','old_file_left_day','INT','2','[0,365]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:42','2022-11-23 19:57:42',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12962,'PredixyTendisplusCluster','config','fullbackup','tar_split','BOOL','true','true|false','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:42','2022-11-23 19:57:42',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12963,'PredixyTendisplusCluster','config','fullbackup','tar_split_part_size','STRING','8G','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:44','2022-11-23 19:57:44',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12959,'PredixyTendisplusCluster','config','fullbackup','to_backup_system','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:42','2022-11-23 19:57:42',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12967,'PredixyTendisplusCluster','config','heartbeat','cron','STRING','@every 10s','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:52','2022-11-23 19:57:52',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12968,'PredixyTendisplusCluster','config','monitor','bkmonitor_data_id','INT','542898','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:52','2022-11-23 19:57:52',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12969,'PredixyTendisplusCluster','config','monitor','bkmonitor_token','STRING','8108b6fe1c8343ca8d6538652242d439','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:53','2022-11-23 19:57:53',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (12970,'PredixyTendisplusCluster','config','monitor','cron','STRING','@every 1m','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2022-11-23 19:57:55','2022-11-23 19:57:55',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15973,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','bind','STRING','{{address}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15994,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','binlog-using-defaultCF','STRING','off','on|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16010,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','binlogdelrange','INT','500000','[0,10000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15984,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','cluster-enabled','STRING','{{cluster_enabled}}','\non|off','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15998,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','cluster-migration-rate-limit','INT','200','[16,2048]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15981,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','databases','INT','{{databases}}','[1,16]','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16012,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','deletefilesinrange-for-binlog','INT','1','0|1','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15977,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','dir','STRING','{{redis_data_dir}}/data/db','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16005,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','domain-enabled','STRING','off','on|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15978,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','dumpdir','STRING','{{redis_data_dir}}/data/dump','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15986,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','executorThreadNum','INT','24','[8,56]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15985,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','executorWorkPoolSize','INT','2','[2,8]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16013,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','incrpushthreadnum','INT','10','[1,10]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15990,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','kvstorecount','INT','10','10','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15976,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','logdir','STRING','{{redis_data_dir}}/data/log','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16286,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','loglevel','STRING','notice','debug|verbose|notice|warning','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:19:09','2023-04-20 17:19:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15983,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','masterauth','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15995,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','maxBinlogKeepNum','INT','1','[0,50000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16011,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','migrate-gc-enabled','STRING','false','true|false','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16001,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','migrate-snapshot-key-num','INT','30000','[64,200000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15999,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','migrateReceiveThreadnum','INT','4','[1,64]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16000,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','migrateSenderThreadnum','INT','4','[1,64]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16009,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','minbinlogkeepsec','INT','1800','[0,2592000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15996,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','netBatchSize','INT','1048576','[1048576,536870912]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15997,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','netBatchTimeoutSec','INT','10','[2,300]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15987,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','netIoThreadNum','INT','3','[2,12]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15988,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','noexpire','STRING','no','no|yes','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16006,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','pauseTimeIndexMgr','INT','1','[0,300]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15979,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','pidfile','STRING','{{redis_data_dir}}data/tendisplus.pid','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15974,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','port','INT','{{port}}','[6379,55535]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16014,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','rename-command','STRING','config confxx \nrename-command flushdb cleandb \nrename-command flushall cleanall\nrename-command debug nobug\nrename-command keys mykeys','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15982,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','requirepass','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15989,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','rocks.blockcachemb','STRING','{{rocks_blockcachemb}}','[32,262144]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16003,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','rocks.cache_index_and_filter_blocks','INT','0','0|1','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15991,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','rocks.compress_type','STRING','lz4','none|snappy|lz4','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15992,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','rocks.max_background_compactions','INT','12','[2,256]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15993,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','rocks.write_buffer_size','INT','{{rocks_write_buffer_size}}','[4194304,268435456]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16007,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','scanCntIndexMgr','INT','10000','[0,200000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16002,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','slave-migrate-enabled','STRING','on','\non|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (15980,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','slowlog','STRING','{{redis_data_dir}}/data/slowlog','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16008,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','truncateBinlogIntervalMs','INT','100','[1,300000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16004,'PredixyTendisplusCluster','dbconf','Tendisplus-2.5','truncateBinlogNum','INT','10000000','[50000,2000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16015,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','bind','STRING','{{address}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16036,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','binlog-using-defaultCF','STRING','off','on|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16026,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','cluster-enabled','STRING','{{cluster_enabled}}','\non|off','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16040,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','cluster-migration-rate-limit','INT','200','[16,2048]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16023,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','databases','INT','{{databases}}','[1,16]','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16019,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','dir','STRING','{{redis_data_dir}}/data/db','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16047,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','domain-enabled','STRING','off','on|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16020,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','dumpdir','STRING','{{redis_data_dir}}/data/dump','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16028,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','executorThreadNum','INT','24','[8,56]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16027,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','executorWorkPoolSize','INT','2','[2,8]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16052,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','incrpushthreadnum','INT','10','[1,10]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16032,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','kvstorecount','INT','10','10','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16018,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','logdir','STRING','{{redis_data_dir}}/data/log','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16287,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','loglevel','STRING','notice','debug|verbose|notice|warning','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:19:09','2023-04-20 17:19:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16025,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','masterauth','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16037,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','maxBinlogKeepNum','INT','1','[0,50000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16043,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','migrate-snapshot-key-num','INT','30000','[64,200000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16041,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','migrateReceiveThreadnum','INT','4','[1,64]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16042,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','migrateSenderThreadnum','INT','4','[1,64]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16051,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','minbinlogkeepsec','INT','1800','[0,2592000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16038,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','netBatchSize','INT','1048576','[1048576,536870912]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16039,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','netBatchTimeoutSec','INT','10','[2,300]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16029,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','netIoThreadNum','INT','3','[2,12]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16030,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','noexpire','STRING','no','no|yes','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16048,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','pauseTimeIndexMgr','INT','1','[0,300]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16021,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','pidfile','STRING','{{redis_data_dir}}data/tendisplus.pid','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16016,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','port','INT','{{port}}','[6379,55535]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16053,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','rename-command','STRING','config confxx \nrename-command flushdb cleandb \nrename-command flushall cleanall\nrename-command debug nobug\nrename-command keys mykeys','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16024,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','requirepass','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16031,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','rocks.blockcachemb','STRING','{{rocks_blockcachemb}}','[32,262144]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16045,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','rocks.cache_index_and_filter_blocks','INT','0','0|1','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16033,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','rocks.compress_type','STRING','lz4','none|snappy|lz4','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16034,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','rocks.max_background_compactions','INT','12','[2,256]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16035,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','rocks.write_buffer_size','INT','{{rocks_write_buffer_size}}','[4194304,268435456]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16049,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','scanCntIndexMgr','INT','10000','[0,200000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16044,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','slave-migrate-enabled','STRING','on','\non|off','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16022,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','slowlog','STRING','{{redis_data_dir}}/data/slowlog','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16050,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','truncateBinlogIntervalMs','INT','100','[1,300000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16046,'PredixyTendisplusCluster','dbconf','Tendisplus-2.6','truncateBinlogNum','INT','10000000','[50000,2000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16060,'PredixyTendisplusCluster','proxyconf','Predixy-latest','clienttimeout','INT','0','[0,300]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16059,'PredixyTendisplusCluster','proxyconf','Predixy-latest','keepalive','INT','0','[0,300]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16056,'PredixyTendisplusCluster','proxyconf','Predixy-latest','password','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16055,'PredixyTendisplusCluster','proxyconf','Predixy-latest','port','INT','{{port}}','[50000,59999]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16054,'PredixyTendisplusCluster','proxyconf','Predixy-latest','redis_password','STRING','{{redis_password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16061,'PredixyTendisplusCluster','proxyconf','Predixy-latest','refreshinterval','INT','1','[1,30]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16062,'PredixyTendisplusCluster','proxyconf','Predixy-latest','serverfailurelimit','INT','10','[2,60]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16063,'PredixyTendisplusCluster','proxyconf','Predixy-latest','serverretrytimeout','INT','1','[1,60]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16058,'PredixyTendisplusCluster','proxyconf','Predixy-latest','servertimeout','INT','0','[0,300]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16057,'PredixyTendisplusCluster','proxyconf','Predixy-latest','workerthreads','INT','8','[1,64]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:47','2023-04-20 17:03:47',0);
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

