-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_file_def`
--
-- WHERE:  namespace='TwemproxyTendisSSDInstance'

INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (174,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','redis配置','TendisSSD-1.2','plat,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'TendisSSD的配置文件','2023-03-01 10:27:53','2023-06-29 10:35:22','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (175,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','redis配置','TendisSSD-1.3','plat,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'TendisSSD的配置文件','2023-03-01 10:27:53','2023-06-29 10:35:27','');
INSERT INTO `tb_config_file_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_type_lc`, `conf_file_lc`, `level_names`, `level_versioned`, `conf_name_validate`, `conf_value_validate`, `value_type_strict`, `namespace_info`, `version_keep_limit`, `version_keep_days`, `conf_name_order`, `description`, `created_at`, `updated_at`, `updated_by`) VALUES (176,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','redis配置','twemproxy配置文件','plat,app,module,cluster','cluster',1,1,0,'Tendisplus',5,365,0,'twemproxy配置文件','2023-03-01 10:27:53','2023-03-22 12:08:50','');
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- MySQL dump 10.13  Distrib 5.7.20, for Linux (x86_64)
--
-- Host: localhost    Database: bk_dbconfig
-- ------------------------------------------------------
-- Server version	5.7.20-tmysql-3.3-log
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!50717 SELECT COUNT(*) INTO @rocksdb_has_p_s_session_variables FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'performance_schema' AND TABLE_NAME = 'session_variables' */;
/*!50717 SET @rocksdb_get_is_supported = IF (@rocksdb_has_p_s_session_variables, 'SELECT COUNT(*) INTO @rocksdb_is_supported FROM performance_schema.session_variables WHERE VARIABLE_NAME=\'rocksdb_bulk_load\'', 'SELECT 0') */;
/*!50717 PREPARE s FROM @rocksdb_get_is_supported */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;
/*!50717 SET @rocksdb_enable_bulk_load = IF (@rocksdb_is_supported, 'SET SESSION rocksdb_bulk_load = 1', 'SET @rocksdb_dummy_bulk_load = 0') */;
/*!50717 PREPARE s FROM @rocksdb_enable_bulk_load */;
/*!50717 EXECUTE s */;
/*!50717 DEALLOCATE PREPARE s */;

--
-- Dumping data for table `tb_config_name_def`
--
-- WHERE:  namespace='TwemproxyTendisSSDInstance' AND (flag_encrypt!=1 or value_default like '{{%')

INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16179,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','activerehashing','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16169,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','aof-rewrite-incremental-fsync','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16164,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','appendfilename','STRING','appendonly.aof','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16165,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','appendfsync','STRING','everysec','always|everysec|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16163,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','appendonly','STRING','no','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16168,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','auto-aof-rewrite-min-size','STRING','64mb','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16167,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','auto-aof-rewrite-percentage','INT','100','[0,1000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16137,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','bind','STRING','{{address}} 127.0.0.1','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16189,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','binlog-enabled','INT','1','0|1','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16201,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','binlog-filesize','INT','268435456','[1024,1073741824]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16193,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','clean-time','INT','3','[1,16]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16171,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','client-output-buffer-limit','STRING','normal 256mb 512mb 300\nclient-output-buffer-limit slave 2048mb 2048mb 300\nclient-output-buffer-limit pubsub 32mb 8mb 60','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16145,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','daemonize','STRING','yes','yes|no','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16144,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','databases','INT','{{databases}}','[1,16]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16156,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','dbfilename','STRING','dump.rdb','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16143,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','dir','STRING','{{redis_data_dir}}/data','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16198,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','disk-delete-count','INT','50','[0,1024]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16197,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','disk-delete-time','INT','50','[0,1024]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16191,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','dumpdir','STRING','{{redis_data_dir}}/rbinlog/','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16172,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','hash-max-ziplist-entries','INT','512','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16173,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','hash-max-ziplist-value','INT','64','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16149,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','hz','INT','10','[1,500]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16174,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','list-max-ziplist-entries','INT','512','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16175,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','list-max-ziplist-value','INT','64','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16192,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','log-count','INT','200000','[2000,2000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16199,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','log-keep-count','INT','20000000','[2000,2000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16200,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','log-keep-time','INT','36000','[0,3600000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16141,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','logfile','STRING','{{redis_data_dir}}/redis.log','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16284,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','loglevel','STRING','notice','debug|verbose|notice|warning','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:19:09','2023-04-20 17:19:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16170,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','lua-time-limit','INT','5000','[0,60000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16150,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','maxclients','INT','50000','[10,204800]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16140,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','maxmemory','STRING','{{maxmemory}}','[0,137438953472]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16147,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','maxmemory-policy','STRING','noeviction','noeviction|volatile-ttl|allkeys-random|volatile-random|allkeys-lru|volatile-lru','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16188,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','max_manifest_file_size','INT','200000000','200000000','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16187,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','max_open_files','INT','100000','[10000,204800]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16166,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','no-appendfsync-on-rewrite','STRING','no','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16194,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','pause-clean-time','INT','5','[1,16]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16196,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','pause-scan-expires-time','INT','100','[64,1024]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16142,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','pidfile','STRING','{{redis_data_dir}}/redis.pid','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16138,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','port','INT','{{port}}','[6379,55535]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16155,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','rdbchecksum','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16154,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','rdbcompression','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16162,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','rename-command','STRING','config confxx \nrename-command debug nobug\nrename-command keys mykeys','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16160,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','repl-disable-tcp-nodelay','STRING','no','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16190,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','repl-mode','STRING','tredis-binlog','tredis-binlog','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16159,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','repl-timeout','INT','600','[60,36000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16139,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','requirepass','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16183,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','rocksdb_block_cache','INT','500000000','[500000,2000000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16184,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','rocksdb_block_size','INT','32000','[8000,128000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16185,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','rocksdb_write_buffer_size','INT','32000000','[500000,2000000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16152,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','save','STRING','','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16195,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','scan-expires-time','INT','1','[1,16]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16176,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','set-max-intset-entries','INT','512','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16161,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','slave-priority','INT','100','[0,1000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16158,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','slave-read-only','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16157,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','slave-serve-stale-data','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16180,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','slowlog-log-slower-than','INT','10000','[10,1000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16181,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','slowlog-max-len','INT','256','[0,10240]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16153,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','stop-writes-on-bgsave-error','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16186,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','target_file_size_base','INT','8000000','[512000,128000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16146,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','tcp-keepalive','INT','300','[10,3600]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16148,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','timeout','INT','0','[0,2147483647]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16202,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','transfer-enabled','INT','0','0|1','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16182,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','write_batch_size','INT','2','2','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16177,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','zset-max-ziplist-entries','INT','128','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16178,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.2','zset-max-ziplist-value','INT','64','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16245,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','activerehashing','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16235,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','aof-rewrite-incremental-fsync','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16230,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','appendfilename','STRING','appendonly.aof','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16231,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','appendfsync','STRING','everysec','always|everysec|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16229,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','appendonly','STRING','no','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16234,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','auto-aof-rewrite-min-size','BYTES','64mb','[16mb,1gb]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16233,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','auto-aof-rewrite-percentage','INT','100','[0,1000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16203,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','bind','STRING','{{address}} 127.0.0.1','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16255,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','binlog-enabled','INT','1','0|1','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16267,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','binlog-filesize','INT','268435456','[1024,1073741824]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16259,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','clean-time','INT','3','[1,16]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16237,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','client-output-buffer-limit','STRING','normal 256mb 512mb 300\nclient-output-buffer-limit slave 2048mb 2048mb 300\nclient-output-buffer-limit pubsub 32mb 8mb 60','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16211,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','daemonize','STRING','yes','yes|no','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16210,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','databases','INT','{{databases}}','[1,16]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16222,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','dbfilename','STRING','dump.rdb','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16209,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','dir','STRING','{{redis_data_dir}}/data','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16264,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','disk-delete-count','INT','50','[0,1024]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16263,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','disk-delete-time','INT','50','[0,1024]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16257,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','dumpdir','STRING','{{redis_data_dir}}/rbinlog/','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16238,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','hash-max-ziplist-entries','INT','512','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16239,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','hash-max-ziplist-value','INT','64','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16215,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','hz','INT','10','[1,500]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16240,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','list-max-ziplist-entries','INT','512','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16241,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','list-max-ziplist-value','INT','64','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16258,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','log-count','INT','200000','[2000,2000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16265,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','log-keep-count','INT','20000000','[2000,2000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16266,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','log-keep-time','INT','36000','[0,3600000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16207,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','logfile','STRING','{{redis_data_dir}}/redis.log','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16285,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','loglevel','STRING','notice','debug|verbose|notice|warning','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:19:09','2023-04-20 17:19:09',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16236,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','lua-time-limit','INT','5000','[0,60000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16216,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','maxclients','INT','50000','[10,204800]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16206,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','maxmemory','STRING','{{maxmemory}}','[0,137438953472]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16213,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','maxmemory-policy','STRING','noeviction','noeviction|volatile-ttl|allkeys-random|volatile-random|allkeys-lru|volatile-lru','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16254,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','max_manifest_file_size','INT','200000000','200000000','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16253,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','max_open_files','INT','100000','[10000,204800]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16232,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','no-appendfsync-on-rewrite','STRING','no','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16260,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','pause-clean-time','INT','5','[1,16]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16262,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','pause-scan-expires-time','INT','100','[64,1024]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16208,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','pidfile','STRING','{{redis_data_dir}}/redis.pid','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16204,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','port','INT','{{port}}','[6379,55535]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16221,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','rdbchecksum','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16220,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','rdbcompression','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16228,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','rename-command','STRING','config confxx \nrename-command debug nobug\nrename-command keys mykeys','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16226,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','repl-disable-tcp-nodelay','STRING','no','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16256,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','repl-mode','STRING','tredis-binlog','tredis-binlog','ENUM',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16225,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','repl-timeout','INT','600','[60,36000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16205,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','requirepass','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16249,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','rocksdb_block_cache','INT','500000000','[500000,2000000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16250,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','rocksdb_block_size','INT','32000','[8000,128000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16251,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','rocksdb_write_buffer_size','INT','32000000','[500000,2000000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16218,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','save','STRING','','','',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16261,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','scan-expires-time','INT','1','[1,16]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16242,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','set-max-intset-entries','INT','512','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16227,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','slave-priority','INT','100','[0,1000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16224,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','slave-read-only','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16223,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','slave-serve-stale-data','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16246,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','slowlog-log-slower-than','INT','10000','[10,1000000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16247,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','slowlog-max-len','INT','256','[0,10240]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16219,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','stop-writes-on-bgsave-error','STRING','yes','yes|no','ENUM',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16252,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','target_file_size_base','INT','8000000','[512000,128000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16212,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','tcp-keepalive','INT','300','[10,3600]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16214,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','timeout','INT','0','[0,2147483647]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16248,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','write_batch_size','INT','2','2','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16243,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','zset-max-ziplist-entries','INT','128','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16244,'TwemproxyTendisSSDInstance','dbconf','TendisSSD-1.3','zset-max-ziplist-value','INT','64','[1,10000]','RANGE',1,0,0,0,0,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16274,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','auto_eject_hosts','STRING','false','true|false','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16269,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','backlog','INT','512','nullNULL','nullNULL',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16271,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','distribution','STRING','modhash','modhash','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16272,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','hash','STRING','fnv1a_64','fnv1a_64','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16273,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','hash_tag','STRING','{}','{}','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16279,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','mbuf-size','INT','1024','[128,102400]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16282,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','password','STRING','{{password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16281,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','port','INT','{{port}}','[50000,59999]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16275,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','preconnect','STRING','false','true|false','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16270,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','redis','STRING','true','true','ENUM',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16280,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','redis_password','STRING','{{redis_password}}','','',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16277,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','server_connections','INT','1','[1,10]','RANGE',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16278,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','server_failure_limit','INT','3','[1,10]','RANGE',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16276,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','server_retry_timeout','INT','2000','[1000,10000]','RANGE',1,0,1,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
INSERT INTO `tb_config_name_def` (`id`, `namespace`, `conf_type`, `conf_file`, `conf_name`, `value_type`, `value_default`, `value_allowed`, `value_type_sub`, `flag_status`, `flag_disable`, `flag_locked`, `flag_encrypt`, `need_restart`, `value_formula`, `extra_info`, `conf_name_lc`, `order_index`, `since_version`, `description`, `created_at`, `updated_at`, `stage`) VALUES (16268,'TwemproxyTendisSSDInstance','proxyconf','Twemproxy-latest','slowms','INT','1000000','[0,10000000]','RANGE',1,0,0,0,1,NULL,NULL,NULL,-1,NULL,NULL,'2023-04-20 17:03:54','2023-04-20 17:03:54',0);
/*!50112 SET @disable_bulk_load = IF (@is_rocksdb_supported, 'SET SESSION rocksdb_bulk_load = @old_rocksdb_bulk_load', 'SET @dummy_rocksdb_bulk_load = 0') */;
/*!50112 PREPARE s FROM @disable_bulk_load */;
/*!50112 EXECUTE s */;
/*!50112 DEALLOCATE PREPARE s */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

