{{- $apiKey := include "qdrant.apiKey" . | trim }}
{{- if and .Values.observeConfig.svcMonitor.enabled $apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-apikey
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "qdrant.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  api-key: {{ $apiKey | b64enc | quote }}
{{- end }}
