{{- $dbInfo := fromYaml (include "bk-dbm.database" (list . "backupServer")) -}}
{{- $etcdInfo := fromYaml (include "bk-dbm.etcd" (list . "backupServer")) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-server-configmap
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
data:
  cos-server.yaml: |-
    cos-server:
      databases:
        mysql:
          name: "cos_mysql"
          host: "{{ $dbInfo.host }}"
          port: {{ $dbInfo.port }}
          user: "{{ $dbInfo.user }}"
          password: "{{ $dbInfo.password }}"
          database: "{{ $dbInfo.name }}"
          charset: "utf8mb4"

      log:
        level: "debug"
        format: "text"
        disable-timestamp: false
        filename: "log/cos_server.log"
      coslimits:
        local_total_limit: 100
        local_file_limit: 50
        chunk_size: 100
      public:
        port: "7000"
        order_process: 100
        single_order_thread: 8
        order_number: 200
        backupclient_repository: "{{ index .Values "backup-server" "backup_client" "repository" }}"
        backupclient_medium_dir: "{{ index .Values "backup-server" "backup_client" "mediumDir" }}"
      gse:
        {{- if .Values.bk.bkJobApiUrl }}
        address: "{{ .Values.bk.bkJobApiUrl }}"
        {{- else }}
        address: "{{ .Values.bk.bkComponentApiUrl }}/api/c/compapi/v2/jobv3"
        {{- end }}
        app_code: "{{ .Values.dbm.envs.bkAppCode }}"
        app_secret: "{{ .Values.dbm.envs.bkAppToken }}"
        app_id: {{ .Values.bk.bluekingBizId | default "9991001"}}
        operator: "{{ .Values.bk.bkJobV3Operator | default "admin"}}"
      etcdset:
        endpoints: "{{ $etcdInfo.schema }}://{{ $etcdInfo.host }}:{{ $etcdInfo.port }}"
        user: "{{ $etcdInfo.username }}"
        password: "{{ $etcdInfo.password }}"
        srv_path: "dbmcos/"
        ttl: 10
      migrate:
        enable: true
    {{- if index .Values "backup-server" "hdfs" "enable" }}
    hdfs-server:
      server_addr: "{{ index .Values "backup-server" "hdfs" "server_addr" }}"
      api_sys_id: "{{ index .Values "backup-server" "hdfs" "api_sys_id" }}"
      api_key: "{{ index .Values "backup-server" "hdfs" "api_key" }}"
      api_ticket: ""
      api_version: "1.0"
    {{- end }}