{{- if and .Values.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dbm.serviceAccountName" . }}
  labels:
    {{- include "dbm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dbm.fullname" . }}-role
rules:
- apiGroups:
  - batch
  - ""
  resources:
  - jobs
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dbm.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dbm.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "dbm.serviceAccountName" . }}
  namespace: {{ default "default" .Release.Namespace }}
{{- end }}
