// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/strategies/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy create",
                "operationId": "openapi_strategy_create",
                "parameters": [
                    {
                        "description": "strategy create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/api/admin/strategies/{id}/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy get",
                "operationId": "openapi_strategy_get",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "bk_biz_id",
                        "name": "bk_biz_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyCreateRequest": {
            "type": "object",
            "required": [
                "action",
                "bk_biz_id",
                "name",
                "priority",
                "scope",
                "trigger_count",
                "trigger_event_name",
                "trigger_event_name_reason"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "bk_biz_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer",
                    "minimum": 0
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "trigger_count": {
                    "type": "integer",
                    "minimum": 1
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                },
                "trigger_event_name_reason": {
                    "minimum": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventNameReason"
                        }
                    ]
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "bk_biz_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "status": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                },
                "trigger_event_name_reason": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventNameReason"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType": {
            "type": "string",
            "enum": [
                "cluster",
                "host"
            ],
            "x-enum-varnames": [
                "ActionScopeTypeCluster",
                "ActionScopeTypeHost"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType": {
            "type": "string",
            "enum": [
                "notify",
                "switch"
            ],
            "x-enum-varnames": [
                "ActionTypeNotify",
                "ActionTypeSwitch"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType": {
            "type": "string",
            "enum": [
                "enabled",
                "disabled",
                "deleted"
            ],
            "x-enum-varnames": [
                "StatusTypeEnabled",
                "StatusTypeDisabled",
                "StatusTypeDeleted"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName": {
            "type": "string",
            "enum": [
                "dbha_redis_switch_succ",
                "dbha_redis_switch_err",
                "dbha_mysql_switch_ok",
                "dbha_mysql_switch_err",
                "dbha_riak_switch_ok",
                "dbha_riak_switch_err",
                "dbha_sqlserver_switch_ok",
                "dbha_sqlserver_switch_err",
                "dbha_mongos_switch_succ",
                "dbha_mongos_switch_err",
                "dbha_detect_redis_auth_fail",
                "dbha_detect_ssh_auth_fail",
                "dbha_detect_ssh_fail",
                "dbha_detect_db_fail",
                "dbha_doublecheck_ssh_fail",
                "dbha_doublecheck_auth_fail",
                "dbha_global_monitor",
                "dbha_call_api_fail",
                "dbha_detect_db_failure",
                "dbha_detect_ssh_failure",
                "dbha_probe_offline"
            ],
            "x-enum-varnames": [
                "DbEventNameRedisSwitchSuccessV1",
                "DbEventNameRedisSwitchFailureV1",
                "DbEventNameMysqlSwitchSuccessV1",
                "DbEventNameMysqlSwitchFailureV1",
                "DbEventNameRiakSwitchSuccessV1",
                "DbEventNameRiakSwitchFailureV1",
                "DbEventNameSqlServerSwitchSuccessV1",
                "DbEventNameSqlServerSwitchFailureV1",
                "DbEventNameMongoSwitchSuccessV1",
                "DbEventNameMongoSwitchFailureV1",
                "DbEventNameDetectRedisAuthFailureV1",
                "DbEventNameDetectSshAuthFailureV1",
                "DbEventNameDetectSshFailureV1",
                "DbEventNameDetectDbFailureV1",
                "DbEventNameDoubleCheckSshFailureV1",
                "DbEventNameDoubleCheckAuthFailureV1",
                "DbEventNameGlobalMonitorV1",
                "DbEventNameApiFailureV1",
                "DbEventNameDetectFailure",
                "DbEventNameDetectSSHFailure",
                "DbEventNameProbeOffline"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventNameReason": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "DbEventNameReasonConnectionException",
                "DbEventNameReasonAuthException",
                "DbEventNameReasonSSHAuthException",
                "DbEventNameReasonMissedProbe",
                "DbEventNameReasonNoTarget"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
