// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/global/strategies/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "global strategy list",
                "operationId": "openapi_global_strategy_list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_ginx.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "global strategy create",
                "operationId": "openapi_global_strategy_create",
                "parameters": [
                    {
                        "description": "strategy create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.GlobalStrategyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/api/admin/global/strategies/{id}/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "global strategy get",
                "operationId": "openapi_global_strategy_get",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "global strategy update",
                "operationId": "openapi_global_strategy_update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "strategy update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.GlobalStrategyUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "global strategy delete",
                "operationId": "openapi_global_strategy_delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/admin/global/strategies/{id}/status/": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "global strategy status update",
                "operationId": "openapi_global_strategy_status_update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "strategy status update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.GlobalStrategyStatusUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/admin/strategies/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy list",
                "operationId": "openapi_strategy_list",
                "parameters": [
                    {
                        "type": "string",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "bk_biz_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_ginx.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy create",
                "operationId": "openapi_strategy_create",
                "parameters": [
                    {
                        "description": "strategy create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/api/admin/strategies/batch/": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy batch update",
                "operationId": "openapi_strategy_batch_update",
                "parameters": [
                    {
                        "description": "strategy batch update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy batch create",
                "operationId": "openapi_strategy_batch_create",
                "parameters": [
                    {
                        "description": "strategy batch create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy batch delete",
                "operationId": "openapi_strategy_batch_delete",
                "parameters": [
                    {
                        "description": "strategy batch delete request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/admin/strategies/batch/status/": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy batch update status",
                "operationId": "openapi_strategy_batch_update_status",
                "parameters": [
                    {
                        "description": "strategy batch update status request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchUpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/admin/strategies/eventnames/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy trigger event names list",
                "operationId": "openapi_strategy_trigger_event_names_list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/strategies/{id}/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy get",
                "operationId": "openapi_strategy_get",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "bk_biz_id",
                        "name": "bk_biz_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy update",
                "operationId": "openapi_strategy_update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "strategy update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy delete",
                "operationId": "openapi_strategy_delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "bk_biz_id",
                        "name": "bk_biz_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/admin/strategies/{id}/status/": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "openapi.strategy"
                ],
                "summary": "strategy status update",
                "operationId": "openapi_strategy_status_update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "strategy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "strategy status update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyStatusUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.GlobalStrategyCreateRequest": {
            "type": "object",
            "required": [
                "name",
                "trigger_event_name"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.GlobalStrategyStatusUpdateRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.GlobalStrategyUpdateRequest": {
            "type": "object",
            "required": [
                "name",
                "trigger_event_name"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchCreateRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "data"
            ],
            "properties": {
                "bk_biz_id": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyInfo"
                    }
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchDeleteRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "ids"
            ],
            "properties": {
                "bk_biz_id": {
                    "type": "integer"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchUpdateRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "data"
            ],
            "properties": {
                "bk_biz_id": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyInfo"
                    }
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyBatchUpdateStatusRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "ids",
                "status"
            ],
            "properties": {
                "bk_biz_id": {
                    "type": "integer"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyCreateRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "name"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "bk_biz_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyInfo": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "name"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "bk_biz_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyOutputInfo": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "name"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "bk_biz_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "status": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyStatusUpdateRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "status"
            ],
            "properties": {
                "bk_biz_id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_api_open_serializer.StrategyUpdateRequest": {
            "type": "object",
            "required": [
                "bk_biz_id",
                "name"
            ],
            "properties": {
                "action": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType"
                },
                "bk_biz_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "scope": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType"
                },
                "trigger_count": {
                    "type": "integer"
                },
                "trigger_event_name": {
                    "$ref": "#/definitions/dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName"
                }
            }
        },
        "dbm-services_common_dbha-v2_internal_admin_ginx.PaginatedResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "results": {}
            }
        },
        "dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionScopeType": {
            "type": "string",
            "enum": [
                "cluster",
                "host"
            ],
            "x-enum-varnames": [
                "ActionScopeTypeCluster",
                "ActionScopeTypeHost"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_hamodel.ActionType": {
            "type": "string",
            "enum": [
                "notify",
                "switch"
            ],
            "x-enum-varnames": [
                "ActionTypeNotify",
                "ActionTypeSwitch"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_hamodel.StatusType": {
            "type": "string",
            "enum": [
                "enabled",
                "disabled",
                "deleted"
            ],
            "x-enum-varnames": [
                "StatusTypeEnabled",
                "StatusTypeDisabled",
                "StatusTypeDeleted"
            ]
        },
        "dbm-services_common_dbha-v2_pkg_storage_haprobe.DbEventName": {
            "type": "string",
            "enum": [
                "dbha_redis_switch_succ",
                "dbha_redis_switch_err",
                "dbha_mysql_switch_ok",
                "dbha_mysql_switch_err",
                "dbha_riak_switch_ok",
                "dbha_riak_switch_err",
                "dbha_sqlserver_switch_ok",
                "dbha_sqlserver_switch_err",
                "dbha_mongos_switch_succ",
                "dbha_mongos_switch_err",
                "dbha_detect_redis_auth_fail",
                "dbha_detect_ssh_auth_fail",
                "dbha_detect_ssh_fail",
                "dbha_detect_db_fail",
                "dbha_doublecheck_ssh_fail",
                "dbha_doublecheck_auth_fail",
                "dbha_global_monitor",
                "dbha_call_api_fail",
                "dbha_detect_db_failure",
                "dbha_detect_ssh_failure",
                "dbha_probe_offline"
            ],
            "x-enum-varnames": [
                "DbEventNameRedisSwitchSuccessV1",
                "DbEventNameRedisSwitchFailureV1",
                "DbEventNameMysqlSwitchSuccessV1",
                "DbEventNameMysqlSwitchFailureV1",
                "DbEventNameRiakSwitchSuccessV1",
                "DbEventNameRiakSwitchFailureV1",
                "DbEventNameSqlServerSwitchSuccessV1",
                "DbEventNameSqlServerSwitchFailureV1",
                "DbEventNameMongoSwitchSuccessV1",
                "DbEventNameMongoSwitchFailureV1",
                "DbEventNameDetectRedisAuthFailureV1",
                "DbEventNameDetectSshAuthFailureV1",
                "DbEventNameDetectSshFailureV1",
                "DbEventNameDetectDbFailureV1",
                "DbEventNameDoubleCheckSshFailureV1",
                "DbEventNameDoubleCheckAuthFailureV1",
                "DbEventNameGlobalMonitorV1",
                "DbEventNameApiFailureV1",
                "DbEventNameDetectFailure",
                "DbEventNameDetectSSHFailure",
                "DbEventNameProbeOffline"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
