# Generated by Django 3.2.25 on 2025-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceReplenishRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("details", models.JSONField(verbose_name="资源补给详情")),
                ("ticket_ids", models.JSONField(verbose_name="关联单据ID")),
            ],
            options={
                "verbose_name": "资源补货记录",
            },
        ),
    ]
