# Generated by Django 4.2.30 on 2026-07-16 03:13

from django.db import migrations, models

import backend.ticket.constants


class Migration(migrations.Migration):

    dependencies = [
        ("dbresource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcereplenishrecord",
            name="replenish_type",
            field=models.CharField(
                choices=[("full", "全量补货"), ("increment", "部分补货")],
                default=backend.ticket.constants.ReplenishTypeEnum["FULL"],
                max_length=64,
                verbose_name="补货类型",
            ),
        ),
    ]
