user root;
events {
    worker_connections  65535;
}
http {
    # 基础配置
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    server {
        listen 80;
        server_name $DBM_NGINX_DOMAIN;
        client_max_body_size 500M;
        proxy_connect;
        proxy_connect_allow 443 563;

        set_real_ip_from 0.0.0.0/0;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 转发dbm组件服务(反向上报)
        location /apis/proxypass/ {
            proxy_pass $BK_DBM_URL;
        }

        # 包含到大数据服务的子配置
        include /usr/local/bkdb/nginx-portable/conf/cluster_service/*.conf;
    }
}
