# Generated by Django 3.2.25 on 2024-09-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_authorize", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBRuleActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operator", models.CharField(max_length=32, verbose_name="操作人")),
                ("record_time", models.DateTimeField(auto_now=True, verbose_name="记录时间")),
                ("account_id", models.IntegerField(verbose_name="账号ID")),
                ("rule_id", models.IntegerField(verbose_name="权限规则ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[("auth", "授权"), ("create", "创建"), ("change", "修改"), ("delete", "删除")],
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限变更记录",
                "verbose_name_plural": "权限变更记录",
                "ordering": ["-record_time"],
            },
        ),
        migrations.AddIndex(
            model_name="dbruleactionlog",
            index=models.Index(fields=["rule_id"], name="db_authoriz_rule_id_35a12d_idx"),
        ),
        migrations.AddIndex(
            model_name="dbruleactionlog",
            index=models.Index(fields=["account_id"], name="db_authoriz_account_06c480_idx"),
        ),
    ]
