# Generated by Django 4.2.23 on 2025-12-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketFlowAILog",
            fields=[
                ("ticket_id", models.BigIntegerField(default=0, verbose_name="单据ID")),
                (
                    "flow_obj_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="流程ID"),
                ),
                ("ai_summary", models.TextField(blank=True, null=True, verbose_name="AI日志总结")),
            ],
            options={
                "verbose_name": "工单流程AI日志",
                "verbose_name_plural": "工单流程AI日志",
            },
        ),
    ]
