# Generated by Django 4.2.27 on 2026-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbm_aiagent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketflowailog",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
