# Generated by Django 4.2.27 on 2026-03-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbm_aiagent", "0002_ticketflowailog_update_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineDisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "disk_name",
                    models.CharField(
                        help_text="磁盘配置的唯一名称，如 NVMe_SSD_3570", max_length=128, unique=True, verbose_name="磁盘配置名称"
                    ),
                ),
                (
                    "disk_type",
                    models.CharField(
                        choices=[
                            ("NVME_SSD", "NVMe SSD 硬盘"),
                            ("SATA_SSD", "SATA SSD 硬盘"),
                            ("SAS", "SAS 硬盘"),
                            ("HDD", "HDD 机械硬盘"),
                            ("CLOUD_PREMIUM", "高性能云硬盘"),
                            ("CLOUD_BSSD", "通用型SSD云硬盘"),
                            ("CLOUD_SSD", "SSD云硬盘"),
                            ("CLOUD_HSSD", "增强型SSD云硬盘"),
                            ("CLOUD_TSSD", "极速型SSD云硬盘"),
                        ],
                        help_text="磁盘类型，如 NVMe SSD",
                        max_length=32,
                        verbose_name="磁盘类型",
                    ),
                ),
                ("disk_model", models.CharField(help_text="磁盘型号或系列编码，如 3570", max_length=64, verbose_name="磁盘型号")),
                ("is_local", models.BooleanField(default=True, help_text="指示磁盘是否为本地盘", verbose_name="是否本地盘")),
                (
                    "capacity_gb",
                    models.IntegerField(blank=True, help_text="单块磁盘的容量大小，如 3570", null=True, verbose_name="单盘容量(GB)"),
                ),
                (
                    "performance_iops",
                    models.IntegerField(blank=True, help_text="磁盘的平均IOPS性能指标", null=True, verbose_name="性能IOPS"),
                ),
                (
                    "performance_throughput_mbps",
                    models.IntegerField(
                        blank=True, help_text="磁盘的平均吞吐量性能指标(MB/s)", null=True, verbose_name="性能吞吐(MB/s)"
                    ),
                ),
                (
                    "sequential_write_throughput_mbps",
                    models.IntegerField(
                        blank=True, help_text="磁盘的顺序写吞吐量性能指标(MB/s)", null=True, verbose_name="顺序写吞吐(MB/s)"
                    ),
                ),
                (
                    "random_read_iops",
                    models.IntegerField(blank=True, help_text="磁盘的随机读IOPS性能指标", null=True, verbose_name="随机读IOPS"),
                ),
                (
                    "write_latency_ms",
                    models.FloatField(blank=True, help_text="磁盘的写延迟性能指标，单位毫秒", null=True, verbose_name="写延迟(ms)"),
                ),
            ],
            options={
                "verbose_name": "基线磁盘配置",
                "verbose_name_plural": "基线磁盘配置",
                "ordering": ["disk_type", "disk_model"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BaselineHost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "device_class",
                    models.CharField(
                        help_text="机型的唯一编码，如 ITA3.4XLARGE64-p2w", max_length=128, unique=True, verbose_name="机型编码"
                    ),
                ),
                (
                    "spec_type",
                    models.CharField(default="", help_text="机型所属的系列类型，如 高IO型ITA3", max_length=64, verbose_name="机型系列"),
                ),
                (
                    "cpu_model",
                    models.CharField(
                        default="", help_text="CPU型号，如 AMD EPYC 7K83", max_length=64, verbose_name="CPU型号"
                    ),
                ),
                (
                    "cpu_frequency_ghz",
                    models.FloatField(
                        blank=True, help_text="CPU主频或全核睿频，单位GHz，如 2.55", null=True, verbose_name="CPU主频(GHz)"
                    ),
                ),
                (
                    "network_card_speed",
                    models.CharField(
                        blank=True, help_text="网卡速度，如 100G", max_length=32, null=True, verbose_name="网卡速度"
                    ),
                ),
                ("vcpu", models.IntegerField(help_text="虚拟CPU核心数量", verbose_name="vCPU数量")),
                ("memory_gb", models.IntegerField(help_text="内存大小，单位GB", verbose_name="内存大小(GB)")),
                (
                    "max_connections_w",
                    models.IntegerField(
                        blank=True, help_text="最大连接数，单位万，如 110 (表示110万)", null=True, verbose_name="最大连接数(万)"
                    ),
                ),
                (
                    "network_pps_w",
                    models.IntegerField(
                        blank=True,
                        help_text="网络每秒收发包数量，单位万pps，如 130 (表示130万pps)",
                        null=True,
                        verbose_name="网络收发包(万pps)",
                    ),
                ),
                (
                    "intranet_bandwidth_gbps",
                    models.IntegerField(blank=True, help_text="内网带宽能力，单位Gbps", null=True, verbose_name="内网带宽能力(Gbps)"),
                ),
                ("queue_count", models.IntegerField(blank=True, help_text="主机硬件队列数量", null=True, verbose_name="队列数")),
                ("remarks", models.TextField(blank=True, help_text="其他非结构化的备注信息", null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "基线主机配置",
                "verbose_name_plural": "基线主机配置",
                "ordering": ["device_class"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BenchmarkHostConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "os_version",
                    models.CharField(
                        help_text="操作系统版本，如 CentOS 7.9, Ubuntu 20.04", max_length=64, verbose_name="操作系统版本"
                    ),
                ),
                ("disk_quantity", models.IntegerField(help_text="该配置使用的磁盘数量，如 2、4、8、16", verbose_name="磁盘数量")),
                (
                    "baseline_disk",
                    models.ForeignKey(
                        help_text="关联的基线磁盘配置",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dbm_aiagent.baselinedisk",
                    ),
                ),
                (
                    "baseline_host",
                    models.ForeignKey(
                        help_text="关联的基线主机配置",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dbm_aiagent.baselinehost",
                    ),
                ),
            ],
            options={
                "verbose_name": "性能基准测试主机配置",
                "verbose_name_plural": "性能基准测试主机配置",
                "ordering": ["baseline_host", "baseline_disk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenDBSingleBenchmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "mysql_version",
                    models.CharField(help_text="MySQL版本，如 5.7.20", max_length=64, verbose_name="MySQL版本"),
                ),
                (
                    "stress_test_tool",
                    models.CharField(
                        blank=True, help_text="压测工具名称，如 sysbench, tpcc", max_length=64, null=True, verbose_name="压测工具"
                    ),
                ),
                (
                    "stress_test_tool_version",
                    models.CharField(blank=True, help_text="压测工具版本号", max_length=64, null=True, verbose_name="压测工具版本"),
                ),
                (
                    "loaded_data_volume_gb",
                    models.IntegerField(
                        blank=True, help_text="压测前预先导入到集群的数据量，单位GB", null=True, verbose_name="预导入数据量(GB)"
                    ),
                ),
                (
                    "loaded_data_volume_rows",
                    models.BigIntegerField(
                        blank=True, help_text="压测前预先导入到集群的数据行数", null=True, verbose_name="预导入数据量(行数)"
                    ),
                ),
                (
                    "concurrent_threads",
                    models.IntegerField(help_text="并发线程数，如 10, 20, 50, 100, 200, 500, 1000", verbose_name="并发线程数"),
                ),
                (
                    "read_write_ratio",
                    models.CharField(
                        blank=True, help_text="读写比例，如 读写8/2", max_length=32, null=True, verbose_name="读写比例"
                    ),
                ),
                (
                    "avg_qps",
                    models.IntegerField(
                        blank=True, help_text="平均QPS（Queries Per Second）", null=True, verbose_name="平均QPS"
                    ),
                ),
                (
                    "avg_tps",
                    models.FloatField(
                        blank=True, help_text="平均TPS（Transactions Per Second）", null=True, verbose_name="平均TPS"
                    ),
                ),
                (
                    "avg_latency_ms",
                    models.FloatField(blank=True, help_text="平均耗时，单位毫秒", null=True, verbose_name="平均耗时(ms)"),
                ),
                (
                    "p95_latency_ms",
                    models.FloatField(blank=True, help_text="95%平均耗时，单位毫秒", null=True, verbose_name="95%平均耗时(ms)"),
                ),
                (
                    "io_usage_rate",
                    models.FloatField(blank=True, help_text="IO使用率，百分比，0-100", null=True, verbose_name="IO使用率(%)"),
                ),
                (
                    "cpu_usage_rate",
                    models.FloatField(blank=True, help_text="CPU使用率，百分比，0-100", null=True, verbose_name="CPU使用率(%)"),
                ),
                (
                    "host_config",
                    models.ForeignKey(
                        help_text="关联的主机配置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tendbsingle_benchmarks",
                        to="dbm_aiagent.benchmarkhostconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "TenDBSingle性能基准测试结果",
                "verbose_name_plural": "TenDBSingle性能基准测试结果",
                "ordering": ["host_config", "mysql_version", "concurrent_threads"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenDBHABenchmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("proxy_version", models.CharField(help_text="Proxy版本号", max_length=64, verbose_name="Proxy版本")),
                ("proxy_count", models.IntegerField(help_text="Proxy节点数量，如 2, 3, 4", verbose_name="Proxy数量")),
                (
                    "backend_version",
                    models.CharField(help_text="Backend（MySQL）版本", max_length=64, verbose_name="Backend版本"),
                ),
                (
                    "backend_master_count",
                    models.IntegerField(default=1, help_text="Master数量（通常为1）", verbose_name="Master数量"),
                ),
                ("backend_slave_count", models.IntegerField(help_text="Slave节点数量", verbose_name="Slave数量")),
                (
                    "stress_test_tool",
                    models.CharField(
                        blank=True, help_text="压测工具名称，如 sysbench, tpcc", max_length=64, null=True, verbose_name="压测工具"
                    ),
                ),
                (
                    "stress_test_tool_version",
                    models.CharField(blank=True, help_text="压测工具版本号", max_length=64, null=True, verbose_name="压测工具版本"),
                ),
                ("concurrent_threads", models.IntegerField(help_text="并发线程数", verbose_name="并发线程数")),
                (
                    "loaded_data_volume_gb",
                    models.IntegerField(
                        blank=True, help_text="压测前预先导入到集群的数据量，单位GB", null=True, verbose_name="预导入数据量(GB)"
                    ),
                ),
                (
                    "loaded_data_volume_rows",
                    models.BigIntegerField(
                        blank=True, help_text="压测前预先导入到集群的数据行数", null=True, verbose_name="预导入数据量(行数)"
                    ),
                ),
                (
                    "read_write_ratio",
                    models.CharField(
                        blank=True, help_text="读写比例，如 读写8/2", max_length=32, null=True, verbose_name="读写比例"
                    ),
                ),
                (
                    "avg_qps",
                    models.IntegerField(
                        blank=True, help_text="平均QPS（Queries Per Second）", null=True, verbose_name="平均QPS"
                    ),
                ),
                (
                    "avg_tps",
                    models.FloatField(
                        blank=True, help_text="平均TPS（Transactions Per Second）", null=True, verbose_name="平均TPS"
                    ),
                ),
                (
                    "avg_latency_ms",
                    models.FloatField(blank=True, help_text="平均耗时，单位毫秒", null=True, verbose_name="平均耗时(ms)"),
                ),
                (
                    "p95_latency_ms",
                    models.FloatField(blank=True, help_text="95%平均耗时，单位毫秒", null=True, verbose_name="95%平均耗时(ms)"),
                ),
                (
                    "proxy_io_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Proxy IO使用率，百分比，0-100", null=True, verbose_name="Proxy IO使用率(%)"
                    ),
                ),
                (
                    "proxy_cpu_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Proxy CPU使用率，百分比，0-100", null=True, verbose_name="Proxy CPU使用率(%)"
                    ),
                ),
                (
                    "backend_io_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Backend IO使用率，百分比，0-100", null=True, verbose_name="Backend IO使用率(%)"
                    ),
                ),
                (
                    "backend_cpu_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Backend CPU使用率，百分比，0-100", null=True, verbose_name="Backend CPU使用率(%)"
                    ),
                ),
                (
                    "backend_host_config",
                    models.ForeignKey(
                        help_text="Backend 主机配置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tendbha_backend_benchmarks",
                        to="dbm_aiagent.benchmarkhostconfig",
                    ),
                ),
                (
                    "proxy_host_config",
                    models.ForeignKey(
                        help_text="Proxy 主机配置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tendbha_proxy_benchmarks",
                        to="dbm_aiagent.benchmarkhostconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "TenDBHA性能基准测试结果",
                "verbose_name_plural": "TenDBHA性能基准测试结果",
                "ordering": ["proxy_host_config", "backend_host_config", "concurrent_threads"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenDBClusterBenchmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("spider_version", models.CharField(help_text="Spider版本号", max_length=64, verbose_name="Spider版本")),
                ("spider_count", models.IntegerField(help_text="Spider节点数量", verbose_name="Spider数量")),
                (
                    "remote_version",
                    models.CharField(help_text="Remote（MySQL）版本", max_length=64, verbose_name="Remote版本"),
                ),
                ("shard_count", models.IntegerField(help_text="分片数量，每个分片包含 1 Master + 1 Slave", verbose_name="分片数量")),
                (
                    "stress_test_tool",
                    models.CharField(
                        blank=True, help_text="压测工具名称，如 sysbench, tpcc", max_length=64, null=True, verbose_name="压测工具"
                    ),
                ),
                (
                    "stress_test_tool_version",
                    models.CharField(blank=True, help_text="压测工具版本号", max_length=64, null=True, verbose_name="压测工具版本"),
                ),
                ("concurrent_threads", models.IntegerField(help_text="并发线程数", verbose_name="并发线程数")),
                (
                    "loaded_data_volume_gb",
                    models.IntegerField(
                        blank=True, help_text="压测前预先导入到集群的数据量，单位GB", null=True, verbose_name="预导入数据量(GB)"
                    ),
                ),
                (
                    "loaded_data_volume_rows",
                    models.BigIntegerField(
                        blank=True, help_text="压测前预先导入到集群的数据行数", null=True, verbose_name="预导入数据量(行数)"
                    ),
                ),
                (
                    "read_write_ratio",
                    models.CharField(
                        blank=True, help_text="读写比例，如 读写8/2", max_length=32, null=True, verbose_name="读写比例"
                    ),
                ),
                (
                    "avg_qps",
                    models.IntegerField(
                        blank=True, help_text="平均QPS（Queries Per Second）", null=True, verbose_name="平均QPS"
                    ),
                ),
                (
                    "avg_tps",
                    models.FloatField(
                        blank=True, help_text="平均TPS（Transactions Per Second）", null=True, verbose_name="平均TPS"
                    ),
                ),
                (
                    "avg_latency_ms",
                    models.FloatField(blank=True, help_text="平均耗时，单位毫秒", null=True, verbose_name="平均耗时(ms)"),
                ),
                (
                    "p95_latency_ms",
                    models.FloatField(blank=True, help_text="95%平均耗时，单位毫秒", null=True, verbose_name="95%平均耗时(ms)"),
                ),
                (
                    "spider_io_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Spider IO使用率，百分比，0-100", null=True, verbose_name="Spider IO使用率(%)"
                    ),
                ),
                (
                    "spider_cpu_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Spider CPU使用率，百分比，0-100", null=True, verbose_name="Spider CPU使用率(%)"
                    ),
                ),
                (
                    "remote_io_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Remote IO使用率，百分比，0-100", null=True, verbose_name="Remote IO使用率(%)"
                    ),
                ),
                (
                    "remote_cpu_usage_rate",
                    models.FloatField(
                        blank=True, help_text="Remote CPU使用率，百分比，0-100", null=True, verbose_name="Remote CPU使用率(%)"
                    ),
                ),
                (
                    "remote_host_config",
                    models.ForeignKey(
                        help_text="Remote 主机配置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tendbcluster_remote_benchmarks",
                        to="dbm_aiagent.benchmarkhostconfig",
                    ),
                ),
                (
                    "spider_host_config",
                    models.ForeignKey(
                        help_text="Spider 主机配置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tendbcluster_spider_benchmarks",
                        to="dbm_aiagent.benchmarkhostconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "TenDBCluster性能基准测试结果",
                "verbose_name_plural": "TenDBCluster性能基准测试结果",
                "ordering": ["spider_host_config", "remote_host_config", "concurrent_threads"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="baselinehost",
            index=models.Index(fields=["spec_type", "cpu_model"], name="dbm_aiagent_spec_ty_8e0654_idx"),
        ),
        migrations.AddIndex(
            model_name="baselinedisk",
            index=models.Index(fields=["disk_type"], name="dbm_aiagent_disk_ty_77bada_idx"),
        ),
        migrations.AddIndex(
            model_name="baselinedisk",
            index=models.Index(fields=["disk_model"], name="dbm_aiagent_disk_mo_79c8d8_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbsinglebenchmark",
            index=models.Index(fields=["host_config"], name="dbm_aiagent_host_co_c4f653_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbsinglebenchmark",
            index=models.Index(fields=["mysql_version"], name="dbm_aiagent_mysql_v_050959_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbsinglebenchmark",
            index=models.Index(fields=["concurrent_threads"], name="dbm_aiagent_concurr_17dfc8_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbsinglebenchmark",
            index=models.Index(fields=["avg_qps"], name="dbm_aiagent_avg_qps_e9f326_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbsinglebenchmark",
            index=models.Index(fields=["host_config", "mysql_version"], name="dbm_aiagent_host_co_3eeda4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tendbsinglebenchmark",
            unique_together={("host_config", "mysql_version", "concurrent_threads", "read_write_ratio")},
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["proxy_host_config"], name="dbm_aiagent_proxy_h_aa3db8_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["proxy_version"], name="dbm_aiagent_proxy_v_2efd5d_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["proxy_count"], name="dbm_aiagent_proxy_c_ac8186_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["backend_host_config"], name="dbm_aiagent_backend_451018_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["backend_version"], name="dbm_aiagent_backend_d3276b_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["backend_slave_count"], name="dbm_aiagent_backend_39d4e6_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["concurrent_threads"], name="dbm_aiagent_concurr_3be85a_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(fields=["avg_qps"], name="dbm_aiagent_avg_qps_e96f50_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbhabenchmark",
            index=models.Index(
                fields=["proxy_host_config", "backend_host_config", "proxy_version", "backend_version"],
                name="dbm_aiagent_proxy_h_f59b9e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tendbhabenchmark",
            unique_together={
                (
                    "proxy_host_config",
                    "backend_host_config",
                    "proxy_version",
                    "backend_version",
                    "proxy_count",
                    "backend_slave_count",
                    "concurrent_threads",
                    "read_write_ratio",
                )
            },
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["spider_host_config"], name="dbm_aiagent_spider__69060c_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["spider_version"], name="dbm_aiagent_spider__3604ca_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["spider_count"], name="dbm_aiagent_spider__0cedfa_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["remote_host_config"], name="dbm_aiagent_remote__9c0d47_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["remote_version"], name="dbm_aiagent_remote__be7f6a_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["shard_count"], name="dbm_aiagent_shard_c_323389_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["concurrent_threads"], name="dbm_aiagent_concurr_1c882e_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(fields=["avg_qps"], name="dbm_aiagent_avg_qps_e51ea1_idx"),
        ),
        migrations.AddIndex(
            model_name="tendbclusterbenchmark",
            index=models.Index(
                fields=["spider_host_config", "remote_host_config", "spider_version", "remote_version", "shard_count"],
                name="dbm_aiagent_spider__2dae07_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tendbclusterbenchmark",
            unique_together={
                (
                    "spider_host_config",
                    "remote_host_config",
                    "spider_version",
                    "remote_version",
                    "spider_count",
                    "shard_count",
                    "concurrent_threads",
                    "read_write_ratio",
                )
            },
        ),
        migrations.AddIndex(
            model_name="benchmarkhostconfig",
            index=models.Index(fields=["baseline_host"], name="dbm_aiagent_baselin_eecb84_idx"),
        ),
        migrations.AddIndex(
            model_name="benchmarkhostconfig",
            index=models.Index(fields=["baseline_disk"], name="dbm_aiagent_baselin_c90412_idx"),
        ),
        migrations.AddIndex(
            model_name="benchmarkhostconfig",
            index=models.Index(fields=["os_version"], name="dbm_aiagent_os_vers_a5c946_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="benchmarkhostconfig",
            unique_together={("baseline_host", "baseline_disk", "os_version", "disk_quantity")},
        ),
    ]
