# Generated by Django 4.2.27 on 2026-05-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbm_aiagent", "0003_baselinedisk_baselinehost_benchmarkhostconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpCalleePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("username", models.CharField(help_text="发起用户名", max_length=255)),
                ("callee_mcp_id", models.CharField(help_text="被调用 mcp id", max_length=255)),
                ("params", models.JSONField(default=dict, help_text="调用参数")),
                ("time_window_start", models.DateTimeField(help_text="计划生效起始时间")),
                ("time_window_end", models.DateTimeField(help_text="计划生效截止时间")),
                ("max_call_count", models.PositiveIntegerField(help_text="最大调用次数")),
                ("current_call_count", models.PositiveIntegerField(default=0, help_text="已调用次数")),
                (
                    "status",
                    models.CharField(
                        choices=[("rejected", "已拒绝"), ("approved", "已批准"), ("expired", "已过期")],
                        default="rejected",
                        help_text="审批状态",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
