/*
 * TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-DB管理系统(BlueKing-BK-DBM) available.
 * Copyright (C) 2017-2023 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at https://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package cst

// 已废弃
var TRUNCATE_TABLES_SQL_FOR_NO_FK = `
use [%s]
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'
EXEC sp_MSForEachTable 'ALTER TABLE ? DISABLE TRIGGER ALL'
EXEC sp_MSForEachTable 'TRUNCATE TABLE ?;'
EXEC sp_MSForEachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL'
EXEC sp_MSForEachTable 'ALTER TABLE ? ENABLE TRIGGER ALL'
`

// LIST_FKS_ON_DB_SQL 拉取数据库内所有用户表的外键关系（parent → referenced）
// 用于"按表清理"场景做 FK 越界检查，%s 为数据库名
var LIST_FKS_ON_DB_SQL = `
USE [%s];
SELECT
    fk.name              AS fk_name,
    ps.name              AS parent_schema,
    pt.name              AS parent_table,
    rs.name              AS ref_schema,
    rt.name              AS ref_table
FROM sys.foreign_keys fk
JOIN sys.tables  pt ON pt.object_id = fk.parent_object_id
JOIN sys.schemas ps ON ps.schema_id = pt.schema_id
JOIN sys.tables  rt ON rt.object_id = fk.referenced_object_id
JOIN sys.schemas rs ON rs.schema_id = rt.schema_id
WHERE pt.is_ms_shipped = 0;
`

// LIST_SCHEMABOUND_REFS_SQL 查找 schema-bound 对象（带 SCHEMABINDING 的视图/UDF 等）
// 对用户表的引用。这类引用会阻止 DROP TABLE，必须在 drop 前提示用户。
// %s 为数据库名
var LIST_SCHEMABOUND_REFS_SQL = `
USE [%s];
SELECT
    referencing  = QUOTENAME(SCHEMA_NAME(o.schema_id)) + '.' + QUOTENAME(o.name)
                 + N' (' + o.type_desc + N')' COLLATE DATABASE_DEFAULT,
    referenced   = QUOTENAME(s2.name) + '.' + QUOTENAME(t.name) COLLATE DATABASE_DEFAULT
FROM sys.sql_expression_dependencies d
JOIN sys.objects  o  ON o.object_id  = d.referencing_id
JOIN sys.tables   t  ON t.object_id  = d.referenced_id
JOIN sys.schemas  s2 ON s2.schema_id = t.schema_id
WHERE d.is_schema_bound_reference = 1
  AND t.is_ms_shipped = 0
  AND o.type NOT IN ('U', 'S')  -- Exclude user tables and system tables as referencers, only return true schema-bound objects
`

// DELETE_TABLES_FOR_FK_BY_LIST 对指定表清单执行 DELETE 清理方案
// 第一个 %s: 数据库名
// DELETE_TABLES_FOR_FK_BY_LIST 对指定表清单执行 DELETE 清理方案
// 第一个 %s: 数据库名
// 第二个 %s: 由 Go 侧拼接的多行 INSERT INTO #T(...) 语句，注入待清理表清单
// 步骤：disable constraint -> disable trigger -> delete -> reseed identity ->
//
//	WITH CHECK CHECK CONSTRAINT ALL -> enable trigger
var DELETE_TABLES_FOR_FK_BY_LIST = `
USE [%s]
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRAN;

    IF OBJECT_ID('tempdb..#T') IS NOT NULL DROP TABLE #T;
    CREATE TABLE #T(
        object_id   int            NOT NULL,
        FullName    nvarchar(512)  NOT NULL,
        HasIdentity bit            NOT NULL
    );

    -- Inject target table list (generated by Go side)
    %s

    DECLARE @sql nvarchar(max) = N'';

    -- 1) Disable constraints on all target tables
    SELECT @sql += N'ALTER TABLE ' + FullName + N' NOCHECK CONSTRAINT ALL;' FROM #T;
    EXEC sp_executesql @sql;

    -- 2) Disable triggers on all target tables
    SET @sql = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' DISABLE TRIGGER ALL;' FROM #T;
    EXEC sp_executesql @sql;

    -- 3) Delete all data from target tables
    SET @sql = N'';
    SELECT @sql += N'DELETE FROM ' + FullName + N';' FROM #T;
    EXEC sp_executesql @sql;

    -- 4) Reseed identity for tables with identity columns
    SET @sql = N'';
    SELECT @sql += N'DBCC CHECKIDENT (''' + FullName + N''', RESEED, 0) WITH NO_INFOMSGS;'
    FROM #T WHERE HasIdentity = 1;
    EXEC sp_executesql @sql;

    -- 5) Re-enable constraints and force validation to re-trust FKs
    SET @sql = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' WITH CHECK CHECK CONSTRAINT ALL;' FROM #T;
    EXEC sp_executesql @sql;

    -- 6) Re-enable triggers
    SET @sql = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' ENABLE TRIGGER ALL;' FROM #T;
    EXEC sp_executesql @sql;

    COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;
`

// 已废弃
var DELETE_TABLES_FOR_FK = `
/* =========================================================
   Plan A: Full DB purge with DELETE (safe/default)
   - Disable constraints/triggers
   - DELETE all target tables
   - Optional identity reseed
   - Re-enable constraints with trust (WITH CHECK CHECK)
   ========================================================= */
USE [%s]
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRAN;

    ---------------------------------------------------------
    -- 0) Build target table list (exclude what you want to keep)
    ---------------------------------------------------------
    IF OBJECT_ID('tempdb..#T') IS NOT NULL DROP TABLE #T;

    SELECT
        t.object_id,
        FullName = QUOTENAME(s.name) + '.' + QUOTENAME(t.name),
        HasIdentity =
            CASE WHEN EXISTS (
                SELECT 1
                FROM sys.identity_columns ic
                WHERE ic.object_id = t.object_id
            ) THEN 1 ELSE 0 END
    INTO #T
    FROM sys.tables t
    JOIN sys.schemas s ON s.schema_id = t.schema_id
    WHERE t.is_ms_shipped = 0
      AND NOT (s.name = 'dbo' AND t.name = '__EFMigrationsHistory'); -- keep EF Core migration history table

    ---------------------------------------------------------
    -- 1) Disable constraint checks
    ---------------------------------------------------------
    DECLARE @sql nvarchar(max) = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' NOCHECK CONSTRAINT ALL;'
    FROM #T;
    EXEC sp_executesql @sql;

    ---------------------------------------------------------
    -- 2) Disable triggers
    ---------------------------------------------------------
    SET @sql = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' DISABLE TRIGGER ALL;'
    FROM #T;
    EXEC sp_executesql @sql;

    ---------------------------------------------------------
    -- 3) Delete data from all target tables
    ---------------------------------------------------------
    SET @sql = N'';
    SELECT @sql += N'DELETE FROM ' + FullName + N';'
    FROM #T;
    EXEC sp_executesql @sql;

    ---------------------------------------------------------
    -- 4) Optional: reseed identity to 0 (next insert starts at 1)
    ---------------------------------------------------------
    SET @sql = N'';
    SELECT @sql += N'DBCC CHECKIDENT (''' + FullName + N''', RESEED, 0) WITH NO_INFOMSGS;'
    FROM #T
    WHERE HasIdentity = 1;
    EXEC sp_executesql @sql;

    ---------------------------------------------------------
    -- 5) Re-enable constraints and re-trust them
    ---------------------------------------------------------
    SET @sql = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' WITH CHECK CHECK CONSTRAINT ALL;'
    FROM #T;
    EXEC sp_executesql @sql;

    ---------------------------------------------------------
    -- 6) Re-enable triggers
    ---------------------------------------------------------
    SET @sql = N'';
    SELECT @sql += N'ALTER TABLE ' + FullName + N' ENABLE TRIGGER ALL;'
    FROM #T;
    EXEC sp_executesql @sql;

    COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;

`

// DROP_TABLES_BY_LIST_SQL 按指定顺序批量 DROP TABLE
//
// 第一个 %s: 数据库名
// 第二个 %s: 由 Go 侧按拓扑顺序拼接的多条 DROP 语句，
//
//	形如 "DROP TABLE [s1].[t1]; DROP TABLE [s2].[t2]; ..."
//
// 设计要点：
//  1. SET XACT_ABORT ON + 显式事务，任一条失败整体回滚，避免半截状态
//  2. SET LOCK_TIMEOUT 30000，防止被长事务持有 Sch-S 锁卡死
//  3. 由调用方保证传入顺序：被引用方在最后；循环依赖由调用方先 DROP CONSTRAINT
var DROP_TABLES_BY_LIST_SQL = `
USE [%s]
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET LOCK_TIMEOUT 30000;

BEGIN TRY
    BEGIN TRAN;

    %s

    COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;
`

// 已废弃
var DROP_TABLES_SQL = `
use [%s]
EXEC sp_MSForEachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'
EXEC sp_MSForEachTable 'ALTER TABLE ? DISABLE TRIGGER ALL'
EXEC sp_MSForEachTable 'DROP TABLE ?;'
`
var TRUNCATE_TABLES_SQL_FOR_PER = `
use [%s]
ALTER TABLE [%s].[%s] NOCHECK CONSTRAINT ALL;
ALTER TABLE [%s].[%s] DISABLE TRIGGER ALL;
TRUNCATE TABLE [%s].[%s];
ALTER TABLE [%s].[%s] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [%s].[%s] ENABLE TRIGGER ALL;
`

// 已废弃
var DROP_TABLES_SQL_FOR_PER = `
use %s
ALTER TABLE [%s].[%s] NOCHECK CONSTRAINT ALL;
ALTER TABLE [%s].[%s] DISABLE TRIGGER ALL;
DROP TABLE [%s].[%s];
`

// CHECK_FK_EXISTS_SQL 检查数据库下是否存在外键约束（仅简单判断），%s 为数据库名
var CHECK_FK_EXISTS_SQL = `
USE [%s];
SELECT COUNT(0) AS cnt FROM sys.foreign_keys fk
JOIN sys.tables t ON t.object_id = fk.parent_object_id
WHERE t.is_ms_shipped = 0;
`

// CHECK_FK_NOT_TRUSTED_SQL 检查执行 DELETE 清档后，是否仍存在 is_not_trusted = 1 的外键
// 返回不可信外键的列表（schema.table.fk_name），%s 为数据库名
var CHECK_FK_NOT_TRUSTED_SQL = `
USE [%s];
SELECT QUOTENAME(s.name) + '.' + QUOTENAME(t.name) + '.' + QUOTENAME(fk.name) AS fk_full_name
FROM sys.foreign_keys fk
JOIN sys.tables t  ON t.object_id = fk.parent_object_id
JOIN sys.schemas s ON s.schema_id = t.schema_id
WHERE t.is_ms_shipped = 0 AND fk.is_not_trusted = 1;
`

// CHECK_CLEAN_RESULT_SQL 校验清档结果：表是否为空，identity 是否会从 1 开始
// 仅返回未清干净的表（IsEmpty=0 或 IdentityStartsFrom1_OK=0），%s 为数据库名
var CHECK_CLEAN_RESULT_SQL = `
USE [%s];
WITH R AS (
    SELECT
        SchemaName = s.name,
        TableName  = t.name,
        RowCnt     = ISNULL(SUM(CASE WHEN p.index_id IN (0,1) THEN p.row_count ELSE 0 END), 0),
        ic.seed_value,
        ic.last_value
    FROM sys.tables t
    JOIN sys.schemas s ON s.schema_id = t.schema_id
    LEFT JOIN sys.dm_db_partition_stats p ON p.object_id = t.object_id
    LEFT JOIN sys.identity_columns ic ON ic.object_id = t.object_id
    WHERE t.is_ms_shipped = 0
    GROUP BY s.name, t.name, ic.seed_value, ic.last_value
)
SELECT
    SchemaName,
    TableName,
    RowCnt,
    CASE WHEN seed_value IS NULL THEN 0 ELSE 1 END AS HasIdentity,
    CASE
        WHEN seed_value IS NULL THEN 1
        WHEN CONVERT(bigint, seed_value) <> 1 THEN 0
        WHEN last_value IS NULL THEN 1
        WHEN CONVERT(bigint, last_value) = 0 THEN 1
        ELSE 0
    END AS IdentityStartsFrom1_OK
FROM R
WHERE RowCnt > 0
   OR (
        seed_value IS NOT NULL
        AND NOT (
            CONVERT(bigint, seed_value) = 1
            AND (last_value IS NULL OR CONVERT(bigint, last_value) = 0)
        )
   )
ORDER BY SchemaName, TableName;
`

// CHECK_CLEAN_RESULT_BY_LIST_SQL 校验指定表的清档结果：表是否为空，identity 是否会从 1 开始
// 第一个 %s: 数据库名
// 第二个 %s: 由 Go 侧拼接的多行 INSERT INTO #T(...) 语句，注入待校验表清单
var CHECK_CLEAN_RESULT_BY_LIST_SQL = `
USE [%s];
SET NOCOUNT ON;

-- Create temp table to store target table list
IF OBJECT_ID('tempdb..#T') IS NOT NULL DROP TABLE #T;
CREATE TABLE #T(
    SchemaName nvarchar(128) NOT NULL,
    TableName  nvarchar(128) NOT NULL
);

-- Inject target table list (generated by Go side)
%s

-- Check clean result for specified tables only
WITH R AS (
    SELECT
        t.SchemaName,
        t.TableName,
        RowCnt     = ISNULL(SUM(CASE WHEN p.index_id IN (0,1) THEN p.row_count ELSE 0 END), 0),
        ic.seed_value,
        ic.last_value
    FROM #T t
    JOIN sys.tables st ON st.name = t.TableName COLLATE DATABASE_DEFAULT
    JOIN sys.schemas ss ON ss.name = t.SchemaName COLLATE DATABASE_DEFAULT AND ss.schema_id = st.schema_id
    LEFT JOIN sys.dm_db_partition_stats p ON p.object_id = st.object_id
    LEFT JOIN sys.identity_columns ic ON ic.object_id = st.object_id
    WHERE st.is_ms_shipped = 0
    GROUP BY t.SchemaName, t.TableName, ic.seed_value, ic.last_value
)
SELECT
    SchemaName,
    TableName,
    RowCnt,
    CASE WHEN seed_value IS NULL THEN 0 ELSE 1 END AS HasIdentity,
    CASE
        WHEN seed_value IS NULL THEN 1
        WHEN CONVERT(bigint, seed_value) <> 1 THEN 0
        WHEN last_value IS NULL THEN 1
        WHEN CONVERT(bigint, last_value) = 0 THEN 1
        ELSE 0
    END AS IdentityStartsFrom1_OK
FROM R
WHERE RowCnt > 0
   OR (
        seed_value IS NOT NULL
        AND NOT (
            CONVERT(bigint, seed_value) = 1
            AND (last_value IS NULL OR CONVERT(bigint, last_value) = 0)
        )
   )
ORDER BY SchemaName, TableName;
`
