apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: {{ include "rustfs.cmpvName" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - releases:
        - rustfs-1.0.0
      compDefs:
        - {{ include "rustfs.cmpdName" . }}-standalone
        - {{ include "rustfs.cmpdName" . }}-distributed
  releases:
    - name: rustfs-1.0.0
      serviceVersion: 1.0.0
      images:
        rustfs: {{ .Values.image.registry | default "" }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
