- name: riak-err-notice
  enable: true
  schedule: '@every 1m'
  machine_type:
    - riak
- name: riak-load-health
  enable: true
  schedule: '@every 1m'
  machine_type:
    - riak
- name: riak-ring-status
  enable: true
  schedule: '@every 10s'
  machine_type:
    - riak
- name: riak-db-up
  enable: true
  schedule: '@every 10s'
  machine_type:
    - riak
- name: riak_monitor_heart_beat
  enable: true
  schedule: '@every 10s'
  machine_type:
    - riak
