# Generated by Django 3.2.19 on 2023-11-28 09:39

from django.db import migrations, models

from backend.core.encrypt.constants import AsymmetricCipherConfigType


class Migration(migrations.Migration):

    dependencies = [
        ("encrypt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asymmetriccipherkey",
            name="name",
            field=models.CharField(
                choices=AsymmetricCipherConfigType.get_choices(),
                max_length=128,
                verbose_name="密钥名称",
            ),
        ),
    ]
