# Generated by Django 3.2.19 on 2023-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encrypt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asymmetriccipherkey",
            name="name",
            field=models.CharField(
                choices=[("password", "平台密码的非对称秘钥"), ("proxypass", "透传接口的非对称秘钥"), ("cloud", "云区域服务的非对称秘钥")],
                max_length=128,
                verbose_name="密钥名称",
            ),
        ),
    ]
