{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "db-remote-service.serviceAccountName" . }}
  labels:
    {{- include "db-remote-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "db-remote-service.fullname" . }}-role
rules:
- apiGroups:
  - batch
  - ""
  resources:
  - jobs
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "db-remote-service.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "db-remote-service.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "db-remote-service.serviceAccountName" . }}
  namespace: {{ default "default" .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "db-remote-service.fullname" . }}-cluster-role
rules:
- apiGroups:
  - batch
  - ""
  resources:
  - jobs
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "db-remote-service.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "db-remote-service.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "db-remote-service.serviceAccountName" . }}
  namespace: {{ default "default" .Release.Namespace }}
{{- end }}
