# Generated by Django 3.2.19 on 2023-06-05 12:27

from django.db import migrations, models

from backend.configuration.constants import DBType


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipwhitelist",
            name="db_type",
            field=models.CharField(
                choices=DBType.get_choices(),
                default="mysql",
                max_length=32,
                verbose_name="数据库类型",
            ),
            preserve_default=False,
        )
    ]
