# Generated by Django 3.2.19 on 2023-07-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_auto_20230605_2027"),
        ("configuration", "0002_functioncontroller"),
    ]

    operations = []
