# Generated by Django 3.2.19 on 2023-08-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0003_merge_0002_auto_20230605_2027_0002_functioncontroller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipwhitelist",
            name="db_type",
        ),
    ]
