# Generated by Django 3.2.19 on 2023-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_remove_ipwhitelist_db_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BizSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("type", models.CharField(max_length=64, verbose_name="类型")),
                ("key", models.CharField(max_length=64, unique=True, verbose_name="关键字唯一标识")),
                ("value", models.JSONField(verbose_name="系统设置值")),
                ("desc", models.CharField(max_length=255, verbose_name="描述")),
                ("bk_biz_id", models.IntegerField(help_text="业务ID")),
            ],
            options={
                "verbose_name": "业务配置",
                "verbose_name_plural": "业务配置",
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="bizsettings",
            index=models.Index(fields=["bk_biz_id"], name="configurati_bk_biz__6102bd_idx"),
        ),
    ]
