# Generated by Django 3.2.19 on 2023-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0005_auto_20230907_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizsettings",
            name="key",
            field=models.CharField(max_length=64, verbose_name="关键字唯一标识"),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="key",
            field=models.CharField(max_length=64, verbose_name="关键字唯一标识"),
        ),
        migrations.AlterUniqueTogether(
            name="bizsettings",
            unique_together={("bk_biz_id", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="systemsettings",
            unique_together={("key",)},
        ),
    ]
