# Generated by Django 4.2.27 on 2026-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0008_auto_20231121_2147"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbadministrator",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="dbadministrator",
            name="updater",
            field=models.CharField(default="", max_length=64, verbose_name="修改人"),
        ),
    ]
