# Generated by Django 3.2.25 on 2024-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TbRedisModuleSupport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("major_version", models.CharField(default="", max_length=32, verbose_name="主版本号")),
                ("module_name", models.CharField(default="", max_length=32, verbose_name="module名")),
                ("so_file", models.CharField(default="", max_length=32, verbose_name="so文件名")),
            ],
            options={
                "verbose_name": "Redis module支持",
                "verbose_name_plural": "Redis module支持",
                "db_table": "tb_redis_module_support",
                "unique_together": {("major_version", "module_name", "so_file")},
            },
        ),
    ]
