# Generated by Django 3.2.25 on 2024-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redis_modules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tbredismodulesupport",
            name="create_at",
        ),
        migrations.RemoveField(
            model_name="tbredismodulesupport",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="tbredismodulesupport",
            name="update_at",
        ),
        migrations.RemoveField(
            model_name="tbredismodulesupport",
            name="updater",
        ),
    ]
