{{- if .Values.saas.backendApi.enabled | default .Values.enabled -}}
{{- $fullName := ( include "dbm.backend-api.fullname" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dbm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.saas.backendApi.autoscaling.enabled }}
  replicas: {{ .Values.saas.backendApi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dbm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "{{ $fullName }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dbm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "{{ $fullName }}"
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dbm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - export SERVICE_ONLY=true && gunicorn wsgi -w {{ .Values.saas.backendApi.gunicornWorker }} -b :8000 --access-logfile - --error-logfile - --access-logformat '[%(h)s] %({request_id}i)s %(u)s %(t)s "%(r)s" %(s)s %(D)s %(b)s "%(f)s" "%(a)s"'
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/ping"}}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 5}}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 30}}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 5}}
            successThreshold: {{ .Values.livenessProbe.successThreshold | default 1}}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3}}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/ping"}}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 5}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 30}}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5}}
            successThreshold: {{ .Values.readinessProbe.successThreshold | default 1}}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3}}
          {{- include "dbm.container_env" . | nindent 10 }}
          resources:
            {{- toYaml .Values.saas.backendApi.resources | nindent 12 }}
      {{- include "dbm.initContainersWaitForMigrate" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
