{{- if .Values.enabled -}}
{{- $fullName := ( include "dbm.backend-api.fullname" .) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dbm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dbm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "{{ $fullName }}"
{{- end -}}
