# Generated by Django 3.2.19 on 2023-08-31 07:38

from django.db import migrations, models

from backend.db_meta.enums import ClusterType
from backend.db_services.redis.autofix.enums import AutofixStatus


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedisAutofixCtl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(db_index=True, verbose_name="云区域 ID")),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务 ID")),
                ("ctl_name", models.CharField(max_length=64, verbose_name="模块名")),
                ("ctl_value", models.CharField(max_length=64, verbose_name="取值范围")),
            ],
            options={
                "db_table": "tb_tendis_autofix_ctl",
            },
        ),
        migrations.CreateModel(
            name="RedisIgnoreAutofix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("cluster_id", models.IntegerField(verbose_name="集群ID")),
                (
                    "cluster_type",
                    models.CharField(choices=ClusterType.get_choices(), max_length=64, verbose_name="集群类型"),
                ),
                ("immute_domain", models.CharField(max_length=255, verbose_name="集群域名")),
                ("instance_type", models.CharField(max_length=64, verbose_name="实例类型")),
                ("cluster_ports", models.JSONField(max_length=255, verbose_name="实例列表")),
                ("bk_host_id", models.IntegerField(verbose_name="机器ID")),
                ("ip", models.GenericIPAddressField(verbose_name="机器IP")),
                ("switch_ports", models.JSONField(max_length=255, verbose_name="切换端口")),
                ("sw_min_id", models.IntegerField(verbose_name="切换最小值")),
                ("sw_max_id", models.IntegerField(verbose_name="切换最大值")),
                ("sw_result", models.JSONField(max_length=255, verbose_name="切换结果")),
                ("ignore_msg", models.CharField(max_length=64, verbose_name="忽略类型")),
            ],
            options={
                "db_table": "tb_tendis_autofix_ignore",
            },
        ),
        migrations.CreateModel(
            name="RedisAutofixCore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_cloud_id", models.IntegerField(verbose_name="云区域ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("cluster_id", models.IntegerField(verbose_name="集群ID")),
                (
                    "cluster_type",
                    models.CharField(choices=ClusterType.get_choices(), max_length=64, verbose_name="集群类型"),
                ),
                ("immute_domain", models.CharField(max_length=255, verbose_name="集群主域名")),
                ("fault_machines", models.JSONField(max_length=10000, verbose_name="故障机器")),
                ("ticket_id", models.BigIntegerField(default=-1, verbose_name="单据ID")),
                (
                    "deal_status",
                    models.CharField(choices=AutofixStatus.get_choices(), max_length=64, verbose_name="自愈状态"),
                ),
                ("status_version", models.CharField(max_length=64, verbose_name="状态版本")),
            ],
            options={
                "db_table": "tb_tendis_autofix_core",
                "index_together": {("cluster_id",)},
            },
        ),
    ]
