# Generated by Django 3.2.19 on 2023-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autofix", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redisautofixcore",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("tendbsingle", "tendbsingle"),
                    ("tendbha", "tendbha"),
                    ("tendbcluster", "tendbcluster"),
                    ("redis", "Redis集群"),
                    ("PredixyRedisCluster", "Redis集群"),
                    ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                    ("TwemproxyRedisInstance", "TendisCache集群"),
                    ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                    ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                    ("RedisInstance", "RedisCache主从版"),
                    ("TendisSSDInstance", "TendisSSD主从版"),
                    ("TendisplusInstance", "Tendisplus主从版"),
                    ("RedisCluster", "RedisCluster集群"),
                    ("TendisplusCluster", "TendisplusCluster集群"),
                    ("TendisplusInstance", "Tendisplus存储版集群 GetTendisType 获取redis类型值"),
                    ("RedisInstance", "TendisCache集群 GetTendisType 获取redis类型值"),
                    ("TendisSSDInstance", "TendisSSD集群 GetTendisType 获取redis类型值"),
                    ("es", "ES集群"),
                    ("kafka", "Kafka集群"),
                    ("hdfs", "Hdfs集群"),
                    ("influxdb", "Influxdb实例"),
                    ("pulsar", "Pulsar集群"),
                    ("MongoReplicaSet", "Mongo副本集"),
                    ("MongoShardedCluster", "Mongo分片集群"),
                    ("riak", "Riak集群"),
                ],
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="redisautofixcore",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("initautofix", "初始化"),
                    ("initticket", "创建单据"),
                    ("startflow", "发起flow流程"),
                    ("watchflow", "监控流程完成状态"),
                    ("success", "自愈成功"),
                    ("fail", "自愈失败"),
                ],
                max_length=64,
                verbose_name="自愈状态",
            ),
        ),
        migrations.AlterField(
            model_name="redisautofixcore",
            name="fault_machines",
            field=models.JSONField(max_length=10000, verbose_name="故障机器"),
        ),
        migrations.AlterField(
            model_name="redisautofixcore",
            name="ticket_id",
            field=models.BigIntegerField(default=-1, verbose_name="单据ID"),
        ),
        migrations.AlterField(
            model_name="redisignoreautofix",
            name="cluster_ports",
            field=models.JSONField(max_length=255, verbose_name="实例列表"),
        ),
        migrations.AlterField(
            model_name="redisignoreautofix",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("tendbsingle", "tendbsingle"),
                    ("tendbha", "tendbha"),
                    ("tendbcluster", "tendbcluster"),
                    ("redis", "Redis集群"),
                    ("PredixyRedisCluster", "Redis集群"),
                    ("PredixyTendisplusCluster", "Tendisplus存储版集群"),
                    ("TwemproxyRedisInstance", "TendisCache集群"),
                    ("TwemproxyTendisSSDInstance", "TendisSSD集群"),
                    ("TwemproxyTendisplusInstance", "Tendis存储版集群"),
                    ("RedisInstance", "RedisCache主从版"),
                    ("TendisSSDInstance", "TendisSSD主从版"),
                    ("TendisplusInstance", "Tendisplus主从版"),
                    ("RedisCluster", "RedisCluster集群"),
                    ("TendisplusCluster", "TendisplusCluster集群"),
                    ("TendisplusInstance", "Tendisplus存储版集群 GetTendisType 获取redis类型值"),
                    ("RedisInstance", "TendisCache集群 GetTendisType 获取redis类型值"),
                    ("TendisSSDInstance", "TendisSSD集群 GetTendisType 获取redis类型值"),
                    ("es", "ES集群"),
                    ("kafka", "Kafka集群"),
                    ("hdfs", "Hdfs集群"),
                    ("influxdb", "Influxdb实例"),
                    ("pulsar", "Pulsar集群"),
                    ("MongoReplicaSet", "Mongo副本集"),
                    ("MongoShardedCluster", "Mongo分片集群"),
                    ("riak", "Riak集群"),
                ],
                max_length=64,
                verbose_name="集群类型",
            ),
        ),
        migrations.AlterField(
            model_name="redisignoreautofix",
            name="sw_result",
            field=models.JSONField(max_length=255, verbose_name="切换结果"),
        ),
        migrations.AlterField(
            model_name="redisignoreautofix",
            name="switch_ports",
            field=models.JSONField(max_length=255, verbose_name="切换端口"),
        ),
        migrations.AlterIndexTogether(
            name="redisautofixcore",
            index_together={("cluster_id",)},
        ),
    ]
