# Generated by Django 3.2.25 on 2025-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autofix", "0003_alter_redisignoreautofix_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redisautofixctl",
            name="ctl_value",
            field=models.CharField(max_length=10000, verbose_name="取值范围"),
        ),
    ]
