# Generated by Django 3.2.19 on 2024-01-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autofix", "0003_alter_redisignoreautofix_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="redisautofixcore",
            name="shutdown_ticket_ids",
            field=models.CharField(default=-1, max_length=64, verbose_name="实例下架单据IDs"),
        ),
    ]
