{
 "title": "MySQL慢查询",
 "tags": [
  "tendbsingle",
  "tendbha",
  "tendbcluster",
  "慢查询"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {}
   },
   {
    "name": "cluster_domain",
    "query": {}
   },
   {
    "name": "instance_role",
    "label": "instance_role",
    "query": {}
   },
   {
    "name": "db",
    "label": "db",
    "query": "SELECT distinct db_name from tb_mysql_slow_log\nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo() "
   },
   { "name": "digest", "query": "%" }
  ]
 },
 "panels": [
  {
   "title": "Slow logs for Instance",
   "type": "timeseries",
   "description": "slowlog collected from instance host",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  instance_role,\n  concat(instance_host, \":\", instance_port) as instance,\n  count(*) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nGROUP BY time,instance_role,instance_host,instance_port\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Slow queries (1m_sum)",
   "type": "timeseries",
   "description": "global_status_slow_queries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "mode": "ui",
     "query_configs": [
      {
       "alias": "$tag_instance_role, $tag_instance",
       "data_label": "exporter_dbm_mysqld_exporter",
       "data_source_label": "bk_monitor",
       "data_type_label": "time_series",
       "display": true,
       "filter_dict": {},
       "functions": [
        {
         "id": "increase",
         "params": [
          { "id": "window", "value": "1m" }
         ]
        }
       ],
       "group_by": [
        "instance",
        "instance_role"
       ],
       "interval": 60,
       "interval_unit": "s",
       "method": "SUM",
       "metric_field": "mysql_global_status_slow_queries",
       "refId": "a",
       "result_table_id": "exporter_dbm_mysqld_exporter",
       "result_table_label": "component",
       "time_field": "time",
       "where": [
        { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] }
       ]
      }
     ],
     "type": "range"
    }
   ]
  },
  {
   "title": "count query_digest_md5",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' > ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  count(*) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nGROUP BY time,query_digest_md5\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "sum rows_examined",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' > ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  sum(rows_examined) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nGROUP BY time,query_digest_md5\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "sum query_time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' > ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  sum(query_time) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nGROUP BY time,query_digest_md5\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Slow query logs detail [$instance_role]: limit 1000",
   "type": "table",
   "description": "按  db 过滤：db_name: \"xxx\"",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "bk_dbm_stats",
     "rawSql": "SELECT dteventtimestamp,query_time,rows_examined,rows_sent,username,\n db_name,query_digest_md5, query_digest_text, query_string,\n instance_host,instance_port,instance_role,client_host,session_id,query_command,table_names\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nAND query_digest_md5 like '$digest'\nORDER BY sql_timestamp DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Analysis [$instance_role]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count by sql digest",
     "type": "timeseries",
     "description": "慢查询 sql 模式统计 - count",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "dataset": "__internal_schema",
       "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' (', db_name, ')> ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  count(*) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nAND query_digest_md5 like '$digest'\nGROUP BY time,query_digest_md5,db_name\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Rows_scaned by sql digest (1m_max)",
     "type": "timeseries",
     "description": "慢查询 sql 模式统计 - rows_examined_max",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "__internal_schema",
       "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' (', db_name, ')> ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  max(rows_examined) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nAND query_digest_md5 like '$digest'\nGROUP BY time,query_digest_md5,db_name\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Rows_scaned by sql digest (1m_sum)",
     "type": "timeseries",
     "description": "慢查询 sql 模式统计 - rows_examined_sum",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "__internal_schema",
       "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' (', db_name, ')> ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  sum(rows_examined) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nAND query_digest_md5 like '$digest'\nGROUP BY time,query_digest_md5,db_name\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Rows_sent by sql digest (1m_sum)",
     "type": "timeseries",
     "description": "慢查询 sql 模式统计 - rows_sent_sum",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "__internal_schema",
       "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' (', db_name, ')> ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  sum(rows_sent) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nAND query_digest_md5 like '$digest'\nGROUP BY time,query_digest_md5,db_name\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Query_time by sql digest (1m_max)",
     "type": "timeseries",
     "description": "慢查询 sql 模式统计 - query_time_max",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dataset": "__internal_schema",
       "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  CONCAT(query_digest_md5, ' (', db_name, ')> ', LEFT(ANY_VALUE(query_digest_text), 60)) as metric,\n  max(query_time) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nAND query_digest_md5 like '$digest'\nGROUP BY time,query_digest_md5,db_name\nORDER BY time ASC"
      }
     ]
    },
    {
     "title": "SQL count distributed by db.table",
     "type": "timeseries",
     "description": "慢查询库表分布",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "dataset": "__internal_schema",
       "rawSql": "SELECT \n  sql_timestamp div 60 * 60 as time,\n  table_names as metric,\n  count(*) as value\nFROM tb_mysql_slow_log \nWHERE cluster_domain = '$cluster_domain'\nAND instance_role = '$instance_role'\nAND sql_timestamp >= $__unixEpochFrom() and sql_timestamp <= $__unixEpochTo()\nAND db_name like $db\nGROUP BY time,table_names\nORDER BY time ASC"
      }
     ]
    }
   ]
  }
 ]
}