{
 "title": "TenDBCluster Table Detail",
 "tags": [
  "tendbcluster",
  "表容量视图"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "cluster_domain",
    "label": "cluster_domain",
    "query": {}
   },
   {
    "name": "dbname",
    "label": "dbname",
    "query": "select distinct database_name \nfrom mysql_db_table_size \nwhere cluster_domain = '$cluster_domain' and \ndteventtimestamp > (UNIX_TIMESTAMP(now())-86400*2)*1000"
   },
   {
    "name": "tbname",
    "label": "tbname",
    "query": "select distinct table_name \nfrom mysql_db_table_size \nwhere cluster_domain = '$cluster_domain' and \n  database_name = '$dbname' and\n  dteventtimestamp > (UNIX_TIMESTAMP(now())-86400*2)*1000 \n"
   },
   { "name": "statsDbName", "query": "bk_dbm_stats" }
  ]
 },
 "panels": [
  { "title": "Table=$tbname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Table Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "bk_dbm_stats",
     "rawSql": "SELECT $__time(dteventtimehour), concat(database_name,\".\", table_name) as metric ,value\nFROM\n(\n  SELECT\n    dteventtimehour,database_name, table_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour,database_name, table_name, sum(table_size_max) as value \n    FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        table_name,\n        MAX(table_size) table_size_max \n      FROM mysql_db_table_size \n      WHERE cluster_domain = '$cluster_domain' AND \n        database_name = '$dbname' AND\n        table_name in (${tbname:sqlstring}) AND\n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,table_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name,table_name\n  ) as tt\n) ttt\nORDER BY dteventtimehour"
    }
   ]
  },
  {
   "title": "Database=$dbname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Size Top20 for db=$dbname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour), concat(database_name,\".\", table_name) as metric,value\nFROM\n(\n  SELECT\n    dteventtimehour,database_name, table_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour, database_name, table_name, sum(table_size_max) as value \n    FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        table_name,\n        MAX(table_size) table_size_max \n      FROM mysql_db_table_size \n      WHERE cluster_domain = '$cluster_domain' AND \n        database_name = '$dbname' AND\n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,table_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name,table_name\n  ) as tt\n) ttt\nWHERE ranking <=10\nORDER BY dteventtimehour"
      },
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT dteventtimehour, \"_OTHER._OTHER\" as metric, sum(value) as \"_OTHER._OTHER\"\nFROM\n(\n  SELECT\n    dteventtimehour,database_name, table_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n     dteventtimehour,database_name, table_name, sum(table_size_max) as value \n    FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        table_name,\n        MAX(table_size) table_size_max \n      FROM mysql_db_table_size\n      WHERE cluster_domain = '$cluster_domain' AND \n        database_name = '$dbname' AND\n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,table_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name,table_name\n  ) as tt\n) ttt\nWHERE ranking >10\nGROUP BY dteventtimehour"
      }
     ]
    },
    {
     "title": "Table Size for db=$dbname",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour), concat(database_name,\".\", table_name) as metric,value\nFROM\n(\n  SELECT\n    dteventtimehour,database_name, table_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour,database_name, table_name, sum(table_size_max) as value \n    FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        table_name,\n        MAX(table_size) table_size_max \n      FROM mysql_db_table_size\n      WHERE cluster_domain = '$cluster_domain' AND \n        database_name = '$dbname' AND\n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,table_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name,table_name\n  ) as tt\n) ttt\nORDER BY dteventtimehour"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datadir Used du",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "mode": "code",
       "query_configs": [
        {
         "alias": "",
         "data_label": "exporter_dbm_mysqld_exporter",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "cluster_domain" ],
         "interval": 7200,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "mysql_datadir_du_used_mb",
         "refId": "a",
         "result_table_id": "exporter_dbm_mysqld_exporter",
         "result_table_label": "component",
         "time_field": "time",
         "where": [
          { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] },
          { "condition": "and", "key": "instance_role", "method": "eq", "value": [ "remote_master" ] }
         ]
        }
       ],
       "source": "sum by (cluster_domain) (avg by (cluster_domain,instance)(avg_over_time(bkmonitor:exporter_dbm_mysqld_exporter:mysql_datadir_du_used_mb{cluster_domain=\"$cluster_domain\",instance_role=\"remote_master\"}[121m])))",
       "type": "range"
      }
     ]
    },
    {
     "title": "Datadir Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "mode": "ui",
       "query_configs": [
        {
         "alias": "",
         "data_label": "exporter_dbm_mysqld_exporter",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [],
         "interval": "auto",
         "interval_unit": "s",
         "method": "MAX",
         "metric_field": "mysql_datadir_df_usage",
         "refId": "a",
         "result_table_id": "exporter_dbm_mysqld_exporter",
         "result_table_label": "component",
         "time_field": "time",
         "where": [
          { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] },
          { "condition": "and", "key": "instance_role", "method": "eq", "value": [ "remote_master" ] }
         ]
        }
       ],
       "type": "range"
      }
     ]
    },
    {
     "title": "Database Size Top20 (ibd)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 9, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour), database_name as metric, value\nFROM\n(\n  SELECT\n    dteventtimehour,database_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour,database_name,sum(database_size_max) as value FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        MAX(database_size) database_size_max \n      FROM mysql_db_table_size \n      WHERE cluster_domain = '$cluster_domain' AND \n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name\n  ) tt\n) ttt\nWHERE ranking <=20\nORDER BY dteventtimehour"
      },
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour), \"_OTHER\" as metric, sum(value) as \"_OTHER\"\nFROM\n(\n  SELECT\n    dteventtimehour,database_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour,database_name,sum(database_size_max) as value FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        MAX(database_size) database_size_max \n      FROM mysql_db_table_size \n      WHERE cluster_domain = '$cluster_domain' AND \n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name\n  ) tt\n) ttt\nWHERE ranking >20\nGROUP BY dteventtimehour"
      }
     ]
    },
    {
     "title": "Database Size (ibd)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour),database_name as metric,sum(database_size_max) as value FROM\n(\n  SELECT \n    dteventtimehour, \n    database_name,\n    original_database_name,\n    MAX(database_size) database_size_max \n  FROM mysql_db_table_size \n  WHERE cluster_domain = '$cluster_domain' AND \n    $__timeFilter(dteventtimehour)\n  GROUP BY database_name,original_database_name,dteventtimehour\n) as t\nGROUP BY dteventtimehour,database_name\nORDER BY dteventtimehour asc"
      }
     ]
    },
    {
     "title": "Disk Size Used",
     "type": "timeseries",
     "description": "磁盘空间使用率",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
     "targets": [
      {
       "mode": "ui",
       "query_configs": [
        {
         "alias": "$tag_bk_target_ip, $tag_mount_point",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [
          "mount_point",
          "bk_target_ip"
         ],
         "interval": "auto",
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "used",
         "refId": "a",
         "result_table_id": "dbm_system.disk",
         "result_table_label": "os",
         "time_field": "time",
         "where": [
          { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] },
          { "condition": "and", "key": "instance_role", "method": "eq", "value": [ "remote_master" ] }
         ]
        }
       ],
       "type": "range"
      }
     ]
    },
    {
     "title": "Table Size Top20 (ibd)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour),concat(database_name,\".\", table_name) as metric,value\nFROM\n(\n  SELECT\n    dteventtimehour,database_name, table_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour,database_name, table_name, sum(table_size_max) as value \n    FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        table_name,\n        MAX(table_size) table_size_max \n      FROM mysql_db_table_size \n      WHERE cluster_domain = '$cluster_domain' AND \n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,table_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name,table_name\n  ) as tt\n) ttt\nWHERE ranking <=20\nORDER BY dteventtimehour"
      },
      {
       "dataset": "bk_dbm_stats",
       "rawSql": "SELECT $__time(dteventtimehour),\"_OTHER._OTHER\" as metric, sum(value) as \"_OTHER._OTHER\"\nFROM\n(\n  SELECT\n    dteventtimehour,database_name, table_name,value,\n    dense_rank() over (partition by dteventtimehour order by value desc) as ranking\n  FROM\n  (\n    SELECT \n      dteventtimehour,database_name, table_name, sum(table_size_max) as value \n    FROM\n    (\n      SELECT \n        dteventtimehour, \n        database_name,\n        original_database_name,\n        table_name,\n        MAX(table_size) table_size_max \n      FROM mysql_db_table_size \n      WHERE cluster_domain = '$cluster_domain' AND \n        $__timeFilter(dteventtimehour)\n      GROUP BY database_name,original_database_name,table_name,dteventtimehour\n    ) as t\n    GROUP BY dteventtimehour,database_name,table_name\n  ) as tt\n) ttt\nWHERE ranking >20\nGROUP BY dteventtimehour"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster by shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "datadir Size by Shard Instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "mode": "ui",
       "query_configs": [
        {
         "alias": "$tag_instance,$tag_path",
         "data_label": "exporter_dbm_mysqld_exporter",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [
          "path",
          "instance"
         ],
         "interval": 7200,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "mysql_datadir_du_used_mb",
         "refId": "a",
         "result_table_id": "exporter_dbm_mysqld_exporter",
         "result_table_label": "component",
         "time_field": "time",
         "where": [
          { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] },
          { "condition": "and", "key": "instance_role", "method": "eq", "value": [ "remote_master" ] }
         ]
        }
       ],
       "type": "range"
      }
     ]
    },
    {
     "title": "Datadir size for df partition",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "mode": "ui",
       "query_configs": [
        {
         "alias": "used $tag_instance_host $tag_mount_point",
         "data_label": "exporter_dbm_mysqld_exporter",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [
          "mount_point",
          "instance_host"
         ],
         "interval": 7200,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "mysql_datadir_df_used_mb",
         "refId": "a",
         "result_table_id": "exporter_dbm_mysqld_exporter",
         "result_table_label": "component",
         "time_field": "time",
         "where": [
          { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] },
          { "condition": "and", "key": "instance_role", "method": "eq", "value": [ "remote_master" ] }
         ]
        },
        {
         "alias": "total $tag_instance_host $tag_mount_point",
         "data_label": "exporter_dbm_mysqld_exporter",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [
          "mount_point",
          "instance_host"
         ],
         "interval": 7200,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "mysql_datadir_df_total_mb",
         "refId": "b",
         "result_table_id": "exporter_dbm_mysqld_exporter",
         "result_table_label": "component",
         "time_field": "time",
         "where": [
          { "key": "cluster_domain", "method": "eq", "value": [ "$cluster_domain" ] },
          { "condition": "and", "key": "instance_role", "method": "eq", "value": [ "remote_master" ] }
         ]
        }
       ],
       "type": "range"
      }
     ]
    }
   ]
  }
 ]
}