# Generated by Django 3.2.19 on 2024-03-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TbTendisMaxmemoryBackends",
            fields=[
                (
                    "cluster_domain",
                    models.CharField(
                        default="", max_length=255, primary_key=True, serialize=False, verbose_name="集群域名"
                    ),
                ),
                ("backends", models.TextField(default="", verbose_name="backends")),
                ("update_time", models.DateTimeField(verbose_name="更新时间")),
            ],
            options={
                "db_table": "tb_tendis_maxmemory_backends",
            },
        ),
        migrations.AddIndex(
            model_name="tbtendismaxmemorybackends",
            index=models.Index(fields=["update_time"], name="idx_maxmemory_update_time"),
        ),
    ]
