# Generated by Django 3.2.25 on 2024-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maxmemory_set", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TbTendisMaxmemoryConfig",
            fields=[
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("bk_biz_id_blacklist", "bk_biz_id黑名单"),
                            ("cluster_id_blacklist", "cluster_id黑名单"),
                            ("used_memory_change_threshold", "used_memory变更阈值"),
                            ("used_memory_change_percent", "used_memory变更百分比"),
                        ],
                        default="",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="配置类型",
                    ),
                ),
                ("config_data", models.TextField(default="", verbose_name="配置数据")),
            ],
            options={
                "verbose_name": "redis maxmemory配置",
                "db_table": "tb_tendis_maxmemory_config",
            },
        ),
    ]
