SET names utf8;
CREATE TABLE IF NOT EXISTS `tb_request_log` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `request_id` varchar(64) NOT NULL,
    `request_user` varchar(32) NOT NULL,
    `request_body` json DEFAULT NULL,
    `request_url` varchar(32) NOT NULL,
    `source_ip` varchar(32) NOT NULL,
    `respone_body` json DEFAULT NULL,
    `respone_code` int(11) NOT NULL,
    `respone_messsage` text,
    `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `request_id` (`request_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE IF NOT EXISTS `tb_rp_apply_detail_log` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `request_id` varchar(64) NOT NULL,
    `item` varchar(64) NOT NULL,
    `bk_cloud_id` int(11) NOT NULL COMMENT '云区域 ID',
    `ip` varchar(20) NOT NULL,
    `bk_host_id` int(11) NOT NULL COMMENT 'bk主机ID',
    `update_time` timestamp NULL DEFAULT NULL,
    `create_time` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_request_id` (`request_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE IF NOT EXISTS `tb_rp_detail` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `bk_cloud_id` int(11) NOT NULL COMMENT '云区域 ID',
    `bk_biz_id` int(11) NOT NULL COMMENT '机器当前所属业务',
    `dedicated_biz` int(11) DEFAULT '0' COMMENT '专属业务',
    `rs_type` varchar(64) DEFAULT 'PUBLIC' COMMENT '资源专用组件类型',
    `bk_host_id` int(11) NOT NULL COMMENT 'bk主机ID',
    `ip` varchar(20) NOT NULL,
    `asset_id` varchar(64) NOT NULL COMMENT '固定资产编号',
    `device_class` varchar(64) NOT NULL,
    `svr_type_name` varchar(64) NOT NULL COMMENT '服务器型号,判断是否是云机器',
    `cpu_num` int(11) NOT NULL COMMENT 'cpu核数',
    `dram_cap` int(11) NOT NULL COMMENT '内存大小',
    `storage_device` json DEFAULT NULL COMMENT '磁盘设备',
    `total_storage_cap` int(11) DEFAULT NULL COMMENT '磁盘总容量',
    `raid` varchar(20) NOT NULL,
    `city_id` varchar(64) NOT NULL,
    `city` varchar(128) NOT NULL,
    `sub_zone` varchar(32) NOT NULL,
    `sub_zone_id` varchar(64) NOT NULL,
    `rack_id` varchar(64) NOT NULL,
    `net_device_id` varchar(128) DEFAULT NULL,
    `label` json DEFAULT NULL,
    `is_init` int(11) DEFAULT NULL COMMENT '是否初始化过',
    `is_idle` int(11) DEFAULT NULL COMMENT '是否空闲检查过',
    `status` varchar(20) NOT NULL,
    `bk_agent_id` varchar(64) NOT NULL,
    `gse_agent_status_code` int(11) NOT NULL,
    `agent_status_update_time` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01',
    `consume_time` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01',
    `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `os_type` varchar(32) NOT NULL COMMENT '操作系统类型',
    `os_bit` varchar(32) NOT NULL COMMENT '操作系统位数',
    `os_version` varchar(64) NOT NULL COMMENT '操作系统版本',
    `os_name` varchar(64) NOT NULL COMMENT '操作系统名称',
    PRIMARY KEY (`id`),
    UNIQUE KEY `ip` (`bk_cloud_id`, `ip`),
    KEY `idx_host_id` (`bk_host_id`),
    KEY `idx_bk_agent_id` (`bk_agent_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE IF NOT EXISTS `tb_rp_detail_archive` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `bk_cloud_id` int(11) NOT NULL COMMENT '云区域 ID',
    `bk_biz_id` int(11) NOT NULL COMMENT '机器当前所属业务',
    `dedicated_biz` int(11) DEFAULT '0' COMMENT '专属业务',
    `rs_type` varchar(64) DEFAULT 'PUBLIC' COMMENT '资源专用组件类型',
    `bk_host_id` int(11) NOT NULL COMMENT 'bk主机ID',
    `ip` varchar(20) NOT NULL,
    `asset_id` varchar(64) NOT NULL COMMENT '固定资产编号',
    `device_class` varchar(64) NOT NULL,
    `svr_type_name` varchar(64) NOT NULL COMMENT '服务器型号,判断是否是云机器',
    `cpu_num` int(11) NOT NULL COMMENT 'cpu核数',
    `dram_cap` int(11) NOT NULL COMMENT '内存大小',
    `storage_device` json DEFAULT NULL COMMENT '磁盘设备',
    `total_storage_cap` int(11) DEFAULT NULL COMMENT '磁盘总容量',
    `os_type` varchar(32) NOT NULL COMMENT '操作系统类型',
    `os_bit` varchar(32) NOT NULL COMMENT '操作系统位数',
    `os_version` varchar(64) NOT NULL COMMENT '操作系统版本',
    `raid` varchar(20) NOT NULL,
    `city_id` varchar(64) NOT NULL,
    `city` varchar(128) NOT NULL,
    `sub_zone` varchar(32) NOT NULL,
    `sub_zone_id` varchar(64) NOT NULL,
    `rack_id` varchar(64) NOT NULL,
    `net_device_id` varchar(128) DEFAULT NULL,
    `label` json DEFAULT NULL,
    `is_init` int(11) DEFAULT NULL COMMENT '是否初始化过',
    `is_idle` int(11) DEFAULT NULL COMMENT '是否空闲检查过',
    `status` varchar(20) NOT NULL,
    `bk_agent_id` varchar(64) NOT NULL,
    `gse_agent_status_code` int(11) NOT NULL,
    `agent_status_update_time` timestamp NULL DEFAULT '1970-01-01 08:00:01',
    `consume_time` timestamp NULL DEFAULT '1970-01-01 08:00:01',
    `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `os_name` varchar(64) NOT NULL COMMENT '操作系统名称',
    PRIMARY KEY (`id`),
    KEY `idx_bk_agent_id` (`bk_agent_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE IF NOT EXISTS `tb_rp_operation_info` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `request_id` varchar(64) NOT NULL,
    `total_count` int(11) DEFAULT NULL COMMENT 'task Id',
    `bk_host_ids` json DEFAULT NULL COMMENT '主机Id',
    `ip_list` json DEFAULT NULL COMMENT '主机ip',
    `operation_type` varchar(64) NOT NULL COMMENT 'operation type',
    `operator` varchar(64) NOT NULL COMMENT 'operator user',
    `status` varchar(64) NOT NULL COMMENT ' status',
    `task_id` varchar(128) NOT NULL COMMENT 'task Id',
    `bill_id` varchar(128) NOT NULL COMMENT 'bill Id',
    `bill_type` varchar(128) NOT NULL COMMENT 'bill type',
    `description` varchar(256) DEFAULT '' COMMENT 'description',
    `update_time` timestamp NULL DEFAULT NULL,
    `create_time` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_request_id` (`request_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;