# Generated by Django 3.2.19 on 2023-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dumper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dumpersubscribeconfig",
            name="dumper_process_ids",
            field=models.JSONField(blank=True, default=list, help_text="订阅配置关联的订阅实例列表", null=True),
        ),
    ]
