swagger: '2.0'
basePath: /
info:
  version: '0.1'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /mysql/bizs/{bk_biz_id}/cluster/query_clusters/:
    post:
      operationId: query_clusters
      description: ''
      tags:
      - Spider
      - Cluster
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /apis/mysql/bizs/{bk_biz_id}/cluster/query_clusters/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /mysql/bizs/{bk_biz_id}/spider_resources/:
    get:
      operationId: list_spider_resource
      description: 查询spider集群列表
      tags:
      - Spider
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /apis/mysql/bizs/{bk_biz_id}/spider_resources/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: true
        disabledStages: []
        descriptionEn:
  /tickets/:
    post:
      operationId: create_ticket
      description: 创建单据
      tags:
      - Ticket
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /apis/tickets/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
