{{- if and .Values.global.serviceMonitor.enabled .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dbconfig.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbconfig.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dbconfig.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - interval: 30s
      params: {}
      path: /metrics
      port: http
{{- end -}}