go test -v -run TestComponentDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonCategoryDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonHelmRepoDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonTopologyDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonTypeDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonClusterHelmRepoDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonClusterReleaseDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonClusterVersionDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterOperationDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestOperationDefinitionDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestK8sClusterConfigDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterRequestDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterServiceDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterTagDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestComponentOperationDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestK8sClusterAddonsDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestOpsrequestDbAccessTestSuite ./k8s-dbs/metadata/dbaccess/testsuite/