go test -v -run TestComponentDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonCategoryDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonHelmRepoDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonTopologyDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonTypeDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonClusterHelmRepoDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonClusterReleaseDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestAddonClusterVersionDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterOperationDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestOperationDefinitionDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestK8sClusterConfigDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterRequestDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterServiceDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestClusterTagDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestComponentOperationDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestK8sClusterAddonsDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/
go test -v -run TestOpsRequestDbAccess ./k8s-dbs/metadata/dbaccess/testsuite/