# Generated by Django 3.2.4 on 2023-04-18 11:32

from django.db import migrations, models

import backend.flow.consts
import backend.ticket.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlowTree",
            fields=[
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("uid", models.CharField(blank=True, db_index=True, max_length=127, null=True, verbose_name="单据ID")),
                (
                    "ticket_type",
                    models.CharField(
                        choices=backend.ticket.constants.TicketType.get_choices(),
                        max_length=64,
                        verbose_name="单据类型",
                    ),
                ),
                ("root_id", models.CharField(max_length=33, primary_key=True, serialize=False, verbose_name="流程ID")),
                ("tree", models.JSONField(blank=True, null=True, verbose_name="流程树")),
                (
                    "status",
                    models.CharField(
                        choices=backend.flow.consts.StateType.get_choices(),
                        default="CREATED",
                        max_length=20,
                        verbose_name="流程状态",
                    ),
                ),
                ("created_by", models.CharField(max_length=20, null=True, verbose_name="流程创建人")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="启动时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="流程结束时间")),
            ],
            options={
                "db_table": "flow_tree",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FlowNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(blank=True, max_length=127, null=True, verbose_name="单据ID")),
                ("root_id", models.CharField(max_length=33, verbose_name="流程ID")),
                ("node_id", models.CharField(max_length=33, verbose_name="节点ID")),
                ("version_id", models.CharField(blank=True, max_length=33, verbose_name="当前版本ID")),
                (
                    "status",
                    models.CharField(
                        choices=backend.flow.consts.StateType.get_choices(),
                        default="CREATED",
                        max_length=20,
                        verbose_name="节点状态",
                    ),
                ),
                ("hosts", models.JSONField(blank=True, default=list, null=True, verbose_name="节点运行时IP")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始执行时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "db_table": "flow_node",
                "unique_together": {("root_id", "node_id", "version_id")},
            },
        ),
    ]
