# Generated by Django 3.2.19 on 2024-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flownode",
            name="is_expired",
            field=models.BooleanField(default=False, help_text="运行时被定期清理即为过期", verbose_name="是否已经过期"),
        ),
        migrations.AddField(
            model_name="flowtree",
            name="is_expired",
            field=models.BooleanField(default=False, help_text="运行时被定期清理即为过期", verbose_name="是否已经过期"),
        ),
    ]
