# Generated by Django 3.2.25 on 2025-06-24 12:36

from django.db import migrations, models

from backend.flow.consts import FlowNodeOperateType


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0004_alter_flowtree_index_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowNodeOperateRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_id", models.CharField(max_length=33, verbose_name="流程ID")),
                ("node_id", models.CharField(max_length=33, verbose_name="节点ID")),
                ("version_id", models.CharField(blank=True, max_length=33, verbose_name="版本ID")),
                ("operator", models.CharField(max_length=128, verbose_name="操作人")),
                (
                    "operate_type",
                    models.CharField(choices=FlowNodeOperateType.get_choices(), max_length=64, verbose_name="操作类型"),
                ),
                ("operate_date", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
            ],
            options={
                "db_table": "flow_node_operate_record",
            },
        ),
        migrations.AddIndex(
            model_name="flownodeoperaterecord",
            index=models.Index(fields=["root_id"], name="flow_node_o_root_id_c98249_idx"),
        ),
        migrations.AddIndex(
            model_name="flownodeoperaterecord",
            index=models.Index(fields=["node_id"], name="flow_node_o_node_id_26590f_idx"),
        ),
    ]
