# Generated by Django 4.2.27 on 2026-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_auto_20250624_2036"),
    ]

    operations = [
        migrations.AddField(
            model_name="flownodeoperaterecord",
            name="remark",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="备注"),
        ),
    ]
