# Generated by Django 4.2.27 on 2026-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0005_auto_20250624_2036"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowWithAITaskGuardianReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.CharField(blank=True, max_length=127, null=True, verbose_name="单据ID")),
                ("root_id", models.CharField(max_length=33, verbose_name="流程ID")),
                (
                    "enable_converge",
                    models.BooleanField(default=True, help_text="默认启用，设为False则每次有风险都推送", verbose_name="是否启用消息收敛"),
                ),
                ("send_count", models.IntegerField(default=0, verbose_name="已推送次数")),
                ("last_send_time", models.DateTimeField(blank=True, null=True, verbose_name="最后一次推送时间")),
                (
                    "last_risk_level",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="最后一次推送的风险等级"),
                ),
                (
                    "last_report_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="存储上一次推送的完整风险报告，用于与本次报告进行AI语义比对，判断是否为同一风险",
                        verbose_name="最后一次推送的风险报告内容",
                    ),
                ),
                (
                    "no_risk_streak",
                    models.IntegerField(default=0, help_text="连续N次检测无风险后重置退避计数器", verbose_name="连续无风险检测次数"),
                ),
            ],
            options={
                "db_table": "flow_with_ai_task_guardian_report",
                "unique_together": {("uid", "root_id")},
            },
        ),
    ]
