# Generated by Django 4.2.27 on 2026-03-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0006_flowwithaitaskguardianreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowwithaitaskguardianreport",
            name="uid",
            field=models.CharField(blank=True, default="", max_length=127, verbose_name="单据ID"),
        ),
    ]
