# Generated by Django 4.2.27 on 2026-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0008_flownodeoperaterecord_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowBkJobInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticket_id", models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="单据ID")),
                ("root_id", models.CharField(db_index=True, max_length=33, verbose_name="流程任务ID")),
                ("job_instance_id", models.BigIntegerField(db_index=True, verbose_name="蓝鲸作业实例ID")),
                (
                    "step_instance_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="可选，尽力从任务返回或 job 状态接口解析",
                        null=True,
                        verbose_name="蓝鲸步骤实例ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=33, verbose_name="节点ID")),
                ("version_id", models.CharField(blank=True, default="", max_length=33, verbose_name="版本ID")),
                ("node_name", models.CharField(blank=True, default="", max_length=64, verbose_name="节点名称")),
                ("component_code", models.CharField(blank=True, default="", max_length=64, verbose_name="组件代码")),
                (
                    "cluster_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, help_text="可选，仅当上下文中能确定集群主键时写入", null=True, verbose_name="集群ID"
                    ),
                ),
                (
                    "exec_ips",
                    models.JSONField(
                        blank=True,
                        help_text="可选，与节点实际下发的 exec_ip 一致，可能为 IP 字符串或含 ip/bk_cloud_id 的字典列表",
                        null=True,
                        verbose_name="执行目标IP",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "db_table": "flow_bk_job_instance",
                "indexes": [models.Index(fields=["root_id", "node_id", "version_id"], name="flow_bk_jobinst_rnv_idx")],
            },
        ),
    ]
