# Generated by Django 4.2.27 on 2026-05-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0009_flowbkjobinstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowExecIpRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticket_id", models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="单据ID")),
                ("root_id", models.CharField(db_index=True, max_length=33, verbose_name="流程任务ID")),
                ("bk_cloud_id", models.IntegerField(default=0, verbose_name="云区域ID")),
                ("ip", models.CharField(max_length=64, verbose_name="执行目标IP")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "db_table": "flow_exec_ip_record",
                "indexes": [
                    models.Index(fields=["bk_cloud_id", "ip"], name="flow_exec_ip_cloud_ip_idx"),
                    models.Index(fields=["ip", "ticket_id"], name="flow_exec_ip_ip_ticket_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="flowexeciprecord",
            constraint=models.UniqueConstraint(fields=("bk_cloud_id", "ip", "root_id"), name="flow_exec_ip_uniq"),
        ),
    ]
