# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flow", "0009_flowbkjobinstance"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisClusterShutdownMetaSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bk_biz_id", models.IntegerField(verbose_name="业务ID")),
                ("cluster_id", models.IntegerField(db_index=True, verbose_name="集群ID")),
                ("cluster_name", models.CharField(blank=True, default="", max_length=64, verbose_name="集群名称")),
                ("domain_name", models.CharField(blank=True, default="", max_length=255, verbose_name="域名")),
                ("port", models.IntegerField(blank=True, null=True, verbose_name="访问端口")),
                ("cluster_type", models.CharField(blank=True, default="", max_length=64, verbose_name="架构类型")),
                ("db_version", models.CharField(blank=True, default="", max_length=64, verbose_name="版本")),
                ("region", models.CharField(blank=True, default="", max_length=128, verbose_name="地区")),
                ("proxy_password", models.CharField(blank=True, default="", max_length=255, verbose_name="Proxy密码")),
                ("redis_password", models.CharField(blank=True, default="", max_length=255, verbose_name="Redis密码")),
                ("proxies", models.JSONField(blank=True, default=list, verbose_name="Proxy列表")),
                ("master_slave_pairs", models.JSONField(blank=True, default=list, verbose_name="主从关系及分片")),
                ("spec_config", models.JSONField(blank=True, default=list, verbose_name="规格")),
                ("root_id", models.CharField(blank=True, default="", max_length=33, verbose_name="流程ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "db_table": "flow_redis_cluster_shutdown_meta_snapshot",
                "indexes": [
                    models.Index(fields=["cluster_id"], name="flow_redis_meta_cluster_idx"),
                    models.Index(fields=["bk_biz_id"], name="flow_redis_meta_bizid_idx"),
                ],
            },
        ),
    ]
