## busybox，集合了常用的linux工具箱
FROM busybox:latest

ENV DOWNLOAD_URL=https://github.com/TencentBlueKing/blueking-dbm/releases/download
ENV VERSION=v1.0.0

## 获取二进制介质，将静态介质存放到/data目录
RUN set -ex && \
    mkdir /data && cd /data && \
    wget -qO hdfspack-2.6.0-cdh5.4.11-tendataV0.2.tar.gz ${DOWNLOAD_URL}/${VERSION}/hdfspack-2.6.0-cdh5.4.11-tendataV0.2.tar.gz --no-check-certificate  && \
    wget -qO dbm_hdfs_exporter.tgz ${DOWNLOAD_URL}/${VERSION}/dbm_hdfs_exporter.tgz --no-check-certificate

## 将install的文件移动到/install/xxx，这样通过挂载/install可以共享文件
ENTRYPOINT ["/bin/sh", "-c", "mkdir -p /install/hdfs && mv /data/* /install/hdfs/"]
