## busybox，集合了常用的linux工具箱
FROM busybox:latest

ENV DOWNLOAD_URL=https://github.com/TencentBlueKing/blueking-dbm/releases/download
ENV VERSION=v1.0.0

## 获取二进制介质，将静态介质存放到/data目录
RUN set -ex && \
    mkdir /data && cd /data && \
    wget -qO dbm_mysqld_exporter.tgz ${DOWNLOAD_URL}/${VERSION}/dbm_mysqld_exporter.tgz --no-check-certificate  && \
    wget -qO dbm_mysqlproxy_exporter.tgz ${DOWNLOAD_URL}/${VERSION}/dbm_mysqlproxy_exporter.tgz --no-check-certificate  && \
    wget -qO dbm_tbinlogdumper_exporter.tgz ${DOWNLOAD_URL}/${VERSION}/dbm_tbinlogdumper_exporter.tgz --no-check-certificate  && \
    wget -qO mysql-5.7.20-linux-x86_64-tmysql-3.3-gcs.tar.gz ${DOWNLOAD_URL}/${VERSION}/mysql-5.7.20-linux-x86_64-tmysql-3.3-gcs.tar.gz --no-check-certificate  && \
    wget -qO mysql-8.0.32-linux-glibc2.12-x86_64.tar.xz ${DOWNLOAD_URL}/${VERSION}/mysql-8.0.32-linux-glibc2.12-x86_64.tar.xz --no-check-certificate && \
    wget -qO mysql-proxy-0.82.15.tar.gz ${DOWNLOAD_URL}/${VERSION}/mysql-proxy-0.82.15.tar.gz --no-check-certificate


## 将install的文件移动到/mysql-install，这样通过挂载/mysql-install可以共享文件
ENTRYPOINT ["/bin/sh", "-c", "mkdir -p /install/mysql && mv /data/* /install/mysql/"]
