name: analysis
version: v2.0.0

service:
  listen_address: 127.0.0.1:22223

discovery:
  endpoints: http://127.0.0.1:2379;http://127.0.0.2:2379
  user: root
  password: 1234567890

log:
  path: /var/log/dbha/analysis.log
  level: debug
  file_count: 10
  file_size: 100
