name: analysis
version: v2.0.0

discovery:
  endpoints: http://127.0.0.1:2379;http://127.0.0.2:2379
  user: root
  password: 1234567890

workflow:
  # -1 is unlimited
  #  0 is autocomputed
  workerBusinessCount: 0
  lockBusinessWaitTimeout: 5s
  scanTimeout: 60s
  scanInterval: 3s

notifier:
  enable: true
  endpoints: 127.0.0.1:9090

metacache:
  endpoints: 127.0.0.1:3306
  user: root
  password: 123456

dbhadata:
  endpoints: 127.0.0.1:3306
  user: root
  password: 123456

log:
  path: /var/log/dbha/analysis.log
  level: debug
  fileCount: 10
  fileSize: 100
