name: probe
version: v2.0.0

admin:
  endpoints: 127.0.0.1:22222,127.0.0.2:222222
  syncInterval: 10

receiver:
  endpoints: 127.0.0.1:22223,127.0.0.2:22224
  syncInterval: 10

harvester:
  - name: mysql
    reportInterval: 20
    instances:
    - host: 127.0.0.1
      port: 3306
      user: root
      password: 123456 
      name: mysql-1
    - host: 127.0.0.2
      port: 3306
      user: root 
      password: 123456
      name: mysql-2

  - name: redis
    user: root
    password: 123456
    reportInterval: 20

log:
  path: /var/log/dbha/probe.log
  level: debug
  fileCount: 10
  fileSize: 100

gse:
  dataId: 123456
  domainSocketPath: 