name: probe
version: v2.0.0

admin:
  endpoints: 127.0.0.1:22222,127.0.0.2:222222
  syncInterval: 10

receiver:
  endpoints: 127.0.0.1:22223,127.0.0.2:22224
  syncInterval: 10

harvester:
  - name: mysql
    user: root
    password: 123456
    reportInterval: 20

  - name: redis
    user: root
    password: 123456
    reportInterval: 20

log:
  path: /var/log/dbha/probe.log
  level: debug
  fileCount: 10
  fileSize: 100
