# Generated by Django 3.2.4 on 2023-04-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotSpec",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("snapshot_id", models.AutoField(primary_key=True, serialize=False)),
                ("spec_id", models.PositiveIntegerField()),
                ("spec_name", models.CharField(max_length=128)),
                ("spec_type", models.CharField(default="MySQL", max_length=64)),
                ("cpu", models.JSONField(help_text="cpu规格描述:{'min':1,'max':10}", null=True)),
                ("mem", models.JSONField(help_text="mem规格描述:{'min':100,'max':1000}", null=True)),
                ("device_class", models.JSONField(help_text="实际机器机型: ['class1','class2'] ", null=True)),
                ("storage_spec", models.JSONField(null=True)),
                ("desc", models.TextField(default="", help_text="资源规格描述")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Spec",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("spec_id", models.AutoField(primary_key=True, serialize=False)),
                ("spec_name", models.CharField(help_text="虚拟规格名称", max_length=128)),
                ("spec_db_type", models.CharField(default="DB组件:MySQL、Proxy、Spider", max_length=64)),
                ("cpu", models.JSONField(help_text="cpu规格描述:{'min':1,'max':10}", null=True)),
                ("mem", models.JSONField(help_text="mem规格描述:{'min':100,'max':1000}", null=True)),
                ("device_class", models.JSONField(help_text="实际机器机型: ['class1','class2'] ", null=True)),
                (
                    "storage_spec",
                    models.JSONField(help_text="存储磁盘需求配置：｛'mount_point':'/data','size':500,'type':'ssd'}", null=True),
                ),
                ("desc", models.TextField(default="", help_text="资源规格描述")),
            ],
            options={
                "unique_together": {("spec_name", "spec_db_type")},
            },
        ),
    ]
