# Generated by Django 3.2.4 on 2023-04-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0002_snapshotspec_spec_tendbclusterdeployplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterentry",
            name="forward_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forward_from",
                related_query_name="forward_from",
                to="db_meta.clusterentry",
            ),
        ),
    ]
