# Generated by Django 3.2.4 on 2023-04-24 11:20

from django.db import migrations, models

from backend.db_meta.enums import ClusterType, InstanceStatus, MachineType


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0003_clusterentry_forward_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="spec",
            name="spec_cluster_type",
            field=models.CharField(
                choices=ClusterType.get_choices(),
                default="",
                help_text="集群类型:MySQL、Proxy、Spider",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spec",
            name="spec_machine_type",
            field=models.CharField(
                choices=MachineType.get_choices(),
                default="",
                help_text="机器规格类型",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proxyinstance",
            name="status",
            field=models.CharField(
                choices=InstanceStatus.get_choices(),
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(help_text="存储磁盘需求配置:{'mount_point':'/data','size':500,'type':'ssd'}", null=True),
        ),
        migrations.AlterField(
            model_name="storageinstance",
            name="status",
            field=models.CharField(
                choices=InstanceStatus.get_choices(),
                default="",
                max_length=64,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spec",
            unique_together={("spec_cluster_type", "spec_machine_type", "spec_name")},
        ),
        migrations.RemoveField(
            model_name="spec",
            name="spec_db_type",
        ),
    ]
