# Generated by Django 3.2.4 on 2023-04-26 02:43

import django.db.models.deletion
from django.db import migrations, models

from backend.db_meta.enums import ClusterEntryRole, TenDBClusterSpiderRole


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0004_auto_20230424_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterentry",
            name="role",
            field=models.CharField(choices=ClusterEntryRole.get_choices(), default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="storagesetdtl",
            name="cluster",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db_meta.cluster"),
        ),
        migrations.CreateModel(
            name="TenDBClusterSpiderExt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "spider_role",
                    models.CharField(
                        choices=TenDBClusterSpiderRole.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "instance",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="db_meta.proxyinstance"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenDBClusterStorageSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("shard_id", models.PositiveIntegerField(default=0)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db_meta.cluster")),
                (
                    "storage_instance_tuple",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="db_meta.storageinstancetuple"
                    ),
                ),
            ],
            options={
                "unique_together": {("cluster", "shard_id"), ("cluster", "storage_instance_tuple")},
            },
        ),
    ]
