# Generated by Django 3.2.4 on 2023-05-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0005_auto_20230426_1043"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storagesetdtl",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="storagesetdtl",
            name="bk_biz_id",
        ),
        migrations.RemoveField(
            model_name="storagesetdtl",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="storagesetdtl",
            name="instance",
        ),
        migrations.RemoveField(
            model_name="storagesetdtl",
            name="seg_range",
        ),
        migrations.CreateModel(
            name="NosqlStorageSetDtl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0)),
                ("seg_range", models.CharField(default="", max_length=150)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db_meta.cluster")),
                (
                    "instance",
                    models.ForeignKey(
                        db_column="instance", on_delete=django.db.models.deletion.CASCADE, to="db_meta.storageinstance"
                    ),
                ),
            ],
            options={
                "unique_together": {("instance", "cluster", "bk_biz_id")},
            },
        ),
    ]
