# Generated by Django 3.2.4 on 2023-05-11 10:08

import django.db.models.deletion
from django.db import migrations, models

from backend.db_meta.enums import ClusterEntryRole, ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0006_auto_20230506_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterentry",
            name="role",
            field=models.CharField(
                choices=ClusterEntryRole.get_choices(),
                default="master_entry",
                max_length=64,
            ),
        ),
    ]
