# Generated by Django 3.2.4 on 2023-05-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0008_storageinstance_is_stand_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="deploy_plan_id",
            field=models.BigIntegerField(default=0, help_text="部署方法ID"),
        ),
        migrations.AddField(
            model_name="machine",
            name="spec_config",
            field=models.TextField(default=dict, help_text="当前的虚拟规格配置"),
        ),
        migrations.AddField(
            model_name="machine",
            name="spec_id",
            field=models.PositiveBigIntegerField(default=0, help_text="虚拟规格ID"),
        ),
    ]
