# Generated by Django 3.2.4 on 2023-05-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0006_alter_clusterentry_role"),
        ("db_meta", "0009_auto_20230517_1047"),
    ]

    operations = []
