# Generated by Django 3.2.19 on 2023-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0011_alter_cluster_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="spec_config",
            field=models.JSONField(default={}, help_text="当前的虚拟规格配置"),
        ),
    ]
