# Generated by Django 3.2.19 on 2023-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0011_alter_cluster_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterdeployplan",
            name="capacity",
            field=models.CharField(default="", help_text="集群存储预估总容量/G", max_length=128),
        ),
    ]
