# Generated by Django 3.2.19 on 2023-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0012_alter_clusterdeployplan_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="spec_config",
            field=models.JSONField(default=dict, help_text="当前的虚拟规格配置"),
        ),
    ]
