# Generated by Django 3.2.19 on 2023-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0013_alter_machine_spec_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="spec",
            name="instance_num",
            field=models.IntegerField(default=0, help_text="实例数(es专属)"),
        ),
        migrations.AlterUniqueTogether(
            name="spec",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="spec",
            index_together={("spec_cluster_type", "spec_machine_type", "spec_name")},
        ),
    ]
