# Generated by Django 3.2.19 on 2023-07-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0015_auto_20230703_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spec",
            name="desc",
            field=models.TextField(blank=True, help_text="资源规格描述", null=True),
        ),
    ]
