# Generated by Django 3.2.19 on 2023-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0016_alter_spec_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="immute_domain",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
    ]
