# Generated by Django 3.2.19 on 2023-08-24 09:15

import django.db.models.deletion
from django.db import migrations, models

from backend.db_meta.enums.extra_process_type import ExtraProcessType


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0017_alter_cluster_immute_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraProcessInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0)),
                ("cluster_id", models.IntegerField(default=0, help_text="关联的cluster_id")),
                (
                    "proc_type",
                    models.CharField(
                        choices=ExtraProcessType.get_choices(), default="", help_text="进程类型", max_length=64
                    ),
                ),
                ("version", models.CharField(default="", help_text="版本号", max_length=64)),
                ("listen_port", models.PositiveIntegerField(default=0, help_text="进程监听端口")),
                ("extra_config", models.JSONField(default=dict, help_text="进程的定制化属性")),
                (
                    "machine",
                    models.ForeignKey(
                        help_text="关联的machine信息", on_delete=django.db.models.deletion.PROTECT, to="db_meta.machine"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
