# Generated by Django 3.2.19 on 2023-08-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0018_extraprocessinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraprocessinstance",
            name="bk_cloud_id",
            field=models.IntegerField(default=0, help_text="云区域 ID，对应cmdb"),
        ),
        migrations.AddField(
            model_name="extraprocessinstance",
            name="ip",
            field=models.GenericIPAddressField(default="", help_text="IP 地址"),
        ),
        migrations.AlterField(
            model_name="extraprocessinstance",
            name="bk_biz_id",
            field=models.IntegerField(default=0, help_text="关联的业务id，对应cmdb"),
        ),
        migrations.AlterUniqueTogether(
            name="extraprocessinstance",
            unique_together={("ip", "bk_cloud_id", "listen_port")},
        ),
        migrations.RemoveField(
            model_name="extraprocessinstance",
            name="machine",
        ),
    ]
