# Generated by Django 3.2.19 on 2023-09-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0019_auto_20230829_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="tag",
            field=models.ManyToManyField(blank=True, help_text="集群标签", to="db_meta.Tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[("custom", "custom"), ("system", "system")],
                default="system",
                help_text="tag类型",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(default="", help_text="tag名称", max_length=64),
        ),
    ]
