# Generated by Django 3.2.19 on 2023-09-21 01:52

from django.db import migrations, models

from backend.db_meta.enums import InstancePhase


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0020_auto_20230913_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxyinstance",
            name="phase",
            field=models.CharField(
                choices=InstancePhase.get_choices(),
                default="online",
                max_length=64,
            ),
        ),
    ]
