# Generated by Django 3.2.19 on 2023-09-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0020_auto_20230913_1041"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="tag",
        ),
        migrations.AddField(
            model_name="tag",
            name="cluster",
            field=models.ManyToManyField(blank=True, help_text="关联集群", to="db_meta.Cluster"),
        ),
    ]
