# Generated by Django 3.2.19 on 2023-09-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0020_auto_20230913_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxyinstance",
            name="phase",
            field=models.CharField(
                choices=[
                    ("online", "online"),
                    ("offline", "offline"),
                    ("destroy", "destroy"),
                    ("trans_stage", "trans_stage"),
                ],
                default="online",
                max_length=64,
            ),
        ),
    ]
