# Generated by Django 3.2.19 on 2023-09-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0021_auto_20230918_1750"),
        ("db_meta", "0021_proxyinstance_phase"),
    ]

    operations = []
