# Generated by Django 3.2.19 on 2023-09-25 03:33

from django.db import migrations, models

from backend.configuration.constants import AffinityEnum


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0022_merge_20230921_1147"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="disaster_tolerance_level",
            field=models.CharField(
                choices=AffinityEnum.get_choices(), default="NONE", help_text="容灾要求", max_length=128
            ),
        ),
    ]
