# Generated by Django 3.2.19 on 2023-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0023_cluster_disaster_tolerance_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="bk_agent_id",
            field=models.CharField(default="", help_text="Agent ID", max_length=128),
        ),
    ]
