# Generated by Django 3.2.19 on 2023-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0024_machine_bk_agent_id"),
    ]

    operations = []
