# Generated by Django 3.2.19 on 2023-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0025_dumpersubscribeconfig"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="extraprocessinstance",
            index=models.Index(fields=["cluster_id", "proc_type"], name="db_meta_ext_cluster_2cbc7c_idx"),
        ),
    ]
