# Generated by Django 3.2.19 on 2023-12-01 11:02

from django.db import migrations, models

from backend.db_meta.enums import ClusterPhase


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0026_extraprocessinstance_db_meta_ext_cluster_2cbc7c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraprocessinstance",
            name="phase",
            field=models.CharField(
                choices=ClusterPhase.get_choices(),
                default="online",
                max_length=64,
            ),
        ),
    ]
