# Generated by Django 3.2.19 on 2023-11-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0026_extraprocessinstance_db_meta_ext_cluster_2cbc7c_idx"),
    ]

    operations = []
