# Generated by Django 3.2.19 on 2023-12-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0027_delete_dumpersubscribeconfig"),
        ("db_meta", "0027_extraprocessinstance_phase"),
    ]

    operations = []
