# Generated by Django 3.2.19 on 2023-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0028_merge_20231207_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="spec",
            name="enable",
            field=models.BooleanField(default=True, help_text="是否启用"),
        ),
    ]
