# Generated by Django 3.2.19 on 2023-12-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0029_spec_enable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appcache",
            options={"verbose_name": "CMDB业务信息缓存表(AppCache)", "verbose_name_plural": "CMDB业务信息缓存表(AppCache)"},
        ),
        migrations.AlterModelOptions(
            name="appmonitortopo",
            options={"verbose_name": "业务监控拓扑(AppMonitorTopo)", "verbose_name_plural": "业务监控拓扑(AppMonitorTopo)"},
        ),
        migrations.AlterModelOptions(
            name="bkcity",
            options={"verbose_name": "蓝鲸城市表(BKCity)", "verbose_name_plural": "蓝鲸城市表(BKCity)"},
        ),
        migrations.AlterModelOptions(
            name="cluster",
            options={"verbose_name": "集群(Cluster)", "verbose_name_plural": "集群(Cluster)"},
        ),
        migrations.AlterModelOptions(
            name="clusterentry",
            options={"verbose_name": "集群访问入口(ClusterEntry)", "verbose_name_plural": "集群访问入口(ClusterEntry)"},
        ),
        migrations.AlterModelOptions(
            name="clustermonitortopo",
            options={
                "verbose_name": "CMDB模块映射(ClusterMonitorTopo)",
                "verbose_name_plural": "CMDB模块映射(ClusterMonitorTopo)",
            },
        ),
        migrations.AlterModelOptions(
            name="dbmodule",
            options={"verbose_name": "DB模块(DBModule)", "verbose_name_plural": "DB模块(DBModule)"},
        ),
        migrations.AlterModelOptions(
            name="extraprocessinstance",
            options={
                "verbose_name": "附属进程实例(ExtraProcessInstance)",
                "verbose_name_plural": "附属进程实例(ExtraProcessInstance)",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "分组表(Group)", "verbose_name_plural": "分组表(Group)"},
        ),
        migrations.AlterModelOptions(
            name="logicalcity",
            options={"verbose_name": "逻辑城市表(LogicalCity)", "verbose_name_plural": "逻辑城市表(LogicalCity)"},
        ),
        migrations.AlterModelOptions(
            name="machine",
            options={"verbose_name": "机器主机(Machine)", "verbose_name_plural": "机器主机(Machine)"},
        ),
        migrations.AlterModelOptions(
            name="proxyinstance",
            options={
                "ordering": ("-create_at",),
                "verbose_name": "代理实例(ProxyInstance)",
                "verbose_name_plural": "代理实例(ProxyInstance)",
            },
        ),
        migrations.AlterModelOptions(
            name="spec",
            options={"verbose_name": "资源规格(Spec)", "verbose_name_plural": "资源规格(Spec)"},
        ),
        migrations.AlterModelOptions(
            name="storageinstance",
            options={
                "ordering": ("-create_at",),
                "verbose_name": "存储实例(StorageInstance)",
                "verbose_name_plural": "存储实例(StorageInstance)",
            },
        ),
        migrations.AlterModelOptions(
            name="storageinstancetuple",
            options={
                "verbose_name": "存储实例元组对(StorageInstanceTuple)",
                "verbose_name_plural": "存储实例元组对(StorageInstanceTuple)",
            },
        ),
        migrations.AlterModelOptions(
            name="syncfailedmachine",
            options={
                "verbose_name": "同步失败的IP(SyncFailedMachine)",
                "verbose_name_plural": "同步失败的IP(SyncFailedMachine)",
            },
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_agent_id",
            field=models.CharField(blank=True, default="", help_text="Agent ID", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_idc_area",
            field=models.CharField(blank=True, default="", help_text="区域", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_idc_name",
            field=models.CharField(blank=True, default="", help_text="机房", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_os_name",
            field=models.CharField(blank=True, default="", help_text="操作系统", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_rack",
            field=models.CharField(blank=True, default="", help_text="机架", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_sub_zone",
            field=models.CharField(blank=True, default="", help_text="子 Zone", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="bk_svr_device_cls_name",
            field=models.CharField(blank=True, default="", help_text="标准设备类型", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="net_device_id",
            field=models.CharField(blank=True, default="", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="proxyinstance",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proxyinstance",
            name="version",
            field=models.CharField(blank=True, default="", help_text="版本号", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="storageinstance",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="storageinstance",
            name="version",
            field=models.CharField(blank=True, default="", help_text="版本号", max_length=64, null=True),
        ),
    ]
