# Generated by Django 3.2.19 on 2024-01-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0030_auto_20231229_0933"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appmonitortopo",
            unique_together={("bk_biz_id", "db_type", "machine_type", "bk_set_id")},
        ),
        migrations.AlterUniqueTogether(
            name="clustermonitortopo",
            unique_together={("bk_biz_id", "machine_type", "bk_set_id", "bk_module_id")},
        ),
    ]
