# Generated by Django 3.2.19 on 2024-01-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0030_auto_20231229_0933"),
    ]

    operations = [
        migrations.CreateModel(
            name="SqlserverClusterSyncMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "sync_mode",
                    models.CharField(choices=[("mirroring", "镜像同步"), ("always_on", "Always_on同步")], max_length=64),
                ),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db_meta.cluster")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
