# Generated by Django 3.2.19 on 2024-01-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0031_auto_20240118_1113"),
        ("db_meta", "0031_sqlserverclustersyncmode"),
    ]

    operations = []
