# Generated by Django 3.2.19 on 2024-03-01 07:18

from django.db import migrations, models

import backend.db_meta.models.sqlserver_dts
from backend.flow.consts import SqlserverDtsMode


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0032_merge_20240123_1123"),
    ]

    operations = [
        migrations.CreateModel(
            name="SqlserverDtsInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="关联的业务id，对应cmdb")),
                ("source_cluster_id", models.IntegerField(default=0, help_text="源集群ID")),
                ("target_cluster_id", models.IntegerField(default=0, help_text="目标集群ID")),
                (
                    "dts_mode",
                    models.CharField(choices=SqlserverDtsMode.get_choices(), help_text="迁移类型", max_length=64),
                ),
                ("ticket_id", models.PositiveIntegerField(default=0, help_text="关联的单据id")),
                ("root_id", models.CharField(default="", help_text="关联root_id", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=backend.db_meta.models.sqlserver_dts.DtsStatus.get_choices(),
                        default=backend.db_meta.models.sqlserver_dts.DtsStatus["ToDo"],
                        help_text="状态",
                        max_length=64,
                    ),
                ),
                ("dts_config", models.JSONField(default=dict, help_text="迁移配置")),
            ],
            options={
                "verbose_name": "sqlserver数据迁移记录表",
                "verbose_name_plural": "sqlserver数据迁移记录表",
            },
        ),
    ]
