# Generated by Django 3.2.19 on 2024-04-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0032_merge_20240123_1123"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterDBHAExt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("begin_time", models.DateTimeField(auto_now=True, db_index=True, help_text="屏蔽开始时间")),
                ("end_time", models.DateTimeField(db_index=True, default=None, help_text="屏蔽结束时间")),
                ("cluster", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="db_meta.cluster")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
