# Generated by Django 3.2.19 on 2024-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0032_merge_20240123_1123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(default="", help_text="集群英文名", max_length=64),
        ),
    ]
