# Generated by Django 3.2.19 on 2024-03-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0033_alter_cluster_name"),
        ("db_meta", "0033_sqlserverdtsinfo"),
    ]

    operations = []
