# Generated by Django 3.2.19 on 2024-04-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0035_machine_system_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterentry",
            name="access_port",
            field=models.IntegerField(default=0, help_text="数据库服务的端口", verbose_name="端口"),
        ),
        migrations.AlterUniqueTogether(
            name="sqlserverdtsinfo",
            unique_together={("ticket_id", "source_cluster_id", "target_cluster_id")},
        ),
    ]
