# Generated by Django 3.2.25 on 2024-04-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0033_clusterdbhaext"),
        ("db_meta", "0035_machine_system_info"),
    ]

    operations = []
