# Generated by Django 3.2.19 on 2024-04-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0035_machine_system_info"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sqlserverdtsinfo",
            unique_together={("ticket_id", "source_cluster_id", "target_cluster_id")},
        ),
    ]
