# Generated by Django 3.2.25 on 2024-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0038_auto_20240621_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlserverdtsinfo",
            name="db_list",
            field=models.JSONField(blank=True, default=list, help_text="库正则", null=True),
        ),
        migrations.AddField(
            model_name="sqlserverdtsinfo",
            name="ignore_db_list",
            field=models.JSONField(blank=True, default=list, help_text="忽略库正则", null=True),
        ),
    ]
