# Generated by Django 3.2.25 on 2024-07-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0039_auto_20240626_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbmodule",
            name="alias_name",
            field=models.CharField(default="", help_text="dbmodule 别名,用于生成域名", max_length=200),
        ),
        migrations.AddIndex(
            model_name="dbmodule",
            index=models.Index(fields=["bk_biz_id", "alias_name"], name="db_meta_dbm_bk_biz__dd0601_idx"),
        ),
        migrations.AddIndex(
            model_name="dbmodule",
            index=models.Index(fields=["alias_name"], name="db_meta_dbm_alias_n_a367cb_idx"),
        ),
    ]
