# Generated by Django 3.2.25 on 2024-09-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0041_auto_20240819_1031"),
    ]

    operations = [
        migrations.CreateModel(
            name="BKSubzone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "bk_sub_zone",
                    models.CharField(blank=True, default="", help_text="子 Zone", max_length=128, null=True),
                ),
                ("bk_sub_zone_id", models.IntegerField(default=0, help_text="子 Zone ID")),
                ("bk_city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db_meta.bkcity")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
