# Generated by Django 3.2.25 on 2024-09-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0041_auto_20240819_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spec",
            name="cpu",
            field=models.JSONField(help_text='cpu规格描述:{"min":1,"max":10}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="device_class",
            field=models.JSONField(help_text='实际机器机型: ["class1","class2"]', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="mem",
            field=models.JSONField(help_text='mem规格描述:{"min":100,"max":1000}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="qps",
            field=models.JSONField(default=dict, help_text='qps规格描述:{"min": 1, "max": 100}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(help_text='存储磁盘需求配置:[{"mount_point":"/data","size":500,"type":"ssd"}]', null=True),
        ),
    ]
