# Generated by Django 3.2.25 on 2024-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0042_auto_20240903_1138"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bksubzone",
            options={"verbose_name": "蓝鲸园区表(BKSubzone)", "verbose_name_plural": "蓝鲸园区表(BKSubzone)"},
        ),
        migrations.AddField(
            model_name="cluster",
            name="tags",
            field=models.ManyToManyField(blank=True, help_text="标签（外键）", to="db_meta.Tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="key",
            field=models.CharField(default="", help_text="标签键", max_length=64),
        ),
        migrations.AddField(
            model_name="tag",
            name="value",
            field=models.CharField(default="", help_text="标签值", max_length=255),
        ),
        migrations.AlterField(
            model_name="spec",
            name="cpu",
            field=models.JSONField(help_text='cpu规格描述:{"min":1,"max":10}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="device_class",
            field=models.JSONField(help_text='实际机器机型: ["class1","class2"]', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="mem",
            field=models.JSONField(help_text='mem规格描述:{"min":100,"max":1000}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="qps",
            field=models.JSONField(default=dict, help_text='qps规格描述:{"min": 1, "max": 100}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(help_text='存储磁盘需求配置:[{"mount_point":"/data","size":500,"type":"ssd"}]', null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="bk_biz_id",
            field=models.IntegerField(default=0, help_text="业务 ID"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[("custom", "自定义标签"), ("system", "系统标签"), ("builtin", "内置标签")],
                default="custom",
                help_text="tag类型",
                max_length=64,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("bk_biz_id", "key", "value")},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
    ]
