# Generated by Django 3.2.25 on 2024-10-14 02:42

from django.db import migrations, models

from backend.db_meta.enums.spec import SpecClusterType, SpecMachineType


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0042_auto_20240903_1138"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bksubzone",
            options={"verbose_name": "蓝鲸园区表(BKSubzone)", "verbose_name_plural": "蓝鲸园区表(BKSubzone)"},
        ),
        migrations.AlterField(
            model_name="spec",
            name="cpu",
            field=models.JSONField(default=dict, help_text='cpu规格描述:{"min":1,"max":10}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="device_class",
            field=models.JSONField(default=dict, help_text='实际机器机型: ["class1","class2"]'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="mem",
            field=models.JSONField(default=dict, help_text='mem规格描述:{"min":100,"max":1000}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="qps",
            field=models.JSONField(default=dict, help_text='qps规格描述:{"min": 1, "max": 100}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="spec_cluster_type",
            field=models.CharField(choices=SpecClusterType.get_choices(), help_text="组件类型", max_length=64),
        ),
        migrations.AlterField(
            model_name="spec",
            name="spec_machine_type",
            field=models.CharField(choices=SpecMachineType.get_choices(), help_text="机器类型", max_length=64),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(
                default=dict, help_text='存储磁盘需求配置:[{"mount_point":"/data","size":500,"type":"ssd"}]'
            ),
        ),
    ]
