# Generated by Django 3.2.25 on 2024-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0043_auto_20241014_1042"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_type", models.CharField(help_text="机型类型", max_length=128)),
                ("cpu", models.IntegerField(default=0, help_text="机型cpu")),
                ("mem", models.IntegerField(default=0, help_text="机型内存")),
                ("disk", models.IntegerField(default=0, help_text="机型磁盘")),
            ],
            options={
                "verbose_name": "机型(DeviceClass)",
                "verbose_name_plural": "机型(DeviceClass)",
            },
        ),
    ]
