# Generated by Django 3.2.25 on 2024-11-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0044_deviceclass"),
        ("db_meta", "0043_auto_20241015_2128"),
    ]

    operations = []
