# Generated by Django 3.2.25 on 2025-01-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0045_alter_polarisentrydetail_polaris_name"),
        ("db_meta", "0045_merge_0043_auto_20241014_1042_0043_auto_20241015_2128"),
    ]

    operations = []
