# Generated by Django 3.2.25 on 2025-03-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0042_auto_20240919_1016"),
        ("db_meta", "0045_alter_polarisentrydetail_polaris_name"),
    ]

    operations = []
