# Generated by Django 3.2.25 on 2025-03-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0046_merge_20250120_1529"),
        ("db_meta", "0046_merge_20250312_1422"),
    ]

    operations = []
