# Generated by Django 3.2.25 on 2025-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0047_merge_20250319_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="clbentrydetail",
            name="clb_port",
            field=models.IntegerField(default=0),
        ),
    ]
