# Generated by Django 3.2.25 on 2025-04-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0047_merge_20250319_1451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spec",
            name="cpu",
            field=models.JSONField(default=dict, help_text='cpu规格描述:{"min":1,"max":10}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="device_class",
            field=models.JSONField(default=dict, help_text='实际机器机型: ["class1","class2"]'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="mem",
            field=models.JSONField(default=dict, help_text='mem规格描述:{"min":100,"max":1000}'),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(
                default=dict, help_text='存储磁盘需求配置:[{"mount_point":"/data","size":500,"type":"ssd"}]'
            ),
        ),
    ]
