# Generated by Django 3.2.25 on 2025-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0048_auto_20250407_0846"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="zone_list",
            field=models.JSONField(default=list, help_text="指定机房列表，空列表代表随机"),
        ),
    ]
