# Generated by Django 3.2.25 on 2025-05-07 08:26

from django.db import migrations, models


def migrate_target_cluster_id_to_ids(apps, schema_editor):
    SqlserverDtsInfo = apps.get_model("db_meta", "SqlserverDtsInfo")
    for record in SqlserverDtsInfo.objects.all():
        # 将旧的 target_cluster_id 转换为新的 target_cluster_ids
        record.target_cluster_ids = [record.target_cluster_id]
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0048_auto_20250408_1828"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlserverdtsinfo",
            name="target_cluster_ids",
            field=models.JSONField(default=list, help_text="目标集群id列表"),
        ),
        migrations.RunPython(migrate_target_cluster_id_to_ids),
        migrations.AlterUniqueTogether(
            name="sqlserverdtsinfo",
            unique_together=set(),
        ),
    ]
