# Generated by Django 3.2.25 on 2025-05-08 13:42

from django.db import migrations, models

from backend.db_meta.enums.comm import TagType


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0049_auto_20250507_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_builtin",
            field=models.BooleanField(default=False, help_text="是否内置"),
        ),
        migrations.AlterField(
            model_name="clusterdbhaext",
            name="begin_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text="屏蔽开始时间"),
        ),
        migrations.AlterField(
            model_name="spec",
            name="cpu",
            field=models.JSONField(default=dict, help_text='cpu规格描述:{"min":1,"max":10}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="device_class",
            field=models.JSONField(default=dict, help_text='实际机器机型: ["class1","class2"]', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="mem",
            field=models.JSONField(default=dict, help_text='mem规格描述:{"min":100,"max":1000}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="qps",
            field=models.JSONField(default=dict, help_text='qps规格描述:{"min": 1, "max": 100}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(
                default=dict, help_text='存储磁盘需求配置:[{"mount_point":"/data","size":500,"type":"ssd"}]', null=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(choices=TagType.get_choices(), help_text="tag类型", max_length=64),
        ),
    ]
