# Generated by Django 3.2.25 on 2025-07-23 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0051_redishotkeydetail_redishotkeyinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DorisResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="关联的业务id，对应cmdb")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 ID")),
                ("name", models.CharField(help_text="资源名称，唯一", max_length=255, unique=True)),
                ("bucket_name", models.CharField(help_text="存储桶名称", max_length=255)),
                ("region", models.CharField(help_text="地域", max_length=64)),
                ("endpoint", models.CharField(help_text="API地址", max_length=255)),
                ("root_path", models.CharField(default="/data", help_text="存储桶目录名", max_length=255)),
                ("enable", models.BooleanField(default=True, help_text="是否启用")),
                (
                    "tag",
                    models.CharField(
                        choices=[("public", "公共资源"), ("private", "独立集群资源")],
                        help_text="资源标记: public|private",
                        max_length=64,
                    ),
                ),
                (
                    "control",
                    models.CharField(
                        choices=[("dbm", "由DBM创建及删除"), ("others", "其他")], help_text="dbm|others", max_length=64
                    ),
                ),
                ("account_id", models.CharField(help_text="访问账号ID", max_length=255)),
            ],
            options={
                "verbose_name": "doris资源记录表",
                "verbose_name_plural": "doris资源记录表",
            },
        ),
        migrations.CreateModel(
            name="DorisResourceSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db_meta.cluster")),
                (
                    "resource",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db_meta.dorisresource"),
                ),
            ],
            options={
                "unique_together": {("cluster", "resource")},
            },
        ),
    ]
