# Generated by Django 3.2.25 on 2025-06-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0051_redishotkeydetail_redishotkeyinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantCache",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("tenant_id", models.CharField(help_text="租户ID", max_length=128, primary_key=True, serialize=False)),
                ("tenant_name", models.CharField(default="", max_length=128, verbose_name="租户名称")),
                ("status", models.CharField(default="enabled", max_length=64, verbose_name="状态")),
                ("admin", models.CharField(default="admin", max_length=128, verbose_name="管理员")),
                ("clouds", models.JSONField(default=[], verbose_name="云区域列表")),
                ("dba_app_id", models.IntegerField(default=0, help_text="当前租户默认业务ID")),
                ("dba_job_id", models.IntegerField(default=0, help_text="当前租户默认JOB执行业务集ID")),
            ],
            options={
                "verbose_name": "租户信息缓存表(TenantCache)",
                "verbose_name_plural": "租户信息缓存表(TenantCache)",
            },
        ),
        migrations.AddField(
            model_name="appcache",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
    ]
