# Generated by Django 3.2.25 on 2025-07-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0052_dorisresource_dorisresourceset"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("bk_biz_id", "key", "value", "type")},
        ),
    ]
