# Generated by Django 3.2.25 on 2025-07-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0052_auto_20250611_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
    ]
