# Generated by Django 3.2.25 on 2025-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0053_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceclass",
            name="bandwidth",
            field=models.IntegerField(default=2147483647, help_text="机型带宽(单位Mbps)"),
        ),
        migrations.AlterField(
            model_name="deviceclass",
            name="disk",
            field=models.IntegerField(default=0, help_text="机型磁盘(单位GB)"),
        ),
        migrations.AlterField(
            model_name="deviceclass",
            name="mem",
            field=models.IntegerField(default=0, help_text="机型内存(单位MB)"),
        ),
    ]
