# Generated by Django 3.2.25 on 2025-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0053_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="zone_list",
            field=models.JSONField(default=list, help_text="指定机房列表，空列表代表随机"),
        ),
    ]
