# Generated by Django 3.2.25 on 2025-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0054_auto_20250731_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="spec",
            name="biz_scope",
            field=models.JSONField(default=list, help_text="业务范围:[3,4,5]", null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(
                default=dict,
                help_text='存储磁盘需求配置:[{"mount_point":"/data","min":500,"max":1000,"type":"ssd"}]',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deviceclass",
            name="mem",
            field=models.IntegerField(default=0, help_text="机型内存(单位GB)"),
        ),
    ]
