# Generated by Django 3.2.25 on 2025-08-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0054_auto_20250731_1520"),
        ("db_meta", "0054_cluster_zone_list"),
    ]

    operations = []
