# Generated by Django 3.2.25 on 2025-09-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0055_auto_20250826_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="zone_list",
            field=models.JSONField(blank=True, default=list, help_text="指定机房列表，空列表代表随机", null=True),
        ),
    ]
