# Generated by Django 3.2.25 on 2025-09-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0056_cluster_zone_list"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RedisHotKeyDetail",
        ),
        migrations.DeleteModel(
            name="RedisHotKeyInfo",
        ),
    ]
