# Generated by Django 3.2.25 on 2025-10-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_package", "0001_initial"),
        ("db_meta", "0056_cluster_zone_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(default="", help_text="发行版", max_length=256)),
                ("engine", models.CharField(default="", help_text="引擎", max_length=64)),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("tendbcluster", "TenDBCluster"),
                            ("redis", "Redis"),
                            ("mongodb", "MongoDB"),
                            ("kafka", "Kafka"),
                            ("hdfs", "HDFS"),
                            ("es", "ElasticSearch"),
                            ("pulsar", "Pulsar"),
                            ("influxdb", "InfluxDB"),
                            ("riak", "Riak"),
                            ("sqlserver", "SQLServer"),
                            ("doris", "Doris"),
                            ("vm", "Vm"),
                            ("oracle", "Oracle"),
                            ("cloud", "Cloud"),
                            ("tbinlogdumper", "TBinlogDumper"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "pkg_type",
                    models.CharField(
                        choices=[
                            ("mysql", "mysql"),
                            ("mysql-proxy", "mysql-proxy"),
                            ("redis", "redis"),
                            ("tendisplus", "tendisplus"),
                            ("tendisssd", "tendisssd"),
                            ("dbbackup", "dbbackup"),
                            ("dbbackup-txsql", "dbbackup-txsql"),
                            ("actuator", "actuator"),
                            ("exporter", "exporter"),
                            ("latest", "最新版本"),
                            ("twemproxy", "twemproxy"),
                            ("predixy", "predixy"),
                            ("tools", "redis_tools"),
                            ("es", "es"),
                            ("kafka", "kafka"),
                            ("hdfs", "hdfs"),
                            ("pulsar", "pulsar"),
                            ("influxdb", "influxdb"),
                            ("dbmon", "dbmon"),
                            ("dbtools", "db工具包"),
                            ("mysql-checksum", "mysql-checksum"),
                            ("rotate-binlog", "Binlog 滚动备份工具"),
                            ("dba-toolkit", "DBA 工具集"),
                            ("mysql-crond", "mysql-crond"),
                            ("mysql-monitor", "MySQL 监控"),
                            ("cloud-nginx", "nginx 服务"),
                            ("cloud-dns-bind", "dns-bind 服务"),
                            ("cloud-dns-pullcrond", "dns-pull-crond服务"),
                            ("cloud-dbha", "cloud-dbha服务"),
                            ("cloud-drs", "cloud-drs服务"),
                            ("cloud-drs-tmysqlparse", "cloud-drs-tmysqlparse服务"),
                            ("spider", "spider节点名称"),
                            ("tdbctl", "spider中控节点名称"),
                            ("riak", "riak"),
                            ("riak-monitor", "riak-monitor"),
                            ("redis-dts", "redis-dts"),
                            ("redis-modules", "redis-modules"),
                            ("tbinlogdumper", "tbinlogdumper实例"),
                            ("sqlserver", "sqlserver实例"),
                            ("mongodb", "mongodb"),
                            ("mongo-toolkit", "Mongo 工具集"),
                            ("mongo-monitor", "Mongo 监控"),
                            ("doris", "doris"),
                            ("vm", "vm"),
                            ("oracle", "oracle"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VersionSeries",
            fields=[
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "name",
                    models.CharField(default="", help_text="版本系列", max_length=128, primary_key=True, serialize=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dbmodule",
            name="current_db_version_info_dict",
            field=models.JSONField(default=dict, help_text="当前版本信息 id"),
        ),
        migrations.AddField(
            model_name="dbmodule",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict, help_text="扩展信息, mysql/sqlsvr 用到", null=True),
        ),
        migrations.AddField(
            model_name="dbmodule",
            name="in_upgrade",
            field=models.BooleanField(default=False, help_text="在升级状态"),
        ),
        migrations.AddField(
            model_name="dbmodule",
            name="target_db_version_info_dict",
            field=models.JSONField(blank=True, default=dict, help_text="目标版本信息 id", null=True),
        ),
        migrations.CreateModel(
            name="DBVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("full_version", models.CharField(default="", help_text="完整版本", max_length=128)),
                ("distribution_snapshot", models.JSONField(default=dict, help_text="发行版快照", null=True)),
                ("phase", models.CharField(choices=[("alpha", "alpha")], help_text="版本阶段", max_length=128)),
                ("enable", models.BooleanField(default=True, help_text="版本启用")),
                (
                    "version_series",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="db_meta.versionseries"),
                ),
            ],
            options={
                "unique_together": {("full_version", "version_series")},
            },
        ),
        migrations.AddField(
            model_name="proxyinstance",
            name="db_package",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="db_package.package"
            ),
        ),
        migrations.AddField(
            model_name="storageinstance",
            name="db_package",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="db_package.package"
            ),
        ),
    ]
