# Generated by Django 3.2.25 on 2025-10-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0057_auto_20250919_1028"),
        ("db_meta", "0057_auto_20251021_1215"),
    ]

    operations = []
