# Generated by Django 4.2.23 on 2025-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0058_merge_0057_auto_20250919_1028_0057_auto_20251021_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbversion",
            name="phase",
            field=models.CharField(
                choices=[("alpha", "alpha"), ("beta", "beta"), ("rc", "rc"), ("release", "release")],
                help_text="版本阶段",
                max_length=128,
            ),
        ),
    ]
