# Generated by Django 4.2.23 on 2025-10-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0058_merge_0057_auto_20250919_1028_0057_auto_20251021_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="bksubzone",
            name="bk_cloud_region",
            field=models.CharField(blank=True, default="", help_text="云地域", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="bksubzone",
            name="bk_cloud_zone",
            field=models.CharField(blank=True, default="", help_text="云可用区", max_length=128, null=True),
        ),
    ]
