# Generated by Django 4.2.23 on 2025-10-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0063_alter_mongodbstorageinstanceext_instance"),
        ("db_meta", "0061_spec_tags_alter_extraprocessinstance_phase_and_more"),
    ]

    operations = [
        # 步骤 1: 添加 distribution 外键字段
        migrations.AddField(
            model_name="versionseries",
            name="distribution",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="db_meta.distribution"
            ),
        ),
        # 步骤 2a: 清空 DBVersion 的旧 unique_together（同步 state 与 DB）
        # 0057 创建 DBVersion 时声明了 unique_together={("full_version", "version_series")}。
        # 紧接着步骤 2b 的 RemoveField(version_series) 在 MySQL 上会 DROP COLUMN，
        # 隐式连带删除该列上的 unique 索引；但 Django state 中的 unique_together 集合不会自动清空。
        # 不在这里显式清空的话，后续 0063 的 AlterUniqueTogether 会基于"过时的 state 旧值"算出
        # 一个需要 DROP 但实际不存在的索引，全新数据库执行时会抛：
        #   ValueError: Found wrong number (0) of constraints for db_meta_dbversion(full_version, version_series_id)
        migrations.AlterUniqueTogether(
            name="dbversion",
            unique_together=set(),
        ),
        # 步骤 2b: 删除 DBVersion 的旧外键字段（引用 VersionSeries.name）
        migrations.RemoveField(
            model_name="dbversion",
            name="version_series",
        ),
        # 步骤 3: 将 VersionSeries.name 从主键改为普通字段
        migrations.AlterField(
            model_name="versionseries",
            name="name",
            field=models.CharField(default="", help_text="版本系列", max_length=128),
        ),
        # 步骤 4: 添加 id 字段作为新的主键
        migrations.AddField(
            model_name="versionseries",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
            preserve_default=False,
        ),
        # 步骤 5: 重新添加 DBVersion 的外键字段（引用 VersionSeries.id）
        migrations.AddField(
            model_name="dbversion",
            name="version_series",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="db_meta.versionseries"
            ),
        ),
        # 步骤 6: 设置 unique 约束
        migrations.AlterUniqueTogether(
            name="versionseries",
            unique_together={("distribution", "name")},
        ),
        # 步骤 7: 添加 description 和 recommend 字段
        migrations.AddField(
            model_name="dbversion",
            name="description",
            field=models.TextField(default="", help_text="版本描述"),
        ),
        migrations.AddField(
            model_name="dbversion",
            name="recommend",
            field=models.BooleanField(default=False, help_text="版本推荐"),
        ),
    ]
