# Generated by Django 4.2.23 on 2025-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0059_bksubzone_bk_cloud_region_bksubzone_bk_cloud_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("mysql", "MySQL"),
                    ("tendbcluster", "TenDBCluster"),
                    ("redis", "Redis"),
                    ("mongodb", "MongoDB"),
                    ("kafka", "Kafka"),
                    ("hdfs", "HDFS"),
                    ("es", "ElasticSearch"),
                    ("pulsar", "Pulsar"),
                    ("influxdb", "InfluxDB"),
                    ("riak", "Riak"),
                    ("sqlserver", "SQLServer"),
                    ("doris", "Doris"),
                    ("vm", "Vm"),
                    ("oracle", "Oracle"),
                    ("k8s", "K8s"),
                    ("cloud", "Cloud"),
                    ("tbinlogdumper", "TBinlogDumper"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="pkg_type",
            field=models.CharField(
                choices=[
                    ("mysql", "mysql"),
                    ("mysql-proxy", "mysql-proxy"),
                    ("redis", "redis"),
                    ("tendisplus", "tendisplus"),
                    ("tendisssd", "tendisssd"),
                    ("dbbackup", "dbbackup"),
                    ("dbbackup-txsql", "dbbackup-txsql"),
                    ("actuator", "actuator"),
                    ("exporter", "exporter"),
                    ("latest", "最新版本"),
                    ("twemproxy", "twemproxy"),
                    ("predixy", "predixy"),
                    ("tools", "redis_tools"),
                    ("es", "es"),
                    ("kafka", "kafka"),
                    ("hdfs", "hdfs"),
                    ("pulsar", "pulsar"),
                    ("influxdb", "influxdb"),
                    ("dbmon", "dbmon"),
                    ("dbtools", "db工具包"),
                    ("mysql-checksum", "mysql-checksum"),
                    ("rotate-binlog", "Binlog 滚动备份工具"),
                    ("dba-toolkit", "DBA 工具集"),
                    ("mysql-crond", "mysql-crond"),
                    ("mysql-monitor", "MySQL 监控"),
                    ("cloud-nginx", "nginx 服务"),
                    ("cloud-dns-bind", "dns-bind 服务"),
                    ("cloud-dns-pullcrond", "dns-pull-crond服务"),
                    ("cloud-dbha", "cloud-dbha服务"),
                    ("cloud-drs", "cloud-drs服务"),
                    ("cloud-drs-tmysqlparse", "cloud-drs-tmysqlparse服务"),
                    ("spider", "spider节点名称"),
                    ("tdbctl", "spider中控节点名称"),
                    ("riak", "riak"),
                    ("riak-monitor", "riak-monitor"),
                    ("redis-dts", "redis-dts"),
                    ("redis-modules", "redis-modules"),
                    ("tbinlogdumper", "tbinlogdumper实例"),
                    ("sqlserver", "sqlserver实例"),
                    ("mongodb", "mongodb"),
                    ("mongo-toolkit", "Mongo 工具集"),
                    ("mongo-monitor", "Mongo 监控"),
                    ("doris", "doris"),
                    ("vm", "vm"),
                    ("oracle", "oracle"),
                    ("tlinux4-dependencies", "tlinux4-dependencies"),
                ],
                max_length=128,
            ),
        ),
    ]
