# Generated by Django 4.2.23 on 2025-12-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0059_bksubzone_bk_cloud_region_bksubzone_bk_cloud_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="spec",
            name="tags",
            field=models.ManyToManyField(blank=True, help_text="标签", to="db_meta.tag"),
        ),
        migrations.AlterField(
            model_name="spec",
            name="cpu",
            field=models.JSONField(blank=True, default=dict, help_text='cpu描述:{"min":1,"max":10}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="device_class",
            field=models.JSONField(blank=True, default=dict, help_text='机型描述:["class1","class2"]', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="mem",
            field=models.JSONField(blank=True, default=dict, help_text='mem描述:{"min":100,"max":1000}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="qps",
            field=models.JSONField(blank=True, default=dict, help_text='qps描述:{"min": 1, "max": 100}', null=True),
        ),
        migrations.AlterField(
            model_name="spec",
            name="storage_spec",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='磁盘描述:[{"mount_point":"/data","min":100,"max":500,"type":"ssd"}]',
                null=True,
            ),
        ),
    ]
