# Generated by Django 4.2.27 on 2026-03-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0061_spec_tags_alter_extraprocessinstance_phase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MongoDBStorageInstanceExt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="UNKNOWN", help_text="实例状态", max_length=64)),
                ("state_code", models.IntegerField(default=-1, help_text="实例状态码")),
                ("priority", models.IntegerField(default=-1, help_text="优先级")),
                ("hidden", models.IntegerField(default=0, help_text="是否隐藏")),
                (
                    "shard_name",
                    models.CharField(blank=True, default="", help_text="shard名称", max_length=256, null=True),
                ),
                (
                    "update_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, help_text="最后更新时间", null=True),
                ),
                (
                    "instance",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="db_meta.storageinstance"),
                ),
            ],
        ),
    ]
