# Generated by Django 4.2.23 on 2025-12-31 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0061_spec_tags_alter_extraprocessinstance_phase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MongoDBStorageInstanceExt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="未检测", help_text="实例状态", max_length=64)),
                ("state_code", models.IntegerField(default=-1, help_text="实例状态码")),
                ("priority", models.IntegerField(default=-1, help_text="优先级")),
                ("hidden", models.BooleanField(default=False, help_text="是否隐藏")),
                (
                    "update_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default="0000-00-00 00:00:00", help_text="最后更新时间", null=True
                    ),
                ),
                (
                    "instance",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="db_meta.storageinstance"),
                ),
            ],
        ),
    ]
