# Generated by Django 4.2.23 on 2026-01-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0060_versionseries_distribution_versionseries_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbversion",
            name="name",
            field=models.CharField(default="", help_text="版本名称", max_length=128),
        ),
        migrations.AlterField(
            model_name="dbversion",
            name="description",
            field=models.TextField(blank=True, default="", help_text="版本描述"),
        ),
    ]
