# Generated by Django 4.2.23 on 2025-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0062_mongodbstorageinstanceext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mongodbstorageinstanceext",
            name="hidden",
            field=models.IntegerField(default=0, help_text="是否隐藏"),
        ),
    ]
