# Generated by Django 4.2.27 on 2026-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0062_alter_dbversion_unique_together_dbversion_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbversion",
            name="distribution_id",
            field=models.IntegerField(default=0, help_text="发行版ID"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="dbversion",
            unique_together={("full_version", "distribution_id"), ("name", "distribution_id")},
        ),
    ]
