# Generated by Django 4.2.27 on 2026-05-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0063_alter_mongodbstorageinstanceext_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="cloud_inst_id",
            field=models.CharField(blank=True, default="", help_text="云主机实例 ID，例如 ins-xxx", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="storage_device",
            field=models.JSONField(
                default=dict,
                help_text='主机真实磁盘块设备信息: {"/data": {"size": 100, "disk_id": "disk-xxx", "disk_type": "CLOUD_PREMIUM", "file_type": "ext4"}}',
            ),
        ),
    ]
