# Generated by Django 4.2.27 on 2026-04-28 02:17

import backend.db_meta.models.app
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0063_alter_mongodbstorageinstanceext_instance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppOperate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(help_text="业务ID")),
                (
                    "operate_type",
                    models.CharField(
                        choices=[
                            ("dba_change", "人员变更"),
                            ("managed ", "纳管"),
                            ("cancel_managed ", "取消纳管"),
                            ("tag_change", "标签变更"),
                            ("default_dba_change", "默认dba变更"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("tendbcluster", "TenDBCluster"),
                            ("redis", "Redis"),
                            ("mongodb", "MongoDB"),
                            ("kafka", "Kafka"),
                            ("hdfs", "HDFS"),
                            ("es", "ElasticSearch"),
                            ("pulsar", "Pulsar"),
                            ("influxdb", "InfluxDB"),
                            ("riak", "Riak"),
                            ("sqlserver", "SQLServer"),
                            ("doris", "Doris"),
                            ("vm", "Vm"),
                            ("oracle", "Oracle"),
                            ("k8s_surrealdb", "K8s SurrealDB"),
                            ("k8s_victoriametrics", "K8s VictoriaMetrics"),
                            ("k8s_risingwave", "K8s Risingwave"),
                            ("k8s_milvus", "K8s Milvus"),
                            ("k8s_qdrant", "K8s Qdrant"),
                            ("k8s_greptimedb", "K8s GreptimeDB"),
                            ("cloud", "Cloud"),
                            ("tbinlogdumper", "TBinlogDumper"),
                        ],
                        default="",
                        max_length=64,
                        verbose_name="组件类型",
                    ),
                ),
                ("role", models.CharField(default="", max_length=64, verbose_name="变更角色")),
                ("change_before", models.CharField(default="", max_length=128, verbose_name="变更前")),
                ("change_after", models.CharField(default="", max_length=128, verbose_name="变更后")),
            ],
            options={
                "verbose_name": "业务操作记录表(AppOperate)",
                "verbose_name_plural": "业务操作记录表(AppOperate)",
            },
        ),
        migrations.AddField(
            model_name="appcache",
            name="managed_time",
            field=models.DateTimeField(null=True, verbose_name="纳管时间"),
        ),
        migrations.AddField(
            model_name="appcache",
            name="status",
            field=models.CharField(
                choices=[("managed ", "已纳管"), ("unmanaged ", "未纳管")],
                default=backend.db_meta.models.app.AppManagedStatus["UNMANAGED"],
                max_length=20,
                verbose_name="纳管状态",
            ),
        ),
        migrations.AddField(
            model_name="appcache",
            name="tags",
            field=models.ManyToManyField(blank=True, help_text="标签（外键）", to="db_meta.tag"),
        ),
    ]
