# Generated by Django 4.2.27 on 2026-04-28 02:17
import datetime

from django.db import migrations, models
from django.utils import timezone

from backend.configuration.constants import DBType
from backend.db_meta.constants import AppManagedStatus, AppOperateType


def sync_appcache_managed(apps, schema_editor):
    try:
        AppCache = apps.get_model("db_meta", "AppCache")
        Cluster = apps.get_model("db_meta", "Cluster")
        DBAdministrator = apps.get_model("configuration", "DBAdministrator")

        all_biz_ids = set(AppCache.objects.all().values_list("bk_biz_id", flat=True))
        managed_ids = set(Cluster.objects.exclude(phase="destroy").all().values_list("bk_biz_id", flat=True))
        dba_biz_ids = set([dba.bk_biz_id for dba in DBAdministrator.objects.all() if dba.users and len(dba.users) > 0])
        managed_ids.update(dba_biz_ids)
        managed_biz_ids = all_biz_ids & managed_ids
        AppCache.objects.filter(bk_biz_id__in=list(managed_biz_ids)).update(
            status="managed", managed_time=datetime.datetime.now(timezone.utc)
        )
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0064_machine_cloud_inst_id_machine_storage_device"),
        ("configuration", "0009_dbadministrator_update_at_dbadministrator_updater"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppOperate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(help_text="业务ID")),
                (
                    "operate_type",
                    models.CharField(
                        choices=AppOperateType.get_choices(),
                        default="",
                        max_length=64,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=DBType.get_choices(),
                        default="",
                        max_length=64,
                        verbose_name="组件类型",
                    ),
                ),
                ("role", models.CharField(default="", max_length=64, verbose_name="变更角色")),
                ("change_before", models.CharField(default="", max_length=128, verbose_name="变更前")),
                ("change_after", models.CharField(default="", max_length=128, verbose_name="变更后")),
            ],
            options={
                "verbose_name": "业务操作记录表(AppOperate)",
                "verbose_name_plural": "业务操作记录表(AppOperate)",
            },
        ),
        migrations.AddField(
            model_name="appcache",
            name="managed_time",
            field=models.DateTimeField(null=True, verbose_name="纳管时间"),
        ),
        migrations.AddField(
            model_name="appcache",
            name="status",
            field=models.CharField(
                choices=AppManagedStatus.get_choices(),
                default=AppManagedStatus.UNMANAGED,
                max_length=20,
                verbose_name="纳管状态",
            ),
        ),
        migrations.AddField(
            model_name="appcache",
            name="tags",
            field=models.ManyToManyField(blank=True, help_text="标签（外键）", to="db_meta.tag"),
        ),
        migrations.RunPython(sync_appcache_managed),
    ]
