# Generated by Django 4.2.30 on 2026-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0065_appoperate_appcache_managed_time_appcache_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MysqlDtsCluster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(max_length=64, verbose_name="集群名称")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="业务ID")),
                ("bk_cloud_id", models.IntegerField(default=0, verbose_name="云区域ID")),
                (
                    "cluster_id",
                    models.IntegerField(
                        default=0,
                        help_text="已废弃，恒为 0；仅兼容历史数据（曾关联 ClusterType.MySQLDTS）",
                        verbose_name="DBM Cluster ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("deploying", "deploying"), ("running", "running"), ("destroyed", "destroyed")],
                        default="deploying",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("master_nodes", models.JSONField(default=list, verbose_name="Master节点列表")),
                ("worker_nodes", models.JSONField(default=list, verbose_name="Worker节点列表")),
                ("master_addr", models.CharField(default="", max_length=255, verbose_name="dmctl入口")),
                ("deploy_path", models.CharField(default="", max_length=255, verbose_name="部署路径")),
                ("version", models.CharField(default="", max_length=64, verbose_name="版本")),
            ],
            options={
                "verbose_name": "MySQL DTS集群表",
                "verbose_name_plural": "MySQL DTS集群表",
            },
        ),
        migrations.CreateModel(
            name="MysqlDtsInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="关联的业务id")),
                ("source_cluster_ids", models.JSONField(default=list, help_text="源集群ID列表")),
                ("target_cluster_id", models.IntegerField(default=0, help_text="目标集群ID")),
                ("dts_cluster_id", models.IntegerField(default=0, help_text="DTS集群ID")),
                ("migrate_type", models.CharField(default="", help_text="迁移类型", max_length=32)),
                ("migrate_topology", models.CharField(default="", help_text="迁移拓扑", max_length=32)),
                ("ticket_id", models.PositiveIntegerField(default=0, help_text="关联的单据id")),
                ("root_id", models.CharField(default="", help_text="关联root_id", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "待执行"),
                            ("terminated", "已终止"),
                            ("disconnected", "已断开"),
                            ("full_online", "全量传输中"),
                            ("full_failed", "全量传输失败"),
                        ],
                        default="todo",
                        help_text="状态",
                        max_length=64,
                    ),
                ),
                ("sync_scope_snapshot", models.JSONField(default=dict, help_text="同步范围快照")),
                ("dts_task_config_snapshot", models.JSONField(default=dict, help_text="任务配置快照")),
                ("temp_account_snapshot", models.JSONField(default=dict, help_text="DTS临时账号快照(不含密码)")),
                ("dts_task_id", models.CharField(default="", help_text="DTS任务ID", max_length=64)),
                ("dts_source_names", models.JSONField(default=list, help_text="DTS Source名称列表")),
            ],
            options={
                "verbose_name": "MySQL DTS数据迁移记录表",
                "verbose_name_plural": "MySQL DTS数据迁移记录表",
            },
        ),
    ]
