# Generated by Django 4.2.30 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0066_mysqldtscluster_mysqldtsinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="storage_nodes",
            field=models.JSONField(blank=True, default=list, help_text="外部存储节点列表", null=True),
        ),
    ]
