// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
	"schemes": {{ marshal .Schemes }},
	"swagger": "2.0",
	"info": {
		"description": "{{escape .Description}}",
		"title": "{{.Title}}",
		"termsOfService": "http://swagger.io/terms/",
		"contact": {
			"name": "API Support",
			"url": "http://www.swagger.io/support",
			"email": "support@swagger.io"
		},
		"license": {
			"name": "Apache 2.0",
			"url": "http://www.apache.org/licenses/LICENSE-2.0.html"
		},
		"version": "{{.Version}}"
	},
	"host": "{{.Host}}",
	"basePath": "{{.BasePath}}",
	"paths": {
		"/bkconfig/v1/conffile/add": {
			"post": {
				"description": "新增平台级配置文件，定义允许的配置名。指定 req_type 为 ` + "`" + `SaveOnly` + "`" + ` 仅保存, ` + "`" + `SaveAndPublish` + "`" + ` 保存并发布。保存并发布 也必须提供全量，而不能是前面保存基础上的增量\nreq_type=` + "`" + `SaveOnly` + "`" + ` 已废弃\n第一次保存时，会返回 ` + "`" + `file_id` + "`" + `，下次 保存/发布 需传入 ` + "`" + `file_id` + "`" + `\nnamespace,conf_type,conf_file 唯一确定一个配置文件，不同DB版本信息体现在 conf_file 里 (如MySQL-5.7), namespace_info 可以存前端传入的 数据库版本，只用于在展示\nHTTP Header 指定 ` + "`" + `X-Bkapi-User-Name` + "`" + ` 请求的操作人员",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"plat_config"
				],
				"summary": "新增平台级配置文件",
				"parameters": [
					{
						"description": "ConfName for ConfType",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/api.UpsertConfFilePlatReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/api.UpsertConfFilePlatResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/conffile/list": {
			"get": {
				"description": "查询配置文件模板列表。只有平台和业务才有配置文件列表\n返回的 updated_by 代表操作人",
				"produces": [
					"application/json"
				],
				"tags": [
					"plat_config"
				],
				"summary": "查询配置文件列表",
				"parameters": [
					{
						"type": "string",
						"description": "业务id, bk_biz_id=0 代表平台配置",
						"name": "bk_biz_id",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"description": "如果指定了 conf_file 则只查这一个文件信息",
						"name": "conf_file",
						"in": "query"
					},
					{
						"type": "string",
						"example": "dbconf",
						"name": "conf_type",
						"in": "query",
						"required": true
					},
					{
						"enum": [
							"plat",
							"app",
							"module",
							"cluster"
						],
						"type": "string",
						"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
						"name": "level_name",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"description": "配置层级值",
						"name": "level_value",
						"in": "query"
					},
					{
						"type": "string",
						"description": "命名空间，一般指DB类型",
						"name": "namespace",
						"in": "query",
						"required": true
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/api.ListConfFileResp"
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/conffile/query": {
			"get": {
				"description": "查询 平台配置 某个配置类型/配置文件的所有配置名列表",
				"produces": [
					"application/json"
				],
				"tags": [
					"plat_config"
				],
				"summary": "查询平台配置项列表",
				"parameters": [
					{
						"type": "string",
						"example": "MySQL-5.7",
						"name": "conf_file",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"description": "如果设置，会根据前缀模糊匹配搜索",
						"name": "conf_name",
						"in": "query"
					},
					{
						"type": "string",
						"example": "dbconf",
						"name": "conf_type",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "tendbha",
						"name": "namespace",
						"in": "query"
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/QueryConfigNamesResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/conffile/update": {
			"post": {
				"description": "编辑平台级配置文件。指定 req_type 为 ` + "`" + `SaveOnly` + "`" + ` 仅保存, ` + "`" + `SaveAndPublish` + "`" + ` 保存并发布\nHTTP Header 指定 ` + "`" + `X-Bkapi-User-Name` + "`" + ` 请求的操作人员\n编辑平台配置时，如果设置 flag_disable=1 时，该配置不会显示在平台配置项列表，相当于管理 所有允许的配置项列表\n保存时会校验输入的 value_default, value_type, value_allowed\n1. value_type 目前允许 STRING, INT, FLOAT, NUMBER\n2. value_type_sub 允许 ENUM, ENUMS, RANGE, STRING, JSON, REGEX(一种特殊的STRING，会验证 value_default 是否满足 value_allowed 正则)\n3. value_allowed 允许 枚举: 例如` + "`" + `0|1|2` + "`" + `, ` + "`" + `ON|OFF` + "`" + ` 格式， 范围: 例如` + "`" + `(0, 1000]` + "`" + `",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"plat_config"
				],
				"summary": "编辑平台级配置文件",
				"parameters": [
					{
						"description": "ConfName for ConfType",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/api.UpsertConfFilePlatReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/api.UpsertConfFilePlatResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/confitem/query": {
			"post": {
				"description": "根据业务/模块/集群的信息，获取某个配置文件的配置项。一般用户前端请求、再编辑的场景，后端服务直接获取配置文件使用 /version/generate 接口\nconf_file 可以是,号分隔的多个文件名，返回结果是一个按照配置文件名组合的一个 list\n需要指定返回格式 format, 可选值 map, list.\nmap 格式会丢弃 conf_item 的其它信息，只保留 conf_name=conf_value, 一般用于后台服务\nlist 格式会保留 conf_items 的其它信息，conf_name=conf_item，一般用于前端展示\n获取cluster级别配置时，需要提供 level_info:{\"module\":\"xxx\"} 模块信息",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"config_item"
				],
				"summary": "获取配置文件配置项列表",
				"parameters": [
					{
						"description": "GetConfigItemsReq",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/GetConfigItemsReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/GetConfigItemsResp"
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/confitem/save": {
			"post": {
				"description": "编辑层级配置，层级包括业务app、模块module、集群cluster，需要指定修改哪个级别的配置，通过 level_name, level_value 来区分\n针对编辑的配置类型 conf_type 无版本化的概念，即保存生效，无需发布\n保存 cluster级别配置时，需要提供 level_info:{\"module\":\"xxx\"} 模块信息",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"config_item"
				],
				"summary": "编辑配置(无版本概念)",
				"parameters": [
					{
						"description": "SaveConfItemsReq",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/api.SaveConfItemsReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/api.UpsertConfItemsResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/confitem/upsert": {
			"post": {
				"description": "编辑层级配置，层级包括业务app、模块module、集群cluster，需要指定修改哪个级别的配置，通过 level_name, level_value 来区分\n例1: level_name=app, level_value=testapp 表示修改业务 bk_biz_id=testapp 的配置\n例2: level_name=module, level_value=account 表示某业务 bk_biz_id 的模块 module=account 的配置\nHTTP Header 指定 ` + "`" + `X-Bkapi-User-Name` + "`" + ` 请求的操作人员\n获取cluster级别配置时，需要提供 level_info:{\"module\":\"xxx\"} 模块信息",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"config_item"
				],
				"summary": "编辑发布层级配置",
				"parameters": [
					{
						"description": "UpsertConfItemsReq",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/api.UpsertConfItemsReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/api.UpsertConfItemsResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/confname/list": {
			"get": {
				"description": "查询某个配置类型/配置文件的配置名列表，会排除 已锁定的平台配置",
				"produces": [
					"application/json"
				],
				"tags": [
					"config_meta"
				],
				"summary": "查询预定义的配置名列表",
				"parameters": [
					{
						"type": "string",
						"example": "MySQL-5.7",
						"name": "conf_file",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"description": "如果设置，会根据前缀模糊匹配搜索",
						"name": "conf_name",
						"in": "query"
					},
					{
						"type": "string",
						"example": "dbconf",
						"name": "conf_type",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "tendbha",
						"name": "namespace",
						"in": "query"
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/QueryConfigNamesResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/simpleitem/list": {
			"get": {
				"description": "请勿使用",
				"produces": [
					"application/json"
				],
				"tags": [
					"simple_item"
				],
				"summary": "查询配置项列表通用接口",
				"parameters": [
					{
						"type": "string",
						"name": "bk_biz_id",
						"in": "query"
					},
					{
						"type": "string",
						"name": "cluster",
						"in": "query"
					},
					{
						"type": "string",
						"name": "conf_file",
						"in": "query"
					},
					{
						"type": "string",
						"name": "conf_name",
						"in": "query"
					},
					{
						"type": "string",
						"name": "conf_type",
						"in": "query"
					},
					{
						"type": "string",
						"name": "conf_value",
						"in": "query"
					},
					{
						"type": "string",
						"name": "created_at",
						"in": "query"
					},
					{
						"type": "string",
						"name": "created_by",
						"in": "query"
					},
					{
						"type": "string",
						"name": "description",
						"in": "query"
					},
					{
						"type": "string",
						"name": "format",
						"in": "query"
					},
					{
						"type": "string",
						"name": "inherit_from",
						"in": "query"
					},
					{
						"type": "string",
						"name": "level_name",
						"in": "query"
					},
					{
						"type": "string",
						"name": "level_value",
						"in": "query"
					},
					{
						"type": "string",
						"name": "module",
						"in": "query"
					},
					{
						"type": "string",
						"name": "namespace",
						"in": "query"
					},
					{
						"type": "string",
						"name": "revision",
						"in": "query"
					},
					{
						"type": "string",
						"name": "updated_at",
						"in": "query"
					},
					{
						"type": "string",
						"name": "updated_by",
						"in": "query"
					},
					{
						"type": "string",
						"name": "view",
						"in": "query"
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/model.ConfigModel"
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/version/detail": {
			"get": {
				"description": "查询历史配置版本的详情",
				"produces": [
					"application/json"
				],
				"tags": [
					"config_version"
				],
				"summary": "查询版本的详细信息",
				"parameters": [
					{
						"type": "string",
						"example": "testapp",
						"description": "业务ID，必选项",
						"name": "bk_biz_id",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "MySQL-5.7",
						"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
						"name": "conf_file",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "dbconf",
						"description": "配置类型，如 dbconf,backup",
						"name": "conf_type",
						"in": "query",
						"required": true
					},
					{
						"enum": [
							"plat",
							"app",
							"module",
							"cluster"
						],
						"type": "string",
						"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
						"name": "level_name",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"description": "配置层级值",
						"name": "level_value",
						"in": "query"
					},
					{
						"type": "string",
						"example": "tendbha",
						"description": "命名空间，一般指DB类型",
						"name": "namespace",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "v_20220309215824",
						"name": "revision",
						"in": "query"
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/api.GetVersionedDetailResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/version/generate": {
			"post": {
				"description": "从现有配置项直接生成配置文件并返回，每次调用会生成一个新版本，可以选择是否直接发布。这个接口一般用户后台服务查询配置\n修改配置并发布，使用 /confitem/upsert 接口\n直接查询配置文件内容，使用 /confitem/query 接口\n根据 ` + "`" + `method` + "`" + ` 生成方式不同，可以生成配置并存储 ` + "`" + `GenerateAndSave` + "`" + `、生成配置并存储且发布` + "`" + `GenerateAndPublish` + "`" + `\n使用 ` + "`" + `GenerateAndSave` + "`" + ` 方式需要进一步调用 PublishConfigFile 接口进行发布",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"config_version"
				],
				"summary": "生成并获取配置文件新版本",
				"parameters": [
					{
						"description": "Generate config file versioned",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/GenerateConfigReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/GenerateConfigResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/version/list": {
			"get": {
				"description": "Get config file versions list",
				"produces": [
					"application/json"
				],
				"tags": [
					"config_version"
				],
				"summary": "查询历史配置版本名列表",
				"parameters": [
					{
						"type": "string",
						"example": "testapp",
						"description": "业务ID，必选项",
						"name": "bk_biz_id",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "MySQL-5.7",
						"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
						"name": "conf_file",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"example": "dbconf",
						"description": "配置类型，如 dbconf,backup",
						"name": "conf_type",
						"in": "query",
						"required": true
					},
					{
						"enum": [
							"plat",
							"app",
							"module",
							"cluster"
						],
						"type": "string",
						"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
						"name": "level_name",
						"in": "query",
						"required": true
					},
					{
						"type": "string",
						"description": "配置层级值",
						"name": "level_value",
						"in": "query"
					},
					{
						"type": "string",
						"example": "tendbha",
						"description": "命名空间，一般指DB类型",
						"name": "namespace",
						"in": "query",
						"required": true
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/ListConfigVersionsResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		},
		"/bkconfig/v1/version/publish": {
			"post": {
				"description": "发布指定版本的配置文件，未发布状态的配置文件是不能使用的\n发布操作会把已有 published 状态的配置文件下线；同一个 revision 版本的配置无法重复发布\n发布时带上 patch 参数可以覆盖配置中心该版本的配置项(只有配置项值是` + "`" + `{{` + "`" + `开头的才能被覆盖)",
				"consumes": [
					"application/json"
				],
				"produces": [
					"application/json"
				],
				"tags": [
					"config_version"
				],
				"summary": "直接发布一个版本[废弃]",
				"parameters": [
					{
						"description": "Publish config file versioned",
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {
							"$ref": "#/definitions/PublishConfigFileReq"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/api.HTTPOkNilResp"
						}
					},
					"400": {
						"description": "Bad Request",
						"schema": {
							"$ref": "#/definitions/api.HTTPClientErrResp"
						}
					}
				}
			}
		}
	},
	"definitions": {
		"GenerateConfigReq": {
			"type": "object",
			"required": [
				"bk_biz_id",
				"conf_file",
				"conf_type",
				"format",
				"level_name",
				"method",
				"namespace"
			],
			"properties": {
				"bk_biz_id": {
					"description": "业务ID，必选项",
					"type": "string",
					"example": "testapp"
				},
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"format": {
					"description": "` + "`" + `map.` + "`" + `, ` + "`" + `map#` + "`" + `, ` + "`" + `map|` + "`" + ` 是特殊的map格式，返回结果会以 . 或者 # 或者 | 拆分 conf_name",
					"type": "string",
					"enum": [
						"list",
						"map",
						"map.",
						"map#",
						"map|"
					]
				},
				"level_info": {
					"description": "上层级信息，如获取当前层级 cluster=c1 的配置，需要设置 level_info: {\"module\": \"m1\"} 提供cluster所属上级 module 的信息\n非必选项，目前只在查询 cluster 级别配置时需要指定模块信息有用\ntodo 将来可能本配置中心，直接请求dbmeta元数据来获取 可能的 app-module-cluster-host-instance 关系",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				},
				"method": {
					"description": "method must be one of GenerateOnly|GenerateAndSave|GenerateAndPublish\n` + "`" + `GenerateOnly` + "`" + `: generate merged config\n` + "`" + `GenerateAndSave` + "`" + `: generate and save the merged config to db (snapshot).\n` + "`" + `GenerateAndPublish` + "`" + `: generate and save the merged config to db, and mark it as published (release)",
					"type": "string",
					"enum": [
						"GenerateAndSave",
						"GenerateAndPublish"
					]
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				}
			}
		},
		"GenerateConfigResp": {
			"type": "object",
			"required": [
				"level_name"
			],
			"properties": {
				"bk_biz_id": {
					"type": "string"
				},
				"conf_file": {
					"type": "string"
				},
				"content": {
					"description": "content is a {conf_name:conf_type} dict like {\"a\":1, \"b\":\"string\"}",
					"type": "object",
					"additionalProperties": true
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				},
				"revision": {
					"description": "version name for this config_file generation",
					"type": "string"
				}
			}
		},
		"GetConfigItemsReq": {
			"type": "object",
			"required": [
				"bk_biz_id",
				"conf_file",
				"conf_type",
				"format",
				"level_name",
				"namespace"
			],
			"properties": {
				"bk_biz_id": {
					"description": "业务ID，必选项",
					"type": "string",
					"example": "testapp"
				},
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_name": {
					"description": "指定要查询的 conf_name， 多个值以,分隔，为空表示查询该 conf_file 的所有conf_name",
					"type": "string"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"format": {
					"description": "` + "`" + `map.` + "`" + `, ` + "`" + `map#` + "`" + `, ` + "`" + `map|` + "`" + ` 是特殊的map格式，返回结果会以 . 或者 # 或者 | 拆分 conf_name",
					"type": "string",
					"enum": [
						"list",
						"map",
						"map.",
						"map#",
						"map|"
					]
				},
				"level_info": {
					"description": "上层级信息，如获取当前层级 cluster=c1 的配置，需要设置 level_info: {\"module\": \"m1\"} 提供cluster所属上级 module 的信息\n非必选项，目前只在查询 cluster 级别配置时需要指定模块信息有用\ntodo 将来可能本配置中心，直接请求dbmeta元数据来获取 可能的 app-module-cluster-host-instance 关系",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				}
			}
		},
		"GetConfigItemsResp": {
			"type": "object",
			"required": [
				"conf_file",
				"conf_type",
				"level_name",
				"namespace"
			],
			"properties": {
				"bk_biz_id": {
					"type": "string"
				},
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_file_lc": {
					"description": "配置文件中文名，也可以是其它 locale 语言类型",
					"type": "string",
					"example": "5.7_参数配置"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"conf_type_lc": {
					"description": "配置类型中文名",
					"type": "string",
					"example": "DB参数配置"
				},
				"content": {
					"description": "content is a {conf_name:conf_type} dict like {\"a\":1, \"b\":\"string\"}",
					"type": "object",
					"additionalProperties": true
				},
				"created_at": {
					"type": "string"
				},
				"description": {
					"description": "配置文件的描述",
					"type": "string"
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"namespace_info": {
					"description": "namespace信息，比如数据库版本，与 conf_file 对应",
					"type": "string",
					"example": "MySQL 5.7"
				},
				"updated_at": {
					"type": "string"
				},
				"updated_by": {
					"type": "string"
				}
			}
		},
		"ListConfigVersionsResp": {
			"type": "object",
			"required": [
				"level_name"
			],
			"properties": {
				"bk_biz_id": {
					"type": "string"
				},
				"conf_file": {
					"type": "string"
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				},
				"namespace": {
					"type": "string"
				},
				"published": {
					"description": "version published. empty when published version is not in versions",
					"type": "string"
				},
				"versions": {
					"description": "版本列表，格式 [{\"revision\":\"v1\", \"rows_affected\":1},{\"revision\":\"v2\", \"rows_affected\":2}]",
					"type": "array",
					"items": {
						"type": "object",
						"additionalProperties": true
					}
				}
			}
		},
		"PublishConfigFileReq": {
			"type": "object",
			"required": [
				"bk_biz_id",
				"conf_file",
				"conf_type",
				"namespace",
				"revision"
			],
			"properties": {
				"bk_biz_id": {
					"description": "业务ID，必选项",
					"type": "string",
					"example": "testapp"
				},
				"cluster": {
					"type": "string"
				},
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"patch": {
					"description": "patch will overwrite conf_value to versioned config_file. it's a key-value dict",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"revision": {
					"description": "the version you want to publish",
					"type": "string",
					"example": "v_20220309161928"
				}
			}
		},
		"QueryConfigNamesResp": {
			"type": "object",
			"properties": {
				"conf_file": {
					"type": "string"
				},
				"conf_names": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/api.ConfNameDef"
					}
				}
			}
		},
		"api.ConfFileDef": {
			"type": "object",
			"required": [
				"conf_file",
				"conf_type",
				"namespace"
			],
			"properties": {
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_file_lc": {
					"description": "配置文件中文名，也可以是其它 locale 语言类型",
					"type": "string",
					"example": "5.7_参数配置"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"conf_type_lc": {
					"description": "配置类型中文名",
					"type": "string",
					"example": "DB参数配置"
				},
				"description": {
					"description": "配置文件的描述",
					"type": "string"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"namespace_info": {
					"description": "namespace信息，比如数据库版本，与 conf_file 对应",
					"type": "string",
					"example": "MySQL 5.7"
				}
			}
		},
		"api.ConfNameDef": {
			"type": "object",
			"required": [
				"conf_name",
				"value_type"
			],
			"properties": {
				"conf_name": {
					"description": "配置项，也叫参数项",
					"type": "string"
				},
				"conf_name_lc": {
					"description": "配置项中文名，可不填",
					"type": "string"
				},
				"description": {
					"description": "配置项说明",
					"type": "string"
				},
				"flag_disable": {
					"description": "是否禁用，代表该配置项状态. 默认0启用",
					"type": "integer",
					"example": 0
				},
				"flag_locked": {
					"description": "是否锁定. 默认0",
					"type": "integer",
					"example": 0
				},
				"need_restart": {
					"description": "是否需要重启生效. 默认1",
					"type": "integer",
					"example": 1
				},
				"value_allowed": {
					"description": "允许设定值，如枚举/范围等，为空时表示不限制范围\n当 value_type_sub=ENUM 时，value_allowed 格式 0|1 或者 ON|OFF 或者 aaa|bbb|ccc ， 会校验value的合法性\n当 value_type_sub=REGEX 时，会根据 value_allowed 进行正则校验\n当 value_type_sub=RANGE 时，也会校验value 范围的合法性.\n - BYTES 是一种特殊的RANGE，value允许1mm 但value_allowed 必须是数字的range",
					"type": "string"
				},
				"value_default": {
					"description": "配置项默认值",
					"type": "string",
					"example": "1"
				},
				"value_type": {
					"description": "配置项的值类型，如 ` + "`" + `STRING` + "`" + `,` + "`" + `INT` + "`" + `,` + "`" + `FLOAT` + "`" + `,` + "`" + `NUMBER` + "`" + `",
					"type": "string",
					"enum": [
						"STRING",
						"INT",
						"FLOAT",
						"NUMBER"
					],
					"example": "STRING"
				},
				"value_type_sub": {
					"description": "value_type 的子类型，如果设置则用于校验 value_type 的具体类型，或者返回用于告知前端控件类型，例如 ENUM,RANGE",
					"type": "string",
					"enum": [
						"",
						"STRING",
						"ENUM",
						"RANGE",
						"BYTES",
						"REGEX",
						"JSON",
						"COMPLEX"
					],
					"example": "ENUM"
				}
			}
		},
		"api.GetVersionedDetailResp": {
			"type": "object",
			"properties": {
				"configs": {
					"description": "配置项",
					"type": "object",
					"additionalProperties": true
				},
				"configs_diff": {
					"description": "与上一个版本的差异",
					"type": "object",
					"additionalProperties": true
				},
				"content": {
					"type": "string"
				},
				"created_at": {
					"description": "发布时间",
					"type": "string"
				},
				"created_by": {
					"description": "发布人",
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"id": {
					"type": "integer"
				},
				"is_published": {
					"type": "integer"
				},
				"pre_revision": {
					"description": "上一个版本好",
					"type": "string"
				},
				"revision": {
					"description": "版本号",
					"type": "string"
				},
				"rows_affected": {
					"description": "相对上一个版本 影响行数",
					"type": "integer"
				}
			}
		},
		"api.HTTPClientErrResp": {
			"type": "object",
			"properties": {
				"code": {
					"type": "integer",
					"example": 400
				},
				"data": {},
				"message": {
					"description": "status bad request",
					"type": "string",
					"example": "输入参数错误"
				}
			}
		},
		"api.HTTPOkNilResp": {
			"type": "object",
			"properties": {
				"code": {
					"type": "integer",
					"example": 200
				},
				"data": {},
				"message": {
					"type": "string"
				}
			}
		},
		"api.ListConfFileResp": {
			"type": "object",
			"required": [
				"conf_file",
				"conf_type",
				"namespace"
			],
			"properties": {
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_file_lc": {
					"description": "配置文件中文名，也可以是其它 locale 语言类型",
					"type": "string",
					"example": "5.7_参数配置"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"conf_type_lc": {
					"description": "配置类型中文名",
					"type": "string",
					"example": "DB参数配置"
				},
				"created_at": {
					"description": "创建时间",
					"type": "string"
				},
				"description": {
					"description": "配置文件的描述",
					"type": "string"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"namespace_info": {
					"description": "namespace信息，比如数据库版本，与 conf_file 对应",
					"type": "string",
					"example": "MySQL 5.7"
				},
				"updated_at": {
					"description": "更新时间",
					"type": "string"
				},
				"updated_by": {
					"description": "更新人",
					"type": "string"
				}
			}
		},
		"api.SaveConfItemsReq": {
			"type": "object",
			"required": [
				"bk_biz_id",
				"level_name"
			],
			"properties": {
				"bk_biz_id": {
					"description": "业务ID，必选项",
					"type": "string",
					"example": "testapp"
				},
				"conf_file_info": {
					"$ref": "#/definitions/api.ConfFileDef"
				},
				"conf_items": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/api.UpsertConfItem"
					}
				},
				"confirm": {
					"description": "保存时如果与下层级存在冲突，提示确认，用 confirm=1 重新请求",
					"type": "integer"
				},
				"description": {
					"description": "发布描述",
					"type": "string"
				},
				"level_info": {
					"description": "上层级信息，如获取当前层级 cluster=c1 的配置，需要设置 level_info: {\"module\": \"m1\"} 提供cluster所属上级 module 的信息\n非必选项，目前只在查询 cluster 级别配置时需要指定模块信息有用\ntodo 将来可能本配置中心，直接请求dbmeta元数据来获取 可能的 app-module-cluster-host-instance 关系",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				}
			}
		},
		"api.UpsertConfFilePlatReq": {
			"type": "object",
			"required": [
				"conf_file",
				"conf_type",
				"namespace",
				"req_type"
			],
			"properties": {
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_file_lc": {
					"description": "配置文件中文名，也可以是其它 locale 语言类型",
					"type": "string",
					"example": "5.7_参数配置"
				},
				"conf_names": {
					"description": "如果revision为空，表示第一次保存。每次 update 操作都会返回 revision，确保在这一轮编辑操作下都是操作这个revision\n已发布的 revision 不能编辑\nRevision string ` + "`" + `json:\"revision\" form:\"revision\"` + "`" + `",
					"type": "array",
					"items": {
						"$ref": "#/definitions/api.UpsertConfNames"
					}
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"conf_type_lc": {
					"description": "配置类型中文名",
					"type": "string",
					"example": "DB参数配置"
				},
				"confirm": {
					"description": "保存时如果与下层级存在冲突，提示确认，用 confirm=1 重新请求",
					"type": "integer"
				},
				"description": {
					"description": "配置文件的描述",
					"type": "string"
				},
				"file_id": {
					"description": "新建配置文件，第一次保存返回 file_id, 后续保存/发布 需传入 file_id",
					"type": "integer"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"namespace_info": {
					"description": "namespace信息，比如数据库版本，与 conf_file 对应",
					"type": "string",
					"example": "MySQL 5.7"
				},
				"req_type": {
					"description": "配置文件修改动作的请求类型，` + "`" + `SaveOnly` + "`" + `: 仅保存, ` + "`" + `SaveAndPublish` + "`" + `保存并发布",
					"type": "string",
					"enum": [
						"SaveOnly",
						"SaveAndPublish"
					]
				}
			}
		},
		"api.UpsertConfFilePlatResp": {
			"type": "object",
			"required": [
				"conf_file",
				"conf_type",
				"namespace"
			],
			"properties": {
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"file_id": {
					"type": "integer"
				},
				"is_published": {
					"type": "integer"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"revision": {
					"description": "编辑配置文件，仅保存时不会产生 revision，保存并发布时才返回",
					"type": "string"
				}
			}
		},
		"api.UpsertConfItem": {
			"type": "object",
			"required": [
				"conf_name",
				"op_type"
			],
			"properties": {
				"conf_name": {
					"description": "配置项名称",
					"type": "string"
				},
				"conf_value": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"extra_info": {
					"type": "string"
				},
				"flag_disable": {
					"description": "是否禁用，默认 0 表示启用. 1表示禁用",
					"type": "integer",
					"example": 0
				},
				"flag_locked": {
					"description": "是否锁定，默认 0 表上不锁定",
					"type": "integer",
					"example": 0
				},
				"op_type": {
					"description": "配置项修改动作，需提供操作类型字段，允许值 ` + "`" + `add` + "`" + `,` + "`" + `update` + "`" + `,` + "`" + `remove` + "`" + `",
					"type": "string",
					"enum": [
						"add",
						"update",
						"remove"
					]
				}
			}
		},
		"api.UpsertConfItemsReq": {
			"type": "object",
			"required": [
				"bk_biz_id",
				"level_name",
				"req_type"
			],
			"properties": {
				"bk_biz_id": {
					"description": "业务ID，必选项",
					"type": "string",
					"example": "testapp"
				},
				"conf_file_info": {
					"$ref": "#/definitions/api.ConfFileDef"
				},
				"conf_items": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/api.UpsertConfItem"
					}
				},
				"confirm": {
					"description": "保存时如果与下层级存在冲突，提示确认，用 confirm=1 重新请求",
					"type": "integer"
				},
				"description": {
					"description": "发布描述",
					"type": "string"
				},
				"level_info": {
					"description": "上层级信息，如获取当前层级 cluster=c1 的配置，需要设置 level_info: {\"module\": \"m1\"} 提供cluster所属上级 module 的信息\n非必选项，目前只在查询 cluster 级别配置时需要指定模块信息有用\ntodo 将来可能本配置中心，直接请求dbmeta元数据来获取 可能的 app-module-cluster-host-instance 关系",
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"level_name": {
					"description": "配置层级名，当前允许值 ` + "`" + `app` + "`" + `,` + "`" + `module` + "`" + `,` + "`" + `cluster` + "`" + `\n配合 flag_locked 锁定标记，可以知道 锁定级别",
					"type": "string",
					"enum": [
						"plat",
						"app",
						"module",
						"cluster"
					]
				},
				"level_value": {
					"description": "配置层级值",
					"type": "string"
				},
				"req_type": {
					"description": "配置文件修改动作的请求类型，` + "`" + `SaveOnly` + "`" + `: 仅保存, ` + "`" + `SaveAndPublish` + "`" + `保存并发布",
					"type": "string",
					"enum": [
						"SaveOnly",
						"SaveAndPublish"
					]
				},
				"revision": {
					"type": "string"
				}
			}
		},
		"api.UpsertConfItemsResp": {
			"type": "object",
			"required": [
				"conf_file",
				"conf_type",
				"namespace"
			],
			"properties": {
				"bk_biz_id": {
					"type": "string"
				},
				"conf_file": {
					"description": "配置文件名，一般配置类型与配置文件一一对应，但如 mysql 5.6, 5.7 两个版本同属 dbconf 配置，所以有 MySQL-5.5, MySQL-5.6 两个配置文件",
					"type": "string",
					"example": "MySQL-5.7"
				},
				"conf_type": {
					"description": "配置类型，如 dbconf,backup",
					"type": "string",
					"example": "dbconf"
				},
				"is_published": {
					"type": "integer"
				},
				"namespace": {
					"description": "命名空间，一般指DB类型",
					"type": "string",
					"example": "tendbha"
				},
				"revision": {
					"description": "编辑配置文件，第一次保存返回 revision, 后续保存/发布 需传入 revision",
					"type": "string"
				}
			}
		},
		"api.UpsertConfNames": {
			"type": "object",
			"required": [
				"conf_name",
				"op_type",
				"value_type"
			],
			"properties": {
				"conf_name": {
					"description": "配置项，也叫参数项",
					"type": "string"
				},
				"conf_name_lc": {
					"description": "配置项中文名，可不填",
					"type": "string"
				},
				"description": {
					"description": "配置项说明",
					"type": "string"
				},
				"flag_disable": {
					"description": "是否禁用，代表该配置项状态. 默认0启用",
					"type": "integer",
					"example": 0
				},
				"flag_locked": {
					"description": "是否锁定. 默认0",
					"type": "integer",
					"example": 0
				},
				"need_restart": {
					"description": "是否需要重启生效. 默认1",
					"type": "integer",
					"example": 1
				},
				"op_type": {
					"description": "配置项修改动作，需提供操作类型字段，允许值 ` + "`" + `add` + "`" + `,` + "`" + `update` + "`" + `,` + "`" + `remove` + "`" + `",
					"type": "string",
					"enum": [
						"add",
						"update",
						"remove"
					]
				},
				"value_allowed": {
					"description": "允许设定值，如枚举/范围等，为空时表示不限制范围\n当 value_type_sub=ENUM 时，value_allowed 格式 0|1 或者 ON|OFF 或者 aaa|bbb|ccc ， 会校验value的合法性\n当 value_type_sub=REGEX 时，会根据 value_allowed 进行正则校验\n当 value_type_sub=RANGE 时，也会校验value 范围的合法性.\n - BYTES 是一种特殊的RANGE，value允许1mm 但value_allowed 必须是数字的range",
					"type": "string"
				},
				"value_default": {
					"description": "配置项默认值",
					"type": "string",
					"example": "1"
				},
				"value_type": {
					"description": "配置项的值类型，如 ` + "`" + `STRING` + "`" + `,` + "`" + `INT` + "`" + `,` + "`" + `FLOAT` + "`" + `,` + "`" + `NUMBER` + "`" + `",
					"type": "string",
					"enum": [
						"STRING",
						"INT",
						"FLOAT",
						"NUMBER"
					],
					"example": "STRING"
				},
				"value_type_sub": {
					"description": "value_type 的子类型，如果设置则用于校验 value_type 的具体类型，或者返回用于告知前端控件类型，例如 ENUM,RANGE",
					"type": "string",
					"enum": [
						"",
						"STRING",
						"ENUM",
						"RANGE",
						"BYTES",
						"REGEX",
						"JSON",
						"COMPLEX"
					],
					"example": "ENUM"
				}
			}
		},
		"model.ConfigModel": {
			"type": "object",
			"properties": {
				"bk_biz_id": {
					"type": "string"
				},
				"conf_file": {
					"type": "string"
				},
				"conf_name": {
					"type": "string"
				},
				"conf_type": {
					"type": "string"
				},
				"conf_value": {
					"type": "string"
				},
				"created_at": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"extra_info": {
					"type": "string"
				},
				"flag_disable": {
					"type": "integer"
				},
				"flag_locked": {
					"type": "integer"
				},
				"id": {
					"type": "integer"
				},
				"level_locked": {
					"type": "string"
				},
				"level_name": {
					"type": "string"
				},
				"level_value": {
					"type": "string"
				},
				"namespace": {
					"type": "string"
				},
				"updated_at": {
					"type": "string"
				}
			}
		}
	},
	"securityDefinitions": {
		"BasicAuth": {
			"type": "basic"
		}
	}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "bkconfigsvr API",
	Description:      "This is a bkconfigsvr celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
