basePath: /
host: localhost:80
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a bkconfigsvr celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: bkconfigsvr API
  version: 0.0.1
paths: {}
schemes:
- http
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
