# Generated by Django 3.2.19 on 2023-11-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("open_area", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tendbopenareaconfig",
            name="bk_biz_id",
            field=models.IntegerField(help_text="业务ID"),
        ),
    ]
