# Generated by Django 3.2.19 on 2023-08-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBPeriodicTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="周期任务名称")),
                (
                    "task_type",
                    models.CharField(
                        choices=[("remote", "远程 API 周期任务"), ("local", "本地函数周期任务")], max_length=32, verbose_name="任务类型"
                    ),
                ),
                ("is_frozen", models.BooleanField(default=False, help_text="人工冻结此任务，将不受更新影响", verbose_name="是否冻结")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                        verbose_name="celery 周期任务实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "周期任务 PeriodicTask",
                "verbose_name_plural": "周期任务 PeriodicTask",
                "ordering": ["-id"],
            },
        ),
    ]
