# Generated by Django 3.2.25 on 2024-06-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dbperiodictask",
            options={
                "ordering": ["-id"],
                "verbose_name": "周期任务(PeriodicTask)",
                "verbose_name_plural": "周期任务(PeriodicTask)",
            },
        ),
    ]
