# Generated by Django 3.2.25 on 2025-07-02 11:30

import django.utils.timezone
from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0002_alter_dbperiodictask_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySQLBackupRecoverTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, verbose_name="演练业务ID")),
                ("cluster_id", models.IntegerField(default=0, verbose_name="备份来源集群ID")),
                ("cluster_domain", models.CharField(default="", max_length=255, verbose_name="备份来源域名")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("backup_id", models.CharField(default="", max_length=255, verbose_name="备份ID")),
                ("backup_begin_time", models.DateTimeField(default=None, verbose_name="备份开始时间")),
                ("backup_end_time", models.DateTimeField(default=None, verbose_name="备份结束时间")),
                ("backup_total_size", models.IntegerField(default=0, verbose_name="备份总大小")),
                ("backup_type", models.CharField(default="", max_length=32, verbose_name="备份类型")),
                ("backup_tool", models.CharField(default="", max_length=32, verbose_name="备份工具")),
                ("time_zone", models.CharField(default="", max_length=32, verbose_name="时区")),
                (
                    "recover_start_time",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="备份恢复开始时间"),
                ),
                ("recover_end_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="备份恢复结束时间")),
                ("task_id", models.CharField(default="", max_length=255, verbose_name="关联的任务ID")),
                ("task_status", models.CharField(default="", max_length=32, verbose_name="任务状态")),
                ("task_info", models.TextField(default="", verbose_name="任务信息")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
