# Generated by Django 3.2.25 on 2025-07-22 04:24

from django.db import migrations, models

from backend.db_meta.enums import ClusterType


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0003_mysqlbackuprecovertask"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailoverDrillConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("bk_biz_id", models.IntegerField(default=0, help_text="业务的 cmdb id")),
                ("bk_cloud_id", models.IntegerField(default=0, help_text="云区域 id")),
                ("db_module_id", models.IntegerField(default=0, help_text="db模块 id")),
                ("labels", models.JSONField(help_text="资源标签")),
                (
                    "cluster_type",
                    models.CharField(
                        choices=ClusterType.get_choices(),
                        default="",
                        max_length=64,
                    ),
                ),
                ("switch_flag", models.BooleanField(default=False, help_text="是否启用任务")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
