# Generated by Django 3.2.25 on 2025-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0004_failoverdrillconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="failoverdrillconfig",
            name="city_map",
            field=models.JSONField(default=dict, help_text="城市缩写映射表"),
        ),
    ]
