# Generated by Django 3.2.25 on 2025-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0005_failoverdrillconfig_city_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="failoverdrillconfig",
            name="interval",
            field=models.IntegerField(default=10, help_text="重试间隔 分钟"),
        ),
        migrations.AddField(
            model_name="failoverdrillconfig",
            name="max_retry",
            field=models.IntegerField(default=6, help_text="最大重试次数"),
        ),
    ]
