# Generated by Django 3.2.25 on 2025-08-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0006_auto_20250722_2017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqlbackuprecovertask",
            name="backup_total_size",
            field=models.IntegerField(default=0, verbose_name="备份总大小G"),
        ),
    ]
