# Generated by Django 3.2.25 on 2025-08-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0006_auto_20250722_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="backup_host",
            field=models.CharField(default="", max_length=255, verbose_name="备份主机"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="backup_host_role",
            field=models.CharField(default="", max_length=32, verbose_name="备份主机角色"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="charset",
            field=models.CharField(default="", max_length=32, verbose_name="字符集"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="mysql_version",
            field=models.CharField(default="", max_length=32, verbose_name="MySQL版本"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="sql_mode",
            field=models.CharField(default="", max_length=255, verbose_name="SQL模式"),
        ),
        migrations.AlterField(
            model_name="mysqlbackuprecovertask",
            name="backup_total_size",
            field=models.IntegerField(default=0, verbose_name="备份总大小G"),
        ),
    ]
