# Generated by Django 3.2.25 on 2025-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0007_auto_20250806_1801"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="bk_cloud_id",
            field=models.IntegerField(default=0, help_text="云区域 id"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="msg",
            field=models.TextField(default="", help_text="备注信息"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="status",
            field=models.BooleanField(default=False, help_text="巡检结果状态, 默认正常"),
        ),
    ]
