# Generated by Django 3.2.25 on 2025-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0008_auto_20250813_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="phase",
            field=models.CharField(default="", max_length=32, verbose_name="阶段"),
        ),
    ]
