# Generated by Django 3.2.25 on 2025-08-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0007_alter_mysqlbackuprecovertask_backup_total_size"),
        ("db_periodic_task", "0008_auto_20250813_1610"),
    ]

    operations = []
