# Generated by Django 3.2.25 on 2025-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0009_mysqlbackuprecovertask_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseIgnoreConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "ignore_type",
                    models.CharField(
                        choices=[("biz", "业务"), ("cluster", "集群")],
                        help_text="忽略类型：biz-业务级别，cluster-集群级别",
                        max_length=32,
                        verbose_name="忽略类型",
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(
                        help_text="当ignore_type为biz时，存储bk_biz_id；当ignore_type为cluster时，存储cluster_id",
                        verbose_name="目标ID",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(default="", help_text="业务名称或集群域名，用于展示", max_length=255, verbose_name="目标名称"),
                ),
                ("reason", models.TextField(default="", help_text="说明为什么要忽略此业务或集群的演练", verbose_name="忽略原因")),
                ("is_active", models.BooleanField(default=True, help_text="是否启用此忽略配置", verbose_name="是否生效")),
                (
                    "expire_time",
                    models.DateTimeField(blank=True, help_text="忽略配置的过期时间，为空表示永久生效", null=True, verbose_name="过期时间"),
                ),
            ],
            options={
                "verbose_name": "演练忽略配置",
                "verbose_name_plural": "演练忽略配置",
                "ordering": ["-id"],
                "unique_together": {("ignore_type", "target_id")},
            },
        ),
    ]
