# Generated by Django 3.2.25 on 2025-09-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0010_exerciseignoreconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="exercise_host_ip",
            field=models.CharField(default="", help_text="用于演练的机器IP地址", max_length=64, verbose_name="演练机器IP"),
        ),
    ]
