# Generated by Django 3.2.25 on 2025-09-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0011_mysqlbackuprecovertask_exercise_host_ip"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mysqlbackuprecovertask",
            index=models.Index(fields=["bk_biz_id", "task_status"], name="idx_biz_task_status"),
        ),
        migrations.AddIndex(
            model_name="mysqlbackuprecovertask",
            index=models.Index(fields=["cluster_id", "task_status"], name="idx_cluster_task_status"),
        ),
        migrations.AddIndex(
            model_name="mysqlbackuprecovertask",
            index=models.Index(fields=["backup_id", "task_status"], name="idx_backup_task_status"),
        ),
    ]
