# Generated by Django 3.2.25 on 2025-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0012_auto_20250913_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="failed_days",
            field=models.IntegerField(default=0, help_text="失败持续天数"),
        ),
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="state",
            field=models.CharField(default="", help_text="巡检结果状态", max_length=64),
        ),
    ]
