# Generated by Django 4.2.23 on 2025-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0013_auto_20250917_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysqlbackuprecovertask",
            name="status",
            field=models.BooleanField(default=True, help_text="巡检结果状态, 默认正常"),
        ),
    ]
