# Generated by Django 3.2.25 on 2025-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_periodic_task", "0013_auto_20250917_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysqlbackuprecovertask",
            name="tenant_id",
            field=models.CharField(default="default", help_text="租户ID", max_length=128),
        ),
    ]
