# Generated by Django 4.2.30 on 2026-07-16 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_periodic_task", "0014_alter_mysqlbackuprecovertask_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchQueueSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("namespace", models.CharField(max_length=128, unique=True, verbose_name="队列命名空间")),
                ("config", models.JSONField(blank=True, default=dict, verbose_name="配置覆盖项")),
            ],
            options={
                "verbose_name": "Dispatch队列设置",
                "verbose_name_plural": "Dispatch队列设置",
                "ordering": ["namespace"],
            },
        ),
        migrations.CreateModel(
            name="DispatchTaskSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("task_key", models.CharField(max_length=255, unique=True, verbose_name="任务唯一标识")),
                ("config", models.JSONField(blank=True, default=dict, verbose_name="配置覆盖项")),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_settings",
                        to="db_periodic_task.dispatchqueuesettings",
                        verbose_name="队列设置",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch任务设置",
                "verbose_name_plural": "Dispatch任务设置",
                "ordering": ["queue__namespace", "task_key"],
                "indexes": [models.Index(fields=["queue", "task_key"], name="idx_dispatch_queue_task")],
            },
        ),
        migrations.CreateModel(
            name="DispatchQueueRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updater", models.CharField(max_length=64, verbose_name="修改人")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("namespace", models.CharField(max_length=128, unique=True, verbose_name="队列命名空间")),
                ("redis_alias", models.CharField(max_length=64, verbose_name="Redis 实例别名")),
            ],
            options={
                "verbose_name": "Dispatch队列路由",
                "verbose_name_plural": "Dispatch队列路由",
                "ordering": ["namespace"],
            },
        ),
    ]
