---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: qdrant-{{ .Chart.Version }}
spec:
  topologies:
  - name: cluster
    components:
    - name: qdrant
      compDef: {{ include "qdrant.cmpdRegexPattern" . }}
