name: Commit Message Check

on:
  push:
    branches:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "helm-charts/bk-dbm/Chart.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2

    - name: Run read-yaml action
      id: yaml-data
      uses: jbutcher5/read-yaml@main
      with:
        file: 'helm-charts/bk-dbm/Chart.yaml'
        key-path: '["version"]'

    - id: build-release-log
      name: Build release log
      uses: mikepenz/release-changelog-builder-action@v3.5.0
      with:
        # 参考：https://github.com/mikepenz/release-changelog-builder-action
        configuration: ".github/configuration.json"
        commitMode: true
        ignorePreReleases: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: create-tag
      name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          const tagName = '${{ steps.yaml-data.outputs.data }}';
          const tagMessage = '${{ steps.build-release-log.outputs.changelog }}';
          
          // Create a lightweight tag
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${tagName}`,
            sha: context.sha
          });

          // Create a tag object
          const tagObject = await github.rest.git.createTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tagName,
            message: tagMessage,
            object: context.sha,
            type: 'commit'
          });
          
          // Create a new release with the tag
          await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: tagName,
            name: tagName,
            body: tagMessage
          });

          // Output the name of the created tag to use in other steps
          return tagName;
